// client/src/lib/businessOligarchPool.ts
// 100 hand-crafted business oligarch candidates across 10 sectors and 6 zones.

import type { BusinessOligarchCandidate } from "./businessOligarchTypes";

export const BUSINESS_OLIGARCH_CANDIDATES: BusinessOligarchCandidate[] = [
  // ═══════════════════════════════════════════════
  // OIL & GAS (10 candidates)
  // ═══════════════════════════════════════════════
  {
    name: "Alhaji Musa Dantata III",
    zone: "NW", state: "Kano", sector: "oil-gas",
    religion: "Islam", ethnicity: "Hausa",
    description: "Third-generation petroleum dynasty heir who controls fuel distribution across northern Nigeria. Leverages ancestral political ties to secure lucrative NNPC contracts.",
    traits: { aggression: 72, loyalty: 45, greed: 88, visibility: 55 },
    disposition: "neutral", dealStyle: "favour-bank",
    interests: ["petroleum-policy", "northern-development", "trade-liberalization", "infrastructure"],
    influenceScore: 89,
    stableTemplate: { governorStates: ["Kano", "Jigawa", "Katsina"], houseLegislators: 14, senateLegislators: 5, cabinetInterests: ["Petroleum Resources", "Trade and Investment"] },
    connectionDescriptions: ["Bankrolled three consecutive Kano gubernatorial campaigns", "Holds exclusive fuel depot licenses across seven northern states", "Personal friend of two former heads of state", "Silent partner in a major Turkish refinery consortium"],
  },
  {
    name: "Chief Bode Akindele",
    zone: "SW", state: "Lagos", sector: "oil-gas",
    religion: "Christianity", ethnicity: "Yoruba",
    description: "Lagos-based oil trading magnate who built his empire through strategic offshore block acquisitions. Known for aggressive courtroom tactics and willingness to challenge regulatory bodies.",
    traits: { aggression: 85, loyalty: 30, greed: 91, visibility: 70 },
    disposition: "cold", dealStyle: "contract",
    interests: ["deregulation", "foreign-investment", "maritime-policy", "tax-reform"],
    influenceScore: 82,
    stableTemplate: { governorStates: ["Lagos", "Ogun"], houseLegislators: 10, senateLegislators: 3, cabinetInterests: ["Petroleum Resources", "Finance"] },
    connectionDescriptions: ["Owns minority stakes in four publicly traded Nigerian banks", "Major donor to the Lagos business caucus within the ruling party", "Retained a former petroleum minister as board chairman"],
  },
  {
    name: "High Chief Tari Ekiyor",
    zone: "SS", state: "Bayelsa", sector: "oil-gas",
    religion: "Christianity", ethnicity: "Ijaw",
    description: "Niger Delta oil services tycoon who rose from militant activism to become one of the region's wealthiest pipeline security contractors. Commands fierce loyalty from creek communities.",
    traits: { aggression: 88, loyalty: 65, greed: 78, visibility: 45 },
    disposition: "hostile", dealStyle: "favour-bank",
    interests: ["niger-delta-development", "pipeline-security", "amnesty-programme", "oil-revenue-sharing"],
    influenceScore: 75,
    stableTemplate: { governorStates: ["Bayelsa"], houseLegislators: 5, senateLegislators: 2, cabinetInterests: ["Niger Delta Affairs"] },
    connectionDescriptions: ["Former militant commander who negotiated with three sitting presidents", "Controls pipeline surveillance contracts worth billions annually", "Godfather figure to most Bayelsa state assembly members", "Maintains a private security force larger than some state police commands"],
  },
  {
    name: "Engr. Emeka Offor Jr.",
    zone: "SE", state: "Anambra", sector: "oil-gas",
    religion: "Christianity", ethnicity: "Igbo",
    description: "Shrewd Anambra-born petroleum logistics mogul who dominates the Southeast fuel distribution chain. Quietly funds political aspirants while maintaining a carefully curated philanthropic image.",
    traits: { aggression: 58, loyalty: 50, greed: 82, visibility: 35 },
    disposition: "neutral", dealStyle: "contract",
    interests: ["petroleum-policy", "southeast-infrastructure", "free-trade-zones", "power-sector"],
    influenceScore: 77,
    stableTemplate: { governorStates: ["Anambra", "Imo"], houseLegislators: 8, senateLegislators: 2, cabinetInterests: ["Petroleum Resources", "Power"] },
    connectionDescriptions: ["Sole distributor for a major international oil company across five southeastern states", "Funded construction of three federal roads in Anambra", "Brother-in-law to a former Senate President"],
  },
  {
    name: "Alhaji Sani Bello Kontagora",
    zone: "NC", state: "Niger", sector: "oil-gas",
    religion: "Islam", ethnicity: "Nupe",
    description: "Niger State-born oil pipeline construction magnate with deep ties to the military establishment. His companies have built critical petroleum infrastructure across the Middle Belt.",
    traits: { aggression: 65, loyalty: 55, greed: 72, visibility: 30 },
    disposition: "friendly", dealStyle: "favour-bank",
    interests: ["infrastructure", "military-spending", "oil-pipeline-security", "northern-development"],
    influenceScore: 68,
    stableTemplate: { governorStates: ["Niger"], houseLegislators: 6, senateLegislators: 1, cabinetInterests: ["Works and Housing"] },
    connectionDescriptions: ["Former military officers populate his board of directors", "Built the Abuja-Kaduna petroleum products pipeline under sole-source contract", "Traditional title holder in the Nupe emirate council"],
  },
  {
    name: "Chief Mrs. Eniola Fadahunsi",
    zone: "SW", state: "Oyo", sector: "oil-gas",
    religion: "Christianity", ethnicity: "Yoruba",
    description: "One of Nigeria's few female oil trading billionaires. Built a crude lifting empire through sharp commodity trading instincts. Fiercely private but politically influential in Oyo politics.",
    traits: { aggression: 60, loyalty: 40, greed: 85, visibility: 25 },
    disposition: "cold", dealStyle: "contract",
    interests: ["petroleum-policy", "women-in-business", "trade-liberalization", "education-funding"],
    influenceScore: 71,
    stableTemplate: { governorStates: ["Oyo"], houseLegislators: 4, senateLegislators: 1, cabinetInterests: ["Petroleum Resources"] },
    connectionDescriptions: ["Holds one of the few female-owned crude oil lifting allocations", "Major benefactor of two private universities in the Southwest", "Quietly bankrolled the last Oyo State governorship primary"],
  },
  {
    name: "Alhaji Abdullahi Garba Yola",
    zone: "NE", state: "Adamawa", sector: "oil-gas",
    religion: "Islam", ethnicity: "Fulani",
    description: "Adamawa-based petroleum products distributor who controls fuel supply across the Northeast corridor. His monopoly on the Yola-Maiduguri fuel route gives him enormous leverage.",
    traits: { aggression: 70, loyalty: 60, greed: 76, visibility: 40 },
    disposition: "neutral", dealStyle: "favour-bank",
    interests: ["northeast-reconstruction", "petroleum-policy", "border-trade", "security-spending"],
    influenceScore: 62,
    stableTemplate: { governorStates: ["Adamawa", "Gombe"], houseLegislators: 7, senateLegislators: 2, cabinetInterests: ["Petroleum Resources"] },
    connectionDescriptions: ["Only licensed fuel mega-depot operator in the Northeast", "Married into the Lamido of Adamawa's royal family", "Donated fuel and logistics worth billions during the Boko Haram crisis"],
  },
  {
    name: "Chief Kelvin Okonkwo-Briggs",
    zone: "SS", state: "Rivers", sector: "oil-gas",
    religion: "Christianity", ethnicity: "Ikwerre",
    description: "Port Harcourt oil magnate spanning upstream exploration, midstream processing, and downstream retail. A consummate dealmaker who has survived multiple regime changes.",
    traits: { aggression: 78, loyalty: 25, greed: 90, visibility: 65 },
    disposition: "neutral", dealStyle: "contract",
    interests: ["oil-revenue-sharing", "refinery-construction", "gas-flaring-policy", "niger-delta-development"],
    influenceScore: 86,
    stableTemplate: { governorStates: ["Rivers", "Bayelsa"], houseLegislators: 12, senateLegislators: 4, cabinetInterests: ["Petroleum Resources", "Environment"] },
    connectionDescriptions: ["Joint venture partner with three international oil majors", "Rumoured to have financed both sides of the last Rivers governorship", "Owns the largest private jetty on the Bonny waterway", "Sits on the NEITI advisory board"],
  },
  {
    name: "Alhaji Bukar Kashim",
    zone: "NE", state: "Borno", sector: "oil-gas",
    religion: "Islam", ethnicity: "Kanuri",
    description: "Borno-born fuel logistics mogul who made his fortune supplying petroleum products to military operations in the Lake Chad basin. His closeness to the security establishment is indispensable.",
    traits: { aggression: 75, loyalty: 70, greed: 68, visibility: 20 },
    disposition: "cold", dealStyle: "favour-bank",
    interests: ["security-spending", "northeast-reconstruction", "petroleum-policy", "military-contracts"],
    influenceScore: 58,
    stableTemplate: { governorStates: ["Borno"], houseLegislators: 4, senateLegislators: 1, cabinetInterests: ["Defence"] },
    connectionDescriptions: ["Primary fuel supplier to military formations in the Northeast", "Cousin to a former Chief of Army Staff", "Operates under extreme secrecy with no public corporate filings"],
  },
  {
    name: "Chief Obinna Eze-Kalu",
    zone: "SE", state: "Abia", sector: "oil-gas",
    religion: "Christianity", ethnicity: "Igbo",
    description: "Aba-born gas processing industrialist who pivoted from manufacturing into the lucrative LNG sector. Controls significant gas supply infrastructure feeding Southeast industrial clusters.",
    traits: { aggression: 62, loyalty: 48, greed: 80, visibility: 50 },
    disposition: "friendly", dealStyle: "contract",
    interests: ["gas-industrialization", "manufacturing-policy", "southeast-infrastructure", "power-sector"],
    influenceScore: 65,
    stableTemplate: { governorStates: ["Abia"], houseLegislators: 5, senateLegislators: 1, cabinetInterests: ["Gas Resources", "Industry"] },
    connectionDescriptions: ["Built the first privately owned gas processing plant in the Southeast", "Major employer in Aba with over four thousand workers", "Funded the senatorial campaign of Abia's current senior senator"],
  },
  // ═══════════════════════════════════════════════
  // BANKING & FINANCE (10 candidates)
  // ═══════════════════════════════════════════════
  {
    name: "Alhaji Umaru Mutallab",
    zone: "NW", state: "Katsina", sector: "banking-finance",
    religion: "Islam", ethnicity: "Hausa",
    description: "Patriarch of a Katsina banking dynasty who founded one of northern Nigeria's first merchant banks. His financial network stretches from Kano to London.",
    traits: { aggression: 42, loyalty: 65, greed: 70, visibility: 55 },
    disposition: "friendly", dealStyle: "favour-bank",
    interests: ["monetary-policy", "islamic-banking", "northern-development", "education-funding"],
    influenceScore: 91,
    stableTemplate: { governorStates: ["Katsina", "Kano", "Zamfara"], houseLegislators: 16, senateLegislators: 6, cabinetInterests: ["Finance"] },
    connectionDescriptions: ["Former chairman of the Nigerian Bankers' Committee", "Personal banker to at least four sitting state governors", "Endowed scholarship programmes at three northern universities", "Maintains a London residence frequented by visiting heads of state"],
  },
  {
    name: "Chief Adeyemi Lawson",
    zone: "SW", state: "Lagos", sector: "banking-finance",
    religion: "Christianity", ethnicity: "Yoruba",
    description: "Lagos financial titan who transformed a small mortgage institution into a top-five bank through aggressive acquisition and digital banking innovation.",
    traits: { aggression: 55, loyalty: 35, greed: 78, visibility: 75 },
    disposition: "neutral", dealStyle: "contract",
    interests: ["monetary-policy", "fintech-regulation", "capital-markets", "tax-reform"],
    influenceScore: 88,
    stableTemplate: { governorStates: ["Lagos", "Osun"], houseLegislators: 11, senateLegislators: 3, cabinetInterests: ["Finance", "Trade and Investment"] },
    connectionDescriptions: ["His bank handles salary payments for twelve state governments", "Lead financier of the ruling party's last presidential campaign", "Sits on the board of Nigeria's sovereign wealth fund"],
  },
  {
    name: "Hajia Zainab Wali",
    zone: "NW", state: "Sokoto", sector: "banking-finance",
    religion: "Islam", ethnicity: "Hausa-Fulani",
    description: "Sokoto-born Islamic finance pioneer who established Nigeria's most successful non-interest bank. Wields quiet influence through philanthropic networks and royal family connections.",
    traits: { aggression: 30, loyalty: 72, greed: 48, visibility: 28 },
    disposition: "friendly", dealStyle: "favour-bank",
    interests: ["islamic-banking", "women-empowerment", "education-funding", "northern-development"],
    influenceScore: 64,
    stableTemplate: { governorStates: ["Sokoto", "Kebbi"], houseLegislators: 6, senateLegislators: 2, cabinetInterests: ["Finance"] },
    connectionDescriptions: ["Daughter of a former Sultan of Sokoto", "Her bank manages zakat funds for five northern state governments", "Advisory board member of the Central Bank of Nigeria"],
  },
  {
    name: "Chief Godwin Obaseki-Igbinosa",
    zone: "SS", state: "Edo", sector: "banking-finance",
    religion: "Christianity", ethnicity: "Bini",
    description: "Benin City-born investment banker turned private equity mogul. His firm controls significant stakes in telecoms, cement, and real estate across West Africa.",
    traits: { aggression: 50, loyalty: 38, greed: 85, visibility: 18 },
    disposition: "cold", dealStyle: "contract",
    interests: ["capital-markets", "foreign-investment", "deregulation", "real-estate-policy"],
    influenceScore: 74,
    stableTemplate: { governorStates: ["Edo"], houseLegislators: 5, senateLegislators: 1, cabinetInterests: ["Finance", "Trade and Investment"] },
    connectionDescriptions: ["His private equity fund holds controlling stakes in two insurance companies", "Arranged financing for Edo State's last infrastructure bond issuance", "Former managing director of a tier-one Nigerian bank"],
  },
  {
    name: "Dr. Chukwuma Nwosu",
    zone: "SE", state: "Enugu", sector: "banking-finance",
    religion: "Christianity", ethnicity: "Igbo",
    description: "Enugu-born microfinance-to-commercial-banking success story who built a financial empire serving the Southeast's vast informal trading economy.",
    traits: { aggression: 45, loyalty: 58, greed: 72, visibility: 42 },
    disposition: "friendly", dealStyle: "favour-bank",
    interests: ["microfinance-policy", "southeast-infrastructure", "trade-liberalization", "sme-funding"],
    influenceScore: 67,
    stableTemplate: { governorStates: ["Enugu", "Ebonyi"], houseLegislators: 7, senateLegislators: 2, cabinetInterests: ["Finance"] },
    connectionDescriptions: ["His agent banking network processes more Southeast transactions than any tier-one bank", "Major sponsor of the Ohaneze Ndigbo annual convention", "Funded infrastructure projects in rural Enugu"],
  },
  {
    name: "Alhaji Ibrahim Danmusa",
    zone: "NC", state: "Kwara", sector: "banking-finance",
    religion: "Islam", ethnicity: "Yoruba",
    description: "Kwara-born insurance and banking magnate who straddles the cultural divide between North and Southwest. His holding company spans insurance, pension fund management, and commercial banking.",
    traits: { aggression: 38, loyalty: 52, greed: 65, visibility: 48 },
    disposition: "neutral", dealStyle: "contract",
    interests: ["insurance-regulation", "pension-reform", "monetary-policy", "north-central-development"],
    influenceScore: 72,
    stableTemplate: { governorStates: ["Kwara", "Kogi"], houseLegislators: 8, senateLegislators: 2, cabinetInterests: ["Finance"] },
    connectionDescriptions: ["His insurance firm underwrites policies for the federal civil service", "Former treasurer of the ruling party's North Central chapter", "Married to the daughter of a former Kwara military governor"],
  },
  {
    name: "Chief Mrs. Ngozi Adekunle-Okafor",
    zone: "SS", state: "Delta", sector: "banking-finance",
    religion: "Christianity", ethnicity: "Itsekiri",
    description: "Delta State-born asset management queen who controls one of Nigeria's largest pension fund custodians. Intermarriage into a prominent Yoruba business family extends her network.",
    traits: { aggression: 35, loyalty: 44, greed: 74, visibility: 38 },
    disposition: "neutral", dealStyle: "contract",
    interests: ["pension-reform", "capital-markets", "women-empowerment", "niger-delta-development"],
    influenceScore: 69,
    stableTemplate: { governorStates: ["Delta"], houseLegislators: 4, senateLegislators: 1, cabinetInterests: ["Finance"] },
    connectionDescriptions: ["Her firm manages pension assets for over two million Nigerian workers", "Sister to a former Delta State deputy governor", "Board member of the SEC advisory committee"],
  },
  {
    name: "Alhaji Gambo Abdulmalik",
    zone: "NE", state: "Bauchi", sector: "banking-finance",
    religion: "Islam", ethnicity: "Hausa",
    description: "Bauchi-born bureau de change kingpin turned licensed commercial banker. His network facilitates cross-border trade between Nigeria, Chad, and Cameroon.",
    traits: { aggression: 68, loyalty: 55, greed: 82, visibility: 15 },
    disposition: "hostile", dealStyle: "favour-bank",
    interests: ["forex-policy", "border-trade", "northeast-reconstruction", "security-spending"],
    influenceScore: 56,
    stableTemplate: { governorStates: ["Bauchi"], houseLegislators: 3, senateLegislators: 1, cabinetInterests: ["Finance"] },
    connectionDescriptions: ["Operates the largest bureau de change network in northeastern Nigeria", "Suspected of facilitating parallel market forex flows", "Close associate of customs officials along the Chad border", "Provided financial support to the Bauchi emirate"],
  },
  {
    name: "Chief Osaro Ighodalo",
    zone: "NC", state: "Plateau", sector: "banking-finance",
    religion: "Christianity", ethnicity: "Esan",
    description: "Jos-based venture capital pioneer whose fund has backed dozens of Nigerian technology startups. Born to Edo parents but raised on the Plateau, he bridges ethnic divides.",
    traits: { aggression: 40, loyalty: 60, greed: 58, visibility: 52 },
    disposition: "neutral", dealStyle: "contract",
    interests: ["fintech-regulation", "startup-ecosystem", "education-funding", "north-central-development"],
    influenceScore: 61,
    stableTemplate: { governorStates: ["Plateau"], houseLegislators: 3, senateLegislators: 1, cabinetInterests: ["Science and Technology"] },
    connectionDescriptions: ["His venture fund holds stakes in three of Nigeria's five largest fintech companies", "Informal economic adviser to the Plateau State governor", "Co-founded a tech incubator attracting Silicon Valley attention"],
  },
  {
    name: "Alhaji Lawal Kebbi",
    zone: "NW", state: "Kebbi", sector: "banking-finance",
    religion: "Islam", ethnicity: "Hausa",
    description: "Kebbi State rice magnate who diversified into agricultural commodity finance. His bank serves the entire northwestern farming belt, controlling agricultural credit across the region.",
    traits: { aggression: 48, loyalty: 68, greed: 62, visibility: 32 },
    disposition: "neutral", dealStyle: "favour-bank",
    interests: ["agricultural-policy", "rural-banking", "northern-development", "trade-liberalization"],
    influenceScore: 59,
    stableTemplate: { governorStates: ["Kebbi", "Sokoto"], houseLegislators: 9, senateLegislators: 2, cabinetInterests: ["Agriculture", "Finance"] },
    connectionDescriptions: ["His commodity bank finances over sixty percent of rice production in Kebbi", "Key architect of the federal rice import substitution programme", "Traditional title holder in the Gwandu Emirate", "Hosts annual farming summits attended by northwestern governors"],
  },
  // ═══════════════════════════════════════════════
  // TELECOMS & TECH (10 candidates)
  // ═══════════════════════════════════════════════
  {
    name: "Otunba Wale Adenuga Jr.",
    zone: "SW", state: "Lagos", sector: "telecoms-tech",
    religion: "Christianity", ethnicity: "Yoruba",
    description: "Lagos tech entrepreneur who built Nigeria's largest cloud computing platform. His data centres power most of the country's fintech and e-commerce ecosystem.",
    traits: { aggression: 45, loyalty: 40, greed: 68, visibility: 72 },
    disposition: "neutral", dealStyle: "contract",
    interests: ["digital-economy", "fintech-regulation", "broadband-policy", "tax-reform"],
    influenceScore: 80,
    stableTemplate: { governorStates: ["Lagos"], houseLegislators: 5, senateLegislators: 1, cabinetInterests: ["Communications Technology"] },
    connectionDescriptions: ["His data centres host critical government databases", "Major sponsor of Nigeria's annual tech conference", "Advisory board member to the National Information Technology Agency"],
  },
  {
    name: "Alhaji Abdulsamad Rabiu II",
    zone: "NW", state: "Kano", sector: "telecoms-tech",
    religion: "Islam", ethnicity: "Hausa",
    description: "Kano industrialist who expanded from cement into telecoms tower infrastructure. His tower company leases to every major mobile operator in the North.",
    traits: { aggression: 55, loyalty: 60, greed: 75, visibility: 50 },
    disposition: "friendly", dealStyle: "favour-bank",
    interests: ["telecoms-infrastructure", "northern-development", "manufacturing-policy", "power-sector"],
    influenceScore: 85,
    stableTemplate: { governorStates: ["Kano", "Kaduna"], houseLegislators: 12, senateLegislators: 4, cabinetInterests: ["Communications Technology"] },
    connectionDescriptions: ["Owns over three thousand telecoms tower sites across northern Nigeria", "His cement company supplies federal road construction projects", "Sits on the Presidential Advisory Council"],
  },
  {
    name: "Chief Chidi Ajaere",
    zone: "SE", state: "Imo", sector: "telecoms-tech",
    religion: "Christianity", ethnicity: "Igbo",
    description: "Imo-born fibre optic infrastructure builder who laid most of the broadband backbone connecting the Southeast. Turned undersea cable landing stations into political leverage.",
    traits: { aggression: 52, loyalty: 45, greed: 70, visibility: 40 },
    disposition: "neutral", dealStyle: "contract",
    interests: ["broadband-policy", "southeast-infrastructure", "digital-economy", "education-funding"],
    influenceScore: 66,
    stableTemplate: { governorStates: ["Imo", "Abia"], houseLegislators: 6, senateLegislators: 2, cabinetInterests: ["Communications Technology"] },
    connectionDescriptions: ["Holds exclusive fibre optic right-of-way across five southeastern states", "Major donor to ICT departments at three federal universities", "Contract partner for the Galaxy Backbone national network"],
  },
  {
    name: "Hajia Amina Dikko",
    zone: "NC", state: "FCT", sector: "telecoms-tech",
    religion: "Islam", ethnicity: "Hausa",
    description: "Abuja-based satellite communications mogul who built Nigeria's first private VSAT network. Her company provides internet connectivity to military installations and remote government offices.",
    traits: { aggression: 35, loyalty: 65, greed: 55, visibility: 35 },
    disposition: "friendly", dealStyle: "contract",
    interests: ["digital-economy", "security-spending", "space-technology", "women-empowerment"],
    influenceScore: 58,
    stableTemplate: { governorStates: ["FCT"], houseLegislators: 2, senateLegislators: 0, cabinetInterests: ["Communications Technology"] },
    connectionDescriptions: ["Exclusive VSAT provider to the Nigerian military", "Board member of NASRDA (space agency)", "Her late father was a prominent diplomat"],
  },
  {
    name: "Chief Ade Bakare",
    zone: "SW", state: "Ogun", sector: "telecoms-tech",
    religion: "Christianity", ethnicity: "Yoruba",
    description: "Ogun State mobile payment pioneer whose platform processes most of Nigeria's mobile money transactions. Aggressive in lobby efforts to protect fintech from traditional banking regulation.",
    traits: { aggression: 60, loyalty: 30, greed: 72, visibility: 68 },
    disposition: "cold", dealStyle: "contract",
    interests: ["fintech-regulation", "digital-economy", "cashless-policy", "tax-reform"],
    influenceScore: 73,
    stableTemplate: { governorStates: ["Ogun", "Lagos"], houseLegislators: 4, senateLegislators: 1, cabinetInterests: ["Finance", "Communications Technology"] },
    connectionDescriptions: ["His mobile platform has more active users than any Nigerian bank", "Lobbied successfully against CBN licensing restrictions", "Recruited former CBN deputy governors to his board"],
  },
  {
    name: "Engr. Mohammed Jibrin",
    zone: "NE", state: "Gombe", sector: "telecoms-tech",
    religion: "Islam", ethnicity: "Tangale",
    description: "Gombe-born telecoms engineer who built the Northeast's mobile network after Boko Haram destroyed existing infrastructure. His reconstruction contracts made him the region's richest tech figure.",
    traits: { aggression: 40, loyalty: 70, greed: 58, visibility: 30 },
    disposition: "friendly", dealStyle: "favour-bank",
    interests: ["telecoms-infrastructure", "northeast-reconstruction", "security-spending", "education-funding"],
    influenceScore: 52,
    stableTemplate: { governorStates: ["Gombe"], houseLegislators: 3, senateLegislators: 1, cabinetInterests: ["Communications Technology"] },
    connectionDescriptions: ["Rebuilt mobile infrastructure across three northeastern states post-insurgency", "Close ties to military commanders in the Northeast", "His company employs ex-combatants in infrastructure maintenance"],
  },
  {
    name: "Chief Mrs. Ada Okonkwo",
    zone: "SE", state: "Anambra", sector: "telecoms-tech",
    religion: "Christianity", ethnicity: "Igbo",
    description: "Anambra-born cybersecurity entrepreneur who built West Africa's largest digital security firm. Her company protects Nigerian banks and government networks from cyber attacks.",
    traits: { aggression: 38, loyalty: 55, greed: 60, visibility: 45 },
    disposition: "neutral", dealStyle: "contract",
    interests: ["cybersecurity-policy", "digital-economy", "fintech-regulation", "data-protection"],
    influenceScore: 55,
    stableTemplate: { governorStates: ["Anambra"], houseLegislators: 3, senateLegislators: 1, cabinetInterests: ["Communications Technology"] },
    connectionDescriptions: ["Provides cybersecurity for the CBN and eleven commercial banks", "Advisory role to the National Cybersecurity Coordinator", "Founded a women-in-tech accelerator with government funding"],
  },
  {
    name: "Alhaji Nasir Ahmad Danu",
    zone: "NW", state: "Kaduna", sector: "telecoms-tech",
    religion: "Islam", ethnicity: "Hausa",
    description: "Kaduna-based telecoms wholesaler who controls fibre capacity sales to most mobile operators in northern Nigeria. His low-profile style belies enormous behind-the-scenes influence.",
    traits: { aggression: 50, loyalty: 55, greed: 78, visibility: 15 },
    disposition: "neutral", dealStyle: "favour-bank",
    interests: ["telecoms-infrastructure", "northern-development", "broadband-policy", "power-sector"],
    influenceScore: 70,
    stableTemplate: { governorStates: ["Kaduna", "Kano"], houseLegislators: 8, senateLegislators: 2, cabinetInterests: ["Communications Technology"] },
    connectionDescriptions: ["Controls wholesale fibre bandwidth in six northern states", "Silent partner in two mobile virtual network operators", "Traditional title holder in the Kaduna emirate"],
  },
  {
    name: "Chief Tonye Cole-Hart",
    zone: "SS", state: "Rivers", sector: "telecoms-tech",
    religion: "Christianity", ethnicity: "Kalabari",
    description: "Port Harcourt tech investor who pivoted from oil services into digital infrastructure. His company provides cloud services and managed IT to oil companies across the Niger Delta.",
    traits: { aggression: 42, loyalty: 50, greed: 64, visibility: 55 },
    disposition: "friendly", dealStyle: "contract",
    interests: ["digital-economy", "niger-delta-development", "power-sector", "foreign-investment"],
    influenceScore: 60,
    stableTemplate: { governorStates: ["Rivers"], houseLegislators: 3, senateLegislators: 1, cabinetInterests: ["Communications Technology", "Petroleum Resources"] },
    connectionDescriptions: ["Provides IT infrastructure to all major IOCs in the Niger Delta", "Former gubernatorial candidate in Rivers State", "Advisory board member of the NCC"],
  },
  {
    name: "Dr. Halima Ibrahim",
    zone: "NE", state: "Taraba", sector: "telecoms-tech",
    religion: "Islam", ethnicity: "Mumuye",
    description: "Taraba-born AI researcher turned tech company founder. Her agricultural technology platform uses satellite imaging to serve millions of Nigerian farmers. Politically connected through her late father's legacy.",
    traits: { aggression: 28, loyalty: 62, greed: 45, visibility: 60 },
    disposition: "neutral", dealStyle: "contract",
    interests: ["agricultural-policy", "digital-economy", "education-funding", "women-empowerment"],
    influenceScore: 48,
    stableTemplate: { governorStates: ["Taraba"], houseLegislators: 2, senateLegislators: 0, cabinetInterests: ["Agriculture", "Science and Technology"] },
    connectionDescriptions: ["Her agritech platform serves three million farmers across northern Nigeria", "Received the National Productivity Award from the President", "Her late father served as minister under two administrations"],
  },
  // ═══════════════════════════════════════════════
  // MANUFACTURING (10 candidates)
  // ═══════════════════════════════════════════════
  {
    name: "Chief Alex Ibru Jr.",
    zone: "SS", state: "Delta", sector: "manufacturing",
    religion: "Christianity", ethnicity: "Urhobo",
    description: "Delta-born industrialist whose conglomerate operates breweries, packaging plants, and food processing across southern Nigeria. Family legacy in media gives him additional political reach.",
    traits: { aggression: 55, loyalty: 50, greed: 70, visibility: 65 },
    disposition: "neutral", dealStyle: "contract",
    interests: ["manufacturing-policy", "power-sector", "tax-reform", "trade-liberalization"],
    influenceScore: 78,
    stableTemplate: { governorStates: ["Delta", "Edo"], houseLegislators: 7, senateLegislators: 2, cabinetInterests: ["Industry", "Trade and Investment"] },
    connectionDescriptions: ["His breweries employ over fifteen thousand workers across seven states", "Family newspaper chain gives him media influence", "Former chairman of the Manufacturers Association of Nigeria"],
  },
  {
    name: "Alhaji Aliko Mohammed",
    zone: "NW", state: "Kano", sector: "manufacturing",
    religion: "Islam", ethnicity: "Hausa",
    description: "Kano cement and sugar magnate whose factories dominate the northern manufacturing landscape. His business empire intersects with every major political decision affecting the industrial sector.",
    traits: { aggression: 70, loyalty: 35, greed: 88, visibility: 75 },
    disposition: "neutral", dealStyle: "contract",
    interests: ["manufacturing-policy", "import-tariffs", "power-sector", "infrastructure"],
    influenceScore: 95,
    stableTemplate: { governorStates: ["Kano", "Sokoto", "Zamfara"], houseLegislators: 20, senateLegislators: 6, cabinetInterests: ["Industry", "Finance"] },
    connectionDescriptions: ["His cement company supplies virtually every government construction project", "Largest employer in northern Nigeria's private sector", "His foundation funds education and health across all six zones", "Controls a media empire spanning TV, print, and digital"],
  },
  {
    name: "Chief Cosmos Maduka",
    zone: "SE", state: "Anambra", sector: "manufacturing",
    religion: "Christianity", ethnicity: "Igbo",
    description: "Anambra-born automobile assembly magnate who pioneered local vehicle manufacturing. His rags-to-riches story from spare parts apprentice to industrial baron makes him a folk hero in the Southeast.",
    traits: { aggression: 45, loyalty: 60, greed: 65, visibility: 55 },
    disposition: "friendly", dealStyle: "favour-bank",
    interests: ["manufacturing-policy", "automotive-industry", "southeast-infrastructure", "education-funding"],
    influenceScore: 72,
    stableTemplate: { governorStates: ["Anambra"], houseLegislators: 5, senateLegislators: 1, cabinetInterests: ["Industry"] },
    connectionDescriptions: ["His automobile assembly plant is the largest in the Southeast", "Major benefactor of technical education programmes", "His life story has been adapted into a bestselling biography and film"],
  },
  {
    name: "Otunba Oba Otudeko Jr.",
    zone: "SW", state: "Ogun", sector: "manufacturing",
    religion: "Christianity", ethnicity: "Yoruba",
    description: "Ogun State brewery and FMCG magnate who controls a significant share of Nigeria's beer and consumer goods market through strategic joint ventures with European brands.",
    traits: { aggression: 58, loyalty: 42, greed: 80, visibility: 62 },
    disposition: "cold", dealStyle: "contract",
    interests: ["manufacturing-policy", "trade-liberalization", "tax-reform", "consumer-protection"],
    influenceScore: 76,
    stableTemplate: { governorStates: ["Ogun", "Lagos"], houseLegislators: 6, senateLegislators: 2, cabinetInterests: ["Industry", "Trade and Investment"] },
    connectionDescriptions: ["His brewery's products are distributed in all 36 states", "Joint venture partner with two major European consumer brands", "Former chairman of the Lagos Chamber of Commerce"],
  },
  {
    name: "Alhaji Abdulkadir Balarabe",
    zone: "NC", state: "Niger", sector: "manufacturing",
    religion: "Islam", ethnicity: "Gwari",
    description: "Niger State textile and steel manufacturing tycoon who has survived the collapse of Nigeria's textile industry by pivoting to steel production and government contracts.",
    traits: { aggression: 50, loyalty: 65, greed: 72, visibility: 30 },
    disposition: "friendly", dealStyle: "favour-bank",
    interests: ["manufacturing-policy", "import-tariffs", "infrastructure", "northern-development"],
    influenceScore: 58,
    stableTemplate: { governorStates: ["Niger"], houseLegislators: 5, senateLegislators: 1, cabinetInterests: ["Industry", "Mines and Steel"] },
    connectionDescriptions: ["Largest private steel producer in the North Central zone", "His factory employs several thousand workers in Minna", "Traditional title holder in the Gwari chieftaincy council"],
  },
  {
    name: "Chief Cletus Ibeto",
    zone: "SE", state: "Anambra", sector: "manufacturing",
    religion: "Christianity", ethnicity: "Igbo",
    description: "Nnewi-based auto parts manufacturing king whose factories produce components for global automakers. His industrial empire spans petrochemicals, cement, and banking.",
    traits: { aggression: 65, loyalty: 50, greed: 78, visibility: 48 },
    disposition: "neutral", dealStyle: "contract",
    interests: ["manufacturing-policy", "automotive-industry", "power-sector", "southeast-infrastructure"],
    influenceScore: 70,
    stableTemplate: { governorStates: ["Anambra", "Imo"], houseLegislators: 6, senateLegislators: 2, cabinetInterests: ["Industry"] },
    connectionDescriptions: ["His auto parts are exported to twenty countries", "Founder of a polytechnic in Nnewi", "His cement subsidiary competes in the South-South market"],
  },
  {
    name: "Alhaji Dahiru Mangal",
    zone: "NW", state: "Katsina", sector: "manufacturing",
    religion: "Islam", ethnicity: "Hausa",
    description: "Katsina-born industrialist controlling flour mills, edible oil refineries, and commodity processing across the Northwest. Known for ruthless business tactics and deep political connections.",
    traits: { aggression: 80, loyalty: 40, greed: 90, visibility: 35 },
    disposition: "hostile", dealStyle: "favour-bank",
    interests: ["import-tariffs", "manufacturing-policy", "agricultural-policy", "northern-development"],
    influenceScore: 83,
    stableTemplate: { governorStates: ["Katsina", "Zamfara"], houseLegislators: 10, senateLegislators: 3, cabinetInterests: ["Industry", "Trade and Investment"] },
    connectionDescriptions: ["Controls the flour milling market across northwestern Nigeria", "Rumoured to have bankrolled gubernatorial campaigns in three states simultaneously", "His commodity trading network spans West Africa", "Maintains close ties with customs officials at northern border posts"],
  },
  {
    name: "Mrs. Folorunso Alakija Jr.",
    zone: "SW", state: "Lagos", sector: "manufacturing",
    religion: "Christianity", ethnicity: "Yoruba",
    description: "Lagos fashion and textile manufacturing heiress who expanded the family empire into industrial printing and packaging. Her social media visibility makes her a political influencer.",
    traits: { aggression: 35, loyalty: 48, greed: 60, visibility: 78 },
    disposition: "neutral", dealStyle: "contract",
    interests: ["manufacturing-policy", "women-empowerment", "fashion-industry", "education-funding"],
    influenceScore: 55,
    stableTemplate: { governorStates: ["Lagos"], houseLegislators: 3, senateLegislators: 1, cabinetInterests: ["Industry"] },
    connectionDescriptions: ["Her textile brand is the most followed Nigerian label on social media", "Major sponsor of Lagos Fashion Week", "Her foundation awards scholarships to female engineering students"],
  },
  {
    name: "Chief Patrick Utomi",
    zone: "SS", state: "Edo", sector: "manufacturing",
    religion: "Christianity", ethnicity: "Esan",
    description: "Edo-born pharmaceutical manufacturer and policy intellectual. His drug manufacturing plants produce essential medicines and he frequently clashes with government over import policy.",
    traits: { aggression: 55, loyalty: 35, greed: 50, visibility: 70 },
    disposition: "cold", dealStyle: "contract",
    interests: ["healthcare-policy", "manufacturing-policy", "education-funding", "trade-liberalization"],
    influenceScore: 62,
    stableTemplate: { governorStates: ["Edo"], houseLegislators: 3, senateLegislators: 1, cabinetInterests: ["Health", "Industry"] },
    connectionDescriptions: ["His pharmaceutical plants produce twenty percent of locally manufactured drugs", "Frequent op-ed writer critiquing economic policy", "Former presidential aspirant on multiple occasions"],
  },
  {
    name: "Alhaji Isyaku Rabiu",
    zone: "NE", state: "Adamawa", sector: "manufacturing",
    religion: "Islam", ethnicity: "Fulani",
    description: "Adamawa-based food processing industrialist whose factories convert northeastern agricultural produce into packaged goods. His supply chain reaches from rural farms to supermarket shelves.",
    traits: { aggression: 42, loyalty: 62, greed: 68, visibility: 25 },
    disposition: "friendly", dealStyle: "favour-bank",
    interests: ["agricultural-policy", "manufacturing-policy", "northeast-reconstruction", "power-sector"],
    influenceScore: 50,
    stableTemplate: { governorStates: ["Adamawa"], houseLegislators: 4, senateLegislators: 1, cabinetInterests: ["Agriculture", "Industry"] },
    connectionDescriptions: ["Largest employer in Adamawa's private sector after telecoms", "His supply chain supports thousands of smallholder farmers", "Close ties to traditional rulers in the Adamawa emirate"],
  },
  // ═══════════════════════════════════════════════
  // REAL ESTATE & CONSTRUCTION (10 candidates)
  // ═══════════════════════════════════════════════
  {
    name: "Chief Olu Okeowo",
    zone: "SW", state: "Lagos", sector: "real-estate-construction",
    religion: "Christianity", ethnicity: "Yoruba",
    description: "Lagos luxury real estate developer who built entire residential estates on reclaimed land. His developments house the elite class and his construction contracts reshape the city skyline.",
    traits: { aggression: 65, loyalty: 30, greed: 92, visibility: 72 },
    disposition: "neutral", dealStyle: "contract",
    interests: ["real-estate-policy", "infrastructure", "land-reform", "foreign-investment"],
    influenceScore: 82,
    stableTemplate: { governorStates: ["Lagos"], houseLegislators: 6, senateLegislators: 2, cabinetInterests: ["Works and Housing"] },
    connectionDescriptions: ["His developments house several serving and former governors", "Holds over two thousand hectares of prime Lagos waterfront land", "Major donor to both the ruling and opposition parties in Lagos"],
  },
  {
    name: "Alhaji Mustapha Aliyu FCT",
    zone: "NC", state: "FCT", sector: "real-estate-construction",
    religion: "Islam", ethnicity: "Gbagyi",
    description: "Abuja's most powerful construction mogul who has built government buildings, roads, and housing estates since the capital's early development. Controls critical land allocations in the FCT.",
    traits: { aggression: 72, loyalty: 55, greed: 85, visibility: 50 },
    disposition: "neutral", dealStyle: "favour-bank",
    interests: ["infrastructure", "real-estate-policy", "land-reform", "power-sector"],
    influenceScore: 78,
    stableTemplate: { governorStates: ["FCT", "Nasarawa"], houseLegislators: 5, senateLegislators: 1, cabinetInterests: ["Works and Housing", "FCT"] },
    connectionDescriptions: ["Built the ministerial quarters used by federal cabinet members", "Holds strategic land banks in Abuja worth billions", "Close relationship with every FCDA minister since the 2000s"],
  },
  {
    name: "Chief Emeka Okadigbo Jr.",
    zone: "SE", state: "Anambra", sector: "real-estate-construction",
    religion: "Christianity", ethnicity: "Igbo",
    description: "Anambra-born construction magnate who builds affordable housing across the Southeast. His estates have housed hundreds of thousands and he is beloved for keeping prices within reach.",
    traits: { aggression: 40, loyalty: 58, greed: 65, visibility: 42 },
    disposition: "friendly", dealStyle: "favour-bank",
    interests: ["real-estate-policy", "southeast-infrastructure", "affordable-housing", "power-sector"],
    influenceScore: 60,
    stableTemplate: { governorStates: ["Anambra", "Enugu"], houseLegislators: 5, senateLegislators: 1, cabinetInterests: ["Works and Housing"] },
    connectionDescriptions: ["Built over ten thousand affordable housing units across the Southeast", "His father was a former Senate President", "Active in Ohaneze Ndigbo leadership circles"],
  },
  {
    name: "Alhaji Hassan Danbaba",
    zone: "NW", state: "Kaduna", sector: "real-estate-construction",
    religion: "Islam", ethnicity: "Hausa",
    description: "Kaduna-based road construction billionaire whose company has built thousands of kilometers of federal highways. His contracts consistently win regardless of which party is in power.",
    traits: { aggression: 60, loyalty: 45, greed: 82, visibility: 30 },
    disposition: "cold", dealStyle: "contract",
    interests: ["infrastructure", "northern-development", "transport-policy", "power-sector"],
    influenceScore: 75,
    stableTemplate: { governorStates: ["Kaduna", "Kano"], houseLegislators: 8, senateLegislators: 2, cabinetInterests: ["Works and Housing"] },
    connectionDescriptions: ["Has built federal roads in twenty-eight states", "His company employs the largest fleet of heavy equipment in northern Nigeria", "Former president of the Federation of Construction Industry"],
  },
  {
    name: "Chief Mrs. Olayinka Oshodi",
    zone: "SW", state: "Ondo", sector: "real-estate-construction",
    religion: "Christianity", ethnicity: "Yoruba",
    description: "Ondo-born bridge and infrastructure specialist. One of the few female-led construction firms in Nigeria, she has built critical bridges and flyovers connecting the Southwest.",
    traits: { aggression: 50, loyalty: 55, greed: 68, visibility: 48 },
    disposition: "friendly", dealStyle: "contract",
    interests: ["infrastructure", "women-empowerment", "transport-policy", "education-funding"],
    influenceScore: 55,
    stableTemplate: { governorStates: ["Ondo"], houseLegislators: 3, senateLegislators: 1, cabinetInterests: ["Works and Housing"] },
    connectionDescriptions: ["Built the Ondo State network of rural bridges", "First female president of the Nigerian Society of Engineers, Ondo branch", "Her foundation trains young female engineers"],
  },
  {
    name: "Chief Sunny Nwosu-Eze",
    zone: "SS", state: "Rivers", sector: "real-estate-construction",
    religion: "Christianity", ethnicity: "Ogoni",
    description: "Port Harcourt-based construction magnate specializing in oil industry infrastructure. His company builds flow stations, tank farms, and refinery components for international oil companies.",
    traits: { aggression: 58, loyalty: 42, greed: 78, visibility: 35 },
    disposition: "neutral", dealStyle: "contract",
    interests: ["infrastructure", "niger-delta-development", "oil-revenue-sharing", "environmental-policy"],
    influenceScore: 63,
    stableTemplate: { governorStates: ["Rivers"], houseLegislators: 4, senateLegislators: 1, cabinetInterests: ["Petroleum Resources", "Works and Housing"] },
    connectionDescriptions: ["Built flow stations for three major IOCs", "His company handles environmental remediation contracts", "Active in Ogoni community leadership"],
  },
  {
    name: "Alhaji Bala Shagari",
    zone: "NW", state: "Sokoto", sector: "real-estate-construction",
    religion: "Islam", ethnicity: "Fulani",
    description: "Sokoto-born construction scion from a prominent political family. His company dominates government building contracts across the Northwest. Family name opens doors in Abuja.",
    traits: { aggression: 55, loyalty: 60, greed: 72, visibility: 45 },
    disposition: "friendly", dealStyle: "favour-bank",
    interests: ["infrastructure", "northern-development", "real-estate-policy", "education-funding"],
    influenceScore: 68,
    stableTemplate: { governorStates: ["Sokoto", "Kebbi"], houseLegislators: 7, senateLegislators: 2, cabinetInterests: ["Works and Housing"] },
    connectionDescriptions: ["Grandson of a former President of Nigeria", "Built government buildings in twelve northern states", "His family's political network spans three decades"],
  },
  {
    name: "Chief Ogbuefi Nnamdi Obi",
    zone: "SE", state: "Enugu", sector: "real-estate-construction",
    religion: "Christianity", ethnicity: "Igbo",
    description: "Enugu-based property developer who has transformed the state capital's skyline with commercial towers and shopping malls. His projects attract international retail brands to the Southeast.",
    traits: { aggression: 48, loyalty: 52, greed: 75, visibility: 55 },
    disposition: "neutral", dealStyle: "contract",
    interests: ["real-estate-policy", "southeast-infrastructure", "foreign-investment", "trade-liberalization"],
    influenceScore: 56,
    stableTemplate: { governorStates: ["Enugu"], houseLegislators: 3, senateLegislators: 1, cabinetInterests: ["Works and Housing"] },
    connectionDescriptions: ["Built the largest shopping mall in the Southeast", "Attracted three international retail brands to Enugu", "His projects employ thousands of local artisans"],
  },
  {
    name: "Alhaji Bashir Yuguda",
    zone: "NE", state: "Bauchi", sector: "real-estate-construction",
    religion: "Islam", ethnicity: "Hausa",
    description: "Former banker turned Bauchi real estate developer. His housing estates provide the only formal residential developments in much of the Northeast. Government housing contracts are his bread and butter.",
    traits: { aggression: 45, loyalty: 55, greed: 70, visibility: 38 },
    disposition: "neutral", dealStyle: "favour-bank",
    interests: ["affordable-housing", "northeast-reconstruction", "infrastructure", "northern-development"],
    influenceScore: 52,
    stableTemplate: { governorStates: ["Bauchi"], houseLegislators: 4, senateLegislators: 1, cabinetInterests: ["Works and Housing"] },
    connectionDescriptions: ["Former Commissioner of Finance in Bauchi State", "Built emergency housing for displaced persons in the Northeast", "His banking background gives him access to development finance"],
  },
  {
    name: "Chief Anthony Elumelu Jr.",
    zone: "SS", state: "Delta", sector: "real-estate-construction",
    religion: "Christianity", ethnicity: "Itsekiri",
    description: "Delta-born infrastructure investor whose holding company builds everything from housing estates to power plants. Strategic approach of acquiring distressed construction firms and turning them profitable.",
    traits: { aggression: 62, loyalty: 40, greed: 80, visibility: 60 },
    disposition: "cold", dealStyle: "contract",
    interests: ["infrastructure", "power-sector", "real-estate-policy", "foreign-investment"],
    influenceScore: 74,
    stableTemplate: { governorStates: ["Delta", "Rivers"], houseLegislators: 5, senateLegislators: 2, cabinetInterests: ["Works and Housing", "Power"] },
    connectionDescriptions: ["His holding company owns five construction firms across three states", "Built the Delta State government new secretariat complex", "Former investment banker with international deal experience"],
  },
  // ═══════════════════════════════════════════════
  // AGRICULTURE & COMMODITIES (10 candidates)
  // ═══════════════════════════════════════════════
  {
    name: "Alhaji Sani Dangote",
    zone: "NW", state: "Kano", sector: "agriculture-commodities",
    religion: "Islam", ethnicity: "Hausa",
    description: "Kano groundnut and grain trading magnate whose family has dominated northern agricultural commodities since before independence. His warehouse network controls grain prices across the Sahel.",
    traits: { aggression: 55, loyalty: 65, greed: 75, visibility: 40 },
    disposition: "friendly", dealStyle: "favour-bank",
    interests: ["agricultural-policy", "northern-development", "trade-liberalization", "import-tariffs"],
    influenceScore: 80,
    stableTemplate: { governorStates: ["Kano", "Jigawa"], houseLegislators: 10, senateLegislators: 3, cabinetInterests: ["Agriculture"] },
    connectionDescriptions: ["Controls the largest grain storage network in West Africa", "His commodities exchange sets prices for northern markets", "Major employer of seasonal agricultural labour across the Northwest"],
  },
  {
    name: "Chief Akin Adesina",
    zone: "SW", state: "Oyo", sector: "agriculture-commodities",
    religion: "Christianity", ethnicity: "Yoruba",
    description: "Oyo State cocoa and cashew processing mogul who transformed from a smallholder farmer into an agribusiness titan. His exports reach European and Asian markets directly.",
    traits: { aggression: 38, loyalty: 55, greed: 60, visibility: 50 },
    disposition: "friendly", dealStyle: "contract",
    interests: ["agricultural-policy", "export-promotion", "trade-liberalization", "education-funding"],
    influenceScore: 65,
    stableTemplate: { governorStates: ["Oyo", "Osun"], houseLegislators: 5, senateLegislators: 1, cabinetInterests: ["Agriculture"] },
    connectionDescriptions: ["His cocoa exports represent fifteen percent of Nigeria's total", "Former president of the National Cocoa Association", "Built processing facilities employing thousands in Oyo State"],
  },
  {
    name: "Alhaji Buba Marwa Jr.",
    zone: "NE", state: "Adamawa", sector: "agriculture-commodities",
    religion: "Islam", ethnicity: "Fulani",
    description: "Adamawa cattle ranching magnate who controls the largest private herd in the Northeast. His livestock trading routes span from the Sahel to the coast. Key mediator in farmer-herder conflicts.",
    traits: { aggression: 60, loyalty: 70, greed: 65, visibility: 35 },
    disposition: "neutral", dealStyle: "favour-bank",
    interests: ["agricultural-policy", "livestock-development", "security-spending", "northeast-reconstruction"],
    influenceScore: 62,
    stableTemplate: { governorStates: ["Adamawa", "Taraba"], houseLegislators: 6, senateLegislators: 2, cabinetInterests: ["Agriculture"] },
    connectionDescriptions: ["Mediates farmer-herder disputes across the Middle Belt", "His livestock routes span four countries", "His father was a former military governor"],
  },
  {
    name: "Chief Victor Okezie",
    zone: "SE", state: "Abia", sector: "agriculture-commodities",
    religion: "Christianity", ethnicity: "Igbo",
    description: "Abia-born palm oil processing industrialist who pioneered large-scale plantation agriculture in the Southeast. His refined palm oil brand dominates the domestic market.",
    traits: { aggression: 42, loyalty: 55, greed: 68, visibility: 40 },
    disposition: "neutral", dealStyle: "contract",
    interests: ["agricultural-policy", "manufacturing-policy", "southeast-infrastructure", "trade-liberalization"],
    influenceScore: 58,
    stableTemplate: { governorStates: ["Abia"], houseLegislators: 4, senateLegislators: 1, cabinetInterests: ["Agriculture", "Industry"] },
    connectionDescriptions: ["Owns the largest palm oil plantation in southeastern Nigeria", "His brand controls thirty percent of domestic edible oil market", "Former chairman of the Oil Palm Growers Association"],
  },
  {
    name: "Alhaji Aminu Dabo",
    zone: "NW", state: "Kano", sector: "agriculture-commodities",
    religion: "Islam", ethnicity: "Hausa",
    description: "Kano-based cotton and textile raw materials trader who supplies Nigeria's surviving textile mills. Controls the cotton ginning industry across the Northwest with iron efficiency.",
    traits: { aggression: 65, loyalty: 50, greed: 78, visibility: 25 },
    disposition: "cold", dealStyle: "favour-bank",
    interests: ["agricultural-policy", "manufacturing-policy", "import-tariffs", "northern-development"],
    influenceScore: 56,
    stableTemplate: { governorStates: ["Kano"], houseLegislators: 5, senateLegislators: 1, cabinetInterests: ["Agriculture"] },
    connectionDescriptions: ["Controls seventy percent of Nigeria's cotton ginning capacity", "His raw materials supply surviving northern textile mills", "Traditional title holder in the Kano emirate"],
  },
  {
    name: "Chief Mrs. Biodun Shobanjo-Ayo",
    zone: "SW", state: "Ekiti", sector: "agriculture-commodities",
    religion: "Christianity", ethnicity: "Yoruba",
    description: "Ekiti-born organic farming pioneer who built a premium agricultural export brand. Her products reach high-end European supermarkets and she advocates for Nigerian agriculture modernization.",
    traits: { aggression: 30, loyalty: 60, greed: 50, visibility: 55 },
    disposition: "friendly", dealStyle: "contract",
    interests: ["agricultural-policy", "export-promotion", "environmental-policy", "women-empowerment"],
    influenceScore: 48,
    stableTemplate: { governorStates: ["Ekiti"], houseLegislators: 2, senateLegislators: 0, cabinetInterests: ["Agriculture"] },
    connectionDescriptions: ["Her organic produce brand sells in fourteen European countries", "Founded an agricultural training centre for rural women", "Adviser to the Federal Ministry of Agriculture on export standards"],
  },
  {
    name: "Chief Osaro Idahosa",
    zone: "SS", state: "Edo", sector: "agriculture-commodities",
    religion: "Christianity", ethnicity: "Bini",
    description: "Edo State rubber and timber magnate who controls vast plantation estates. His products supply both domestic and international markets, but environmental critics challenge his logging practices.",
    traits: { aggression: 55, loyalty: 45, greed: 78, visibility: 30 },
    disposition: "cold", dealStyle: "contract",
    interests: ["agricultural-policy", "forestry-management", "trade-liberalization", "infrastructure"],
    influenceScore: 54,
    stableTemplate: { governorStates: ["Edo"], houseLegislators: 3, senateLegislators: 1, cabinetInterests: ["Agriculture", "Environment"] },
    connectionDescriptions: ["Owns the largest rubber plantation in West Africa", "His timber exports reach Asian markets", "Faces ongoing criticism from environmental groups"],
  },
  {
    name: "Alhaji Umaru Kwairanga",
    zone: "NE", state: "Gombe", sector: "agriculture-commodities",
    religion: "Islam", ethnicity: "Tangale",
    description: "Gombe-born sesame and soybean export king. His commodity trading firm is the largest agricultural exporter in the Northeast, connecting smallholder farmers to global markets.",
    traits: { aggression: 35, loyalty: 62, greed: 60, visibility: 28 },
    disposition: "friendly", dealStyle: "favour-bank",
    interests: ["agricultural-policy", "export-promotion", "northeast-reconstruction", "transport-policy"],
    influenceScore: 50,
    stableTemplate: { governorStates: ["Gombe"], houseLegislators: 3, senateLegislators: 1, cabinetInterests: ["Agriculture"] },
    connectionDescriptions: ["His commodity firm connects fifty thousand smallholder farmers to export markets", "Built the largest sesame processing plant in West Africa", "Active in the reconstruction of agricultural infrastructure post-insurgency"],
  },
  {
    name: "Chief Olumide Olaiya",
    zone: "NC", state: "Benue", sector: "agriculture-commodities",
    religion: "Christianity", ethnicity: "Tiv",
    description: "Benue-born pioneer in commercial rice farming who turned thousands of hectares of the Benue valley into Nigeria's rice bowl. His output rivals imported rice in quality.",
    traits: { aggression: 40, loyalty: 58, greed: 55, visibility: 42 },
    disposition: "neutral", dealStyle: "contract",
    interests: ["agricultural-policy", "import-tariffs", "north-central-development", "infrastructure"],
    influenceScore: 52,
    stableTemplate: { governorStates: ["Benue"], houseLegislators: 4, senateLegislators: 1, cabinetInterests: ["Agriculture"] },
    connectionDescriptions: ["His rice farms produce enough to supply three states annually", "Key beneficiary of the Anchor Borrowers Programme", "Active mediator between farming communities and herders"],
  },
  {
    name: "Chief Mrs. Uduak Essien-Obot",
    zone: "SS", state: "AkwaIbom", sector: "agriculture-commodities",
    religion: "Christianity", ethnicity: "Ibibio",
    description: "Akwa Ibom aquaculture mogul whose fish farming operations supply protein to southern Nigeria. Her integrated fish processing plants export to neighbouring countries.",
    traits: { aggression: 32, loyalty: 55, greed: 58, visibility: 38 },
    disposition: "neutral", dealStyle: "contract",
    interests: ["agricultural-policy", "aquaculture-development", "export-promotion", "women-empowerment"],
    influenceScore: 46,
    stableTemplate: { governorStates: ["AkwaIbom"], houseLegislators: 3, senateLegislators: 0, cabinetInterests: ["Agriculture"] },
    connectionDescriptions: ["Operates the largest integrated fish farm in West Africa", "Her processing plants export to Ghana and Cameroon", "Adviser to the state government on blue economy initiatives"],
  },
  // ═══════════════════════════════════════════════
  // MEDIA & ENTERTAINMENT (10 candidates)
  // ═══════════════════════════════════════════════
  {
    name: "Chief Nduka Obaigbena",
    zone: "SS", state: "Delta", sector: "media-entertainment",
    religion: "Christianity", ethnicity: "Itsekiri",
    description: "Delta-born media baron who owns Nigeria's most influential newspaper chain. His editorials have made and broken political careers. Close to every administration regardless of party.",
    traits: { aggression: 70, loyalty: 25, greed: 72, visibility: 80 },
    disposition: "neutral", dealStyle: "favour-bank",
    interests: ["media-freedom", "foreign-investment", "niger-delta-development", "trade-liberalization"],
    influenceScore: 82,
    stableTemplate: { governorStates: ["Delta"], houseLegislators: 4, senateLegislators: 1, cabinetInterests: ["Information and Culture"] },
    connectionDescriptions: ["His newspapers are mandatory reading for every political class member", "Former adviser on media to multiple presidents", "Controls the largest newspaper distribution network in Nigeria", "His editorials have influenced three presidential elections"],
  },
  {
    name: "Chief Moshood Abiola Jr.",
    zone: "SW", state: "Ogun", sector: "media-entertainment",
    religion: "Islam", ethnicity: "Yoruba",
    description: "Ogun State-born heir to a storied political and media dynasty. His TV stations and digital media platforms dominate the Yoruba-speaking media market.",
    traits: { aggression: 45, loyalty: 55, greed: 60, visibility: 78 },
    disposition: "friendly", dealStyle: "favour-bank",
    interests: ["media-freedom", "digital-economy", "education-funding", "southwest-development"],
    influenceScore: 68,
    stableTemplate: { governorStates: ["Ogun", "Oyo"], houseLegislators: 5, senateLegislators: 2, cabinetInterests: ["Information and Culture"] },
    connectionDescriptions: ["His TV stations reach forty million Yoruba-speaking viewers", "Family name carries enormous political symbolism", "Major sponsor of Yoruba cultural festivals"],
  },
  {
    name: "Alhaji Kabiru Yusuf",
    zone: "NW", state: "Kano", sector: "media-entertainment",
    religion: "Islam", ethnicity: "Hausa",
    description: "Kano-based media mogul who owns the most widely read Hausa-language newspapers and a chain of northern radio stations. His coverage shapes political opinion across the Northwest and Northeast.",
    traits: { aggression: 55, loyalty: 60, greed: 58, visibility: 65 },
    disposition: "neutral", dealStyle: "favour-bank",
    interests: ["media-freedom", "northern-development", "education-funding", "islamic-banking"],
    influenceScore: 65,
    stableTemplate: { governorStates: ["Kano", "Kaduna"], houseLegislators: 6, senateLegislators: 2, cabinetInterests: ["Information and Culture"] },
    connectionDescriptions: ["His Hausa newspapers have the largest circulation in northern Nigeria", "His radio stations reach eighty percent of the Northwest", "Close to the Kano emirate establishment"],
  },
  {
    name: "Chief Jason Njoku",
    zone: "SE", state: "Imo", sector: "media-entertainment",
    religion: "Christianity", ethnicity: "Igbo",
    description: "Imo-born digital media entrepreneur who built Africa's largest video streaming platform. His content library of Nollywood films gives him enormous cultural influence.",
    traits: { aggression: 40, loyalty: 35, greed: 55, visibility: 72 },
    disposition: "neutral", dealStyle: "contract",
    interests: ["digital-economy", "media-freedom", "fintech-regulation", "education-funding"],
    influenceScore: 60,
    stableTemplate: { governorStates: ["Lagos"], houseLegislators: 2, senateLegislators: 0, cabinetInterests: ["Information and Culture", "Communications Technology"] },
    connectionDescriptions: ["His streaming platform has more subscribers than all Nigerian cable TV operators combined", "Produces original Nollywood content that reaches global audiences", "Vocal advocate for tech-friendly government policy"],
  },
  {
    name: "Mrs. Mosunmola Abudu",
    zone: "SW", state: "Lagos", sector: "media-entertainment",
    religion: "Christianity", ethnicity: "Yoruba",
    description: "Lagos TV mogul and talk show queen whose media conglomerate spans television, film production, and digital content. Her cultural influence extends far beyond entertainment into politics.",
    traits: { aggression: 50, loyalty: 40, greed: 62, visibility: 80 },
    disposition: "cold", dealStyle: "contract",
    interests: ["media-freedom", "women-empowerment", "digital-economy", "fashion-industry"],
    influenceScore: 72,
    stableTemplate: { governorStates: ["Lagos"], houseLegislators: 3, senateLegislators: 1, cabinetInterests: ["Information and Culture"] },
    connectionDescriptions: ["Her talk show has interviewed every major Nigerian politician", "Produced films that have screened at international festivals", "Her fashion brand has global retail presence"],
  },
  {
    name: "Chief Emeka Mba",
    zone: "SE", state: "Enugu", sector: "media-entertainment",
    religion: "Christianity", ethnicity: "Igbo",
    description: "Former broadcast regulator turned media investor. His company owns radio stations across the East and his regulatory experience gives him unique insider knowledge of the media landscape.",
    traits: { aggression: 55, loyalty: 45, greed: 65, visibility: 55 },
    disposition: "cold", dealStyle: "contract",
    interests: ["media-freedom", "digital-economy", "broadcast-regulation", "southeast-infrastructure"],
    influenceScore: 55,
    stableTemplate: { governorStates: ["Enugu"], houseLegislators: 3, senateLegislators: 1, cabinetInterests: ["Information and Culture"] },
    connectionDescriptions: ["Former Director-General of the National Broadcasting Commission", "Owns radio licences in four southeastern states", "His regulatory contacts give him advance knowledge of media policy changes"],
  },
  {
    name: "Alhaji Garba Shehu Media",
    zone: "NE", state: "Borno", sector: "media-entertainment",
    religion: "Islam", ethnicity: "Kanuri",
    description: "Borno-born journalist turned media company owner. His outlets provide the only significant independent news coverage of the Northeast conflict, giving him unique leverage.",
    traits: { aggression: 60, loyalty: 65, greed: 50, visibility: 58 },
    disposition: "friendly", dealStyle: "favour-bank",
    interests: ["media-freedom", "northeast-reconstruction", "security-spending", "education-funding"],
    influenceScore: 52,
    stableTemplate: { governorStates: ["Borno"], houseLegislators: 3, senateLegislators: 1, cabinetInterests: ["Information and Culture"] },
    connectionDescriptions: ["His reporters are the only journalists embedded with military units in the Northeast", "Former presidential spokesperson", "His coverage of the insurgency has won international journalism awards"],
  },
  {
    name: "Chief Mike Adenuga Jr.",
    zone: "SW", state: "Oyo", sector: "media-entertainment",
    religion: "Christianity", ethnicity: "Yoruba",
    description: "Oyo-born telecoms billionaire who expanded into media, owning a major TV network and music label. His entertainment arm shapes Nigerian pop culture and exports it globally.",
    traits: { aggression: 65, loyalty: 30, greed: 80, visibility: 20 },
    disposition: "hostile", dealStyle: "favour-bank",
    interests: ["telecoms-infrastructure", "media-freedom", "digital-economy", "tax-reform"],
    influenceScore: 90,
    stableTemplate: { governorStates: ["Oyo", "Lagos", "Osun"], houseLegislators: 15, senateLegislators: 4, cabinetInterests: ["Communications Technology", "Information and Culture"] },
    connectionDescriptions: ["His mobile network is the second largest in Nigeria", "His music label has produced many of Nigeria's global music stars", "Known for extreme privacy and never granting interviews", "His charitable foundation operates in all 36 states"],
  },
  {
    name: "Alhaji Abdullahi Ganduje Media",
    zone: "NC", state: "Niger", sector: "media-entertainment",
    religion: "Islam", ethnicity: "Nupe",
    description: "Niger State film producer whose Hausa-language film industry (Kannywood) productions rival Nollywood in audience size across the North. His studios shaped modern Hausa cinema.",
    traits: { aggression: 35, loyalty: 55, greed: 52, visibility: 60 },
    disposition: "neutral", dealStyle: "contract",
    interests: ["media-freedom", "northern-development", "education-funding", "digital-economy"],
    influenceScore: 48,
    stableTemplate: { governorStates: ["Niger"], houseLegislators: 2, senateLegislators: 0, cabinetInterests: ["Information and Culture"] },
    connectionDescriptions: ["His Kannywood productions reach over fifty million northern viewers", "Founded the Northern Nigeria Film Academy", "His films promote moderate Islamic values and cultural dialogue"],
  },
  {
    name: "Chief Obi Asika",
    zone: "SS", state: "Edo", sector: "media-entertainment",
    religion: "Christianity", ethnicity: "Bini",
    description: "Edo-born events and music festival mogul whose entertainment empire spans concert promotion, artist management, and music publishing. His festivals draw international tourists to Nigeria.",
    traits: { aggression: 42, loyalty: 38, greed: 55, visibility: 75 },
    disposition: "friendly", dealStyle: "contract",
    interests: ["digital-economy", "tourism-policy", "media-freedom", "foreign-investment"],
    influenceScore: 50,
    stableTemplate: { governorStates: ["Edo"], houseLegislators: 2, senateLegislators: 0, cabinetInterests: ["Information and Culture"] },
    connectionDescriptions: ["His music festivals attract over two hundred thousand attendees annually", "Manages several of Nigeria's biggest music acts", "His events generate significant tourism revenue for host states"],
  },
  // ═══════════════════════════════════════════════
  // IMPORT-EXPORT (10 candidates)
  // ═══════════════════════════════════════════════
  {
    name: "Chief Obiora Madu",
    zone: "SE", state: "Anambra", sector: "import-export",
    religion: "Christianity", ethnicity: "Igbo",
    description: "Onitsha-based electronics and consumer goods importer who controls the largest market complex in West Africa. His trading networks extend from China to across the continent.",
    traits: { aggression: 60, loyalty: 45, greed: 82, visibility: 35 },
    disposition: "neutral", dealStyle: "contract",
    interests: ["trade-liberalization", "import-tariffs", "southeast-infrastructure", "forex-policy"],
    influenceScore: 75,
    stableTemplate: { governorStates: ["Anambra"], houseLegislators: 6, senateLegislators: 2, cabinetInterests: ["Trade and Investment"] },
    connectionDescriptions: ["Controls the Onitsha Main Market traders' association", "His import network brings goods from China, India, and Turkey", "Major financier of Anambra state politics"],
  },
  {
    name: "Alhaji Ibrahim Shekarau-Bawa",
    zone: "NW", state: "Kano", sector: "import-export",
    religion: "Islam", ethnicity: "Hausa",
    description: "Kano-based textiles and general merchandise importer whose goods supply the entire northern market corridor. His warehouses in Kano's Sabon Gari are the North's commercial nerve centre.",
    traits: { aggression: 55, loyalty: 60, greed: 75, visibility: 30 },
    disposition: "friendly", dealStyle: "favour-bank",
    interests: ["trade-liberalization", "import-tariffs", "northern-development", "border-trade"],
    influenceScore: 70,
    stableTemplate: { governorStates: ["Kano", "Katsina"], houseLegislators: 8, senateLegislators: 2, cabinetInterests: ["Trade and Investment"] },
    connectionDescriptions: ["His warehouses supply goods to fifteen northern states", "Major employer in Kano's commercial district", "Close ties to customs officials at Jibiya border crossing"],
  },
  {
    name: "Chief Ifeanyi Okoronkwo",
    zone: "SE", state: "Imo", sector: "import-export",
    religion: "Christianity", ethnicity: "Igbo",
    description: "Imo-born spare parts import king whose Alaba International Market network distributes auto and electronic parts across West Africa. His trade volumes rival small countries' GDP.",
    traits: { aggression: 65, loyalty: 40, greed: 85, visibility: 25 },
    disposition: "cold", dealStyle: "contract",
    interests: ["trade-liberalization", "import-tariffs", "manufacturing-policy", "forex-policy"],
    influenceScore: 68,
    stableTemplate: { governorStates: ["Lagos"], houseLegislators: 4, senateLegislators: 1, cabinetInterests: ["Trade and Investment"] },
    connectionDescriptions: ["Largest auto spare parts importer in West Africa", "His trade association speaks for over fifty thousand traders", "Funds community development projects in Imo from trade profits"],
  },
  {
    name: "Alhaji Dahiru Barau Mangal II",
    zone: "NW", state: "Zamfara", sector: "import-export",
    religion: "Islam", ethnicity: "Hausa",
    description: "Zamfara-based import magnate dealing in everything from electronics to building materials. His logistics network spans from Lagos ports to landlocked northern border towns.",
    traits: { aggression: 72, loyalty: 48, greed: 88, visibility: 18 },
    disposition: "cold", dealStyle: "favour-bank",
    interests: ["trade-liberalization", "import-tariffs", "infrastructure", "northern-development"],
    influenceScore: 72,
    stableTemplate: { governorStates: ["Zamfara"], houseLegislators: 5, senateLegislators: 1, cabinetInterests: ["Trade and Investment"] },
    connectionDescriptions: ["His truck fleet is one of the largest private logistics operations in Nigeria", "Known for operating at the edge of customs regulations", "Major financier of Zamfara state political campaigns", "His trade routes connect Lagos ports to the Sahel"],
  },
  {
    name: "Chief Samuel Obi-Ocheje",
    zone: "NC", state: "Kogi", sector: "import-export",
    religion: "Christianity", ethnicity: "Igala",
    description: "Kogi-born cement and building materials importer who exploits the Lokoja confluence location as a distribution hub. His strategic positioning at the North-South crossroads gives him logistical advantage.",
    traits: { aggression: 45, loyalty: 52, greed: 68, visibility: 35 },
    disposition: "neutral", dealStyle: "contract",
    interests: ["trade-liberalization", "infrastructure", "transport-policy", "north-central-development"],
    influenceScore: 52,
    stableTemplate: { governorStates: ["Kogi"], houseLegislators: 3, senateLegislators: 1, cabinetInterests: ["Trade and Investment"] },
    connectionDescriptions: ["His Lokoja warehouse complex serves as a distribution hub for the Middle Belt", "Exploits the confluence location for river and road transport", "Former chairman of the Kogi State Chamber of Commerce"],
  },
  {
    name: "Chief Babatunde Gbadamosi",
    zone: "SW", state: "Lagos", sector: "import-export",
    religion: "Christianity", ethnicity: "Yoruba",
    description: "Lagos port clearing agent turned shipping magnate. His freight forwarding company handles a significant share of Nigeria's containerized imports through Apapa and Tin Can ports.",
    traits: { aggression: 58, loyalty: 35, greed: 78, visibility: 50 },
    disposition: "neutral", dealStyle: "contract",
    interests: ["maritime-policy", "trade-liberalization", "port-reform", "infrastructure"],
    influenceScore: 66,
    stableTemplate: { governorStates: ["Lagos"], houseLegislators: 4, senateLegislators: 1, cabinetInterests: ["Trade and Investment", "Transportation"] },
    connectionDescriptions: ["His freight company handles ten percent of all containerized imports", "Former president of the Association of Nigerian Licensed Customs Agents", "Close relationships with shipping line executives globally"],
  },
  {
    name: "Alhaji Shehu Malami",
    zone: "NE", state: "Yobe", sector: "import-export",
    religion: "Islam", ethnicity: "Kanuri",
    description: "Yobe-born cross-border trader who controls the informal trade corridor between Nigeria and Niger Republic. His operations straddle the official and unofficial economies.",
    traits: { aggression: 65, loyalty: 70, greed: 72, visibility: 12 },
    disposition: "neutral", dealStyle: "favour-bank",
    interests: ["border-trade", "trade-liberalization", "northeast-reconstruction", "security-spending"],
    influenceScore: 48,
    stableTemplate: { governorStates: ["Yobe"], houseLegislators: 3, senateLegislators: 1, cabinetInterests: ["Trade and Investment"] },
    connectionDescriptions: ["His trade operations cross three international borders daily", "Known to customs and immigration as both cooperator and negotiator", "His networks provide intelligence about cross-border movements"],
  },
  {
    name: "Chief Innocent Chukwuma Jr.",
    zone: "SE", state: "Anambra", sector: "import-export",
    religion: "Christianity", ethnicity: "Igbo",
    description: "Anambra-born vehicle importer who handles the largest volume of used car imports from Europe and America. His Cotonou-to-Lagos import corridor is a logistics masterpiece.",
    traits: { aggression: 50, loyalty: 42, greed: 75, visibility: 45 },
    disposition: "friendly", dealStyle: "contract",
    interests: ["import-tariffs", "automotive-industry", "trade-liberalization", "transport-policy"],
    influenceScore: 62,
    stableTemplate: { governorStates: ["Anambra"], houseLegislators: 5, senateLegislators: 1, cabinetInterests: ["Trade and Investment"] },
    connectionDescriptions: ["Imports the highest volume of vehicles through Cotonou into Nigeria", "His auto yards in Nnewi employ thousands", "Former chairman of the Vehicle Importers Association"],
  },
  {
    name: "Chief Mrs. Bimbo Ashiru",
    zone: "SW", state: "Ogun", sector: "import-export",
    religion: "Christianity", ethnicity: "Yoruba",
    description: "Ogun State agricultural export queen specializing in processed food exports to Europe. Her food processing and export certification facility is the most advanced in West Africa.",
    traits: { aggression: 32, loyalty: 55, greed: 55, visibility: 42 },
    disposition: "friendly", dealStyle: "contract",
    interests: ["export-promotion", "agricultural-policy", "trade-liberalization", "women-empowerment"],
    influenceScore: 50,
    stableTemplate: { governorStates: ["Ogun"], houseLegislators: 2, senateLegislators: 0, cabinetInterests: ["Trade and Investment", "Agriculture"] },
    connectionDescriptions: ["Her facility processes exports meeting EU food safety standards", "Advisory role to NAFDAC on export certification", "Her foundation trains women in agricultural value addition"],
  },
  {
    name: "Alhaji Zubairu Umar",
    zone: "NC", state: "Niger", sector: "import-export",
    religion: "Islam", ethnicity: "Nupe",
    description: "Niger State cross-border pharmaceutical and medical supplies importer. His distribution network ensures drug availability in underserved northern communities, giving him both wealth and goodwill.",
    traits: { aggression: 38, loyalty: 62, greed: 60, visibility: 28 },
    disposition: "friendly", dealStyle: "favour-bank",
    interests: ["healthcare-policy", "trade-liberalization", "northern-development", "infrastructure"],
    influenceScore: 46,
    stableTemplate: { governorStates: ["Niger"], houseLegislators: 3, senateLegislators: 0, cabinetInterests: ["Health", "Trade and Investment"] },
    connectionDescriptions: ["His drug distribution network reaches every LGA in Niger State", "Supplies essential medicines to state government hospitals", "Active in the Nupe community development association"],
  },
  // ═══════════════════════════════════════════════
  // MINING (10 candidates)
  // ═══════════════════════════════════════════════
  {
    name: "Chief Ladi Jadesimi",
    zone: "SW", state: "Lagos", sector: "mining",
    religion: "Christianity", ethnicity: "Yoruba",
    description: "Lagos-based mining investor who holds exploration licences for gold, tin, and columbite across the Middle Belt. His company is the largest private mining operation in Nigeria.",
    traits: { aggression: 52, loyalty: 40, greed: 75, visibility: 45 },
    disposition: "neutral", dealStyle: "contract",
    interests: ["mining-policy", "infrastructure", "power-sector", "foreign-investment"],
    influenceScore: 68,
    stableTemplate: { governorStates: ["Lagos", "Plateau"], houseLegislators: 4, senateLegislators: 1, cabinetInterests: ["Mines and Steel"] },
    connectionDescriptions: ["Holds exploration licences across four Middle Belt states", "His gold mine is the largest in Nigeria", "Former chairman of the Miners Association of Nigeria"],
  },
  {
    name: "Alhaji Tanko Yakasai-Mining",
    zone: "NC", state: "Nasarawa", sector: "mining",
    religion: "Islam", ethnicity: "Eggon",
    description: "Nasarawa-born solid minerals mogul who controls tin and tantalite mining operations across the Jos Plateau. His community relationships are essential for peaceful mining operations.",
    traits: { aggression: 48, loyalty: 65, greed: 70, visibility: 25 },
    disposition: "friendly", dealStyle: "favour-bank",
    interests: ["mining-policy", "north-central-development", "infrastructure", "environmental-policy"],
    influenceScore: 55,
    stableTemplate: { governorStates: ["Nasarawa", "Plateau"], houseLegislators: 5, senateLegislators: 1, cabinetInterests: ["Mines and Steel"] },
    connectionDescriptions: ["His tin mining operations employ over two thousand workers", "Mediates between mining companies and host communities", "Traditional title holder in the Eggon community"],
  },
  {
    name: "Alhaji Suleiman Bakolori",
    zone: "NW", state: "Zamfara", sector: "mining",
    religion: "Islam", ethnicity: "Hausa",
    description: "Zamfara gold mining baron who formalized artisanal mining operations into a licensed industrial operation. His mines have reshaped the local economy but attracted security concerns.",
    traits: { aggression: 70, loyalty: 55, greed: 80, visibility: 20 },
    disposition: "cold", dealStyle: "favour-bank",
    interests: ["mining-policy", "security-spending", "northern-development", "environmental-policy"],
    influenceScore: 60,
    stableTemplate: { governorStates: ["Zamfara"], houseLegislators: 4, senateLegislators: 1, cabinetInterests: ["Mines and Steel"] },
    connectionDescriptions: ["Controls the largest formal gold mining operation in Zamfara", "His security challenges overlap with banditry in the region", "Employs former artisanal miners in structured operations"],
  },
  {
    name: "Chief Emeka Ugwu-Mining",
    zone: "SE", state: "Ebonyi", sector: "mining",
    religion: "Christianity", ethnicity: "Igbo",
    description: "Ebonyi-born lead-zinc mining magnate who built Nigeria's first fully integrated mineral processing facility. His operations transformed Ebonyi from an agricultural backwater into a mining state.",
    traits: { aggression: 45, loyalty: 50, greed: 68, visibility: 35 },
    disposition: "neutral", dealStyle: "contract",
    interests: ["mining-policy", "manufacturing-policy", "southeast-infrastructure", "environmental-policy"],
    influenceScore: 52,
    stableTemplate: { governorStates: ["Ebonyi"], houseLegislators: 3, senateLegislators: 1, cabinetInterests: ["Mines and Steel"] },
    connectionDescriptions: ["His mineral processing plant is the most advanced in Nigeria", "Major employer and taxpayer in Ebonyi State", "His operations supply raw materials to domestic manufacturers"],
  },
  {
    name: "Chief Rotimi Fashola-Mining",
    zone: "SW", state: "Ondo", sector: "mining",
    religion: "Christianity", ethnicity: "Yoruba",
    description: "Ondo State bitumen and tar sand mining pioneer. His company has developed the technology to extract Nigeria's vast bitumen reserves, potentially rivalling oil in future value.",
    traits: { aggression: 40, loyalty: 45, greed: 62, visibility: 50 },
    disposition: "neutral", dealStyle: "contract",
    interests: ["mining-policy", "power-sector", "infrastructure", "environmental-policy"],
    influenceScore: 48,
    stableTemplate: { governorStates: ["Ondo"], houseLegislators: 2, senateLegislators: 0, cabinetInterests: ["Mines and Steel"] },
    connectionDescriptions: ["His bitumen extraction technology is patented in three countries", "His project could create Nigeria's next major export commodity", "Close working relationship with the Ministry of Mines"],
  },
  {
    name: "Alhaji Mohammed Idris-Kogi",
    zone: "NC", state: "Kogi", sector: "mining",
    religion: "Islam", ethnicity: "Igala",
    description: "Kogi-born iron ore and limestone mining tycoon. His quarries supply the nation's cement industry and his iron ore deposits are being developed for Nigeria's steel ambitions.",
    traits: { aggression: 50, loyalty: 58, greed: 72, visibility: 30 },
    disposition: "friendly", dealStyle: "favour-bank",
    interests: ["mining-policy", "manufacturing-policy", "infrastructure", "north-central-development"],
    influenceScore: 56,
    stableTemplate: { governorStates: ["Kogi"], houseLegislators: 4, senateLegislators: 1, cabinetInterests: ["Mines and Steel"] },
    connectionDescriptions: ["His quarries supply limestone to three major cement companies", "His iron ore deposits are central to the Ajaokuta steel revival plans", "Active in the Igala traditional council"],
  },
  {
    name: "Chief Mrs. Nkechi Obi-Minerals",
    zone: "SS", state: "CrossRiver", sector: "mining",
    religion: "Christianity", ethnicity: "Efik",
    description: "Cross River-born gemstone and mineral processing entrepreneur. Her company has developed ethical mining practices that have attracted international ESG investment attention.",
    traits: { aggression: 30, loyalty: 55, greed: 52, visibility: 42 },
    disposition: "friendly", dealStyle: "contract",
    interests: ["mining-policy", "environmental-policy", "foreign-investment", "women-empowerment"],
    influenceScore: 44,
    stableTemplate: { governorStates: ["CrossRiver"], houseLegislators: 2, senateLegislators: 0, cabinetInterests: ["Mines and Steel"] },
    connectionDescriptions: ["Her ethical mining certification has attracted ESG investors", "Only Nigerian mining company with ISO 14001 environmental certification", "Adviser to the Mining Cadastre Office on sustainability"],
  },
  {
    name: "Alhaji Bello Turaki",
    zone: "NE", state: "Taraba", sector: "mining",
    religion: "Islam", ethnicity: "Mumuye",
    description: "Taraba-based gemstone trader and mining licence holder. His sapphire and tourmaline operations in the Mambilla Plateau supply international gem markets through complex export channels.",
    traits: { aggression: 55, loyalty: 50, greed: 75, visibility: 15 },
    disposition: "cold", dealStyle: "favour-bank",
    interests: ["mining-policy", "export-promotion", "northeast-reconstruction", "infrastructure"],
    influenceScore: 45,
    stableTemplate: { governorStates: ["Taraba"], houseLegislators: 2, senateLegislators: 0, cabinetInterests: ["Mines and Steel"] },
    connectionDescriptions: ["His gemstones reach European and Asian markets through Dubai", "Controls mining access on parts of the Mambilla Plateau", "His operations face ongoing tensions with pastoral communities"],
  },
  {
    name: "Chief Oladipo Jadesimi-Quarry",
    zone: "NC", state: "FCT", sector: "mining",
    religion: "Christianity", ethnicity: "Yoruba",
    description: "Abuja-based granite and dimension stone quarry operator whose materials built much of the Federal Capital Territory. His quarries supply every major construction project in the capital.",
    traits: { aggression: 42, loyalty: 48, greed: 65, visibility: 30 },
    disposition: "neutral", dealStyle: "contract",
    interests: ["mining-policy", "infrastructure", "real-estate-policy", "environmental-policy"],
    influenceScore: 50,
    stableTemplate: { governorStates: ["FCT", "Nasarawa"], houseLegislators: 3, senateLegislators: 0, cabinetInterests: ["Mines and Steel", "FCT"] },
    connectionDescriptions: ["His quarries supplied granite for Abuja's National Assembly complex", "Controls the largest dimension stone operation near the FCT", "His materials supply has given him leverage in FCT development decisions"],
  },
  {
    name: "Alhaji Garba Musa-Gusau",
    zone: "NW", state: "Zamfara", sector: "mining",
    religion: "Islam", ethnicity: "Hausa",
    description: "Gusau-based kaolin and clay mining magnate. His processed minerals supply the ceramics and industrial chemicals industries across Nigeria.",
    traits: { aggression: 38, loyalty: 62, greed: 60, visibility: 20 },
    disposition: "neutral", dealStyle: "favour-bank",
    interests: ["mining-policy", "manufacturing-policy", "northern-development", "infrastructure"],
    influenceScore: 42,
    stableTemplate: { governorStates: ["Zamfara"], houseLegislators: 3, senateLegislators: 0, cabinetInterests: ["Mines and Steel"] },
    connectionDescriptions: ["His kaolin supplies the ceramics industry across West Africa", "Largest employer in Gusau after the state government", "Active member of the Zamfara Chamber of Commerce"],
  },
  // ═══════════════════════════════════════════════
  // CONGLOMERATE (10 candidates)
  // ═══════════════════════════════════════════════
  {
    name: "Chief Femi Otedola",
    zone: "SW", state: "Lagos", sector: "conglomerate",
    religion: "Christianity", ethnicity: "Yoruba",
    description: "Lagos-born conglomerate chieftain whose interests span energy, finance, shipping, and real estate. His strategic acquisitions and divestments shape entire industries.",
    traits: { aggression: 75, loyalty: 28, greed: 88, visibility: 75 },
    disposition: "neutral", dealStyle: "contract",
    interests: ["deregulation", "power-sector", "capital-markets", "foreign-investment"],
    influenceScore: 92,
    stableTemplate: { governorStates: ["Lagos", "Ogun", "Ondo"], houseLegislators: 12, senateLegislators: 4, cabinetInterests: ["Finance", "Power"] },
    connectionDescriptions: ["His energy company controls significant power generation capacity", "Major shareholder in two tier-one Nigerian banks", "His philanthropic profile makes him politically untouchable", "Controls one of the largest shipping fleets in West Africa"],
  },
  {
    name: "Alhaji Abdul Samad Isma'il Rabiu",
    zone: "NW", state: "Kano", sector: "conglomerate",
    religion: "Islam", ethnicity: "Hausa",
    description: "Kano-born industrial titan whose conglomerate spans sugar refining, cement manufacturing, flour milling, and real estate. His economic footprint in the North is unmatched by any single enterprise.",
    traits: { aggression: 62, loyalty: 50, greed: 82, visibility: 55 },
    disposition: "friendly", dealStyle: "contract",
    interests: ["manufacturing-policy", "import-tariffs", "northern-development", "infrastructure"],
    influenceScore: 90,
    stableTemplate: { governorStates: ["Kano", "Kaduna", "Sokoto"], houseLegislators: 18, senateLegislators: 5, cabinetInterests: ["Industry", "Trade and Investment"] },
    connectionDescriptions: ["His conglomerate is the largest private employer in northern Nigeria", "Sugar and cement operations have transformed the Northwest's industrial landscape", "His foundation funds hospitals and schools across all six zones", "Key financier of infrastructure bonds in three northern states"],
  },
  {
    name: "Chief Jim Ovia",
    zone: "SS", state: "Delta", sector: "conglomerate",
    religion: "Christianity", ethnicity: "Urhobo",
    description: "Delta-born banker turned conglomerate builder. Starting from banking, he expanded into telecoms, real estate, and education. His institutions educate thousands of Nigeria's next generation.",
    traits: { aggression: 45, loyalty: 50, greed: 70, visibility: 55 },
    disposition: "friendly", dealStyle: "favour-bank",
    interests: ["monetary-policy", "education-funding", "digital-economy", "niger-delta-development"],
    influenceScore: 78,
    stableTemplate: { governorStates: ["Delta", "Lagos"], houseLegislators: 6, senateLegislators: 2, cabinetInterests: ["Finance", "Education"] },
    connectionDescriptions: ["His bank is one of Nigeria's largest by market capitalization", "Founded a private university ranked in Africa's top fifty", "His telecoms investment spans three West African countries"],
  },
  {
    name: "Chief Arthur Eze",
    zone: "SE", state: "Anambra", sector: "conglomerate",
    religion: "Christianity", ethnicity: "Igbo",
    description: "Anambra-born oil and aviation conglomerate owner. His helicopter services fly virtually every oil company executive and politician in Nigeria. Known as a kingmaker in southeastern politics.",
    traits: { aggression: 80, loyalty: 35, greed: 85, visibility: 65 },
    disposition: "cold", dealStyle: "favour-bank",
    interests: ["petroleum-policy", "aviation-policy", "southeast-infrastructure", "trade-liberalization"],
    influenceScore: 85,
    stableTemplate: { governorStates: ["Anambra", "Enugu", "Imo"], houseLegislators: 10, senateLegislators: 3, cabinetInterests: ["Petroleum Resources", "Aviation"] },
    connectionDescriptions: ["His helicopter company is the sole air transport provider for major oil companies", "Openly influences gubernatorial elections across the Southeast", "His oil bloc allocations date back to the military era", "Known for direct personal confrontation with sitting governors"],
  },
  {
    name: "Alhaji Theophilus Danjuma",
    zone: "NC", state: "Plateau", sector: "conglomerate",
    religion: "Christianity", ethnicity: "Jukun",
    description: "Plateau-born retired military general turned business conglomerate chairman. His oil and shipping interests make him one of Nigeria's wealthiest individuals, and his military background commands respect.",
    traits: { aggression: 60, loyalty: 55, greed: 72, visibility: 40 },
    disposition: "neutral", dealStyle: "favour-bank",
    interests: ["petroleum-policy", "security-spending", "maritime-policy", "north-central-development"],
    influenceScore: 82,
    stableTemplate: { governorStates: ["Plateau", "Taraba"], houseLegislators: 7, senateLegislators: 2, cabinetInterests: ["Defence", "Petroleum Resources"] },
    connectionDescriptions: ["Former Chief of Army Staff turned oil bloc owner", "His shipping line handles significant crude oil exports", "His foundation is one of the largest private philanthropic organizations in Nigeria", "Commands respect across both military and civilian political circles"],
  },
  {
    name: "Chief Obi Cubana",
    zone: "SE", state: "Imo", sector: "conglomerate",
    religion: "Christianity", ethnicity: "Igbo",
    description: "Imo-born hospitality and entertainment magnate whose nightclubs, hotels, and real estate empire spans southern Nigeria. His lavish lifestyle and social media presence make him a cultural icon.",
    traits: { aggression: 55, loyalty: 45, greed: 70, visibility: 80 },
    disposition: "friendly", dealStyle: "favour-bank",
    interests: ["tourism-policy", "real-estate-policy", "digital-economy", "southeast-infrastructure"],
    influenceScore: 65,
    stableTemplate: { governorStates: ["Imo"], houseLegislators: 4, senateLegislators: 1, cabinetInterests: ["Tourism"] },
    connectionDescriptions: ["His hotel chain is the largest Nigerian-owned hospitality brand", "Social media following exceeds most politicians", "His events attract political figures from across the spectrum"],
  },
  {
    name: "Alhaji Mohammed Indimi",
    zone: "NE", state: "Borno", sector: "conglomerate",
    religion: "Islam", ethnicity: "Kanuri",
    description: "Borno-born oil and real estate conglomerate patriarch. His oil exploration company operates in multiple African countries, and his political influence in the Northeast is unrivalled.",
    traits: { aggression: 65, loyalty: 60, greed: 78, visibility: 45 },
    disposition: "neutral", dealStyle: "favour-bank",
    interests: ["petroleum-policy", "northeast-reconstruction", "security-spending", "education-funding"],
    influenceScore: 80,
    stableTemplate: { governorStates: ["Borno", "Yobe"], houseLegislators: 8, senateLegislators: 3, cabinetInterests: ["Petroleum Resources"] },
    connectionDescriptions: ["His oil company operates exploration blocks in Chad and Cameroon", "Married into a former head of state's family", "His philanthropic contributions sustained Borno during the insurgency", "His real estate holdings span Abuja, Lagos, and Dubai"],
  },
  {
    name: "Chief Tony Elumelu",
    zone: "SS", state: "Delta", sector: "conglomerate",
    religion: "Christianity", ethnicity: "Ika",
    description: "Delta-born financial sector titan who pioneered Africapitalism. His holding company spans banking, energy, agribusiness, and real estate across twenty African countries.",
    traits: { aggression: 55, loyalty: 40, greed: 72, visibility: 70 },
    disposition: "neutral", dealStyle: "contract",
    interests: ["foreign-investment", "power-sector", "agricultural-policy", "digital-economy"],
    influenceScore: 88,
    stableTemplate: { governorStates: ["Delta", "Lagos"], houseLegislators: 8, senateLegislators: 3, cabinetInterests: ["Finance", "Power"] },
    connectionDescriptions: ["His bank operates in twenty African countries", "His foundation has funded ten thousand African entrepreneurs", "His energy company generates significant power capacity", "Frequently called upon by international leaders for African economic perspectives"],
  },
  {
    name: "Alhaji Alhassan Ado Bayero",
    zone: "NW", state: "Kano", sector: "conglomerate",
    religion: "Islam", ethnicity: "Hausa-Fulani",
    description: "Kano royal family scion who combines traditional authority with business empire spanning banking, agriculture, and manufacturing. His dual role as business leader and traditional institution figure is unique.",
    traits: { aggression: 35, loyalty: 72, greed: 55, visibility: 60 },
    disposition: "friendly", dealStyle: "favour-bank",
    interests: ["northern-development", "islamic-banking", "agricultural-policy", "education-funding"],
    influenceScore: 75,
    stableTemplate: { governorStates: ["Kano"], houseLegislators: 10, senateLegislators: 3, cabinetInterests: ["Agriculture", "Finance"] },
    connectionDescriptions: ["Member of the Kano royal family with traditional authority", "His agricultural holdings span the entire Kano-Jigawa corridor", "His Islamic banking investments bridge traditional and modern finance"],
  },
  {
    name: "Chief Mrs. Stella Okoli",
    zone: "SE", state: "Anambra", sector: "conglomerate",
    religion: "Christianity", ethnicity: "Igbo",
    description: "Anambra-born pharmaceutical and consumer goods conglomerate builder. Her household brands are found in every Nigerian market, and her business acumen has broken glass ceilings across the Southeast.",
    traits: { aggression: 48, loyalty: 52, greed: 65, visibility: 55 },
    disposition: "neutral", dealStyle: "contract",
    interests: ["healthcare-policy", "manufacturing-policy", "women-empowerment", "southeast-infrastructure"],
    influenceScore: 68,
    stableTemplate: { governorStates: ["Anambra", "Lagos"], houseLegislators: 5, senateLegislators: 2, cabinetInterests: ["Health", "Industry"] },
    connectionDescriptions: ["Her pharmaceutical brand is in every Nigerian market", "First female conglomerate CEO in the Southeast", "Her foundation provides free healthcare in rural Anambra communities"],
  },
];
