// client/src/lib/diplomatPoolBatch1.ts
// Hand-crafted diplomat candidates for the 10 key bilateral ambassador posts
// 5 candidates per post, 50 total — diverse across all 6 geopolitical zones

import type { DiplomatCandidate } from "./diplomatTypes";

export const DIPLOMAT_CANDIDATES_BATCH1: DiplomatCandidate[] = [
  // ══════════════════════════════════════════════════════════════
  // POST 1: amb-usa — United States (5 candidates)
  // ══════════════════════════════════════════════════════════════

  {
    name: "Adebayo Ogundimu",
    state: "Lagos",
    zone: "SW",
    age: 58,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "AO",
    traits: ["Career Diplomat", "Diaspora Champion", "Media Savvy"],
    bio: "A 30-year career diplomat who served as Nigeria's Consul-General in Atlanta and Deputy Chief of Mission in Washington. Known for strengthening the Nigerian-American diaspora engagement framework and navigating complex bilateral trade negotiations.",
    education: "University of Lagos (Political Science); Georgetown University (MA International Affairs)",
    competence: 90,
    languageSkills: ["French"],
    qualifiedFor: ["amb-usa", "amb-uk", "amb-canada", "inst-un-ny"],
    competencies: {
      professional: { economics: 72, diplomacy: 92, security: 65, communications: 80, legal: 60, administration: 70, technology: 55, management: 76, politics: 82 },
      personal: { loyalty: 75, charisma: 85, leadership: 80, ambition: 70, integrity: 82, resilience: 78, intrigue: 45, discretion: 81 },
    },
  },
  {
    name: "Halima Bello-Yusuf",
    state: "Kaduna",
    zone: "NW",
    age: 52,
    gender: "Female",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "HB",
    traits: ["Trade Negotiator", "Business Executive", "Multilingual"],
    bio: "Former Director of External Trade at the Federal Ministry of Industry, she brokered Nigeria's largest non-oil export deal with the United States. Her deep understanding of AGOA provisions makes her a formidable trade diplomat.",
    education: "Ahmadu Bello University (Economics); Harvard Kennedy School (MPA)",
    competence: 85,
    languageSkills: ["French"],
    qualifiedFor: ["amb-usa", "amb-germany", "amb-uk", "inst-wto"],
    competencies: {
      professional: { economics: 88, diplomacy: 82, security: 45, communications: 62, legal: 70, administration: 75, technology: 60, management: 84, politics: 88 },
      personal: { loyalty: 70, charisma: 78, leadership: 75, ambition: 82, integrity: 76, resilience: 72, intrigue: 50, discretion: 83 },
    },
  },
  {
    name: "Chukwuemeka Obi",
    state: "Anambra",
    zone: "SE",
    age: 61,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "CO",
    traits: ["Former Senator", "Political Appointee", "Oil Diplomacy Specialist"],
    bio: "Two-term Senator who chaired the Foreign Affairs Committee and led multiple Congressional liaison visits. His extensive Capitol Hill network and understanding of US legislative processes give him unique access to American policy makers.",
    education: "University of Nigeria, Nsukka (Law); Columbia University (LLM International Law)",
    competence: 78,
    languageSkills: ["None"],
    qualifiedFor: ["amb-usa", "amb-uk", "amb-south-africa"],
    competencies: {
      professional: { economics: 65, diplomacy: 80, security: 58, communications: 75, legal: 82, administration: 68, technology: 42, management: 74, politics: 75 },
      personal: { loyalty: 60, charisma: 82, leadership: 78, ambition: 88, integrity: 62, resilience: 70, intrigue: 72, discretion: 67 },
    },
  },
  {
    name: "Aisha Mohammed-Lawal",
    state: "Kwara",
    zone: "NC",
    age: 49,
    gender: "Female",
    religion: "Islam",
    ethnicity: "Nupe",
    avatar: "AM",
    traits: ["Tech Industry Ties", "Academic Diplomat", "Diaspora Champion"],
    bio: "Former Vice Chancellor liaison officer who built partnerships between Nigerian and American universities. Her Silicon Valley connections through the Nigerian tech diaspora make her a bridge between both nations' innovation ecosystems.",
    education: "University of Ilorin (Computer Science); MIT Sloan School (MBA)",
    competence: 75,
    languageSkills: ["None"],
    qualifiedFor: ["amb-usa", "amb-india", "amb-south-korea", "amb-japan"],
    competencies: {
      professional: { economics: 70, diplomacy: 72, security: 40, communications: 68, legal: 50, administration: 65, technology: 90, management: 78, politics: 79 },
      personal: { loyalty: 72, charisma: 76, leadership: 70, ambition: 78, integrity: 80, resilience: 68, intrigue: 35, discretion: 84 },
    },
  },
  {
    name: "Brigadier Emeka Nwankwo (rtd)",
    state: "Imo",
    zone: "SE",
    age: 63,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "EN",
    traits: ["Security Specialist", "Intelligence Background", "UN Experience"],
    bio: "Retired Brigadier who served as Nigeria's Defence Attaché in Washington and later as a UN military observer. His Pentagon contacts and understanding of US-Nigeria security cooperation including counter-terrorism efforts in the Sahel are unmatched.",
    education: "Nigerian Defence Academy (Military Science); National Defense University, Washington (Strategic Security Studies)",
    competence: 80,
    languageSkills: ["French"],
    qualifiedFor: ["amb-usa", "amb-uk", "amb-south-africa", "inst-un-ny"],
    competencies: {
      professional: { economics: 45, diplomacy: 78, security: 92, communications: 55, legal: 52, administration: 72, technology: 48, management: 78, politics: 76 },
      personal: { loyalty: 85, charisma: 68, leadership: 82, ambition: 60, integrity: 78, resilience: 88, intrigue: 65, discretion: 84 },
    },
  },

  // ══════════════════════════════════════════════════════════════
  // POST 2: amb-uk — United Kingdom (5 candidates)
  // ══════════════════════════════════════════════════════════════

  {
    name: "Olufunmilayo Adeyemi",
    state: "Oyo",
    zone: "SW",
    age: 55,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "OA",
    traits: ["Career Diplomat", "Protocol Expert", "Multilingual"],
    bio: "Nigeria's longest-serving diplomat in London, having spent 12 years across two postings at the High Commission. She orchestrated three successful State Visits and is deeply embedded in Commonwealth diplomatic circles.",
    education: "Obafemi Awolowo University (International Relations); University of Oxford (MSc Diplomatic Studies)",
    competence: 88,
    languageSkills: ["French"],
    qualifiedFor: ["amb-uk", "amb-france", "inst-commonwealth", "amb-netherlands"],
    competencies: {
      professional: { economics: 62, diplomacy: 90, security: 50, communications: 72, legal: 65, administration: 78, technology: 45, management: 69, politics: 76 },
      personal: { loyalty: 80, charisma: 82, leadership: 76, ambition: 68, integrity: 85, resilience: 80, intrigue: 42, discretion: 75 },
    },
  },
  {
    name: "Ibrahim Danjuma",
    state: "Taraba",
    zone: "NE",
    age: 60,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Jukun",
    avatar: "ID",
    traits: ["Former Governor", "Political Appointee", "Trade Negotiator"],
    bio: "Former Governor of Taraba State who cultivated strong ties with British development agencies during his tenure. His political clout and understanding of UK-Nigeria development partnerships make him a high-profile candidate.",
    education: "University of Maiduguri (Public Administration); London School of Economics (MSc Development Studies)",
    competence: 72,
    languageSkills: ["None"],
    qualifiedFor: ["amb-uk", "amb-south-africa", "amb-canada"],
    competencies: {
      professional: { economics: 70, diplomacy: 74, security: 55, communications: 68, legal: 60, administration: 80, technology: 40, management: 81, politics: 75 },
      personal: { loyalty: 65, charisma: 80, leadership: 85, ambition: 82, integrity: 58, resilience: 75, intrigue: 68, discretion: 65 },
    },
  },
  {
    name: "Nkechi Eze-Okoli",
    state: "Enugu",
    zone: "SE",
    age: 48,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "NE",
    traits: ["Human Rights Advocate", "Academic Diplomat", "Media Savvy"],
    bio: "A prominent human rights lawyer who served on the UN Human Rights Council and lectured at SOAS University of London. Her advocacy work on migration rights and her BBC profile make her a respected voice in UK-Nigeria relations.",
    education: "University of Nigeria, Nsukka (Law); SOAS University of London (PhD Human Rights Law)",
    competence: 76,
    languageSkills: ["French"],
    qualifiedFor: ["amb-uk", "amb-usa", "inst-icc", "amb-netherlands"],
    competencies: {
      professional: { economics: 50, diplomacy: 78, security: 42, communications: 82, legal: 90, administration: 55, technology: 48, management: 57, politics: 60 },
      personal: { loyalty: 68, charisma: 80, leadership: 72, ambition: 75, integrity: 92, resilience: 76, intrigue: 38, discretion: 77 },
    },
  },
  {
    name: "Abdulrahman Shehu",
    state: "Sokoto",
    zone: "NW",
    age: 57,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Fulani",
    avatar: "AS",
    traits: ["Career Diplomat", "ECOWAS Expert", "AU Veteran"],
    bio: "A career Foreign Service officer with postings in London, Accra, and Addis Ababa. He was instrumental in negotiating Nigeria's post-Brexit trade framework and has strong relationships across the Commonwealth Secretariat.",
    education: "Usman Danfodiyo University (Political Science); University of Cambridge (MPhil International Relations)",
    competence: 82,
    languageSkills: ["French"],
    qualifiedFor: ["amb-uk", "amb-ghana", "amb-south-africa", "inst-commonwealth", "inst-ecowas"],
    competencies: {
      professional: { economics: 65, diplomacy: 88, security: 55, communications: 58, legal: 62, administration: 72, technology: 42, management: 64, politics: 71 },
      personal: { loyalty: 78, charisma: 72, leadership: 74, ambition: 62, integrity: 80, resilience: 82, intrigue: 48, discretion: 72 },
    },
  },
  {
    name: "Ekanem Bassey-Duke",
    state: "Cross River",
    zone: "SS",
    age: 50,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Efik",
    avatar: "EB",
    traits: ["Cultural Ambassador", "Diaspora Champion", "Business Executive"],
    bio: "A successful arts entrepreneur who built bridges between Nollywood and the British film industry. His cultural diplomacy work earned him an OBE and his deep connections in the Nigerian-British community make him a compelling choice.",
    education: "University of Calabar (Theatre Arts); University of Westminster (MA Diplomacy & International Communication)",
    competence: 68,
    languageSkills: ["None"],
    qualifiedFor: ["amb-uk", "amb-usa", "amb-canada"],
    competencies: {
      professional: { economics: 62, diplomacy: 72, security: 35, communications: 88, legal: 45, administration: 58, technology: 55, management: 72, politics: 74 },
      personal: { loyalty: 72, charisma: 90, leadership: 68, ambition: 76, integrity: 70, resilience: 65, intrigue: 55, discretion: 77 },
    },
  },

  // ══════════════════════════════════════════════════════════════
  // POST 3: amb-china — China (Mandarin required) (5 candidates)
  // ══════════════════════════════════════════════════════════════

  {
    name: "Dr. Obiora Nnamdi-Azikiwe",
    honorific: "Dr.",
    state: "Abia",
    zone: "SE",
    age: 54,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "ON",
    traits: ["Trade Negotiator", "Multilingual", "Business Executive"],
    bio: "Spent 15 years in Guangzhou building one of the largest Nigerian trading networks in China. His fluent Mandarin and deep understanding of Chinese business culture make him invaluable for managing Nigeria's most complex bilateral trade relationship.",
    education: "Abia State University (Business Administration); Peking University (MBA, Mandarin proficiency certificate)",
    competence: 84,
    languageSkills: ["Mandarin"],
    qualifiedFor: ["amb-china", "amb-japan", "amb-south-korea", "amb-singapore"],
    competencies: {
      professional: { economics: 85, diplomacy: 78, security: 42, communications: 55, legal: 58, administration: 72, technology: 68, management: 79, politics: 82 },
      personal: { loyalty: 70, charisma: 75, leadership: 72, ambition: 80, integrity: 72, resilience: 82, intrigue: 55, discretion: 84 },
    },
  },
  {
    name: "Fatima Garba-Wali",
    state: "Borno",
    zone: "NE",
    age: 47,
    gender: "Female",
    religion: "Islam",
    ethnicity: "Kanuri",
    avatar: "FG",
    traits: ["Academic Diplomat", "Multilingual", "Tech Industry Ties"],
    bio: "A Confucius Institute director who earned her doctorate at Tsinghua University and speaks fluent Mandarin. Her academic exchanges between Nigerian and Chinese universities and her understanding of China's Belt and Road Initiative are critical assets.",
    education: "University of Maiduguri (Chinese Studies); Tsinghua University (PhD International Development)",
    competence: 79,
    languageSkills: ["Mandarin", "Arabic"],
    qualifiedFor: ["amb-china", "amb-india", "amb-malaysia"],
    competencies: {
      professional: { economics: 68, diplomacy: 80, security: 38, communications: 60, legal: 52, administration: 65, technology: 78, management: 69, politics: 75 },
      personal: { loyalty: 75, charisma: 70, leadership: 68, ambition: 72, integrity: 82, resilience: 74, intrigue: 40, discretion: 80 },
    },
  },
  {
    name: "Yakubu Adamu Musa",
    state: "Nasarawa",
    zone: "NC",
    age: 59,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Eggon",
    avatar: "YA",
    traits: ["Oil Diplomacy Specialist", "Multilingual", "Career Diplomat"],
    bio: "Former NNPC liaison to CNOOC and Sinopec who spent a decade negotiating oil exploration partnerships. His Mandarin skills and intricate knowledge of China's energy diplomacy make him the go-to candidate for managing petroleum-related bilateral matters.",
    education: "Federal University Lafia (Petroleum Engineering); Renmin University (MA Energy Policy, Mandarin certificate)",
    competence: 82,
    languageSkills: ["Mandarin"],
    qualifiedFor: ["amb-china", "amb-indonesia", "amb-malaysia", "inst-opec"],
    competencies: {
      professional: { economics: 82, diplomacy: 76, security: 48, communications: 45, legal: 55, administration: 68, technology: 62, management: 67, politics: 70 },
      personal: { loyalty: 78, charisma: 65, leadership: 70, ambition: 68, integrity: 75, resilience: 80, intrigue: 52, discretion: 76 },
    },
  },
  {
    name: "Adaobi Chukwuma",
    state: "Delta",
    zone: "SS",
    age: 46,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Itsekiri",
    avatar: "AC",
    traits: ["Tech Industry Ties", "Multilingual", "Trade Negotiator"],
    bio: "Led Huawei's West Africa partnerships division before transitioning to public service. Her Mandarin fluency, tech industry networks, and understanding of China's digital infrastructure investments across Africa make her a future-focused candidate.",
    education: "Federal University of Petroleum Technology, Effurun (Computer Engineering); Shanghai Jiao Tong University (MSc Telecom Engineering)",
    competence: 77,
    languageSkills: ["Mandarin"],
    qualifiedFor: ["amb-china", "amb-south-korea", "amb-india", "amb-japan"],
    competencies: {
      professional: { economics: 72, diplomacy: 70, security: 45, communications: 62, legal: 48, administration: 60, technology: 92, management: 70, politics: 72 },
      personal: { loyalty: 68, charisma: 72, leadership: 65, ambition: 85, integrity: 70, resilience: 72, intrigue: 42, discretion: 78 },
    },
  },
  {
    name: "Suleiman Bako",
    state: "Kano",
    zone: "NW",
    age: 62,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "SB",
    traits: ["Career Diplomat", "Multilingual", "Protocol Expert"],
    bio: "Nigeria's former Deputy Ambassador to Beijing with over 20 years in the Foreign Service. He witnessed the evolution of Sino-Nigerian relations firsthand and has cultivated relationships across the Chinese Communist Party's diplomatic corps.",
    education: "Bayero University, Kano (History); Beijing Foreign Studies University (Mandarin Diploma); University of Leeds (MA Diplomacy)",
    competence: 86,
    languageSkills: ["Mandarin", "French"],
    qualifiedFor: ["amb-china", "amb-usa", "amb-japan"],
    competencies: {
      professional: { economics: 62, diplomacy: 92, security: 55, communications: 50, legal: 60, administration: 75, technology: 48, management: 69, politics: 78 },
      personal: { loyalty: 82, charisma: 70, leadership: 75, ambition: 58, integrity: 80, resilience: 85, intrigue: 50, discretion: 77 },
    },
  },

  // ══════════════════════════════════════════════════════════════
  // POST 4: amb-france — France (French required) (5 candidates)
  // ══════════════════════════════════════════════════════════════

  {
    name: "Aminata Abdullahi-Dikko",
    state: "Niger",
    zone: "NC",
    age: 51,
    gender: "Female",
    religion: "Islam",
    ethnicity: "Gwari",
    avatar: "AA",
    traits: ["Career Diplomat", "Multilingual", "ECOWAS Expert"],
    bio: "Born on the Niger-Nigeria border and raised bilingual in French and Hausa, she has served in Francophone postings across West Africa. Her 18-year diplomatic career includes key roles mediating Niger-Nigeria border disputes and ECOWAS integration projects.",
    education: "Ahmadu Bello University (French & International Studies); Sciences Po Paris (Master Affaires Internationales)",
    competence: 87,
    languageSkills: ["French"],
    qualifiedFor: ["amb-france", "amb-niger", "amb-cameroon", "amb-belgium", "inst-ecowas"],
    competencies: {
      professional: { economics: 60, diplomacy: 90, security: 58, communications: 65, legal: 62, administration: 72, technology: 45, management: 77, politics: 84 },
      personal: { loyalty: 78, charisma: 80, leadership: 76, ambition: 68, integrity: 82, resilience: 78, intrigue: 45, discretion: 83 },
    },
  },
  {
    name: "Jean-Pierre Okolie",
    state: "Ebonyi",
    zone: "SE",
    age: 56,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "JO",
    traits: ["Academic Diplomat", "Multilingual", "Cultural Ambassador"],
    bio: "Professor of Francophone Studies at the University of Nigeria who spent a decade at the Sorbonne. His scholarly work on Franco-African relations and his deep cultural networks in Paris's intellectual circles give him a distinctive diplomatic voice.",
    education: "University of Nigeria, Nsukka (French); Sorbonne University (Doctorat Lettres Modernes)",
    competence: 74,
    languageSkills: ["French"],
    qualifiedFor: ["amb-france", "amb-belgium", "amb-switzerland", "amb-senegal"],
    competencies: {
      professional: { economics: 50, diplomacy: 78, security: 35, communications: 72, legal: 55, administration: 58, technology: 42, management: 57, politics: 63 },
      personal: { loyalty: 72, charisma: 78, leadership: 65, ambition: 60, integrity: 85, resilience: 68, intrigue: 38, discretion: 72 },
    },
  },
  {
    name: "Moussa Tanko",
    state: "Adamawa",
    zone: "NE",
    age: 53,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Fulani",
    avatar: "MT",
    traits: ["Career Diplomat", "Multilingual", "Security Specialist"],
    bio: "A career diplomat from the Nigeria-Cameroon border region, fluent in French from childhood. He played a pivotal role in the ICJ Bakassi Peninsula resolution and has served at the Nigerian Embassy in Paris for two separate postings.",
    education: "Federal University of Technology, Yola (International Relations); Institut d'Etudes Politiques de Paris (Certificat d'Etudes Politiques)",
    competence: 83,
    languageSkills: ["French", "Arabic"],
    qualifiedFor: ["amb-france", "amb-cameroon", "amb-chad", "amb-senegal", "inst-au"],
    competencies: {
      professional: { economics: 55, diplomacy: 85, security: 72, communications: 52, legal: 68, administration: 70, technology: 40, management: 82, politics: 86 },
      personal: { loyalty: 80, charisma: 72, leadership: 78, ambition: 62, integrity: 78, resilience: 82, intrigue: 55, discretion: 88 },
    },
  },
  {
    name: "Ngozi Okafor-Dubois",
    state: "Imo",
    zone: "SE",
    age: 48,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "NO",
    traits: ["Trade Negotiator", "Multilingual", "Business Executive"],
    bio: "Married to a French national and based in Lyon for a decade running an import-export business connecting Nigerian agriculture to European markets. Her bilingual family life and EU trade expertise give her authentic cross-cultural credibility.",
    education: "Imo State University (Agricultural Economics); HEC Paris (MBA)",
    competence: 71,
    languageSkills: ["French"],
    qualifiedFor: ["amb-france", "amb-italy", "amb-belgium", "amb-spain"],
    competencies: {
      professional: { economics: 82, diplomacy: 72, security: 35, communications: 58, legal: 55, administration: 65, technology: 52, management: 71, politics: 73 },
      personal: { loyalty: 68, charisma: 76, leadership: 68, ambition: 78, integrity: 72, resilience: 70, intrigue: 48, discretion: 75 },
    },
  },
  {
    name: "Garba Aliyu Madaki",
    state: "Katsina",
    zone: "NW",
    age: 64,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "GA",
    traits: ["Former Senator", "Political Appointee", "Multilingual"],
    bio: "Former Senate Committee Chair on Foreign Affairs who championed Nigeria-France defence cooperation. His fluent French acquired during military training at Saint-Cyr and his political connections make him a heavyweight candidate.",
    education: "Bayero University, Kano (Political Science); Ecole Spéciale Militaire de Saint-Cyr (Defence Studies)",
    competence: 76,
    languageSkills: ["French"],
    qualifiedFor: ["amb-france", "amb-germany", "amb-uk"],
    competencies: {
      professional: { economics: 58, diplomacy: 78, security: 72, communications: 68, legal: 65, administration: 74, technology: 38, management: 70, politics: 68 },
      personal: { loyalty: 62, charisma: 78, leadership: 82, ambition: 80, integrity: 60, resilience: 75, intrigue: 70, discretion: 60 },
    },
  },

  // ══════════════════════════════════════════════════════════════
  // POST 5: amb-germany — Germany (5 candidates)
  // ══════════════════════════════════════════════════════════════

  {
    name: "Dr. Amara Nwosu",
    honorific: "Dr.",
    state: "Abia",
    zone: "SE",
    age: 50,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "AN",
    traits: ["Trade Negotiator", "Academic Diplomat", "Tech Industry Ties"],
    bio: "Former Director of Nigeria-EU trade relations at the Ministry of Foreign Affairs with extensive knowledge of German manufacturing partnerships. She coordinated Volkswagen and Siemens investment projects in Nigeria's industrial zones.",
    education: "University of Port Harcourt (Economics); Technical University of Munich (MSc Industrial Engineering & Management)",
    competence: 81,
    languageSkills: ["French"],
    qualifiedFor: ["amb-germany", "amb-netherlands", "amb-italy", "amb-sweden"],
    competencies: {
      professional: { economics: 85, diplomacy: 80, security: 40, communications: 58, legal: 62, administration: 72, technology: 78, management: 73, politics: 78 },
      personal: { loyalty: 74, charisma: 72, leadership: 70, ambition: 76, integrity: 80, resilience: 74, intrigue: 38, discretion: 79 },
    },
  },
  {
    name: "Bala Maikudi",
    state: "Plateau",
    zone: "NC",
    age: 57,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Berom",
    avatar: "BM",
    traits: ["Career Diplomat", "UN Experience", "Protocol Expert"],
    bio: "A 25-year Foreign Service veteran with postings in Berlin, Vienna, and Geneva. His meticulous diplomatic style and understanding of EU institutional mechanics earned him respect across European capitals.",
    education: "University of Jos (Political Science); Freie Universität Berlin (MA European Studies)",
    competence: 84,
    languageSkills: ["French"],
    qualifiedFor: ["amb-germany", "amb-usa", "amb-uk", "amb-switzerland"],
    competencies: {
      professional: { economics: 65, diplomacy: 88, security: 52, communications: 55, legal: 68, administration: 80, technology: 48, management: 82, politics: 90 },
      personal: { loyalty: 82, charisma: 68, leadership: 72, ambition: 58, integrity: 85, resilience: 80, intrigue: 40, discretion: 89 },
    },
  },
  {
    name: "Hauwa Ibrahim-Waziri",
    state: "Bauchi",
    zone: "NE",
    age: 45,
    gender: "Female",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "HI",
    traits: ["Human Rights Advocate", "Multilingual", "Academic Diplomat"],
    bio: "An international human rights lawyer who worked with German NGOs on Boko Haram displacement programs. Her legal advocacy in German and EU courts and her GIZ development connections make her a strong development-focused candidate.",
    education: "Abubakar Tafawa Balewa University (Law); Heidelberg University (LLM International Humanitarian Law)",
    competence: 73,
    languageSkills: ["French"],
    qualifiedFor: ["amb-germany", "amb-switzerland", "amb-sweden", "inst-icc"],
    competencies: {
      professional: { economics: 52, diplomacy: 75, security: 48, communications: 70, legal: 88, administration: 55, technology: 45, management: 71, politics: 74 },
      personal: { loyalty: 70, charisma: 76, leadership: 68, ambition: 72, integrity: 90, resilience: 78, intrigue: 35, discretion: 93 },
    },
  },
  {
    name: "Olusegun Fagbemi",
    state: "Ondo",
    zone: "SW",
    age: 62,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "OF",
    traits: ["Oil Diplomacy Specialist", "Trade Negotiator", "Business Executive"],
    bio: "Former Managing Director of a German-Nigerian energy joint venture who spent 18 years in Hamburg. His deep industrial connections and understanding of German Mittelstand business culture make him an effective economic diplomat.",
    education: "Federal University of Technology, Akure (Mechanical Engineering); RWTH Aachen University (Dr.-Ing. Process Engineering)",
    competence: 78,
    languageSkills: ["None"],
    qualifiedFor: ["amb-germany", "amb-netherlands", "amb-norway", "inst-opec"],
    competencies: {
      professional: { economics: 82, diplomacy: 72, security: 40, communications: 50, legal: 55, administration: 70, technology: 75, management: 73, politics: 72 },
      personal: { loyalty: 72, charisma: 68, leadership: 74, ambition: 78, integrity: 74, resilience: 80, intrigue: 45, discretion: 78 },
    },
  },
  {
    name: "Musa Usman Gombe",
    state: "Gombe",
    zone: "NE",
    age: 55,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Fulani",
    avatar: "MU",
    traits: ["Career Diplomat", "Security Specialist", "Intelligence Background"],
    bio: "Former Defence Attaché to Germany with a deep understanding of NATO-affiliated security cooperation. His intelligence background and role in coordinating German military training assistance to Nigeria give him unique security diplomacy credentials.",
    education: "Nigerian Defence Academy (Defence Studies); Bundeswehr University Munich (MSc Security Policy)",
    competence: 80,
    languageSkills: ["French"],
    qualifiedFor: ["amb-germany", "amb-france", "amb-turkey"],
    competencies: {
      professional: { economics: 48, diplomacy: 78, security: 90, communications: 45, legal: 55, administration: 72, technology: 52, management: 71, politics: 71 },
      personal: { loyalty: 85, charisma: 62, leadership: 78, ambition: 60, integrity: 76, resilience: 88, intrigue: 62, discretion: 78 },
    },
  },

  // ══════════════════════════════════════════════════════════════
  // POST 6: amb-saudi — Saudi Arabia (Arabic required) (5 candidates)
  // ══════════════════════════════════════════════════════════════

  {
    name: "Sheikh Abubakar Gumi",
    state: "Zamfara",
    zone: "NW",
    age: 63,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "AG",
    traits: ["Career Diplomat", "Multilingual", "Protocol Expert"],
    bio: "A senior career diplomat who served as Deputy Ambassador to Riyadh and managed Nigeria's Hajj Commission operations for a decade. His fluent Arabic and deep familiarity with Saudi royal court protocol make him the most experienced candidate.",
    education: "Usman Danfodiyo University (Arabic & Islamic Studies); King Saud University (MA Political Science)",
    competence: 88,
    languageSkills: ["Arabic"],
    qualifiedFor: ["amb-saudi", "amb-uae", "amb-egypt", "amb-morocco"],
    competencies: {
      professional: { economics: 58, diplomacy: 92, security: 52, communications: 48, legal: 60, administration: 78, technology: 35, management: 83, politics: 90 },
      personal: { loyalty: 82, charisma: 75, leadership: 78, ambition: 62, integrity: 80, resilience: 82, intrigue: 55, discretion: 86 },
    },
  },
  {
    name: "Hajiya Maryam Sani-Abacha",
    state: "Kano",
    zone: "NW",
    age: 49,
    gender: "Female",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "MS",
    traits: ["Oil Diplomacy Specialist", "Multilingual", "Trade Negotiator"],
    bio: "Former NNPC representative to Saudi Aramco who negotiated critical oil pricing agreements. Her Arabic fluency and understanding of OPEC dynamics within the Saudi context make her a vital candidate for Nigeria's energy diplomacy.",
    education: "Bayero University, Kano (Petroleum Chemistry); King Fahd University (MSc Energy Economics)",
    competence: 82,
    languageSkills: ["Arabic"],
    qualifiedFor: ["amb-saudi", "amb-uae", "inst-opec", "amb-algeria"],
    competencies: {
      professional: { economics: 85, diplomacy: 78, security: 42, communications: 52, legal: 55, administration: 68, technology: 58, management: 68, politics: 72 },
      personal: { loyalty: 74, charisma: 72, leadership: 70, ambition: 78, integrity: 72, resilience: 75, intrigue: 48, discretion: 73 },
    },
  },
  {
    name: "Malam Idris Wada",
    state: "Kogi",
    zone: "NC",
    age: 58,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Igala",
    avatar: "IW",
    traits: ["Multilingual", "ECOWAS Expert", "Career Diplomat"],
    bio: "A Foreign Affairs career officer who has served in Jeddah, Cairo, and Rabat. His 20-year immersion in Arab diplomatic circles and his role coordinating Nigeria's OIC membership activities give him unparalleled Middle Eastern credentials.",
    education: "Kogi State University (Arabic Studies); Cairo University (MA Middle Eastern Politics)",
    competence: 80,
    languageSkills: ["Arabic", "French"],
    qualifiedFor: ["amb-saudi", "amb-egypt", "amb-morocco", "amb-uae"],
    competencies: {
      professional: { economics: 58, diplomacy: 84, security: 55, communications: 50, legal: 60, administration: 72, technology: 40, management: 74, politics: 80 },
      personal: { loyalty: 78, charisma: 68, leadership: 72, ambition: 60, integrity: 78, resilience: 80, intrigue: 50, discretion: 81 },
    },
  },
  {
    name: "Zainab Bello-Kano",
    state: "Jigawa",
    zone: "NW",
    age: 46,
    gender: "Female",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "ZB",
    traits: ["Business Executive", "Multilingual", "Diaspora Champion"],
    bio: "Built a thriving Nigerian-Saudi import-export firm specializing in petrochemicals and agricultural produce. Her Arabic fluency and extensive network among the Nigerian community in Riyadh and Jeddah make her an effective bridge between both nations.",
    education: "Bayero University, Kano (Business Administration); Islamic University of Madinah (Arabic & Commerce Diploma)",
    competence: 70,
    languageSkills: ["Arabic"],
    qualifiedFor: ["amb-saudi", "amb-uae", "amb-turkey"],
    competencies: {
      professional: { economics: 80, diplomacy: 68, security: 35, communications: 55, legal: 50, administration: 65, technology: 52, management: 62, politics: 64 },
      personal: { loyalty: 70, charisma: 78, leadership: 65, ambition: 82, integrity: 68, resilience: 72, intrigue: 55, discretion: 67 },
    },
  },
  {
    name: "Colonel Aliyu Modibbo (rtd)",
    state: "Yobe",
    zone: "NE",
    age: 60,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Kanuri",
    avatar: "AM",
    traits: ["Security Specialist", "Multilingual", "Intelligence Background"],
    bio: "Retired Colonel who served as Military Attaché to Saudi Arabia and coordinated counter-terrorism intelligence sharing between Nigerian and Saudi security agencies. His Arabic skills and military-to-military connections are unmatched in the candidate pool.",
    education: "Nigerian Defence Academy (Military Science); Royal Saudi Military Academy (Advanced Course); King's College London (MA War Studies)",
    competence: 78,
    languageSkills: ["Arabic"],
    qualifiedFor: ["amb-saudi", "amb-uae", "amb-egypt", "amb-turkey"],
    competencies: {
      professional: { economics: 42, diplomacy: 74, security: 90, communications: 42, legal: 52, administration: 70, technology: 45, management: 68, politics: 65 },
      personal: { loyalty: 88, charisma: 62, leadership: 80, ambition: 55, integrity: 78, resilience: 90, intrigue: 68, discretion: 77 },
    },
  },

  // ══════════════════════════════════════════════════════════════
  // POST 7: amb-india — India (5 candidates)
  // ══════════════════════════════════════════════════════════════

  {
    name: "Adekunle Ojo-Ajayi",
    state: "Ekiti",
    zone: "SW",
    age: 53,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "AJ",
    traits: ["Tech Industry Ties", "Trade Negotiator", "Academic Diplomat"],
    bio: "Former Director of Nigeria-India tech partnerships at the Ministry of Communications. He coordinated the deployment of Indian IT companies across Nigerian government digital infrastructure projects and has deep ties to Bangalore's tech ecosystem.",
    education: "Ekiti State University (Computer Science); Indian Institute of Technology Delhi (MTech Information Systems)",
    competence: 77,
    languageSkills: ["None"],
    qualifiedFor: ["amb-india", "amb-singapore", "amb-malaysia", "amb-south-korea"],
    competencies: {
      professional: { economics: 72, diplomacy: 75, security: 42, communications: 60, legal: 48, administration: 68, technology: 88, management: 75, politics: 79 },
      personal: { loyalty: 72, charisma: 70, leadership: 68, ambition: 75, integrity: 78, resilience: 72, intrigue: 40, discretion: 82 },
    },
  },
  {
    name: "Sadiya Mustapha-Lawan",
    state: "Borno",
    zone: "NE",
    age: 48,
    gender: "Female",
    religion: "Islam",
    ethnicity: "Kanuri",
    avatar: "SM",
    traits: ["Career Diplomat", "UN Experience", "Human Rights Advocate"],
    bio: "A career diplomat who served as First Secretary at the Nigerian High Commission in New Delhi and later at the UN's South-South Cooperation office. Her work on the India-Africa Summit preparations earned her recognition from both governments.",
    education: "University of Maiduguri (International Studies); Jawaharlal Nehru University (MA International Politics)",
    competence: 80,
    languageSkills: ["French"],
    qualifiedFor: ["amb-india", "amb-south-africa", "amb-kenya", "inst-un-ny"],
    competencies: {
      professional: { economics: 60, diplomacy: 85, security: 48, communications: 62, legal: 65, administration: 70, technology: 50, management: 80, politics: 87 },
      personal: { loyalty: 76, charisma: 74, leadership: 72, ambition: 68, integrity: 85, resilience: 78, intrigue: 40, discretion: 91 },
    },
  },
  {
    name: "Chidi Okonkwo",
    state: "Enugu",
    zone: "SE",
    age: 60,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "CK",
    traits: ["Oil Diplomacy Specialist", "Business Executive", "Trade Negotiator"],
    bio: "Former Chairman of the Nigeria-India Chamber of Commerce who facilitated over $2 billion in bilateral trade deals. His three decades of business between Lagos and Mumbai give him unrivalled commercial diplomacy credentials for this post.",
    education: "University of Nigeria, Nsukka (Business Administration); Indian Institute of Management Ahmedabad (Executive MBA)",
    competence: 75,
    languageSkills: ["None"],
    qualifiedFor: ["amb-india", "amb-indonesia", "amb-south-africa"],
    competencies: {
      professional: { economics: 88, diplomacy: 72, security: 38, communications: 55, legal: 52, administration: 65, technology: 58, management: 77, politics: 77 },
      personal: { loyalty: 65, charisma: 75, leadership: 72, ambition: 80, integrity: 68, resilience: 74, intrigue: 52, discretion: 79 },
    },
  },
  {
    name: "Hajia Rabi Suleiman",
    state: "FCT",
    zone: "NC",
    age: 52,
    gender: "Female",
    religion: "Islam",
    ethnicity: "Gbagyi",
    avatar: "RS",
    traits: ["Career Diplomat", "Multilingual", "AU Veteran"],
    bio: "A seasoned diplomat who coordinated Nigeria's participation in the India-Africa Forum Summit and served at the African Union in Addis Ababa. Her multilateral experience and understanding of India's growing role in African development make her a strategic choice.",
    education: "University of Abuja (Political Science); Delhi University (MA Development Studies); Addis Ababa University (Certificate in AU Affairs)",
    competence: 82,
    languageSkills: ["French"],
    qualifiedFor: ["amb-india", "amb-south-africa", "amb-ethiopia", "inst-au"],
    competencies: {
      professional: { economics: 65, diplomacy: 86, security: 50, communications: 58, legal: 60, administration: 74, technology: 48, management: 75, politics: 80 },
      personal: { loyalty: 80, charisma: 72, leadership: 75, ambition: 65, integrity: 82, resilience: 78, intrigue: 42, discretion: 80 },
    },
  },
  {
    name: "Dr. Emeka Igwe",
    honorific: "Dr.",
    state: "Rivers",
    zone: "SS",
    age: 56,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Ikwerre",
    avatar: "EI",
    traits: ["Academic Diplomat", "Oil Diplomacy Specialist", "Media Savvy"],
    bio: "A petroleum economist who has published extensively on ONGC-NNPC collaboration models. His academic standing at the Indian Council for Research on International Economic Relations and his media presence make him an intellectual heavyweight.",
    education: "University of Port Harcourt (Petroleum Engineering); Indian School of Business (Post-Graduate Programme); University of Delhi (PhD Energy Policy)",
    competence: 73,
    languageSkills: ["None"],
    qualifiedFor: ["amb-india", "amb-china", "amb-indonesia"],
    competencies: {
      professional: { economics: 82, diplomacy: 72, security: 38, communications: 75, legal: 50, administration: 58, technology: 62, management: 68, politics: 71 },
      personal: { loyalty: 68, charisma: 72, leadership: 65, ambition: 70, integrity: 80, resilience: 68, intrigue: 42, discretion: 80 },
    },
  },

  // ══════════════════════════════════════════════════════════════
  // POST 8: amb-south-africa — South Africa (5 candidates)
  // ══════════════════════════════════════════════════════════════

  {
    name: "Folake Adeleke-Johnson",
    state: "Osun",
    zone: "SW",
    age: 54,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "FA",
    traits: ["Career Diplomat", "AU Veteran", "ECOWAS Expert"],
    bio: "Former Director of African Affairs at the Ministry of Foreign Affairs who orchestrated Nigeria's response to xenophobic attacks on Nigerians in South Africa. Her tough-but-diplomatic approach and Pan-Africanist credentials are well known.",
    education: "Obafemi Awolowo University (International Relations); University of Pretoria (MA Diplomatic Studies)",
    competence: 85,
    languageSkills: ["French"],
    qualifiedFor: ["amb-south-africa", "amb-ghana", "amb-kenya", "inst-au", "inst-ecowas"],
    competencies: {
      professional: { economics: 62, diplomacy: 88, security: 58, communications: 70, legal: 65, administration: 74, technology: 45, management: 78, politics: 81 },
      personal: { loyalty: 76, charisma: 80, leadership: 82, ambition: 72, integrity: 78, resilience: 85, intrigue: 48, discretion: 82 },
    },
  },
  {
    name: "Sunday Okoro-Edeh",
    state: "Benue",
    zone: "NC",
    age: 59,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Tiv",
    avatar: "SO",
    traits: ["Diaspora Champion", "Human Rights Advocate", "Media Savvy"],
    bio: "A veteran journalist-turned-diplomat who covered the anti-apartheid movement from Lagos and later served as Nigeria's Consul in Johannesburg. His understanding of the Nigerian diaspora in South Africa and media skills make him a public-facing asset.",
    education: "Benue State University (Mass Communication); University of the Witwatersrand (MA Journalism & Media Studies)",
    competence: 72,
    languageSkills: ["None"],
    qualifiedFor: ["amb-south-africa", "amb-ghana", "amb-kenya"],
    competencies: {
      professional: { economics: 52, diplomacy: 74, security: 45, communications: 90, legal: 55, administration: 60, technology: 48, management: 60, politics: 62 },
      personal: { loyalty: 72, charisma: 82, leadership: 70, ambition: 68, integrity: 80, resilience: 74, intrigue: 45, discretion: 72 },
    },
  },
  {
    name: "Uche Mbanefo",
    state: "Anambra",
    zone: "SE",
    age: 61,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "UM",
    traits: ["Business Executive", "Trade Negotiator", "Oil Diplomacy Specialist"],
    bio: "Former President of the Nigeria-South Africa Chamber of Commerce who managed Dangote Group's South African operations. His commercial networks across Johannesburg, Cape Town, and Durban make him a trade-focused powerhouse candidate.",
    education: "Nnamdi Azikiwe University (Accountancy); University of Cape Town (MBA)",
    competence: 76,
    languageSkills: ["None"],
    qualifiedFor: ["amb-south-africa", "amb-india", "amb-kenya", "amb-ethiopia"],
    competencies: {
      professional: { economics: 85, diplomacy: 72, security: 38, communications: 55, legal: 58, administration: 68, technology: 52, management: 64, politics: 64 },
      personal: { loyalty: 65, charisma: 74, leadership: 72, ambition: 82, integrity: 68, resilience: 72, intrigue: 55, discretion: 64 },
    },
  },
  {
    name: "Fatima Abubakar-Tafida",
    state: "Kebbi",
    zone: "NW",
    age: 47,
    gender: "Female",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "FT",
    traits: ["Career Diplomat", "Multilingual", "UN Experience"],
    bio: "A rising star in the Foreign Service who served at Nigeria's Permanent Mission to the UN and later at the High Commission in Pretoria. Her experience bridging Nigeria-South Africa rivalries at the AU Security Council gives her sharp diplomatic instincts.",
    education: "Kebbi State University (International Studies); University of Stellenbosch (MA International Relations)",
    competence: 79,
    languageSkills: ["French"],
    qualifiedFor: ["amb-south-africa", "amb-ghana", "inst-au", "inst-un-ny"],
    competencies: {
      professional: { economics: 58, diplomacy: 82, security: 55, communications: 60, legal: 62, administration: 70, technology: 45, management: 72, politics: 78 },
      personal: { loyalty: 78, charisma: 74, leadership: 70, ambition: 72, integrity: 80, resilience: 76, intrigue: 42, discretion: 80 },
    },
  },
  {
    name: "Godwin Obaseki-Olu",
    state: "Edo",
    zone: "SS",
    age: 55,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Bini",
    avatar: "GO",
    traits: ["Former Governor", "Political Appointee", "Security Specialist"],
    bio: "Former Deputy Governor who led a high-level trade delegation to South Africa and coordinated the evacuation of Nigerians during the 2019 xenophobic crisis. His crisis management experience and political weight make him a formidable High Commissioner.",
    education: "University of Benin (Political Science); University of Johannesburg (Post-Graduate Diploma in Governance)",
    competence: 70,
    languageSkills: ["None"],
    qualifiedFor: ["amb-south-africa", "amb-usa", "amb-uk"],
    competencies: {
      professional: { economics: 62, diplomacy: 72, security: 68, communications: 65, legal: 55, administration: 78, technology: 42, management: 88, politics: 84 },
      personal: { loyalty: 65, charisma: 78, leadership: 80, ambition: 85, integrity: 58, resilience: 75, intrigue: 68, discretion: 76 },
    },
  },

  // ══════════════════════════════════════════════════════════════
  // POST 9: amb-uae — UAE (Arabic required) (5 candidates)
  // ══════════════════════════════════════════════════════════════

  {
    name: "Alhaji Kabiru Dan-Asabe",
    honorific: "Alhaji",
    state: "Sokoto",
    zone: "NW",
    age: 56,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "KD",
    traits: ["Business Executive", "Multilingual", "Trade Negotiator"],
    bio: "A real estate and logistics magnate with operations across Dubai, Abu Dhabi, and Sharjah. His two decades in the UAE have made him the unofficial leader of the Nigerian business community in the Emirates, with direct access to Emirati royal family members.",
    education: "Usman Danfodiyo University (Estate Management); American University of Sharjah (MBA, Arabic certificate)",
    competence: 75,
    languageSkills: ["Arabic"],
    qualifiedFor: ["amb-uae", "amb-saudi", "amb-turkey", "minor-qatar"],
    competencies: {
      professional: { economics: 85, diplomacy: 72, security: 38, communications: 58, legal: 52, administration: 68, technology: 55, management: 74, politics: 74 },
      personal: { loyalty: 65, charisma: 80, leadership: 72, ambition: 85, integrity: 62, resilience: 75, intrigue: 60, discretion: 73 },
    },
  },
  {
    name: "Aisha Lawal-Kangiwa",
    state: "Kebbi",
    zone: "NW",
    age: 50,
    gender: "Female",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "AL",
    traits: ["Career Diplomat", "Multilingual", "Diaspora Champion"],
    bio: "A career Foreign Service officer who managed consular affairs for Nigeria's 100,000-strong community in the UAE. Her fluent Arabic and intimate knowledge of Emirati immigration, labour, and commercial law make her a protector of Nigerian interests.",
    education: "Usman Danfodiyo University (Arabic & French); Emirates Diplomatic Academy (Post-Graduate Diploma)",
    competence: 81,
    languageSkills: ["Arabic", "French"],
    qualifiedFor: ["amb-uae", "amb-saudi", "amb-egypt", "minor-qatar", "minor-kuwait"],
    competencies: {
      professional: { economics: 62, diplomacy: 84, security: 48, communications: 58, legal: 70, administration: 75, technology: 42, management: 65, politics: 72 },
      personal: { loyalty: 78, charisma: 72, leadership: 70, ambition: 68, integrity: 80, resilience: 78, intrigue: 45, discretion: 71 },
    },
  },
  {
    name: "Nuhu Ribadu-Lamido",
    state: "Adamawa",
    zone: "NE",
    age: 58,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Fulani",
    avatar: "NR",
    traits: ["Intelligence Background", "Multilingual", "Security Specialist"],
    bio: "Former anti-corruption investigator who tracked illicit financial flows through Dubai's banking system. His Arabic proficiency and understanding of UAE financial architecture make him valuable for confronting money laundering and asset recovery issues.",
    education: "University of Maiduguri (Law); Abu Dhabi University (MA Financial Crime); National Institute for Policy and Strategic Studies (Fellowship)",
    competence: 79,
    languageSkills: ["Arabic"],
    qualifiedFor: ["amb-uae", "amb-saudi", "amb-uk", "inst-icc"],
    competencies: {
      professional: { economics: 72, diplomacy: 75, security: 88, communications: 55, legal: 80, administration: 65, technology: 52, management: 70, politics: 70 },
      personal: { loyalty: 80, charisma: 68, leadership: 75, ambition: 72, integrity: 82, resilience: 85, intrigue: 70, discretion: 84 },
    },
  },
  {
    name: "Maimuna Ciroma",
    state: "Yobe",
    zone: "NE",
    age: 45,
    gender: "Female",
    religion: "Islam",
    ethnicity: "Kanuri",
    avatar: "MC",
    traits: ["Trade Negotiator", "Multilingual", "Tech Industry Ties"],
    bio: "A fintech entrepreneur who built payment platforms connecting Nigerian and Emirati businesses. Her Arabic fluency and deep knowledge of the UAE's non-oil diversification strategy make her a forward-looking candidate for this increasingly important post.",
    education: "University of Maiduguri (Computer Science); Khalifa University (MSc Innovation & Technology Management)",
    competence: 72,
    languageSkills: ["Arabic"],
    qualifiedFor: ["amb-uae", "amb-saudi", "amb-india"],
    competencies: {
      professional: { economics: 78, diplomacy: 68, security: 38, communications: 60, legal: 50, administration: 62, technology: 85, management: 57, politics: 58 },
      personal: { loyalty: 70, charisma: 75, leadership: 65, ambition: 80, integrity: 72, resilience: 70, intrigue: 45, discretion: 64 },
    },
  },
  {
    name: "Dr. Ismail Baba-Ahmed",
    honorific: "Dr.",
    state: "Kaduna",
    zone: "NW",
    age: 65,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "IB",
    traits: ["Oil Diplomacy Specialist", "Multilingual", "Career Diplomat"],
    bio: "Former OPEC delegate and Nigeria's longest-serving energy diplomat in the Gulf region. His Arabic fluency and four-decade career navigating OPEC politics between Riyadh, Abu Dhabi, and Vienna make him the most seasoned Gulf specialist in the pool.",
    education: "Ahmadu Bello University (Economics); University of Baghdad (MA Petroleum Economics); Vienna Diplomatic Academy (Certificate)",
    competence: 85,
    languageSkills: ["Arabic", "French"],
    qualifiedFor: ["amb-uae", "amb-saudi", "inst-opec", "amb-algeria"],
    competencies: {
      professional: { economics: 82, diplomacy: 85, security: 45, communications: 48, legal: 55, administration: 72, technology: 38, management: 81, politics: 86 },
      personal: { loyalty: 80, charisma: 70, leadership: 75, ambition: 58, integrity: 78, resilience: 82, intrigue: 52, discretion: 87 },
    },
  },

  // ══════════════════════════════════════════════════════════════
  // POST 10: amb-brazil — Brazil (Portuguese required) (5 candidates)
  // ══════════════════════════════════════════════════════════════

  {
    name: "Dr. Adebola Oladimeji",
    honorific: "Dr.",
    state: "Ogun",
    zone: "SW",
    age: 52,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "DO",
    traits: ["Cultural Ambassador", "Multilingual", "Academic Diplomat"],
    bio: "A professor of Afro-Brazilian studies who has spent years researching the Yoruba cultural diaspora in Salvador and Rio de Janeiro. His fluent Portuguese and cultural bridge-building between Nigeria's Yoruba heritage and Brazil's Afro-descendant communities are uniquely valuable.",
    education: "University of Ibadan (History); University of São Paulo (PhD Afro-Brazilian Studies)",
    competence: 74,
    languageSkills: ["Portuguese", "French"],
    qualifiedFor: ["amb-brazil", "minor-portugal", "minor-angola", "minor-mozambique"],
    competencies: {
      professional: { economics: 48, diplomacy: 78, security: 35, communications: 72, legal: 50, administration: 55, technology: 42, management: 63, politics: 70 },
      personal: { loyalty: 75, charisma: 82, leadership: 65, ambition: 62, integrity: 85, resilience: 70, intrigue: 38, discretion: 81 },
    },
  },
  {
    name: "Blessing Ogiemwonyi",
    state: "Edo",
    zone: "SS",
    age: 47,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Bini",
    avatar: "BO",
    traits: ["Trade Negotiator", "Multilingual", "Business Executive"],
    bio: "Former Director of South-South Trade at the Nigerian Export Promotion Council who tripled Nigeria-Brazil agricultural trade. Her fluent Portuguese and deep understanding of Mercosur trade mechanisms make her a results-oriented candidate.",
    education: "University of Benin (Agricultural Economics); Fundação Getulio Vargas, São Paulo (MBA International Business)",
    competence: 78,
    languageSkills: ["Portuguese"],
    qualifiedFor: ["amb-brazil", "minor-portugal", "minor-argentina", "amb-south-africa"],
    competencies: {
      professional: { economics: 85, diplomacy: 75, security: 38, communications: 58, legal: 52, administration: 68, technology: 50, management: 66, politics: 69 },
      personal: { loyalty: 72, charisma: 76, leadership: 70, ambition: 78, integrity: 74, resilience: 72, intrigue: 42, discretion: 70 },
    },
  },
  {
    name: "Ahmed Tijani Sule",
    state: "Plateau",
    zone: "NC",
    age: 55,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Angas",
    avatar: "AT",
    traits: ["Career Diplomat", "Multilingual", "Oil Diplomacy Specialist"],
    bio: "Served as Counsellor at the Nigerian Embassy in Brasília and later coordinated NNPC's partnerships with Petrobras on deep-water drilling technology. His Portuguese fluency and energy sector expertise make him a dual-track diplomat.",
    education: "University of Jos (Political Science); Universidade de Brasília (Mestrado em Relações Internacionais)",
    competence: 80,
    languageSkills: ["Portuguese", "French"],
    qualifiedFor: ["amb-brazil", "minor-angola", "minor-mozambique", "inst-opec"],
    competencies: {
      professional: { economics: 75, diplomacy: 82, security: 45, communications: 50, legal: 55, administration: 70, technology: 55, management: 66, politics: 71 },
      personal: { loyalty: 78, charisma: 70, leadership: 72, ambition: 65, integrity: 78, resilience: 80, intrigue: 45, discretion: 74 },
    },
  },
  {
    name: "Ifeoma Uzoma-Silva",
    state: "Akwa Ibom",
    zone: "SS",
    age: 49,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Ibibio",
    avatar: "IU",
    traits: ["Multilingual", "Human Rights Advocate", "Diaspora Champion"],
    bio: "A human rights lawyer who lived in Rio de Janeiro for eight years defending the rights of African migrants in Brazil. Her fluent Portuguese, legal expertise, and grassroots connections with the Afro-Brazilian community make her a people-centred diplomat.",
    education: "University of Uyo (Law); Pontifícia Universidade Católica do Rio de Janeiro (LLM Human Rights)",
    competence: 71,
    languageSkills: ["Portuguese"],
    qualifiedFor: ["amb-brazil", "minor-portugal", "minor-argentina"],
    competencies: {
      professional: { economics: 50, diplomacy: 74, security: 40, communications: 68, legal: 85, administration: 55, technology: 42, management: 56, politics: 59 },
      personal: { loyalty: 72, charisma: 78, leadership: 68, ambition: 70, integrity: 88, resilience: 75, intrigue: 38, discretion: 76 },
    },
  },
  {
    name: "Babajide Fashola-Martins",
    state: "Lagos",
    zone: "SW",
    age: 58,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "BF",
    traits: ["Political Appointee", "Multilingual", "Media Savvy"],
    bio: "Former Special Adviser on International Cooperation to the Lagos State Government who forged the Lagos-São Paulo sister-city partnership. His Portuguese skills and experience managing high-profile cultural exchange programmes make him a visible and charismatic candidate.",
    education: "University of Lagos (Public Administration); Universidade Federal do Rio de Janeiro (MBA Public Policy & Governance)",
    competence: 69,
    languageSkills: ["Portuguese"],
    qualifiedFor: ["amb-brazil", "minor-portugal", "amb-south-africa", "amb-usa"],
    competencies: {
      professional: { economics: 62, diplomacy: 72, security: 38, communications: 82, legal: 50, administration: 70, technology: 48, management: 76, politics: 76 },
      personal: { loyalty: 65, charisma: 85, leadership: 72, ambition: 78, integrity: 65, resilience: 68, intrigue: 55, discretion: 72 },
    },
  },
];
