import type { DiplomatCandidate } from "./diplomatTypes";

// ── Diplomat Institution Candidate Pool ──
// 50 hand-crafted candidates for 10 international institution posts
// 5 candidates per post, each qualified for their primary post + 2-4 others

export const DIPLOMAT_INSTITUTION_CANDIDATES: DiplomatCandidate[] = [
  // ═══════════════════════════════════════════════════════════════════
  // POST 1: inst-un-ny — United Nations (New York)
  // ═══════════════════════════════════════════════════════════════════
  {
    name: "Amina Bello-Kankara",
    state: "Katsina",
    zone: "NW",
    age: 58,
    gender: "Female",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "AB",
    traits: ["Career Diplomat", "UN Experience", "Multilingual"],
    bio: "A 30-year career diplomat who served on the UN Security Council reform committee and chaired the General Assembly's Fifth Committee on Administrative and Budgetary matters. Known for her deft navigation of multilateral politics and deep institutional knowledge of the UN system.",
    education: "ABU Zaria (Political Science); MPA, Columbia University; Diploma in International Law, The Hague Academy",
    competence: 93,
    languageSkills: ["French", "Arabic"],
    qualifiedFor: ["inst-un-ny", "inst-un-geneva", "inst-au", "inst-commonwealth"],
    competencies: {
      professional: { economics: 62, diplomacy: 94, security: 55, communications: 68, legal: 72, administration: 78, technology: 40, management: 84, politics: 87 },
      personal: { loyalty: 70, charisma: 82, leadership: 88, ambition: 75, integrity: 85, resilience: 90, intrigue: 60, discretion: 89 },
    },
  },
  {
    name: "Emeka Okonkwo",
    state: "Anambra",
    zone: "SE",
    age: 61,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "EO",
    traits: ["Career Diplomat", "UN Experience", "Human Rights Advocate"],
    bio: "Former Deputy Permanent Representative to the UN who led Nigeria's campaign for a non-permanent Security Council seat. His expertise in peacekeeping mandates and human rights resolutions has earned him recognition across the African Group at the UN.",
    education: "UNN (International Relations); PhD, Georgetown University; Harvard Kennedy School Executive Programme",
    competence: 90,
    languageSkills: ["French"],
    qualifiedFor: ["inst-un-ny", "inst-icc", "inst-commonwealth", "inst-au"],
    competencies: {
      professional: { economics: 55, diplomacy: 92, security: 68, communications: 65, legal: 78, administration: 70, technology: 35, management: 88, politics: 91 },
      personal: { loyalty: 65, charisma: 78, leadership: 85, ambition: 80, integrity: 88, resilience: 82, intrigue: 55, discretion: 95 },
    },
  },
  {
    name: "Hauwa Suleiman",
    state: "Adamawa",
    zone: "NE",
    age: 54,
    gender: "Female",
    religion: "Islam",
    ethnicity: "Fulani",
    avatar: "HS",
    traits: ["UN Experience", "Multilingual", "Academic Diplomat"],
    bio: "Distinguished scholar-diplomat who directed the UN Institute for Training and Research (UNITAR) Africa desk. Her work on Sustainable Development Goal monitoring frameworks for African states has been widely cited in UN General Assembly deliberations.",
    education: "University of Maiduguri (Sociology); MSc, LSE; PhD, Sciences Po Paris",
    competence: 87,
    languageSkills: ["French", "Arabic"],
    qualifiedFor: ["inst-un-ny", "inst-un-geneva", "inst-afdb", "inst-ecowas"],
    competencies: {
      professional: { economics: 70, diplomacy: 88, security: 42, communications: 60, legal: 58, administration: 75, technology: 52, management: 87, politics: 92 },
      personal: { loyalty: 72, charisma: 75, leadership: 78, ambition: 68, integrity: 90, resilience: 76, intrigue: 40, discretion: 93 },
    },
  },
  {
    name: "Oluwaseun Adeyemi",
    state: "Oyo",
    zone: "SW",
    age: 56,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "OA",
    traits: ["Career Diplomat", "Media Savvy", "Protocol Expert"],
    bio: "A polished diplomat who served as spokesperson for the African Group at the UN and managed Nigeria's high-profile candidacies for multilateral positions. Known for his media presence and ability to build consensus across regional blocs.",
    education: "UI Ibadan (History); MA, SAIS Johns Hopkins; Executive Certificate, INSEAD",
    competence: 85,
    languageSkills: ["French", "Spanish"],
    qualifiedFor: ["inst-un-ny", "inst-commonwealth", "inst-ecowas"],
    competencies: {
      professional: { economics: 50, diplomacy: 90, security: 45, communications: 88, legal: 55, administration: 65, technology: 42, management: 77, politics: 85 },
      personal: { loyalty: 68, charisma: 90, leadership: 75, ambition: 82, integrity: 72, resilience: 70, intrigue: 65, discretion: 78 },
    },
  },
  {
    name: "Dakachi Gyang",
    state: "Plateau",
    zone: "NC",
    age: 60,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Berom",
    avatar: "DG",
    traits: ["Career Diplomat", "Security Specialist", "UN Experience"],
    bio: "Veteran diplomat who coordinated Nigeria's peacekeeping contributions across five UN missions and chaired the Special Committee on Peacekeeping Operations (C-34). His deep understanding of peace and security architecture makes him a formidable multilateral operator.",
    education: "University of Jos (Political Science); MA, King's College London; NDC, National Defence College Abuja",
    competence: 88,
    languageSkills: ["French"],
    qualifiedFor: ["inst-un-ny", "inst-au", "inst-ecowas", "inst-commonwealth"],
    competencies: {
      professional: { economics: 45, diplomacy: 90, security: 85, communications: 55, legal: 60, administration: 72, technology: 38, management: 84, politics: 85 },
      personal: { loyalty: 80, charisma: 70, leadership: 88, ambition: 65, integrity: 82, resilience: 92, intrigue: 58, discretion: 91 },
    },
  },

  // ═══════════════════════════════════════════════════════════════════
  // POST 2: inst-un-geneva — UN Office Geneva (French required)
  // ═══════════════════════════════════════════════════════════════════
  {
    name: "Fatima Dantata",
    state: "Kano",
    zone: "NW",
    age: 55,
    gender: "Female",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "FD",
    traits: ["Career Diplomat", "Multilingual", "Human Rights Advocate"],
    bio: "Served as Nigeria's representative on the UN Human Rights Council in Geneva for two terms, leading the Universal Periodic Review process for African states. Fluent in French and Arabic, she is deeply embedded in the Geneva diplomatic circuit.",
    education: "BUK (French/International Studies); Maîtrise, Université de Paris-Sorbonne; LLM, Graduate Institute Geneva",
    competence: 91,
    languageSkills: ["French", "Arabic"],
    qualifiedFor: ["inst-un-geneva", "inst-un-ny", "inst-icc", "inst-au"],
    competencies: {
      professional: { economics: 50, diplomacy: 92, security: 48, communications: 62, legal: 82, administration: 68, technology: 38, management: 69, politics: 74 },
      personal: { loyalty: 72, charisma: 80, leadership: 82, ambition: 70, integrity: 92, resilience: 85, intrigue: 45, discretion: 83 },
    },
  },
  {
    name: "Chukwuemeka Nwosu",
    state: "Imo",
    zone: "SE",
    age: 52,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "CN",
    traits: ["UN Experience", "Multilingual", "Academic Diplomat"],
    bio: "Former WHO Nigeria liaison officer who transitioned to Geneva-based multilateral diplomacy, specializing in global health governance and pandemic preparedness frameworks. His academic credentials and fluent French make him a natural fit for Geneva institutions.",
    education: "IMSU (Medicine/Public Health); MPH, Université de Genève; PhD, University of Cambridge",
    competence: 84,
    languageSkills: ["French"],
    qualifiedFor: ["inst-un-geneva", "inst-un-ny", "inst-wto"],
    competencies: {
      professional: { economics: 58, diplomacy: 85, security: 35, communications: 55, legal: 60, administration: 72, technology: 65, management: 79, politics: 86 },
      personal: { loyalty: 75, charisma: 68, leadership: 72, ambition: 65, integrity: 88, resilience: 78, intrigue: 38, discretion: 90 },
    },
  },
  {
    name: "Aisha Garba-Jibrin",
    state: "Niger",
    zone: "NC",
    age: 49,
    gender: "Female",
    religion: "Islam",
    ethnicity: "Nupe",
    avatar: "AG",
    traits: ["Multilingual", "Trade Negotiator", "Career Diplomat"],
    bio: "Rising star of Nigeria's foreign service who served on the WTO Dispute Settlement Body and the UN Conference on Trade and Development (UNCTAD) secretariat in Geneva. Her fluency in French, English, and Nupe gives her unique cross-cultural reach.",
    education: "University of Ilorin (Economics); DEA, Université de Bordeaux; LLM, University of Bern",
    competence: 82,
    languageSkills: ["French", "Spanish"],
    qualifiedFor: ["inst-un-geneva", "inst-wto", "inst-ecowas", "inst-afdb"],
    competencies: {
      professional: { economics: 78, diplomacy: 84, security: 30, communications: 50, legal: 70, administration: 62, technology: 48, management: 64, politics: 71 },
      personal: { loyalty: 68, charisma: 72, leadership: 70, ambition: 78, integrity: 80, resilience: 75, intrigue: 42, discretion: 76 },
    },
  },
  {
    name: "Obinna Eze",
    state: "Enugu",
    zone: "SE",
    age: 59,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "OE",
    traits: ["Career Diplomat", "UN Experience", "Protocol Expert"],
    bio: "Longest-serving Nigerian diplomat in Geneva, having spent 14 years across the Permanent Mission to the UN Office at Geneva. Expert in disarmament negotiations and the Conference on Disarmament, with impeccable protocol knowledge.",
    education: "UNN (Law); BL, Nigerian Law School; Diplôme, Institut de Hautes Études Internationales, Geneva",
    competence: 89,
    languageSkills: ["French"],
    qualifiedFor: ["inst-un-geneva", "inst-un-ny", "inst-icc", "inst-wto"],
    competencies: {
      professional: { economics: 48, diplomacy: 92, security: 65, communications: 52, legal: 80, administration: 75, technology: 32, management: 87, politics: 94 },
      personal: { loyalty: 82, charisma: 65, leadership: 78, ambition: 58, integrity: 85, resilience: 88, intrigue: 52, discretion: 97 },
    },
  },
  {
    name: "Salamatu Balarabe",
    state: "Kaduna",
    zone: "NW",
    age: 53,
    gender: "Female",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "SB",
    traits: ["Multilingual", "Human Rights Advocate", "Academic Diplomat"],
    bio: "Former member of the UN Committee on the Elimination of Discrimination Against Women (CEDAW) who championed African women's rights frameworks in Geneva. Her bilingual publications on international humanitarian law are widely referenced.",
    education: "ABU Zaria (Law); LLM, Université de Strasbourg; PhD, University of Oxford",
    competence: 86,
    languageSkills: ["French", "Arabic"],
    qualifiedFor: ["inst-un-geneva", "inst-icc", "inst-au", "inst-commonwealth"],
    competencies: {
      professional: { economics: 42, diplomacy: 88, security: 40, communications: 65, legal: 90, administration: 58, technology: 35, management: 74, politics: 80 },
      personal: { loyalty: 70, charisma: 78, leadership: 75, ambition: 72, integrity: 95, resilience: 80, intrigue: 35, discretion: 95 },
    },
  },

  // ═══════════════════════════════════════════════════════════════════
  // POST 3: inst-au — African Union (French required)
  // ═══════════════════════════════════════════════════════════════════
  {
    name: "Ibrahim Waziri",
    state: "Borno",
    zone: "NE",
    age: 62,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Kanuri",
    avatar: "IW",
    traits: ["AU Veteran", "Career Diplomat", "Security Specialist"],
    bio: "Spent a decade at the AU Peace and Security Council, including leading Nigeria's contributions to the African Standby Force. His deep Addis Ababa networks and understanding of continental security architecture are unmatched among Nigerian diplomats.",
    education: "University of Maiduguri (Political Science); MA, Université Cheikh Anta Diop, Dakar; NDC, National Defence College Abuja",
    competence: 92,
    languageSkills: ["French", "Arabic"],
    qualifiedFor: ["inst-au", "inst-ecowas", "inst-un-ny", "inst-afdb"],
    competencies: {
      professional: { economics: 52, diplomacy: 90, security: 88, communications: 50, legal: 58, administration: 75, technology: 35, management: 91, politics: 91 },
      personal: { loyalty: 78, charisma: 72, leadership: 90, ambition: 70, integrity: 80, resilience: 92, intrigue: 65, discretion: 94 },
    },
  },
  {
    name: "Ngozi Achebe",
    state: "Abia",
    zone: "SE",
    age: 56,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "NA",
    traits: ["AU Veteran", "Multilingual", "Diaspora Champion"],
    bio: "Former Director of Citizens and Diaspora Organizations at the AU Commission, she built the continental diaspora engagement framework. Fluent in French and Portuguese, she has extensive networks across Francophone and Lusophone Africa.",
    education: "ABSU (French); Maîtrise, Université de Yaoundé; MA, Fletcher School of Law and Diplomacy, Tufts",
    competence: 85,
    languageSkills: ["French", "Portuguese"],
    qualifiedFor: ["inst-au", "inst-ecowas", "inst-afdb", "inst-un-ny"],
    competencies: {
      professional: { economics: 55, diplomacy: 86, security: 42, communications: 70, legal: 52, administration: 78, technology: 48, management: 74, politics: 78 },
      personal: { loyalty: 65, charisma: 82, leadership: 78, ambition: 75, integrity: 78, resilience: 72, intrigue: 50, discretion: 71 },
    },
  },
  {
    name: "Adamu Ciroma",
    state: "Jigawa",
    zone: "NW",
    age: 63,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa-Fulani",
    avatar: "AC",
    traits: ["AU Veteran", "Career Diplomat", "ECOWAS Expert"],
    bio: "A pillar of Nigeria's Pan-African diplomacy who chaired the AU's NEPAD Implementation Committee and mediated the AU's engagement in the Lake Chad Basin crisis. His fluent French and decades of continental diplomacy give him unrivalled institutional knowledge.",
    education: "BUK (Public Administration); Diplôme, ENA Paris; MSc, SOAS University of London",
    competence: 90,
    languageSkills: ["French"],
    qualifiedFor: ["inst-au", "inst-ecowas", "inst-un-ny", "inst-afdb", "inst-commonwealth"],
    competencies: {
      professional: { economics: 60, diplomacy: 92, security: 70, communications: 55, legal: 50, administration: 82, technology: 30, management: 85, politics: 87 },
      personal: { loyalty: 85, charisma: 75, leadership: 88, ambition: 62, integrity: 78, resilience: 85, intrigue: 58, discretion: 82 },
    },
  },
  {
    name: "Grace Tarka",
    state: "Benue",
    zone: "NC",
    age: 51,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Tiv",
    avatar: "GT",
    traits: ["Multilingual", "Cultural Ambassador", "AU Veteran"],
    bio: "Led Nigeria's cultural diplomacy at the AU, managing the African Cultural Renaissance Charter implementation. Her work connecting Nigeria's creative economy to continental platforms and her fluent French have made her a distinctive voice in Addis Ababa.",
    education: "Benue State University (French/Arts); MA, Université de Montréal; PhD, University of Cape Town",
    competence: 78,
    languageSkills: ["French"],
    qualifiedFor: ["inst-au", "inst-ecowas", "inst-commonwealth"],
    competencies: {
      professional: { economics: 45, diplomacy: 82, security: 30, communications: 78, legal: 40, administration: 65, technology: 50, management: 62, politics: 69 },
      personal: { loyalty: 72, charisma: 85, leadership: 68, ambition: 60, integrity: 82, resilience: 70, intrigue: 35, discretion: 71 },
    },
  },
  {
    name: "Mohammed Abubakar Geidam",
    state: "Yobe",
    zone: "NE",
    age: 57,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Kanuri",
    avatar: "MA",
    traits: ["Career Diplomat", "Security Specialist", "Multilingual"],
    bio: "Former military attaché turned diplomat who coordinated Nigeria-AU collaboration on the Multinational Joint Task Force against Boko Haram. His security diplomacy expertise and French-Arabic bilingualism are critical assets for the Addis Ababa post.",
    education: "NDA Kaduna (Military Science); MSc, Université de Montpellier; MA, King's College London War Studies",
    competence: 83,
    languageSkills: ["French", "Arabic"],
    qualifiedFor: ["inst-au", "inst-un-ny", "inst-ecowas"],
    competencies: {
      professional: { economics: 38, diplomacy: 82, security: 92, communications: 42, legal: 48, administration: 70, technology: 40, management: 67, politics: 67 },
      personal: { loyalty: 88, charisma: 62, leadership: 82, ambition: 68, integrity: 75, resilience: 90, intrigue: 70, discretion: 74 },
    },
  },

  // ═══════════════════════════════════════════════════════════════════
  // POST 4: inst-ecowas — ECOWAS (French required)
  // ═══════════════════════════════════════════════════════════════════
  {
    name: "Abdulkadir Danmusa",
    state: "Zamfara",
    zone: "NW",
    age: 55,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "AD",
    traits: ["ECOWAS Expert", "Trade Negotiator", "Multilingual"],
    bio: "Architect of the ECOWAS Trade Liberalization Scheme reforms who spent eight years at the ECOWAS Commission in Abuja. His deep knowledge of regional integration protocols and fluent French make him indispensable for West African multilateral diplomacy.",
    education: "Usmanu Danfodiyo University (Economics); MA, Université d'Abidjan; MSc, University of Sussex",
    competence: 88,
    languageSkills: ["French"],
    qualifiedFor: ["inst-ecowas", "inst-wto", "inst-au", "inst-afdb"],
    competencies: {
      professional: { economics: 82, diplomacy: 88, security: 45, communications: 48, legal: 62, administration: 75, technology: 42, management: 80, politics: 85 },
      personal: { loyalty: 72, charisma: 70, leadership: 78, ambition: 75, integrity: 80, resilience: 78, intrigue: 48, discretion: 82 },
    },
  },
  {
    name: "Comfort Adekunle",
    state: "Ondo",
    zone: "SW",
    age: 50,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "CA",
    traits: ["ECOWAS Expert", "Multilingual", "Career Diplomat"],
    bio: "Former head of the ECOWAS Early Warning and Response Network (ECOWARN), she built regional conflict monitoring systems across 15 member states. Her fluent French and deep Abuja-Lomé-Dakar networks are well known across West Africa.",
    education: "FUTA (International Relations); Maîtrise, Université de Lomé; MSc, Uppsala University (Peace and Conflict)",
    competence: 84,
    languageSkills: ["French"],
    qualifiedFor: ["inst-ecowas", "inst-au", "inst-un-ny"],
    competencies: {
      professional: { economics: 50, diplomacy: 86, security: 78, communications: 58, legal: 52, administration: 72, technology: 55, management: 83, politics: 86 },
      personal: { loyalty: 75, charisma: 72, leadership: 80, ambition: 68, integrity: 85, resilience: 82, intrigue: 45, discretion: 91 },
    },
  },
  {
    name: "Yusuf Bello Tambuwal",
    state: "Sokoto",
    zone: "NW",
    age: 58,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Fulani",
    avatar: "YB",
    traits: ["ECOWAS Expert", "Former Senator", "Multilingual"],
    bio: "Two-term senator who chaired the Senate Committee on Foreign Affairs before pivoting to ECOWAS mediation roles across the Sahel. His political gravitas, French fluency, and cross-border Fulani networks give him unparalleled regional reach.",
    education: "Usmanu Danfodiyo University (Law); BL, Nigerian Law School; Diplôme, Institut d'Études Politiques de Paris",
    competence: 80,
    languageSkills: ["French"],
    qualifiedFor: ["inst-ecowas", "inst-au", "inst-un-ny", "inst-afdb"],
    competencies: {
      professional: { economics: 55, diplomacy: 85, security: 62, communications: 72, legal: 75, administration: 68, technology: 28, management: 83, politics: 83 },
      personal: { loyalty: 60, charisma: 82, leadership: 85, ambition: 88, integrity: 65, resilience: 75, intrigue: 72, discretion: 76 },
    },
  },
  {
    name: "Blessing Odiase",
    state: "Edo",
    zone: "SS",
    age: 48,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Edo",
    avatar: "BO",
    traits: ["Multilingual", "Trade Negotiator", "ECOWAS Expert"],
    bio: "Trade policy specialist who negotiated the ECOWAS Common External Tariff implementation for Nigeria. Her bilingual expertise in trade law and regional economic integration has earned her recognition as one of West Africa's top trade diplomats.",
    education: "University of Benin (Law/French); LLM, Université Paris-Dauphine; MBA, IESE Business School Barcelona",
    competence: 82,
    languageSkills: ["French", "Spanish"],
    qualifiedFor: ["inst-ecowas", "inst-wto", "inst-afdb", "inst-au"],
    competencies: {
      professional: { economics: 80, diplomacy: 82, security: 30, communications: 55, legal: 78, administration: 65, technology: 45, management: 62, politics: 67 },
      personal: { loyalty: 68, charisma: 75, leadership: 72, ambition: 78, integrity: 82, resilience: 70, intrigue: 40, discretion: 69 },
    },
  },
  {
    name: "Garba Musa Lafia",
    state: "Nasarawa",
    zone: "NC",
    age: 60,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Eggon",
    avatar: "GM",
    traits: ["ECOWAS Expert", "Security Specialist", "Multilingual"],
    bio: "Coordinated ECOWAS Standby Force deployments to The Gambia and Guinea-Bissau, earning a reputation as the go-to Nigerian for West African peacekeeping operations. His French fluency and military-diplomatic background are ideal for the ECOWAS post.",
    education: "NDA Kaduna (Defence Studies); MA, Université de Dakar; MSc, Cranfield University (Security Sector Management)",
    competence: 81,
    languageSkills: ["French"],
    qualifiedFor: ["inst-ecowas", "inst-au", "inst-un-ny"],
    competencies: {
      professional: { economics: 40, diplomacy: 82, security: 90, communications: 42, legal: 48, administration: 72, technology: 35, management: 84, politics: 84 },
      personal: { loyalty: 85, charisma: 60, leadership: 82, ambition: 58, integrity: 78, resilience: 90, intrigue: 62, discretion: 91 },
    },
  },

  // ═══════════════════════════════════════════════════════════════════
  // POST 5: inst-wto — World Trade Organization (French required)
  // ═══════════════════════════════════════════════════════════════════
  {
    name: "Chibuzo Okoro",
    state: "Delta",
    zone: "SS",
    age: 53,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Urhobo",
    avatar: "CO",
    traits: ["Trade Negotiator", "Multilingual", "Business Executive"],
    bio: "Former lead negotiator for Nigeria at the WTO Doha Round who later served as trade advisor to the ECOWAS Commission. His deep understanding of agricultural subsidies, TRIPS agreements, and Special & Differential Treatment provisions is formidable.",
    education: "University of Ibadan (Economics); LLM, Université de Genève (International Trade Law); MBA, Wharton",
    competence: 90,
    languageSkills: ["French"],
    qualifiedFor: ["inst-wto", "inst-un-geneva", "inst-ecowas", "inst-wb-imf"],
    competencies: {
      professional: { economics: 92, diplomacy: 85, security: 28, communications: 55, legal: 80, administration: 65, technology: 50, management: 80, politics: 83 },
      personal: { loyalty: 62, charisma: 75, leadership: 78, ambition: 82, integrity: 75, resilience: 80, intrigue: 55, discretion: 86 },
    },
  },
  {
    name: "Rahila Danjuma",
    state: "Taraba",
    zone: "NE",
    age: 50,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Jukun",
    avatar: "RD",
    traits: ["Trade Negotiator", "Multilingual", "Career Diplomat"],
    bio: "Specialist in WTO dispute settlement who represented Nigeria in three panel proceedings and served on the Advisory Centre on WTO Law. Her bilingual legal drafting skills and knowledge of trade remedies make her a precision instrument for trade diplomacy.",
    education: "University of Jos (Law/French); BL, Nigerian Law School; LLM, Graduate Institute Geneva; Diplôme, HEC Paris",
    competence: 86,
    languageSkills: ["French"],
    qualifiedFor: ["inst-wto", "inst-un-geneva", "inst-afdb", "inst-ecowas"],
    competencies: {
      professional: { economics: 78, diplomacy: 82, security: 25, communications: 48, legal: 88, administration: 60, technology: 42, management: 62, politics: 67 },
      personal: { loyalty: 70, charisma: 68, leadership: 72, ambition: 75, integrity: 85, resilience: 78, intrigue: 38, discretion: 78 },
    },
  },
  {
    name: "Suleiman Ringim",
    state: "Jigawa",
    zone: "NW",
    age: 57,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "SR",
    traits: ["Trade Negotiator", "Multilingual", "Academic Diplomat"],
    bio: "Professor of International Trade Law who advised the Federal Ministry of Industry, Trade and Investment on AfCFTA negotiations. His published work on South-South trade frameworks and fluent French make him a thought leader in multilateral trade policy.",
    education: "BUK (Economics); MA, Université Laval Québec; PhD, University of Cambridge (Development Economics)",
    competence: 83,
    languageSkills: ["French"],
    qualifiedFor: ["inst-wto", "inst-afdb", "inst-ecowas", "inst-wb-imf"],
    competencies: {
      professional: { economics: 90, diplomacy: 78, security: 22, communications: 60, legal: 72, administration: 55, technology: 48, management: 58, politics: 63 },
      personal: { loyalty: 65, charisma: 72, leadership: 68, ambition: 70, integrity: 88, resilience: 72, intrigue: 32, discretion: 76 },
    },
  },
  {
    name: "Ifeoma Nwankpa",
    state: "Ebonyi",
    zone: "SE",
    age: 52,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "IN",
    traits: ["Trade Negotiator", "Multilingual", "Business Executive"],
    bio: "Former CEO of the Nigerian Export Promotion Council who led the country's non-oil export diversification strategy. Her fluent French, private sector experience, and expertise in trade facilitation agreements give her a practical edge in WTO negotiations.",
    education: "EBSU (Business Administration); MBA, Lagos Business School; MSc, Université Paris-Dauphine (International Economics)",
    competence: 80,
    languageSkills: ["French"],
    qualifiedFor: ["inst-wto", "inst-ecowas", "inst-afdb"],
    competencies: {
      professional: { economics: 85, diplomacy: 78, security: 20, communications: 62, legal: 58, administration: 80, technology: 55, management: 69, politics: 70 },
      personal: { loyalty: 68, charisma: 78, leadership: 75, ambition: 80, integrity: 72, resilience: 68, intrigue: 42, discretion: 61 },
    },
  },
  {
    name: "Murtala Kwankwaso",
    state: "Kano",
    zone: "NW",
    age: 61,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "MK",
    traits: ["Trade Negotiator", "Former Governor", "Multilingual"],
    bio: "Former state commissioner for commerce who rose to become Nigeria's chief negotiator on the ECOWAS Common Investment Code. His political connections, French fluency, and understanding of Nigeria's industrial policy give him both technical depth and political weight.",
    education: "BUK (Accounting); MSc, Université de Lyon (Trade Policy); Executive Programme, Harvard Kennedy School",
    competence: 77,
    languageSkills: ["French"],
    qualifiedFor: ["inst-wto", "inst-ecowas", "inst-afdb", "inst-opec"],
    competencies: {
      professional: { economics: 82, diplomacy: 80, security: 30, communications: 65, legal: 55, administration: 72, technology: 35, management: 72, politics: 73 },
      personal: { loyalty: 58, charisma: 80, leadership: 78, ambition: 85, integrity: 62, resilience: 72, intrigue: 68, discretion: 64 },
    },
  },

  // ═══════════════════════════════════════════════════════════════════
  // POST 6: inst-icc — International Criminal Court (No language req)
  // ═══════════════════════════════════════════════════════════════════
  {
    name: "Olumide Babalola",
    state: "Osun",
    zone: "SW",
    age: 59,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "OB",
    traits: ["Career Diplomat", "Human Rights Advocate", "Academic Diplomat"],
    bio: "Former judge ad litem at the International Criminal Tribunal for Rwanda and Nigeria's representative to the ICC Assembly of States Parties. His expertise in international criminal law, transitional justice, and complementarity principles is unmatched in the Nigerian diplomatic corps.",
    education: "OAU Ile-Ife (Law); LLM, Yale Law School; PhD, Leiden University (International Criminal Law)",
    competence: 94,
    languageSkills: ["French"],
    qualifiedFor: ["inst-icc", "inst-un-ny", "inst-un-geneva", "inst-commonwealth"],
    competencies: {
      professional: { economics: 35, diplomacy: 85, security: 55, communications: 60, legal: 95, administration: 62, technology: 30, management: 61, politics: 64 },
      personal: { loyalty: 72, charisma: 70, leadership: 80, ambition: 68, integrity: 95, resilience: 85, intrigue: 40, discretion: 80 },
    },
  },
  {
    name: "Zainab Mohammed-Lawal",
    state: "Kwara",
    zone: "NC",
    age: 54,
    gender: "Female",
    religion: "Islam",
    ethnicity: "Yoruba",
    avatar: "ZM",
    traits: ["Human Rights Advocate", "Career Diplomat", "Multilingual"],
    bio: "Former legal advisor to the Nigerian National Human Rights Commission who served as amicus curiae in multiple ICC preliminary examinations. Her expertise in victims' participation and reparations frameworks has shaped Nigeria's engagement with international justice.",
    education: "University of Ilorin (Law); BL, Nigerian Law School; LLM, University of Nottingham; SJD, Harvard Law School",
    competence: 88,
    languageSkills: ["French", "Arabic"],
    qualifiedFor: ["inst-icc", "inst-un-geneva", "inst-un-ny"],
    competencies: {
      professional: { economics: 30, diplomacy: 82, security: 48, communications: 58, legal: 92, administration: 55, technology: 32, management: 60, politics: 64 },
      personal: { loyalty: 75, charisma: 72, leadership: 75, ambition: 65, integrity: 92, resilience: 80, intrigue: 35, discretion: 81 },
    },
  },
  {
    name: "Chidi Anyanwu",
    state: "Abia",
    zone: "SE",
    age: 56,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "CA",
    traits: ["Human Rights Advocate", "Academic Diplomat", "Media Savvy"],
    bio: "Professor of International Humanitarian Law at the Nigerian Institute of International Affairs who advised the Office of the Prosecutor on situation analysis. His publications on command responsibility and conflict-related sexual violence inform ICC jurisprudence.",
    education: "ABSU (Law); LLM, University of Cambridge; PhD, European University Institute Florence",
    competence: 85,
    languageSkills: ["None"],
    qualifiedFor: ["inst-icc", "inst-un-ny", "inst-commonwealth"],
    competencies: {
      professional: { economics: 28, diplomacy: 80, security: 52, communications: 72, legal: 90, administration: 50, technology: 38, management: 64, politics: 68 },
      personal: { loyalty: 68, charisma: 75, leadership: 72, ambition: 70, integrity: 90, resilience: 75, intrigue: 38, discretion: 86 },
    },
  },
  {
    name: "Adesola Martins",
    state: "Lagos",
    zone: "SW",
    age: 49,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "AM",
    traits: ["Human Rights Advocate", "Career Diplomat", "Tech Industry Ties"],
    bio: "Pioneering lawyer who led Nigeria's engagement on the ICC's investigation of cyber-enabled war crimes and digital evidence admissibility. Her work at the intersection of technology, human rights, and international criminal law is cutting-edge.",
    education: "UNILAG (Law); BL, Nigerian Law School; LLM, NYU School of Law; MSc, Stanford (Computer Science)",
    competence: 82,
    languageSkills: ["None"],
    qualifiedFor: ["inst-icc", "inst-un-ny", "inst-commonwealth", "inst-wb-imf"],
    competencies: {
      professional: { economics: 45, diplomacy: 78, security: 50, communications: 68, legal: 88, administration: 55, technology: 80, management: 67, politics: 71 },
      personal: { loyalty: 70, charisma: 78, leadership: 70, ambition: 75, integrity: 85, resilience: 72, intrigue: 42, discretion: 83 },
    },
  },
  {
    name: "Bala Usman",
    state: "FCT",
    zone: "NC",
    age: 62,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Gwari",
    avatar: "BU",
    traits: ["Career Diplomat", "Intelligence Background", "Security Specialist"],
    bio: "Former Director of Legal at the National Intelligence Agency who transitioned to diplomatic service as Nigeria's legal counsel for ICC cooperation matters. His unique combination of intelligence expertise and international law knowledge provides critical perspective on state cooperation obligations.",
    education: "University of Abuja (Law); BL, Nigerian Law School; LLM, University of Amsterdam; Certificate, NATO Defense College Rome",
    competence: 79,
    languageSkills: ["None"],
    qualifiedFor: ["inst-icc", "inst-un-ny", "inst-un-geneva"],
    competencies: {
      professional: { economics: 32, diplomacy: 78, security: 82, communications: 40, legal: 85, administration: 68, technology: 45, management: 73, politics: 76 },
      personal: { loyalty: 90, charisma: 55, leadership: 72, ambition: 60, integrity: 70, resilience: 88, intrigue: 78, discretion: 82 },
    },
  },

  // ═══════════════════════════════════════════════════════════════════
  // POST 7: inst-commonwealth — Commonwealth (No language req)
  // ═══════════════════════════════════════════════════════════════════
  {
    name: "Folake Oyediran",
    state: "Ogun",
    zone: "SW",
    age: 57,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "FO",
    traits: ["Career Diplomat", "Diaspora Champion", "Cultural Ambassador"],
    bio: "Former High Commissioner to London who chaired the Commonwealth Ministerial Action Group on governance standards. Her extensive network across the 56-member Commonwealth and deep understanding of the Harare Declaration principles make her a natural leader.",
    education: "OAU Ile-Ife (English/History); MA, University of Edinburgh; MBA, London Business School",
    competence: 89,
    languageSkills: ["None"],
    qualifiedFor: ["inst-commonwealth", "inst-un-ny", "inst-icc", "inst-wb-imf"],
    competencies: {
      professional: { economics: 55, diplomacy: 90, security: 40, communications: 78, legal: 62, administration: 75, technology: 42, management: 74, politics: 77 },
      personal: { loyalty: 72, charisma: 88, leadership: 85, ambition: 72, integrity: 80, resilience: 78, intrigue: 48, discretion: 73 },
    },
  },
  {
    name: "Godwin Emefiele-Obi",
    state: "Rivers",
    zone: "SS",
    age: 54,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Ikwerre",
    avatar: "GO",
    traits: ["Career Diplomat", "Trade Negotiator", "Protocol Expert"],
    bio: "Former Deputy High Commissioner in Ottawa who negotiated the Commonwealth Connectivity Agenda for Trade and Investment. His expertise in Commonwealth trade preferences, visa frameworks, and education partnerships spans two decades of diplomatic service.",
    education: "University of Port Harcourt (Economics); MA, Carleton University Ottawa; Executive Programme, Chatham House London",
    competence: 83,
    languageSkills: ["None"],
    qualifiedFor: ["inst-commonwealth", "inst-un-ny", "inst-wto", "inst-wb-imf"],
    competencies: {
      professional: { economics: 72, diplomacy: 85, security: 35, communications: 60, legal: 55, administration: 70, technology: 48, management: 70, politics: 75 },
      personal: { loyalty: 78, charisma: 72, leadership: 75, ambition: 70, integrity: 78, resilience: 72, intrigue: 42, discretion: 72 },
    },
  },
  {
    name: "Aisha Lawan",
    state: "Bauchi",
    zone: "NE",
    age: 51,
    gender: "Female",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "AL",
    traits: ["Career Diplomat", "Academic Diplomat", "Media Savvy"],
    bio: "Specialist in Commonwealth education and youth development who established Nigeria's Commonwealth Scholarship programme expansion. Her work on democratic governance benchmarking has been adopted across the Commonwealth's African member states.",
    education: "ATBU Bauchi (Education); MA, University of London Institute of Education; PhD, University of Melbourne",
    competence: 76,
    languageSkills: ["None"],
    qualifiedFor: ["inst-commonwealth", "inst-un-ny", "inst-au"],
    competencies: {
      professional: { economics: 48, diplomacy: 80, security: 28, communications: 75, legal: 45, administration: 68, technology: 55, management: 68, politics: 73 },
      personal: { loyalty: 75, charisma: 78, leadership: 70, ambition: 62, integrity: 82, resilience: 72, intrigue: 30, discretion: 76 },
    },
  },
  {
    name: "Tunde Fashola",
    state: "Lagos",
    zone: "SW",
    age: 60,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "TF",
    traits: ["Former Governor", "Media Savvy", "Diaspora Champion"],
    bio: "Former state commissioner for information turned diplomat, who led Nigeria's hosting of the Commonwealth Heads of Government Meeting bid. His political profile, media expertise, and London networks make him a high-visibility representative.",
    education: "UNILAG (Mass Communication); MA, City University London; Executive Certificate, Oxford Said Business School",
    competence: 75,
    languageSkills: ["None"],
    qualifiedFor: ["inst-commonwealth", "inst-un-ny"],
    competencies: {
      professional: { economics: 50, diplomacy: 78, security: 30, communications: 90, legal: 42, administration: 72, technology: 48, management: 73, politics: 72 },
      personal: { loyalty: 60, charisma: 88, leadership: 80, ambition: 85, integrity: 65, resilience: 70, intrigue: 65, discretion: 65 },
    },
  },
  {
    name: "Uche Ikpeazu",
    state: "Abia",
    zone: "SE",
    age: 55,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "UI",
    traits: ["Career Diplomat", "Trade Negotiator", "Diaspora Champion"],
    bio: "Nigeria's foremost expert on Commonwealth preferential trade arrangements who negotiated updated bilateral investment treaties with Commonwealth Pacific Island states. His knowledge of post-Brexit Commonwealth trade realignment is particularly valuable.",
    education: "ABSU (International Relations); MSc, University of Birmingham; PhD, Australian National University",
    competence: 81,
    languageSkills: ["None"],
    qualifiedFor: ["inst-commonwealth", "inst-wto", "inst-wb-imf"],
    competencies: {
      professional: { economics: 75, diplomacy: 82, security: 28, communications: 52, legal: 60, administration: 65, technology: 42, management: 75, politics: 80 },
      personal: { loyalty: 70, charisma: 68, leadership: 72, ambition: 72, integrity: 78, resilience: 75, intrigue: 45, discretion: 83 },
    },
  },

  // ═══════════════════════════════════════════════════════════════════
  // POST 8: inst-opec — OPEC (No language req)
  // ═══════════════════════════════════════════════════════════════════
  {
    name: "Mele Kyari-Dikwa",
    state: "Borno",
    zone: "NE",
    age: 58,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Kanuri",
    avatar: "MK",
    traits: ["Oil Diplomacy Specialist", "Business Executive", "Trade Negotiator"],
    bio: "Former Group General Manager at NNPC who led Nigeria's OPEC quota negotiations during three production cut cycles. His intimate knowledge of global oil markets, OPEC+ dynamics, and upstream petroleum economics makes him the premier oil diplomacy specialist.",
    education: "University of Maiduguri (Geology); MSc, Imperial College London (Petroleum Engineering); MBA, INSEAD",
    competence: 91,
    languageSkills: ["Arabic"],
    qualifiedFor: ["inst-opec", "inst-wb-imf", "inst-wto", "inst-afdb"],
    competencies: {
      professional: { economics: 92, diplomacy: 82, security: 35, communications: 60, legal: 48, administration: 78, technology: 65, management: 72, politics: 72 },
      personal: { loyalty: 72, charisma: 75, leadership: 82, ambition: 78, integrity: 70, resilience: 80, intrigue: 62, discretion: 67 },
    },
  },
  {
    name: "Timipre Ogbe",
    state: "Bayelsa",
    zone: "SS",
    age: 52,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Ijaw",
    avatar: "TO",
    traits: ["Oil Diplomacy Specialist", "Trade Negotiator", "Career Diplomat"],
    bio: "Former Director of International Energy Relations at the Department of Petroleum Resources who served on OPEC's Economic Commission Board. His deep understanding of production quotas, price bands, and the Nigerian oil-gas value chain is exceptional.",
    education: "Niger Delta University (Chemical Engineering); MSc, University of Aberdeen (Oil & Gas); MBA, IMD Lausanne",
    competence: 87,
    languageSkills: ["None"],
    qualifiedFor: ["inst-opec", "inst-wb-imf", "inst-wto"],
    competencies: {
      professional: { economics: 88, diplomacy: 80, security: 30, communications: 52, legal: 45, administration: 72, technology: 60, management: 73, politics: 75 },
      personal: { loyalty: 68, charisma: 70, leadership: 75, ambition: 80, integrity: 72, resilience: 78, intrigue: 55, discretion: 74 },
    },
  },
  {
    name: "Hadiza Umar",
    state: "Kebbi",
    zone: "NW",
    age: 50,
    gender: "Female",
    religion: "Islam",
    ethnicity: "Hausa-Fulani",
    avatar: "HU",
    traits: ["Oil Diplomacy Specialist", "Multilingual", "Business Executive"],
    bio: "Former head of crude oil marketing at NNPC Trading who managed Nigeria's term contract portfolio with major oil-importing nations. Her Arabic fluency and relationships with Gulf OPEC members give her unique leverage in Vienna negotiations.",
    education: "Usmanu Danfodiyo University (Chemistry); MSc, Heriot-Watt University (Petroleum Economics); Executive MBA, London Business School",
    competence: 84,
    languageSkills: ["Arabic"],
    qualifiedFor: ["inst-opec", "inst-wb-imf", "inst-afdb"],
    competencies: {
      professional: { economics: 88, diplomacy: 78, security: 25, communications: 55, legal: 40, administration: 75, technology: 58, management: 64, politics: 68 },
      personal: { loyalty: 70, charisma: 72, leadership: 70, ambition: 82, integrity: 68, resilience: 75, intrigue: 50, discretion: 63 },
    },
  },
  {
    name: "Emeka Onyejekwe",
    state: "Anambra",
    zone: "SE",
    age: 55,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "EO",
    traits: ["Oil Diplomacy Specialist", "Academic Diplomat", "Trade Negotiator"],
    bio: "Professor of Energy Economics who served as Nigeria's alternate governor on the OPEC Board and published influential analysis on OPEC-Russia coordination. His academic credibility and deep data analytics capability inform Nigeria's petroleum pricing strategy.",
    education: "UNN (Economics); PhD, University of Surrey (Energy Economics); Post-doc, Stanford University (Energy Modelling)",
    competence: 82,
    languageSkills: ["None"],
    qualifiedFor: ["inst-opec", "inst-wb-imf", "inst-wto"],
    competencies: {
      professional: { economics: 92, diplomacy: 75, security: 22, communications: 58, legal: 42, administration: 60, technology: 72, management: 65, politics: 69 },
      personal: { loyalty: 65, charisma: 65, leadership: 68, ambition: 72, integrity: 85, resilience: 70, intrigue: 35, discretion: 79 },
    },
  },
  {
    name: "Funke Akinrinade",
    state: "Ekiti",
    zone: "SW",
    age: 49,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "FA",
    traits: ["Oil Diplomacy Specialist", "Business Executive", "Media Savvy"],
    bio: "Former Shell Nigeria executive who transitioned to energy diplomacy, advising the Petroleum Ministry on OPEC strategy and gas monetization frameworks. Her private sector network, media savvy, and understanding of IOC-NOC dynamics are significant assets.",
    education: "University of Ado-Ekiti (Engineering); MSc, University of Dundee (Petroleum Law/Economics); MBA, Chicago Booth",
    competence: 78,
    languageSkills: ["None"],
    qualifiedFor: ["inst-opec", "inst-wb-imf"],
    competencies: {
      professional: { economics: 85, diplomacy: 72, security: 20, communications: 78, legal: 55, administration: 70, technology: 62, management: 79, politics: 79 },
      personal: { loyalty: 62, charisma: 80, leadership: 72, ambition: 85, integrity: 68, resilience: 72, intrigue: 52, discretion: 78 },
    },
  },

  // ═══════════════════════════════════════════════════════════════════
  // POST 9: inst-afdb — African Development Bank (French required)
  // ═══════════════════════════════════════════════════════════════════
  {
    name: "Akinwumi Olayinka",
    state: "Oyo",
    zone: "SW",
    age: 60,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "AO",
    traits: ["Business Executive", "Multilingual", "Trade Negotiator"],
    bio: "Former Managing Director at a major Nigerian bank who served as Nigeria's alternate Executive Director at the AfDB. His deep knowledge of development finance, concessional lending windows, and the African Development Fund replenishment process is extraordinary.",
    education: "UI Ibadan (Agricultural Economics); PhD, Purdue University; Executive Programme, Université de Paris-Dauphine",
    competence: 92,
    languageSkills: ["French"],
    qualifiedFor: ["inst-afdb", "inst-wb-imf", "inst-wto", "inst-au"],
    competencies: {
      professional: { economics: 95, diplomacy: 82, security: 22, communications: 62, legal: 50, administration: 85, technology: 55, management: 90, politics: 87 },
      personal: { loyalty: 68, charisma: 80, leadership: 88, ambition: 82, integrity: 78, resilience: 78, intrigue: 45, discretion: 81 },
    },
  },
  {
    name: "Halima Alao",
    state: "Kogi",
    zone: "NC",
    age: 53,
    gender: "Female",
    religion: "Islam",
    ethnicity: "Ebira",
    avatar: "HA",
    traits: ["Career Diplomat", "Multilingual", "Academic Diplomat"],
    bio: "Former economist at the AfDB headquarters in Abidjan who rose to become Nigeria's representative on the Board of Directors. Her expertise in infrastructure financing, debt sustainability frameworks, and gender-responsive budgeting is widely respected across the continent.",
    education: "Kogi State University (Economics); MSc, Université d'Abidjan (Development Economics); PhD, University of Oxford",
    competence: 87,
    languageSkills: ["French"],
    qualifiedFor: ["inst-afdb", "inst-wb-imf", "inst-au", "inst-ecowas"],
    competencies: {
      professional: { economics: 90, diplomacy: 80, security: 20, communications: 50, legal: 55, administration: 78, technology: 48, management: 82, politics: 83 },
      personal: { loyalty: 75, charisma: 70, leadership: 78, ambition: 72, integrity: 85, resilience: 75, intrigue: 35, discretion: 84 },
    },
  },
  {
    name: "Sanusi Danbatta",
    state: "Kano",
    zone: "NW",
    age: 58,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "SD",
    traits: ["Business Executive", "Multilingual", "Trade Negotiator"],
    bio: "Former CEO of a telecommunications firm who pivoted to development finance, serving on the AfDB's private sector development committee. His expertise in public-private partnerships, blended finance, and technology-enabled development is forward-looking.",
    education: "BUK (Electrical Engineering); MBA, Université de Sherbrooke; MSc, MIT Sloan",
    competence: 84,
    languageSkills: ["French"],
    qualifiedFor: ["inst-afdb", "inst-wb-imf", "inst-opec", "inst-wto"],
    competencies: {
      professional: { economics: 82, diplomacy: 75, security: 18, communications: 65, legal: 42, administration: 80, technology: 88, management: 79, politics: 77 },
      personal: { loyalty: 62, charisma: 78, leadership: 80, ambition: 85, integrity: 72, resilience: 70, intrigue: 48, discretion: 70 },
    },
  },
  {
    name: "Ekanem Bassey",
    state: "Cross River",
    zone: "SS",
    age: 51,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Efik",
    avatar: "EB",
    traits: ["Career Diplomat", "Multilingual", "Academic Diplomat"],
    bio: "Former World Bank consultant who transitioned to the AfDB as a senior infrastructure economist. Her bilingual expertise in climate finance, green bonds, and resilient infrastructure frameworks positions her at the frontier of African development finance.",
    education: "University of Calabar (Economics); MSc, Université de Bordeaux; PhD, University of Manchester",
    competence: 81,
    languageSkills: ["French"],
    qualifiedFor: ["inst-afdb", "inst-wb-imf", "inst-au"],
    competencies: {
      professional: { economics: 88, diplomacy: 78, security: 18, communications: 48, legal: 45, administration: 72, technology: 62, management: 62, politics: 66 },
      personal: { loyalty: 72, charisma: 65, leadership: 70, ambition: 68, integrity: 85, resilience: 72, intrigue: 32, discretion: 70 },
    },
  },
  {
    name: "Kabiru Rabiu",
    state: "Katsina",
    zone: "NW",
    age: 56,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "KR",
    traits: ["Business Executive", "Multilingual", "Oil Diplomacy Specialist"],
    bio: "Industrialist and former chairman of the Manufacturers Association of Nigeria who advised the AfDB on its Industrialize Africa strategy. His French fluency, private sector credibility, and understanding of African manufacturing value chains are major assets.",
    education: "ABU Zaria (Industrial Chemistry); MBA, Université de Grenoble; Executive Programme, Wharton",
    competence: 79,
    languageSkills: ["French"],
    qualifiedFor: ["inst-afdb", "inst-ecowas", "inst-wto", "inst-opec"],
    competencies: {
      professional: { economics: 85, diplomacy: 72, security: 15, communications: 60, legal: 38, administration: 82, technology: 55, management: 73, politics: 70 },
      personal: { loyalty: 58, charisma: 75, leadership: 78, ambition: 88, integrity: 65, resilience: 72, intrigue: 58, discretion: 62 },
    },
  },

  // ═══════════════════════════════════════════════════════════════════
  // POST 10: inst-wb-imf — World Bank/IMF (No language req)
  // ═══════════════════════════════════════════════════════════════════
  {
    name: "Ngozi Okafor-Madueke",
    state: "Imo",
    zone: "SE",
    age: 57,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "NO",
    traits: ["Business Executive", "Trade Negotiator", "Academic Diplomat"],
    bio: "Former Special Advisor to the Executive Director at the World Bank who helped design Nigeria's Development Policy Financing programme. Her deep IMF Article IV consultation experience and World Bank operational knowledge make her the consummate Bretton Woods specialist.",
    education: "IMSU (Economics); MA, American University Washington DC; PhD, University of Oxford (Development Economics)",
    competence: 93,
    languageSkills: ["None"],
    qualifiedFor: ["inst-wb-imf", "inst-afdb", "inst-opec", "inst-un-ny"],
    competencies: {
      professional: { economics: 95, diplomacy: 85, security: 20, communications: 58, legal: 52, administration: 80, technology: 50, management: 89, politics: 89 },
      personal: { loyalty: 70, charisma: 78, leadership: 85, ambition: 80, integrity: 82, resilience: 82, intrigue: 42, discretion: 88 },
    },
  },
  {
    name: "Yemi Cardoso-Adeleke",
    state: "Ogun",
    zone: "SW",
    age: 61,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "YC",
    traits: ["Business Executive", "Career Diplomat", "Trade Negotiator"],
    bio: "Former Deputy Governor of the Central Bank of Nigeria who served as Nigeria's Alternate Executive Director at the IMF. His expertise in monetary policy coordination, balance of payments analysis, and sovereign debt restructuring is formidable.",
    education: "UNILAG (Accounting); MBA, Harvard Business School; Advanced Programme, IMF Institute Washington DC",
    competence: 90,
    languageSkills: ["None"],
    qualifiedFor: ["inst-wb-imf", "inst-afdb", "inst-opec", "inst-wto"],
    competencies: {
      professional: { economics: 92, diplomacy: 82, security: 18, communications: 55, legal: 48, administration: 85, technology: 45, management: 84, politics: 84 },
      personal: { loyalty: 72, charisma: 72, leadership: 82, ambition: 75, integrity: 78, resilience: 80, intrigue: 48, discretion: 79 },
    },
  },
  {
    name: "Fatima Wali-Abdurrahman",
    state: "Sokoto",
    zone: "NW",
    age: 55,
    gender: "Female",
    religion: "Islam",
    ethnicity: "Fulani",
    avatar: "FW",
    traits: ["Career Diplomat", "Academic Diplomat", "Multilingual"],
    bio: "Former Lead Economist at the IMF's African Department who authored influential reports on Nigeria's fiscal federalism and subsidy reform. Her insider knowledge of IMF surveillance methodology and policy conditionality frameworks gives her unmatched analytical depth.",
    education: "Usmanu Danfodiyo University (Economics); MSc, London School of Economics; PhD, MIT (Economics)",
    competence: 88,
    languageSkills: ["French"],
    qualifiedFor: ["inst-wb-imf", "inst-afdb", "inst-un-ny", "inst-un-geneva"],
    competencies: {
      professional: { economics: 95, diplomacy: 80, security: 15, communications: 52, legal: 45, administration: 72, technology: 55, management: 74, politics: 75 },
      personal: { loyalty: 68, charisma: 70, leadership: 78, ambition: 72, integrity: 88, resilience: 78, intrigue: 35, discretion: 82 },
    },
  },
  {
    name: "Paschal Okonjo",
    state: "Delta",
    zone: "SS",
    age: 59,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Ika",
    avatar: "PO",
    traits: ["Business Executive", "Trade Negotiator", "Former Senator"],
    bio: "Former chairman of the Senate Committee on Appropriations who served as Nigeria's Governor on the World Bank Board of Governors. His political weight, understanding of IDA replenishment politics, and fiscal policy expertise bridge Abuja and Washington.",
    education: "University of Benin (Economics); MSc, Georgetown University; Executive Programme, World Bank Institute",
    competence: 82,
    languageSkills: ["None"],
    qualifiedFor: ["inst-wb-imf", "inst-opec", "inst-commonwealth", "inst-afdb"],
    competencies: {
      professional: { economics: 85, diplomacy: 78, security: 25, communications: 65, legal: 55, administration: 78, technology: 38, management: 81, politics: 80 },
      personal: { loyalty: 60, charisma: 78, leadership: 80, ambition: 85, integrity: 65, resilience: 75, intrigue: 68, discretion: 72 },
    },
  },
  {
    name: "Ahmed Kuru",
    state: "Gombe",
    zone: "NE",
    age: 54,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Fulani",
    avatar: "AK",
    traits: ["Business Executive", "Career Diplomat", "Trade Negotiator"],
    bio: "Former Managing Director of the Asset Management Corporation of Nigeria who restructured distressed banking assets worth billions. His expertise in financial sector reform, non-performing loan resolution, and World Bank financial sector assessment programmes is exceptional.",
    education: "University of Maiduguri (Banking & Finance); MBA, Thunderbird School of Global Management; CFA Charterholder",
    competence: 85,
    languageSkills: ["Arabic"],
    qualifiedFor: ["inst-wb-imf", "inst-afdb", "inst-opec"],
    competencies: {
      professional: { economics: 90, diplomacy: 78, security: 18, communications: 50, legal: 52, administration: 82, technology: 55, management: 80, politics: 80 },
      personal: { loyalty: 65, charisma: 68, leadership: 78, ambition: 80, integrity: 75, resilience: 80, intrigue: 52, discretion: 78 },
    },
  },
];
