// directorPoolBatch3.ts — Communications, Environment, Justice, Transport, Youth Dev, Foreign Affairs, Defence
import type { DirectorCandidate } from "./directorPool";

export const DIRECTOR_CANDIDATES_BATCH3: DirectorCandidate[] = [

  // ── Communications & Digital Economy Sector ───────────────────────────────

  {
    name: "Dr. Isa Pantami Kwara",
    age: 52,
    state: "Kwara",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Nupe",
    avatar: "IP",
    traits: ["Tech Strategist", "Ideological Convictions", "Institutional Builder"],
    bio: "Spent eight years at the National Information Technology Development Agency before rising to DG of the NCC, where he oversaw the rollout of Nigeria's first 5G spectrum auction. His 2021 digital economy policy framework became the template for three other African nations. Critics note that his public statements on tech governance sometimes diverge sharply from government positions.",
    education: "Federal University of Technology Minna (Computer Science), University of Surrey (PhD Cybersecurity Policy)",
    tradeOff: "Exceptional technical credibility and 5G rollout capacity, but his outspoken ideology has historically drawn international scrutiny that complicates diplomatic relationships.",
    competencies: {
      professional: { economics: 55, diplomacy: 40, security: 50, media: 60, legal: 55, administration: 72, technology: 90 },
      personal: { loyalty: 65, charisma: 60, leadership: 75, ambition: 70, integrity: 62, resilience: 78, intrigue: 45 },
    },
    qualifiedFor: ["director-communications-commission", "director-it-development"],
  },

  {
    name: "Mrs. Amina Garba-Hussaini",
    age: 49,
    state: "Kano",
    gender: "Female",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "AG",
    traits: ["Regulatory Hawk", "Consumer Advocate", "Northern Bridge"],
    bio: "Rose through the NCC's consumer affairs division to become the first female Director of Regulatory Affairs, where she levied record fines against MTN and Airtel for service failures. Her broadband penetration initiative brought connectivity to 12 million underserved Nigerians in the NW. Commands deep respect in telecom circles despite having no private-sector background.",
    education: "Bayero University Kano (Electrical Engineering), Cranfield University (MSc Telecommunications Management)",
    tradeOff: "A fierce consumer champion whose aggressive enforcement posture will improve service quality but may slow foreign telecom investment.",
    competencies: {
      professional: { economics: 58, diplomacy: 52, security: 35, media: 62, legal: 68, administration: 78, technology: 82 },
      personal: { loyalty: 60, charisma: 65, leadership: 72, ambition: 58, integrity: 80, resilience: 75, intrigue: 38 },
    },
    qualifiedFor: ["director-communications-commission", "director-broadcasting-commission"],
  },

  {
    name: "Prof. Emeka Ezeife-Oduya",
    age: 58,
    state: "Anambra",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "EE",
    traits: ["Academic Heavyweight", "Digital Visionary", "Long-Horizon Thinker"],
    bio: "Chaired the University of Nigeria's pioneering Digital Economy Lab for a decade before co-authoring Nigeria's National Broadband Plan. His AI governance white paper was cited in the AU's continental digital strategy. Lacks operational experience but is Africa's most credible voice on emerging technology policy.",
    education: "University of Nigeria Nsukka (Computer Engineering), MIT (PhD Electrical Engineering and Computer Science)",
    tradeOff: "Brings rare international intellectual capital and long-term vision but may struggle to navigate the political realities of regulatory enforcement.",
    competencies: {
      professional: { economics: 60, diplomacy: 70, security: 28, media: 65, legal: 45, administration: 55, technology: 92 },
      personal: { loyalty: 45, charisma: 72, leadership: 65, ambition: 68, integrity: 85, resilience: 65, intrigue: 30 },
    },
    qualifiedFor: ["director-it-development", "director-communications-commission"],
  },

  {
    name: "Mr. Segun Adeleke-Fashola",
    age: 47,
    state: "Oyo",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "SA",
    traits: ["Startup Ecosystem Builder", "Risk-Taker", "Charismatic"],
    bio: "Founded one of Lagos's first tech incubators before being appointed head of NITDA's Innovation Hub unit, where he brokered fifteen international tech company expansions into Nigeria. His Lagos-Silicon Valley shuttle diplomacy is credited with positioning Nigeria as West Africa's leading startup destination. His personal fintech investments create recurring conflict-of-interest concerns.",
    education: "Obafemi Awolowo University (Computer Science), Stanford Graduate School of Business (MBA)",
    tradeOff: "A uniquely connected tech ecosystem bridge but his existing business interests in the sector he would regulate are a serious governance liability.",
    competencies: {
      professional: { economics: 65, diplomacy: 72, security: 22, media: 75, legal: 38, administration: 60, technology: 85 },
      personal: { loyalty: 52, charisma: 85, leadership: 70, ambition: 82, integrity: 55, resilience: 72, intrigue: 60 },
    },
    qualifiedFor: ["director-it-development", "director-communications-commission"],
  },

  {
    name: "Dr. Fatima Bello-Yusuf",
    age: 44,
    state: "Sokoto",
    gender: "Female",
    religion: "Islam",
    ethnicity: "Fulani",
    avatar: "FB",
    traits: ["Cybersecurity Expert", "Methodical", "Security-Conscious"],
    bio: "Served as Deputy Director of Cybersecurity at the Office of the National Security Adviser before joining the Nigerian Army Signals Corps as a civilian consultant. Her framework for critical infrastructure protection was adopted by ECOWAS as a regional standard. A rare technologist with genuine security clearance and cross-ministry relationships.",
    education: "Usmanu Danfodiyo University (Computer Science), George Washington University (MSc Cybersecurity), Imperial College London (PhD)",
    tradeOff: "Uniquely bridges the technology and security sectors, but her security orientation means she may prioritise state surveillance over digital freedom.",
    competencies: {
      professional: { economics: 42, diplomacy: 48, security: 78, media: 40, legal: 60, administration: 68, technology: 88 },
      personal: { loyalty: 72, charisma: 50, leadership: 70, ambition: 60, integrity: 75, resilience: 80, intrigue: 55 },
    },
    qualifiedFor: ["director-it-development", "director-communications-commission"],
  },

  {
    name: "Mrs. Ngozi Obi-Ikenna",
    age: 53,
    state: "Rivers",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "NI",
    traits: ["Media Regulator", "Blunt Communicator", "Seasoned Operator"],
    bio: "Spent twenty years at the Nigerian Broadcasting Commission, eventually becoming Director of Content Development, before secondment to the Presidency's Strategic Communications Unit. She oversaw Nigeria's transition from analogue to digital broadcasting, a logistical feat involving thirty-seven state transmitters. Her tongue is as sharp as her institutional memory.",
    education: "University of Port Harcourt (Mass Communication), University of Westminster (MA Broadcast Journalism)",
    tradeOff: "Deep operational knowledge of Nigerian broadcasting infrastructure, but her outspokenness creates a perpetual media management risk for the administration.",
    competencies: {
      professional: { economics: 45, diplomacy: 55, security: 30, media: 90, legal: 58, administration: 75, technology: 60 },
      personal: { loyalty: 58, charisma: 78, leadership: 72, ambition: 65, integrity: 70, resilience: 80, intrigue: 42 },
    },
    qualifiedFor: ["director-broadcasting-commission", "director-communications-commission"],
  },

  {
    name: "Mr. Yakubu Tanko-Damagun",
    age: 57,
    state: "Adamawa",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Tiv",
    avatar: "YT",
    traits: ["Broadcasting Insider", "Political Survivor", "Pragmatist"],
    bio: "Began his career as a radio presenter in Yola before climbing through NTA's ranks to become Regional Director for the Northeast. His management of broadcast operations during the Boko Haram crisis years earned him a national service commendation. Has survived five DG changes by being indispensable to every regime.",
    education: "Federal Polytechnic Nasarawa (Mass Communication), University of Jos (BA Broadcasting), Henley Business School (Executive Management)",
    tradeOff: "A proven survivor who will keep the NBC stable and manageable, but his instinct for institutional self-preservation above all else limits bold regulatory reform.",
    competencies: {
      professional: { economics: 40, diplomacy: 58, security: 42, media: 85, legal: 48, administration: 78, technology: 52 },
      personal: { loyalty: 75, charisma: 68, leadership: 65, ambition: 55, integrity: 60, resilience: 88, intrigue: 70 },
    },
    qualifiedFor: ["director-broadcasting-commission"],
  },

  {
    name: "Dr. Chisom Okeke-Eze",
    age: 41,
    state: "Enugu",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "CO",
    traits: ["Digital Rights Advocate", "Academic Reformist", "Media Freedom Champion"],
    bio: "A communications law academic at the University of Nigeria who served on the NBC's Content Review Panel and the Presidential Advisory Committee on Media Reform. Her landmark paper on press freedom and digital regulation reshaped the Broadcasting Code's content provisions. She is outspoken — sometimes uncomfortably so — about government overreach in media.",
    education: "University of Nigeria Nsukka (Law), London School of Economics (LLM Media Law), Edinburgh (PhD Communications Regulation)",
    tradeOff: "A principled reformer who will modernise the NBC's legal framework but whose media freedom stance creates tensions with any administration that wants broadcast compliance.",
    competencies: {
      professional: { economics: 42, diplomacy: 62, security: 22, media: 82, legal: 80, administration: 60, technology: 65 },
      personal: { loyalty: 40, charisma: 72, leadership: 65, ambition: 70, integrity: 88, resilience: 70, intrigue: 30 },
    },
    qualifiedFor: ["director-broadcasting-commission", "director-communications-commission"],
  },

  {
    name: "Alhaji Rabiu Dankama-Birni",
    age: 60,
    state: "Kebbi",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "RD",
    traits: ["Quiet Fixer", "Legislative Liaison", "Veteran Administrator"],
    bio: "A career civil servant who rose to Permanent Secretary at the Ministry of Communications, overseeing spectrum management through three administrations. Built the internal coordination mechanism between the NCC and NITDA that ended their five-year jurisdictional dispute. Does not appear in newspapers but his phone never stops ringing.",
    education: "Usmanu Danfodiyo University (Public Administration), University of Birmingham (MPA)",
    tradeOff: "An irreplaceable back-channel operator and institutional glue, but his instinct to preserve harmony may delay necessary confrontations with underperforming agencies.",
    competencies: {
      professional: { economics: 52, diplomacy: 65, security: 38, media: 45, legal: 60, administration: 88, technology: 55 },
      personal: { loyalty: 80, charisma: 55, leadership: 68, ambition: 52, integrity: 72, resilience: 82, intrigue: 65 },
    },
    qualifiedFor: ["director-communications-commission", "director-it-development"],
  },

  {
    name: "Mrs. Yetunde Adeolu-Bamgboye",
    age: 46,
    state: "Osun",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "YA",
    traits: ["E-Government Evangelist", "Partnership Builder", "Results-Oriented"],
    bio: "Led NITDA's e-Government rollout programme, deploying digital ID infrastructure across nineteen states in three years. Her public-private partnership model with telcos and fintechs to drive last-mile connectivity became a case study at the ITU. She is relentlessly optimistic and publicly visible — the administration's digital face in international forums.",
    education: "University of Ibadan (Computer Science), London Business School (MSc Management)",
    tradeOff: "A high-profile champion of digital inclusion whose eagerness for international visibility may prioritise announcements over unglamorous implementation.",
    competencies: {
      professional: { economics: 58, diplomacy: 68, security: 25, media: 72, legal: 42, administration: 70, technology: 84 },
      personal: { loyalty: 60, charisma: 80, leadership: 72, ambition: 75, integrity: 72, resilience: 68, intrigue: 38 },
    },
    qualifiedFor: ["director-it-development", "director-broadcasting-commission"],
  },

  // ── Environment Sector ────────────────────────────────────────────────────

  {
    name: "Dr. Aisha Mahmoud-Gadzama",
    age: 54,
    state: "Borno",
    gender: "Female",
    religion: "Islam",
    ethnicity: "Kanuri",
    avatar: "AM",
    traits: ["Climate Diplomat", "Lake Chad Expert", "Resilient"],
    bio: "Dedicated twenty years to the Lake Chad Basin Commission, coordinating cross-border environmental response across four nations. Her drought resilience framework is the operational backbone of Nigeria's Northeast climate adaptation strategy. She lost her research station to Boko Haram insurgents in 2014 and rebuilt it within eighteen months.",
    education: "University of Maiduguri (Environmental Science), Wageningen University Netherlands (PhD Water Resources Management)",
    tradeOff: "Uniquely credible on NE environmental crises and international climate diplomacy, but her regional focus may shortchange Southern environmental concerns.",
    competencies: {
      professional: { economics: 50, diplomacy: 80, security: 55, media: 55, legal: 52, administration: 72, technology: 62 },
      personal: { loyalty: 62, charisma: 70, leadership: 78, ambition: 58, integrity: 85, resilience: 92, intrigue: 30 },
    },
    qualifiedFor: ["director-environmental-standards", "director-water-resources"],
  },

  {
    name: "Prof. Onyeka Chukwuemeka-Odi",
    age: 60,
    state: "Delta",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Urhobo",
    avatar: "OC",
    traits: ["Oil Pollution Specialist", "Principled", "Confrontational"],
    bio: "Nigeria's foremost academic authority on hydrocarbon pollution remediation, whose testimony before the House Environment Committee led to the first successful prosecution of an oil major for environmental negligence. His ongoing UNEP Niger Delta study is both Nigeria's greatest environmental achievement and its greatest diplomatic headache with IOCs.",
    education: "University of Benin (Chemistry), University of Aberdeen (PhD Environmental Chemistry), Shell Foundation Research Fellow",
    tradeOff: "Unimpeachable technical authority and genuine passion for the Niger Delta, but appointing him will immediately antagonise the IOCs whose investment the petroleum sector depends on.",
    competencies: {
      professional: { economics: 48, diplomacy: 42, security: 30, media: 70, legal: 65, administration: 60, technology: 75 },
      personal: { loyalty: 38, charisma: 75, leadership: 70, ambition: 62, integrity: 92, resilience: 80, intrigue: 28 },
    },
    qualifiedFor: ["director-environmental-standards"],
  },

  {
    name: "Engr. Bukar Musa-Yerima",
    age: 56,
    state: "Yobe",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Kanuri",
    avatar: "BM",
    traits: ["Water Systems Engineer", "Pragmatic", "Rural Champion"],
    bio: "Designed and delivered the Yobe-Borno trans-basin water transfer scheme, the largest rural water infrastructure project in Nigeria's NE. His tenure as Director of Water Services at the Ministry gave him oversight of 4,000 boreholes and fourteen dams. He speaks eleven local dialects, making him uniquely effective at grassroots project delivery.",
    education: "University of Maiduguri (Civil Engineering), TU Delft Netherlands (MSc Hydraulic Engineering)",
    tradeOff: "Extraordinary water infrastructure delivery track record in underserved regions, but limited experience regulating urban water utilities and managing private sector operators.",
    competencies: {
      professional: { economics: 48, diplomacy: 50, security: 40, media: 40, legal: 38, administration: 75, technology: 70 },
      personal: { loyalty: 70, charisma: 58, leadership: 72, ambition: 55, integrity: 78, resilience: 85, intrigue: 35 },
    },
    qualifiedFor: ["director-water-resources", "director-environmental-standards"],
  },

  {
    name: "Dr. Ngozi Amadi-Okafor",
    age: 48,
    state: "Imo",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "NA",
    traits: ["Environmental Lawyer", "Strategic Litigator", "Corporate Thorn"],
    bio: "Founded the Niger Delta Environmental Rights Centre after losing a brother to pipeline explosion injuries, and successfully sued the Nigerian government at ECOWAS Court over clean-up obligations. Her appointment as Environmental Standards DG would signal the administration's seriousness — and would terrify the oil industry. Has declined four private-sector offers.",
    education: "University of Lagos (Law), Yale Law School (LLM Environmental Law)",
    tradeOff: "Her appointment signals genuine commitment to environmental accountability, but oil revenue, the economy's lifeblood, would face immediate disruption from her enforcement posture.",
    competencies: {
      professional: { economics: 45, diplomacy: 55, security: 30, media: 72, legal: 88, administration: 60, technology: 48 },
      personal: { loyalty: 35, charisma: 78, leadership: 72, ambition: 70, integrity: 95, resilience: 85, intrigue: 32 },
    },
    qualifiedFor: ["director-environmental-standards"],
  },

  {
    name: "Alhaji Ibrahim Takalmawa",
    age: 62,
    state: "Katsina",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "IT",
    traits: ["Desertification Expert", "Consensus Builder", "Elder Statesman"],
    bio: "Spent thirty years at the Federal Ministry of Environment managing the Great Green Wall initiative, the pan-African reforestation programme fighting Saharan encroachment into Nigeria's North. Brokered agreements with twelve state governors to replant 500,000 hectares of degraded farmland. His patient, consensus-driven style frustrates reformers but delivers durable results.",
    education: "Ahmadu Bello University Zaria (Agriculture), University of Arizona (MS Arid Lands Resource Sciences)",
    tradeOff: "A uniquely patient coalition-builder who delivers sustainable environmental progress, but his deliberate approach will feel inadequate to activists demanding urgent action on Nigeria's worsening ecological crises.",
    competencies: {
      professional: { economics: 52, diplomacy: 70, security: 35, media: 48, legal: 45, administration: 80, technology: 50 },
      personal: { loyalty: 68, charisma: 62, leadership: 70, ambition: 48, integrity: 78, resilience: 75, intrigue: 42 },
    },
    qualifiedFor: ["director-environmental-standards", "director-water-resources"],
  },

  {
    name: "Mrs. Blessing Tonye-Amachree",
    age: 45,
    state: "Bayelsa",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Ijaw",
    avatar: "BT",
    traits: ["Activist-Turned-Technocrat", "Community Voice", "Watchful"],
    bio: "Led Ijaw youth environmental protests before transitioning to the HYPREP (Hydrocarbon Pollution Remediation Project) as Community Liaison Director, where she turned adversarial relationships with oil companies into reluctant partnerships. Her fluency in local grievances makes her irreplaceable in fieldwork but makes corporate Nigeria nervous.",
    education: "Niger Delta University (Environmental Management), University of Hull (MSc Environmental Policy)",
    tradeOff: "Her community trust and Niger Delta credibility are priceless for enforcement legitimacy, but her activist origins will make IOCs reluctant to cooperate on voluntary remediation initiatives.",
    competencies: {
      professional: { economics: 40, diplomacy: 62, security: 38, media: 72, legal: 55, administration: 62, technology: 48 },
      personal: { loyalty: 55, charisma: 82, leadership: 68, ambition: 62, integrity: 85, resilience: 88, intrigue: 40 },
    },
    qualifiedFor: ["director-environmental-standards", "director-water-resources"],
  },

  {
    name: "Dr. Suleiman Adamu-Tukur",
    age: 51,
    state: "Adamawa",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Fulani",
    avatar: "ST",
    traits: ["Hydrologist", "Technocrat", "Systems Thinker"],
    bio: "Nigeria's leading authority on the Benue-Niger river system, whose flood modelling work saved an estimated 200,000 lives during the 2022 inundations. His work with the Nigerian Hydrological Services Agency produced the country's first real-time flood early-warning network. Prefers policy papers to press conferences.",
    education: "Federal University of Technology Yola (Civil Engineering), IHE Delft (PhD Hydrology)",
    tradeOff: "Exceptional technical rigour and proven ability to protect lives through water management, but his aversion to political communication may leave the ministry's public standing weak.",
    competencies: {
      professional: { economics: 45, diplomacy: 48, security: 45, media: 32, legal: 40, administration: 70, technology: 82 },
      personal: { loyalty: 60, charisma: 42, leadership: 65, ambition: 52, integrity: 85, resilience: 75, intrigue: 28 },
    },
    qualifiedFor: ["director-water-resources"],
  },

  {
    name: "Prof. Bimbo Adeyemi-Coker",
    age: 57,
    state: "Lagos",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "BA",
    traits: ["Climate Finance Expert", "International Platform", "Connected"],
    bio: "Represented Nigeria on the UNFCCC Adaptation Committee and architected the country's Nationally Determined Contributions under the Paris Agreement. Her skill in translating Nigeria's climate needs into multilateral finance secured $2.3 billion in GCF commitments. Lagos-based and well-connected in both domestic and international environmental circles.",
    education: "University of Lagos (Economics), Columbia SIPA (MPA Environmental Policy), LSE (PhD Climate Finance)",
    tradeOff: "Her international climate finance network is unrivalled and she can unlock funding no one else can, but her cosmopolitan profile may distance her from the ground-level enforcement challenges of environmental standards.",
    competencies: {
      professional: { economics: 72, diplomacy: 85, security: 20, media: 65, legal: 55, administration: 65, technology: 58 },
      personal: { loyalty: 50, charisma: 78, leadership: 70, ambition: 75, integrity: 80, resilience: 70, intrigue: 42 },
    },
    qualifiedFor: ["director-environmental-standards", "director-water-resources"],
  },

  // ── Justice Sector ────────────────────────────────────────────────────────

  {
    name: "Mr. Ibrahim Magu-Keana",
    age: 59,
    state: "Benue",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Tiv",
    avatar: "IM",
    traits: ["Relentless Prosecutor", "Incorruptible", "Politically Radioactive"],
    bio: "The most feared financial crimes investigator in West Africa, who secured convictions against eleven serving politicians and recovered $3.8 billion in stolen assets during his seven-year tenure as EFCC Acting Chairman before a political cabal succeeded in removing him. His case files on the nation's most powerful families are intact and ready. His enemies are everywhere and fear him profoundly.",
    education: "University of Jos (Law), International Anti-Corruption Academy Vienna (Post-Graduate)",
    tradeOff: "The only candidate who will genuinely terrify the corrupt establishment and deliver real prosecutions — but appointing him means the president will face immediate pressure from every powerful interest he has ever investigated.",
    competencies: {
      professional: { economics: 55, diplomacy: 35, security: 70, media: 62, legal: 95, administration: 70, technology: 45 },
      personal: { loyalty: 45, charisma: 65, leadership: 80, ambition: 68, integrity: 98, resilience: 92, intrigue: 50 },
    },
    qualifiedFor: ["director-anti-financial-crimes", "director-anti-corruption-commission"],
  },

  {
    name: "Mrs. Zainab Ahmed-Ringim",
    age: 54,
    state: "Jigawa",
    gender: "Female",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "ZA",
    traits: ["Asset Recovery Specialist", "Diplomatic", "Quietly Effective"],
    bio: "Led the EFCC's Asset Recovery Division for six years, negotiating the return of $940 million in looted funds from Switzerland, Jersey, and the Cayman Islands. Her quiet efficiency and willingness to build bridges with foreign jurisdictions produced results her more confrontational predecessors could not. She chooses results over headlines every time.",
    education: "Usmanu Danfodiyo University (Law), University of Cambridge (LLM International Financial Law)",
    tradeOff: "A diplomatically skilled asset-recovery engine who will produce results without political drama, but her consensual approach means major domestic prosecutions of politically connected individuals will be rare.",
    competencies: {
      professional: { economics: 62, diplomacy: 80, security: 50, media: 48, legal: 88, administration: 75, technology: 52 },
      personal: { loyalty: 65, charisma: 60, leadership: 72, ambition: 58, integrity: 85, resilience: 80, intrigue: 55 },
    },
    qualifiedFor: ["director-anti-financial-crimes", "director-anti-corruption-commission"],
  },

  {
    name: "Prof. Nkiru Onyekachi-Dike",
    age: 56,
    state: "Abia",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "NO",
    traits: ["Anti-Corruption Scholar", "System Reformer", "Institutional Architect"],
    bio: "Nigeria's pre-eminent academic on anti-corruption institutional design, whose advisory work helped restructure the ICPC after its 2015 crisis. Her comparative study of anti-corruption effectiveness across thirty nations directly informed the Proceeds of Crime Act amendments. She is respected across party lines as someone who has never taken a side.",
    education: "University of Nigeria Nsukka (Law), Harvard Law School (LLM), Oxford (DPhil Comparative Law)",
    tradeOff: "Her intellectual independence and non-partisan reputation make her uniquely credible — but she will refuse political direction and insist on institutional autonomy in ways that may constrain the presidency.",
    competencies: {
      professional: { economics: 55, diplomacy: 65, security: 35, media: 62, legal: 90, administration: 68, technology: 50 },
      personal: { loyalty: 38, charisma: 72, leadership: 70, ambition: 65, integrity: 95, resilience: 80, intrigue: 28 },
    },
    qualifiedFor: ["director-anti-corruption-commission", "director-judicial-commission"],
  },

  {
    name: "Alhaji Nuhu Ribadu-Gusau",
    age: 63,
    state: "Zamfara",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Fulani",
    avatar: "NR",
    traits: ["Political Veteran", "Networked", "Survivalist"],
    bio: "A former EFCC Chairman who went into exile, returned to contest the presidency, and re-emerged as a presidential adviser — a testament to Nigeria's political elasticity. His knowledge of how corruption networks operate in Nigeria is encyclopaedic, drawn from both sides of the table. His loyalty has historically followed power, not principle.",
    education: "Ahmadu Bello University (Law), International Institute for Law and Business",
    tradeOff: "His insider knowledge of corruption networks is invaluable for targeted enforcement, but his history of political accommodation means powerful figures will expect lenient treatment.",
    competencies: {
      professional: { economics: 55, diplomacy: 65, security: 65, media: 70, legal: 80, administration: 72, technology: 38 },
      personal: { loyalty: 68, charisma: 80, leadership: 72, ambition: 85, integrity: 52, resilience: 85, intrigue: 82 },
    },
    qualifiedFor: ["director-anti-financial-crimes", "director-anti-corruption-commission"],
  },

  {
    name: "Justice Ngozi Iweala-Chuba (Rtd.)",
    age: 65,
    state: "Anambra",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "NI",
    traits: ["Judicial Elder", "Commanding Presence", "Constitutional Purist"],
    bio: "Served on the Court of Appeal for nineteen years and presided over landmark rulings on judicial independence and electoral integrity. Her dissent in the 2019 gubernatorial election case became the basis for subsequent legislative reform. She has declined every inducement, endured threats, and outlasted every administration that tried to capture her court.",
    education: "University of Nigeria Nsukka (Law), Inner Temple London (Barrister), University of Lagos (LLD Honorary)",
    tradeOff: "A judicial titan who would make the NJC genuinely independent and feared — but her principled constitutionalism may occasionally constrain presidential authority in ways that create political friction.",
    competencies: {
      professional: { economics: 42, diplomacy: 65, security: 40, media: 55, legal: 95, administration: 72, technology: 35 },
      personal: { loyalty: 38, charisma: 72, leadership: 82, ambition: 50, integrity: 98, resilience: 88, intrigue: 25 },
    },
    qualifiedFor: ["director-judicial-commission"],
  },

  {
    name: "Mr. Emeka Wogu-Anyanwu",
    age: 52,
    state: "Ebonyi",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "EW",
    traits: ["Compliance Enforcer", "Detail-Oriented", "Bureaucratic Powerhouse"],
    bio: "Rose to Chief Registrar of the Supreme Court before crossing to the ICPC as Director of Operations, overhauling the commission's case management system and reducing the prosecution backlog by 62% in three years. He operates entirely within the system — never grandstands, always delivers. The civil service regards him as a machine.",
    education: "University of Calabar (Law), Nigerian Law School, University of London (LLM Public Law)",
    tradeOff: "An exceptional institutional manager who will professionalize anti-corruption operations — but he will not pursue cases that carry political risk and will not rock any boats he does not have to rock.",
    competencies: {
      professional: { economics: 50, diplomacy: 52, security: 40, media: 38, legal: 85, administration: 90, technology: 60 },
      personal: { loyalty: 72, charisma: 45, leadership: 68, ambition: 55, integrity: 78, resilience: 78, intrigue: 48 },
    },
    qualifiedFor: ["director-anti-corruption-commission", "director-judicial-commission"],
  },

  {
    name: "Mrs. Halima Dikko-Usman",
    age: 50,
    state: "Niger",
    gender: "Female",
    religion: "Islam",
    ethnicity: "Nupe",
    avatar: "HD",
    traits: ["Financial Intelligence Analyst", "Technocrat", "Apolitical"],
    bio: "Spent fourteen years at the Nigerian Financial Intelligence Unit, rising to Deputy Director and building Nigeria's AML/CFT reporting architecture that achieved FATF compliance for the first time. Her data-driven approach to tracking illicit financial flows has won recognition from the Egmont Group. She has no political patron and intends to keep it that way.",
    education: "University of Abuja (Accounting), ACAMS (Certified Anti-Money Laundering Specialist), King's College London (MSc Financial Crime)",
    tradeOff: "Her technical depth in financial intelligence is world-class, but she lacks prosecutorial experience and the political guile needed to withstand pressure when cases touch powerful interests.",
    competencies: {
      professional: { economics: 70, diplomacy: 55, security: 58, media: 38, legal: 72, administration: 75, technology: 80 },
      personal: { loyalty: 50, charisma: 48, leadership: 65, ambition: 55, integrity: 90, resilience: 72, intrigue: 35 },
    },
    qualifiedFor: ["director-anti-financial-crimes"],
  },

  {
    name: "Justice Musa Bulkachuwa-Kano (Rtd.)",
    age: 67,
    state: "Kano",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "MB",
    traits: ["Sharia Law Expert", "Elder Authority", "Northern Consensus"],
    bio: "Presided over the Kano State Sharia Court of Appeal for twelve years before appointment to the Federal Court of Appeal, where his constitutional rulings on religion and state have been cited in eleven subsequent Supreme Court decisions. His stature in northern Nigeria is unmatched. His appointment would be a powerful political signal — but also a theological lightning rod.",
    education: "Ahmadu Bello University (Islamic Law and Jurisprudence), University of London (LLM Common Law)",
    tradeOff: "His northern authority and judicial gravitas are politically invaluable, but his dual legal framework expertise invites controversy about the NJC's stance on secularism and religious law.",
    competencies: {
      professional: { economics: 40, diplomacy: 68, security: 45, media: 52, legal: 92, administration: 68, technology: 28 },
      personal: { loyalty: 60, charisma: 72, leadership: 78, ambition: 55, integrity: 85, resilience: 80, intrigue: 45 },
    },
    qualifiedFor: ["director-judicial-commission"],
  },

  {
    name: "Dr. Bamidele Arowolo-Soyinka",
    age: 48,
    state: "Ondo",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "BA",
    traits: ["Forensic Accountant", "Private Sector Convert", "Reform Enthusiast"],
    bio: "Built a reputation at Deloitte West Africa dismantling complex financial fraud structures before being recruited to the EFCC's Special Investigation Unit. His forensic reconstruction of a $2.5 billion NNPC crude-lifting fraud case remains the most complex financial investigation ever completed in Nigeria. Forty-eight and already eyeing a political career.",
    education: "Obafemi Awolowo University (Accounting), ICAN, University of Chicago Booth (MBA Finance)",
    tradeOff: "Forensic brilliance that can crack cases no one else can — but his ambitions for elected office mean EFCC chairmanship could become a platform for personal political advancement.",
    competencies: {
      professional: { economics: 78, diplomacy: 50, security: 50, media: 65, legal: 78, administration: 65, technology: 72 },
      personal: { loyalty: 52, charisma: 78, leadership: 70, ambition: 88, integrity: 72, resilience: 75, intrigue: 65 },
    },
    qualifiedFor: ["director-anti-financial-crimes", "director-anti-corruption-commission"],
  },

  {
    name: "Mrs. Fatimah Waziri-Azi",
    age: 57,
    state: "Taraba",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Tiv",
    avatar: "FW",
    traits: ["Quiet Reformer", "Middle Belt Voice", "Institutional Loyalist"],
    bio: "A former EFCC Chairwoman whose tenure was more notable for institutional rebuilding than headline prosecutions — she restored EFCC's internal integrity after a period of internal rot following political manipulation. Her Middle Belt origins make her a consensus figure acceptable to multiple geopolitical blocs. She is not feared, which is both her strength and her limitation.",
    education: "University of Jos (Law), Kellogg School of Management (Executive Leadership), Nigerian Institute of Advanced Legal Studies",
    tradeOff: "A stabilizing institutional rebuilder with broad political acceptability — but major prosecutions of powerful interests will not be her priority and the corrupt will not fear her appointment.",
    competencies: {
      professional: { economics: 52, diplomacy: 68, security: 45, media: 55, legal: 82, administration: 80, technology: 42 },
      personal: { loyalty: 70, charisma: 65, leadership: 72, ambition: 52, integrity: 78, resilience: 80, intrigue: 48 },
    },
    qualifiedFor: ["director-anti-financial-crimes", "director-anti-corruption-commission"],
  },

  // ── Transport Sector ──────────────────────────────────────────────────────

  {
    name: "Engr. Hadiza Bala-Usman",
    age: 48,
    state: "Kaduna",
    gender: "Female",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "HB",
    traits: ["Port Moderniser", "Revenue Hawk", "Anti-Touting Crusader"],
    bio: "Transformed Apapa port operations as NPA Managing Director, reducing cargo clearance time from twenty-two days to eight and plugging revenue leakages that had cost the authority billions annually. Her crackdown on port touts and racketeers made her the target of threats but earned her a standing ovation from importers. Removed by political pressure, never by performance.",
    education: "Ahmadu Bello University (Political Science), Bayero University Kano (MSc Development Studies)",
    tradeOff: "A proven port reformer with a track record no other candidate can match — but re-appointing her means confronting the same port cartel interests that had her removed the first time.",
    competencies: {
      professional: { economics: 72, diplomacy: 55, security: 52, media: 65, legal: 58, administration: 85, technology: 60 },
      personal: { loyalty: 60, charisma: 72, leadership: 82, ambition: 70, integrity: 88, resilience: 90, intrigue: 45 },
    },
    qualifiedFor: ["director-ports-authority"],
  },

  {
    name: "Commodore (Rtd.) Abubakar Dikko-Zungeru",
    age: 61,
    state: "Niger",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Nupe",
    avatar: "AD",
    traits: ["Naval Authority", "Maritime Security", "Disciplined"],
    bio: "Commanded the Western Naval Command before retirement and served as NIMASA Director-General, building Nigeria's coastal surveillance network that reduced piracy incidents in the Gulf of Guinea by 40%. His security instincts and naval network give him command of the maritime security establishment. Bureaucracy is not his natural element.",
    education: "Nigerian Defence Academy (Military Sciences), Naval War College Newport (Strategic Studies)",
    tradeOff: "His maritime security credentials and naval network are unmatched, but his military command culture may create friction in civilian regulatory environments that require persuasion, not orders.",
    competencies: {
      professional: { economics: 48, diplomacy: 55, security: 90, media: 45, legal: 52, administration: 72, technology: 60 },
      personal: { loyalty: 75, charisma: 65, leadership: 85, ambition: 60, integrity: 80, resilience: 88, intrigue: 42 },
    },
    qualifiedFor: ["director-maritime-administration", "director-ports-authority"],
  },

  {
    name: "Dr. Stella Oduah-Mbah",
    age: 53,
    state: "Anambra",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "SO",
    traits: ["Aviation Pioneer", "Bold Operator", "Political Survivor"],
    bio: "Nigeria's longest-serving aviation minister who oversaw the Abuja airport terminal completion and the recapitalisation of two indigenous airlines. Her acquisition of vehicles at inflated government cost remains a political liability that opponents reliably invoke. Her aviation sector relationships, however, are genuinely unmatched across the continent.",
    education: "University of Nigeria Nsukka (Business Administration), Florida State University (MBA Aviation Management)",
    tradeOff: "Deep aviation sector relationships and proven delivery capacity — but the financial scandal attached to her name will invite relentless scrutiny and opposition attacks that could embarrass the administration.",
    competencies: {
      professional: { economics: 65, diplomacy: 62, security: 40, media: 70, legal: 50, administration: 80, technology: 55 },
      personal: { loyalty: 70, charisma: 80, leadership: 75, ambition: 82, integrity: 48, resilience: 88, intrigue: 72 },
    },
    qualifiedFor: ["director-civil-aviation", "director-ports-authority"],
  },

  {
    name: "Engr. Chidi Udeozu-Nkwocha",
    age: 55,
    state: "Rivers",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "CU",
    traits: ["Port Engineer", "Infrastructure Technocrat", "Methodical"],
    bio: "Spent twenty-five years at the NPA's Engineering Division, overseeing the Tin Can Island port expansion that doubled container throughput. His deep understanding of port infrastructure financing — both public and through PPP — has made him the preferred consultant for every port project in the Gulf of Guinea. Has no political connexions and has never sought any.",
    education: "University of Port Harcourt (Civil Engineering), Rotterdam Erasmus University (MSc Port Management)",
    tradeOff: "A port infrastructure expert whose technical credibility will attract shipping line investment, but his aversion to politics means he will struggle to navigate the NPA's deeply politicised management culture.",
    competencies: {
      professional: { economics: 62, diplomacy: 48, security: 40, media: 35, legal: 42, administration: 78, technology: 80 },
      personal: { loyalty: 58, charisma: 45, leadership: 68, ambition: 52, integrity: 85, resilience: 75, intrigue: 28 },
    },
    qualifiedFor: ["director-ports-authority", "director-maritime-administration"],
  },

  {
    name: "Mrs. Hauwa Musa-Imam",
    age: 46,
    state: "Borno",
    gender: "Female",
    religion: "Islam",
    ethnicity: "Kanuri",
    avatar: "HM",
    traits: ["Aviation Safety Expert", "Meticulous", "International Standards"],
    bio: "Served as Director of Airworthiness Standards at the NCAA for eight years before becoming the first Nigerian elected to the ICAO Council's technical committee. Her unannounced ramp inspections have grounded three international airlines for safety violations — and prevented two potential disasters. She is the reason Nigeria has not had a fatal commercial aviation accident in nine years.",
    education: "Federal University of Technology Akure (Aeronautical Engineering), Embry-Riddle University (MSc Aviation Safety)",
    tradeOff: "The most credible aviation safety figure in West Africa whose appointment would signal seriousness about standards — but she will close airports and ground airlines without political notice, creating commercial crises.",
    competencies: {
      professional: { economics: 50, diplomacy: 58, security: 72, media: 45, legal: 68, administration: 80, technology: 82 },
      personal: { loyalty: 52, charisma: 55, leadership: 75, ambition: 58, integrity: 92, resilience: 85, intrigue: 30 },
    },
    qualifiedFor: ["director-civil-aviation"],
  },

  {
    name: "Capt. (Rtd.) Sixtus Okoye-Amadi",
    age: 60,
    state: "Imo",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "SO",
    traits: ["Airline Insider", "Commercial Pragmatist", "Industry Networked"],
    bio: "Flew for Nigerian Airways and later Arik Air before transitioning to airline management, eventually serving as COO of a West African regional carrier. His experience on both sides of the regulator-airline relationship makes him skilled at negotiating competing interests. Led the NCAA's air transport licensing reform that cut new airline certification time from three years to eighteen months.",
    education: "Nigerian College of Aviation Technology Zaria, Cranfield University (MSc Air Transport Management)",
    tradeOff: "His industry relationships make him a persuasive and practical regulator who airlines respect — but those same relationships risk regulatory capture, with favourable treatment for carriers connected to his network.",
    competencies: {
      professional: { economics: 62, diplomacy: 65, security: 55, media: 58, legal: 55, administration: 75, technology: 70 },
      personal: { loyalty: 62, charisma: 72, leadership: 70, ambition: 60, integrity: 65, resilience: 78, intrigue: 55 },
    },
    qualifiedFor: ["director-civil-aviation"],
  },

  {
    name: "Dr. Bashir Jamoh-Katsina",
    age: 52,
    state: "Katsina",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "BJ",
    traits: ["Maritime Economist", "Revenue Builder", "Reform-Minded"],
    bio: "Transformed NIMASA's cabotage enforcement from a porous, corruption-ridden regime into a functioning revenue collection system during his tenure as Director of Maritime Services, increasing cabotage levies by 300% in three years. His doctoral thesis on inland waterway commercialisation is the policy foundation for Nigeria's Blue Economy Strategy.",
    education: "University of Lagos (Economics), World Maritime University Sweden (MSc Maritime Affairs), University of Wales (PhD Maritime Economics)",
    tradeOff: "An evidence-based reformer who will turn NIMASA's revenue potential into reality — but his confrontational enforcement stance will generate resistance from shipping companies with powerful political patrons.",
    competencies: {
      professional: { economics: 78, diplomacy: 58, security: 60, media: 48, legal: 62, administration: 75, technology: 62 },
      personal: { loyalty: 60, charisma: 60, leadership: 72, ambition: 68, integrity: 82, resilience: 78, intrigue: 45 },
    },
    qualifiedFor: ["director-maritime-administration", "director-ports-authority"],
  },

  {
    name: "Mrs. Tosin Ajayi-Olawale",
    age: 44,
    state: "Kwara",
    gender: "Female",
    religion: "Islam",
    ethnicity: "Yoruba",
    avatar: "TA",
    traits: ["Logistics Reformer", "PPP Advocate", "Entrepreneurial"],
    bio: "Pioneered the use of digital port management systems at the Apapa and Tin Can Port complexes, cutting dwell time by 35% in a pilot that was subsequently adopted nationally. Her private sector background at a global logistics company gives her a user perspective rare among port regulators. She understands what traders and freight forwarders actually need.",
    education: "University of Ilorin (Business Administration), Maastricht School of Management (MSc Logistics and Supply Chain Management)",
    tradeOff: "Her private sector lens will drive genuine port efficiency improvements — but she may be naive about the patronage and cartel dynamics within the NPA that derail technically sound reforms.",
    competencies: {
      professional: { economics: 70, diplomacy: 60, security: 35, media: 58, legal: 45, administration: 72, technology: 80 },
      personal: { loyalty: 55, charisma: 70, leadership: 68, ambition: 72, integrity: 78, resilience: 70, intrigue: 38 },
    },
    qualifiedFor: ["director-ports-authority", "director-maritime-administration"],
  },

  {
    name: "Engr. Rabiu Adamu-Wara",
    age: 58,
    state: "Plateau",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Tiv",
    avatar: "RA",
    traits: ["Safety Standards Enforcer", "Process Driven", "Incorruptible"],
    bio: "Served as Deputy Director-General of the NCAA for twelve years and led the ICAO audit that removed Nigeria from the significant safety concern list — the most consequential aviation milestone Nigeria has achieved in thirty years. Known as inflexible, humorless, and absolutely reliable. Never accepted a single bribe across a forty-year career.",
    education: "University of Jos (Mechanical Engineering), Nigerian College of Aviation Technology, McGill University (International Aviation Law)",
    tradeOff: "His incorruptibility and safety record are unimpeachable — but his rigidity and poor political communication skills mean airlines and stakeholders will frequently circumvent him rather than engage.",
    competencies: {
      professional: { economics: 45, diplomacy: 42, security: 65, media: 32, legal: 65, administration: 82, technology: 75 },
      personal: { loyalty: 65, charisma: 38, leadership: 68, ambition: 48, integrity: 95, resilience: 80, intrigue: 25 },
    },
    qualifiedFor: ["director-civil-aviation"],
  },

  // ── Youth Development Sector ──────────────────────────────────────────────

  {
    name: "Brig.-Gen. (Rtd.) Mohammed Kura-Daura",
    age: 57,
    state: "Katsina",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "MK",
    traits: ["NYSC Disciplinarian", "Security-Minded", "Nationalist"],
    bio: "Commanded the NYSC Directorate as Director of Camp Operations, restoring corps member discipline and completing ten consecutive years of camp infrastructure improvements. His reintegration programme for former Boko Haram child soldiers into NYSC-adjacent vocational training is a model studied at UN DDR workshops. Believes the NYSC is Nigeria's most underused national institution.",
    education: "Nigerian Defence Academy (Arts and Social Sciences), National War College Abuja (Strategic Studies)",
    tradeOff: "Exceptional discipline and camp infrastructure track record — but his military mindset may alienate the increasingly politically aware youth corps he is meant to inspire.",
    competencies: {
      professional: { economics: 45, diplomacy: 55, security: 85, media: 50, legal: 52, administration: 82, technology: 45 },
      personal: { loyalty: 80, charisma: 60, leadership: 82, ambition: 55, integrity: 78, resilience: 88, intrigue: 40 },
    },
    qualifiedFor: ["director-youth-service-corps"],
  },

  {
    name: "Dr. Abiodun Funmilayo-Adeola",
    age: 45,
    state: "Ogun",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "AF",
    traits: ["Youth Empowerment Evangelist", "Digital Generation", "Media Savvy"],
    bio: "Founded one of Nigeria's largest youth employability NGOs, placing over 40,000 graduates in formal employment through her NYSC skill-pairing platform. Her TEDx Lagos talk on reforming NYSC's relevance to modern Nigeria has been viewed 3.2 million times. The first DG candidate who was actually a corps member in the digital age.",
    education: "University of Ibadan (Sociology), London School of Economics (MSc Social Policy)",
    tradeOff: "Her credibility with Nigeria's digital youth generation is unmatched — but her NGO background has not prepared her for the bureaucratic and political weight of managing a 300,000-person annual programme.",
    competencies: {
      professional: { economics: 55, diplomacy: 65, security: 28, media: 85, legal: 42, administration: 60, technology: 72 },
      personal: { loyalty: 52, charisma: 90, leadership: 70, ambition: 78, integrity: 80, resilience: 70, intrigue: 38 },
    },
    qualifiedFor: ["director-youth-service-corps", "director-social-investment"],
  },

  {
    name: "Dr. Umar Farouk-Alkali",
    age: 51,
    state: "Bauchi",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "UF",
    traits: ["Social Protection Technocrat", "Data-Driven", "Quiet Operator"],
    bio: "Designed the beneficiary targeting framework for Nigeria's National Social Investment Programme, reaching 1.2 million households with cash transfers under N-Power and the Conditional Cash Transfer scheme. His algorithm-based targeting reduced leakage from 45% to 12% — a feat that attracted World Bank commendation. He does his work and says nothing publicly.",
    education: "Abubakar Tafawa Balewa University (Economics), University of Manchester (MSc Development Economics), Oxford (DPhil Social Policy)",
    tradeOff: "A genuinely excellent social protection architect whose technical rigour will maximise programme impact — but his political passivity leaves him vulnerable to elite capture of programme budgets above his level.",
    competencies: {
      professional: { economics: 80, diplomacy: 52, security: 30, media: 35, legal: 45, administration: 78, technology: 75 },
      personal: { loyalty: 62, charisma: 42, leadership: 65, ambition: 52, integrity: 88, resilience: 72, intrigue: 30 },
    },
    qualifiedFor: ["director-social-investment", "director-youth-service-corps"],
  },

  {
    name: "Mrs. Chidinma Okafor-Ezeh",
    age: 43,
    state: "Enugu",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "CO",
    traits: ["Community Development Practitioner", "Collaborative", "Field-Tested"],
    bio: "Led UNICEF Nigeria's social protection technical team for eight years before joining the NSIP Secretariat as Head of Implementation. She built the field monitoring network that exposed ghost beneficiaries in six states and triggered prosecutions. Her field visits are unannounced and her data collection is meticulous. She has zero tolerance for programme fraud.",
    education: "University of Nigeria Nsukka (Social Sciences), University of Edinburgh (MSc International Development)",
    tradeOff: "A grounded, field-tested programme implementer whose anti-fraud vigilance will protect public resources — but her international development agency background may create friction with politicians who prefer flexible programme delivery.",
    competencies: {
      professional: { economics: 65, diplomacy: 60, security: 32, media: 55, legal: 48, administration: 80, technology: 65 },
      personal: { loyalty: 55, charisma: 65, leadership: 70, ambition: 58, integrity: 90, resilience: 80, intrigue: 30 },
    },
    qualifiedFor: ["director-social-investment"],
  },

  {
    name: "Mr. Nasiru Dambatta-Fulani",
    age: 54,
    state: "Kano",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "ND",
    traits: ["Northern Youth Mobiliser", "Grassroots Politician", "Patronage-Adjacent"],
    bio: "Built his career as a Kano State youth commissioner before rising to National Youth Council President, where he mobilised northern youth support for three successive presidential campaigns. His grassroots networks in the NW and NE are genuinely deep. His critics note that his programme delivery record is thin relative to his political footprint.",
    education: "Bayero University Kano (Political Science), Ahmadu Bello University (MA Public Policy)",
    tradeOff: "His northern youth mobilisation capacity and political loyalty are real assets — but his appointment risks turning NYSC into a political mobilisation platform rather than a national service institution.",
    competencies: {
      professional: { economics: 42, diplomacy: 65, security: 40, media: 72, legal: 38, administration: 60, technology: 40 },
      personal: { loyalty: 85, charisma: 82, leadership: 65, ambition: 82, integrity: 52, resilience: 72, intrigue: 72 },
    },
    qualifiedFor: ["director-youth-service-corps", "director-social-investment"],
  },

  {
    name: "Dr. Sade Oduola-Martins",
    age: 47,
    state: "Edo",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Edo",
    avatar: "SM",
    traits: ["Labour Economist", "Youth Unemployment Expert", "Evidence-Based"],
    bio: "Her landmark study of NYSC's employment impact found that fewer than 22% of corps members received skill training relevant to their eventual jobs — a finding that galvanised the Ministry of Youth's 2023 reform programme. As World Bank consultant on youth employment in SSA, she helped redesign social investment programmes in seven countries. She is a critic of the status quo and will act as one in office.",
    education: "University of Benin (Economics), Cornell (MSc Labour Economics), University of Oxford (DPhil Development Economics)",
    tradeOff: "A rigorous evidence-based reformer who will overhaul NYSC's relevance and impact — but her record of publishing inconvenient findings suggests she will not suppress data that embarrasses the administration.",
    competencies: {
      professional: { economics: 85, diplomacy: 62, security: 22, media: 65, legal: 42, administration: 65, technology: 68 },
      personal: { loyalty: 42, charisma: 72, leadership: 68, ambition: 70, integrity: 88, resilience: 78, intrigue: 28 },
    },
    qualifiedFor: ["director-social-investment", "director-youth-service-corps"],
  },

  // ── Foreign Affairs Sector ────────────────────────────────────────────────

  {
    name: "Amb. Abike Dabiri-Oduola",
    age: 58,
    state: "Ogun",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "AD",
    traits: ["Diaspora Champion", "Media Natural", "Politically Durable"],
    bio: "Built the Nigerians in Diaspora Commission from a three-room secretariat into a functioning agency with twelve bilateral investment agreements and a remittance tracking platform. Her parliamentary experience as a federal lawmaker gives her legislative fluency rare among appointees. She has survived four administrations through sheer usefulness and media savvy.",
    education: "University of Lagos (Mass Communication), Harvard Kennedy School (Executive Programme),",
    tradeOff: "An irreplaceable public face for Nigeria's diaspora relationships with proven media instincts — but her high-profile style generates celebrity-level scrutiny and she invites political envy from colleagues who resent her visibility.",
    competencies: {
      professional: { economics: 60, diplomacy: 88, security: 28, media: 90, legal: 50, administration: 70, technology: 55 },
      personal: { loyalty: 68, charisma: 95, leadership: 72, ambition: 80, integrity: 70, resilience: 85, intrigue: 58 },
    },
    qualifiedFor: ["director-diaspora-commission"],
  },

  {
    name: "Dr. Sunday Ochoche-Benue",
    age: 62,
    state: "Benue",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Tiv",
    avatar: "SO",
    traits: ["Conflict Mediator", "Academic Diplomat", "Peace Architecture"],
    bio: "A former Director of the Institute for Peace and Conflict Resolution who built Nigeria's mediation programme for border communities with seven ECOWAS neighbours. His quiet back-channel work is credited with preventing two border conflicts from escalating into diplomatic crises. He is calm in every storm, visible in none.",
    education: "University of Jos (Political Science), University of Bradford (MA Peace Studies), Johns Hopkins SAIS (PhD International Relations)",
    tradeOff: "A skilled backstage conflict diplomat who prevents crises before they happen — but his preference for quiet work means NIDCOM's public profile and diaspora community engagement will suffer.",
    competencies: {
      professional: { economics: 50, diplomacy: 90, security: 65, media: 42, legal: 60, administration: 68, technology: 40 },
      personal: { loyalty: 62, charisma: 60, leadership: 72, ambition: 48, integrity: 88, resilience: 80, intrigue: 42 },
    },
    qualifiedFor: ["director-diaspora-commission"],
  },

  {
    name: "Mrs. Hannatu Musawa-Doki",
    age: 46,
    state: "Katsina",
    gender: "Female",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "HM",
    traits: ["Investment Diplomat", "GCC Networked", "Northern Bridge"],
    bio: "Served as Nigeria's Deputy High Commissioner in Saudi Arabia where she personally developed the framework that facilitated $1.8 billion in Saudi and Emirati diaspora remittances into Nigeria's agricultural sector. Her Arabic fluency and understanding of Gulf diaspora investment patterns are unique in the Nigerian foreign service. Has cultivated close relationships with Hausa communities in Europe and North America.",
    education: "Usmanu Danfodiyo University (International Relations), Georgetown University (MA Arab Studies), SOAS London (MBA Islamic Finance)",
    tradeOff: "Her Gulf diaspora investment network is unique and lucrative — but her focus on GCC engagement may shortchange Nigeria's African and Western diaspora communities, which are numerically larger.",
    competencies: {
      professional: { economics: 68, diplomacy: 85, security: 42, media: 60, legal: 52, administration: 70, technology: 55 },
      personal: { loyalty: 68, charisma: 75, leadership: 68, ambition: 72, integrity: 75, resilience: 75, intrigue: 50 },
    },
    qualifiedFor: ["director-diaspora-commission"],
  },

  {
    name: "Prof. Victor Ukpong-Effiong",
    age: 61,
    state: "Akwa Ibom",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Efik",
    avatar: "VU",
    traits: ["Diaspora Scholar", "Strategic Planner", "Community Organiser"],
    bio: "Spent fifteen years running the Nigerian Community Association network across the United Kingdom before returning to chair the Diaspora Investment Initiative at the Ministry of Foreign Affairs. His grassroots diaspora organising produced the UK Nigerians Bond subscription that raised £220 million in forty-eight hours. He understands how diaspora communities actually think and what they fear.",
    education: "University of Calabar (Sociology), University of Birmingham (MA African Studies), University of Edinburgh (PhD Migration Studies)",
    tradeOff: "Genuine grassroots diaspora credibility and proven fundraising ability — but his community organising instincts may lead him to prioritise diaspora political mobilisation in ways that create awkward diplomatic sensitivities.",
    competencies: {
      professional: { economics: 58, diplomacy: 80, security: 30, media: 70, legal: 48, administration: 68, technology: 55 },
      personal: { loyalty: 58, charisma: 80, leadership: 68, ambition: 68, integrity: 78, resilience: 72, intrigue: 48 },
    },
    qualifiedFor: ["director-diaspora-commission"],
  },

  // ── Defence Sector ────────────────────────────────────────────────────────

  {
    name: "Maj.-Gen. (Rtd.) Ihejirika Nwosu-Aba",
    age: 63,
    state: "Abia",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "IN",
    traits: ["Defence Industrialist", "Systems Thinker", "Southeast Bridge"],
    bio: "Served as Chief of Army Staff before retiring and chairing the Board of the Defence Industries Corporation, where he oversaw the first successful local production of armoured patrol vehicles under the PROFORCE partnership. His understanding of what the Nigerian military actually needs, versus what it is sold, has saved the defence budget billions. He calls political interference in procurement what it is.",
    education: "Nigerian Defence Academy (Engineering), Royal Military College of Science UK (MSc Defence Technology), National Defence University Washington (MA Strategic Intelligence)",
    tradeOff: "Rare combination of operational military credibility and industrial management experience — but his blunt assessments of procurement corruption will make him a target for the defence contracting networks embedded in the system.",
    competencies: {
      professional: { economics: 60, diplomacy: 55, security: 90, media: 48, legal: 55, administration: 78, technology: 78 },
      personal: { loyalty: 65, charisma: 60, leadership: 88, ambition: 60, integrity: 85, resilience: 88, intrigue: 48 },
    },
    qualifiedFor: ["director-defence-industries"],
  },

  {
    name: "Dr. Zainab Hussain-Dambatta",
    age: 51,
    state: "Sokoto",
    gender: "Female",
    religion: "Islam",
    ethnicity: "Fulani",
    avatar: "ZH",
    traits: ["Defence Economist", "Procurement Reform Advocate", "Technocrat"],
    bio: "Built Nigeria's first defence procurement cost-benefit analysis framework as a civilian analyst at the Defence Headquarters, and subsequently exposed a $200 million inflated contract through her internal audit findings — a report that was quietly buried until it leaked. Her technical rigour is feared by defence contractors, which is precisely why several have lobbied against her appointment.",
    education: "Usmanu Danfodiyo University (Economics), King's College London (MA War Studies, Defence Economics), University of Bath (PhD Defence Procurement)",
    tradeOff: "Her procurement reform expertise would save the defence budget hundreds of millions — but the entrenched contractor networks opposing her appointment will make her tenure a constant political battle.",
    competencies: {
      professional: { economics: 85, diplomacy: 52, security: 68, media: 45, legal: 65, administration: 78, technology: 68 },
      personal: { loyalty: 55, charisma: 52, leadership: 72, ambition: 62, integrity: 92, resilience: 80, intrigue: 40 },
    },
    qualifiedFor: ["director-defence-industries"],
  },

  {
    name: "Air Vice Marshal (Rtd.) Akin Osoba-Ijagba",
    age: 60,
    state: "Ondo",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "AO",
    traits: ["Aerospace Technology", "Strategic Networked", "Pragmatic"],
    bio: "Led the Nigerian Air Force's Engineering Command, overseeing the maintenance and upgrade of thirty-two aircraft platforms, before serving as Nigeria's defence attaché in Washington where he brokered the FMS agreement for the A-29 Super Tucano acquisition. His Washington connexions in defence technology supply chains are genuinely unique in the Nigerian military establishment.",
    education: "Nigerian Defence Academy (Aeronautical Engineering), US Air Force Institute of Technology (MSc Systems Engineering), US Air War College (National Security Strategy)",
    tradeOff: "His US defence network and aerospace technology background open procurement doors no other candidate can access — but his long time in Washington may have misaligned his expectations with Nigeria's actual defence industrial capacity.",
    competencies: {
      professional: { economics: 55, diplomacy: 72, security: 88, media: 50, legal: 50, administration: 72, technology: 85 },
      personal: { loyalty: 68, charisma: 65, leadership: 80, ambition: 68, integrity: 78, resilience: 82, intrigue: 52 },
    },
    qualifiedFor: ["director-defence-industries"],
  },

  {
    name: "Engr. Aminu Bello-Katsina",
    age: 54,
    state: "Kaduna",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "AB",
    traits: ["Defence Manufacturing", "Industrial Policy", "Local Content Champion"],
    bio: "Spent sixteen years at the Defence Industries Corporation's Ordnance Factory before moving to the Bureau of Public Enterprises to manage DICON's privatisation review. His 'buy Nigerian first' defence procurement framework was adopted as policy in 2021 and has since shifted 18% of defence spending toward local suppliers. He understands Nigerian manufacturing constraints from the inside.",
    education: "Ahmadu Bello University Zaria (Mechanical Engineering), Cranfield University (MSc Defence Manufacturing), INSEAD (Executive Programme Industrial Policy)",
    tradeOff: "A committed local content champion who can genuinely grow Nigeria's defence industrial base — but his protectionist instincts may delay critical capability acquisitions that Nigeria needs urgently but cannot yet produce domestically.",
    competencies: {
      professional: { economics: 72, diplomacy: 50, security: 70, media: 42, legal: 50, administration: 80, technology: 80 },
      personal: { loyalty: 70, charisma: 52, leadership: 72, ambition: 62, integrity: 80, resilience: 78, intrigue: 42 },
    },
    qualifiedFor: ["director-defence-industries"],
  },

];
