// directorPoolBatch2.ts — Labour & Employment, Interior, Trade & Investment
import type { DirectorCandidate } from "./directorPool";

export const DIRECTOR_CANDIDATES_BATCH2: DirectorCandidate[] = [

  // ── Labour & Employment Sector ────────────────────────────────────────────

  {
    name: "Dr. Amina Suleiman-Garo",
    age: 52,
    state: "Kano",
    gender: "Female",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "AS",
    traits: ["Pension Architect", "Institutional", "Detail-Oriented"],
    bio: "Spent fifteen years at the National Pension Commission designing the contributory pension framework that now covers 9 million formal workers. Her reforms to the Pension Fund Administrator licensing regime cut fraudulent schemes by 60%. She views every unremitted pension deduction as a personal affront.",
    education: "Bayero University Kano (Actuarial Science), University of Manchester (MSc Pension Management)",
    tradeOff: "Will transform pension compliance rigour but her aggressive enforcement posture will antagonise state governments who habitually withhold pension remittances.",
    competencies: {
      professional: { economics: 80, diplomacy: 52, security: 18, communications: 38, legal: 62, administration: 85, technology: 58, management: 78, politics: 68 },
      personal: { loyalty: 55, charisma: 48, leadership: 72, ambition: 60, integrity: 87, resilience: 78, intrigue: 28, discretion: 82 },
    honorific: "Dr.",
    },
    qualifiedFor: ["director-pensions", "director-social-insurance"],
  },

  {
    name: "Alhaji Yusuf Garba-Ringim",
    age: 59,
    state: "Jigawa",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "YG",
    traits: ["Loyalist", "Consensus Builder", "Patient"],
    bio: "Served as Permanent Secretary in Jigawa's Labour Ministry for eleven years before his appointment as Director of Pensions under two federal administrations. Navigated the NLC general strike of 2021 without a single arrest by keeping back-channel dialogue alive for 72 hours straight. Known as 'the quiet fixer' in Abuja labour circles.",
    education: "Usmanu Danfodiyo University (Public Administration), ABU Zaria (MPA)",
    tradeOff: "Unmatched ability to de-escalate labour crises politically but his consensus instinct means overdue pension reforms will move at a glacial pace.",
    competencies: {
      professional: { economics: 58, diplomacy: 72, security: 28, communications: 45, legal: 55, administration: 80, technology: 32, management: 80, politics: 81 },
      personal: { loyalty: 84, charisma: 65, leadership: 70, ambition: 50, integrity: 68, resilience: 80, intrigue: 52, discretion: 79 },
    honorific: "Alh.",
    },
    qualifiedFor: ["director-pensions", "director-social-insurance"],
  },

  {
    name: "Mrs. Ngozi Chukwuemeka-Eze",
    age: 48,
    state: "Anambra",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "NC",
    traits: ["Labour Litigator", "Principled", "Sharp"],
    bio: "One of Nigeria's foremost labour law practitioners, she represented the NLC in landmark Supreme Court cases that redefined collective bargaining rights under the 1999 Constitution. Her tenure as Legal Adviser at the Industrial Arbitration Panel produced 200 precedent-setting awards. She has never lost a labour law case before the NICN.",
    education: "University of Nigeria Nsukka (LLB), Nigerian Law School (BL), University of London (LLM Labour Law)",
    tradeOff: "Best legal brain for protecting workers' rights in disputes but her combative courtroom instincts translate poorly to the diplomatic needs of union negotiations.",
    competencies: {
      professional: { economics: 42, diplomacy: 50, security: 15, communications: 55, legal: 90, administration: 65, technology: 38, management: 61, politics: 51 },
      personal: { loyalty: 48, charisma: 62, leadership: 70, ambition: 68, integrity: 85, resilience: 80, intrigue: 40, discretion: 76 },
    },
    qualifiedFor: ["director-industrial-relations"],
  },

  {
    name: "Mr. Emeka Nnaji-Obi",
    age: 55,
    state: "Enugu",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "EN",
    traits: ["Union Insider", "Pragmatist", "Streetwise"],
    bio: "Came up through the rank and file of the Nigeria Labour Congress before becoming Deputy Secretary-General, giving him an insider's understanding of union politics that no technocrat can match. Brokered the national minimum wage agreements of 2019 and 2023 by knowing exactly when to push and when to retreat. The NLC trusts him; employers are wary.",
    education: "Enugu State University (Industrial Relations), University of Ibadan (MSc Labour Studies)",
    tradeOff: "His union relationships make him uniquely effective at preventing strikes but employers' federations view him as a covert union operative inside government.",
    competencies: {
      professional: { economics: 55, diplomacy: 78, security: 22, communications: 60, legal: 65, administration: 68, technology: 35, management: 71, politics: 74 },
      personal: { loyalty: 65, charisma: 75, leadership: 72, ambition: 62, integrity: 70, resilience: 82, intrigue: 58, discretion: 77 },
    },
    qualifiedFor: ["director-industrial-relations"],
  },

  {
    name: "Dr. Fatima Aliyu-Musa",
    age: 44,
    state: "Niger",
    gender: "Female",
    religion: "Islam",
    ethnicity: "Nupe",
    avatar: "FA",
    traits: ["Youth Advocate", "Energetic", "Tech-Forward"],
    bio: "Founded the NigerTech Youth Employment Initiative at 32, placing 45,000 graduates into digital economy jobs before the federal government absorbed the programme. Her ILO fellowship produced a comparative study of youth employment schemes across 14 African countries that is now policy scripture at the Ministry of Labour. She speaks in data and dreams in job numbers.",
    education: "Federal University of Technology Minna (Computer Science), London School of Economics (MSc Development Studies)",
    tradeOff: "Exceptional at designing youth employment schemes with measurable impact but her impatience with bureaucratic process creates friction with line agencies.",
    competencies: {
      professional: { economics: 68, diplomacy: 58, security: 15, communications: 65, legal: 38, administration: 72, technology: 82, management: 65, politics: 60 },
      personal: { loyalty: 52, charisma: 78, leadership: 68, ambition: 78, integrity: 80, resilience: 72, intrigue: 32, discretion: 71 },
    honorific: "Dr.",
    },
    qualifiedFor: ["director-youth-employment"],
  },

  {
    name: "Mr. Babatunde Adekunle-Fagbemi",
    age: 50,
    state: "Ondo",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "BA",
    traits: ["Programme Manager", "Systematic", "Results-Oriented"],
    bio: "Oversaw the SURE-P youth employment component as Director at the National Directorate of Employment, managing a ₦28 billion portfolio across 27 states. His redesign of the Graduate Internship Scheme increased private-sector absorption from 12% to 41% in three years. Methodical to a fault but produces outcomes.",
    education: "Obafemi Awolowo University (Sociology), University of Sussex (MPA Development Management)",
    tradeOff: "Consistent programme delivery with strong audit trails but lacks the political instinct to secure supplementary budgets when allocations run dry mid-year.",
    competencies: {
      professional: { economics: 60, diplomacy: 55, security: 18, communications: 45, legal: 42, administration: 85, technology: 55, management: 79, politics: 70 },
      personal: { loyalty: 62, charisma: 50, leadership: 72, ambition: 55, integrity: 80, resilience: 75, intrigue: 30, discretion: 78 },
    },
    qualifiedFor: ["director-youth-employment", "director-social-insurance"],
  },

  {
    name: "Mrs. Hadiza Umar-Bello",
    age: 53,
    state: "Kaduna",
    gender: "Female",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "HU",
    traits: ["Social Protection Expert", "Methodical", "Internationally Networked"],
    bio: "Spent eight years at the ILO's Abuja office designing social insurance frameworks for West African governments before returning as Director of Social Insurance at the NSITF. Her actuarial overhaul of the Employee Compensation Scheme cut fraudulent claims by ₦4 billion annually. She makes the numbers work before anyone else asks whether they will.",
    education: "Ahmadu Bello University (Statistics), University of Leeds (MSc Social Policy), ILO Turin (Executive Programme)",
    tradeOff: "Technically rigorous and will make the NSITF solvent but her technical orientation means she struggles to communicate social insurance value to ordinary workers.",
    competencies: {
      professional: { economics: 75, diplomacy: 55, security: 20, communications: 35, legal: 58, administration: 82, technology: 62, management: 65, politics: 59 },
      personal: { loyalty: 58, charisma: 42, leadership: 68, ambition: 58, integrity: 85, resilience: 72, intrigue: 28, discretion: 69 },
    },
    qualifiedFor: ["director-social-insurance", "director-pensions"],
  },

  {
    name: "Mr. Chidi Okonkwo-Nwachukwu",
    age: 46,
    state: "Rivers",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "CO",
    traits: ["Industrial Diplomat", "Bilingual Negotiator", "Resilient"],
    bio: "Negotiated collective bargaining agreements for the petroleum industry unions at PENGASSAN for a decade, including the 2020 agreement that averted a sector-wide shutdown during COVID. His cross-sector experience mediating disputes in maritime, construction, and oil-field labour makes him rare. He has been tear-gassed at picket lines and hosted ambassadors — often in the same week.",
    education: "University of Port Harcourt (Industrial and Labour Relations), University of Amsterdam (LLM Labour and Employment Law)",
    tradeOff: "Exceptional in high-stakes industry disputes but his background in sectoral unions means general federal civil service relations feel unfamiliar to him.",
    competencies: {
      professional: { economics: 50, diplomacy: 82, security: 30, communications: 58, legal: 72, administration: 60, technology: 38, management: 66, politics: 69 },
      personal: { loyalty: 60, charisma: 72, leadership: 75, ambition: 62, integrity: 75, resilience: 88, intrigue: 45, discretion: 80 },
    },
    qualifiedFor: ["director-industrial-relations"],
  },

  {
    name: "Dr. Abubakar Shehu-Malami",
    age: 57,
    state: "Kebbi",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Fulani",
    avatar: "AM",
    traits: ["Policy Architect", "Deliberate", "Risk-Averse"],
    bio: "Designed the National Social Investment Programme's cash transfer architecture as a World Bank consultant before joining the federal civil service. His doctoral research on pension portability in informal-sector economies remains the most-cited Nigerian labour economics paper of the last decade. Moves slowly but builds institutions that outlast administrations.",
    education: "Usmanu Danfodiyo University (Economics), University of Nottingham (PhD Labour Economics)",
    tradeOff: "Creates durable policy architecture that survives political transitions but his deliberate pace will frustrate any administration demanding quick wins on youth employment.",
    competencies: {
      professional: { economics: 82, diplomacy: 55, security: 18, communications: 38, legal: 52, administration: 75, technology: 48, management: 66, politics: 61 },
      personal: { loyalty: 55, charisma: 42, leadership: 65, ambition: 55, integrity: 82, resilience: 70, intrigue: 32, discretion: 72 },
    honorific: "Dr.",
    },
    qualifiedFor: ["director-pensions", "director-social-insurance", "director-youth-employment"],
  },

  {
    name: "Mrs. Adaeze Nwosu-Ikenna",
    age: 49,
    state: "Imo",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "AN",
    traits: ["Skills Development Champion", "Persuasive", "Coalition Builder"],
    bio: "Ran the Industrial Training Fund's Southeast Zonal Office for nine years before joining the ILO's Lagos skills development programme. Personally negotiated 22 employer partnership agreements that created 18,000 certified apprenticeship slots in manufacturing, automotive, and ICT sectors. She speaks union language and boardroom language fluently.",
    education: "University of Nigeria Nsukka (Education Economics), Columbia University (MEd Workforce Development)",
    tradeOff: "Outstanding at building employer-government-union coalitions for skills programmes but can overcommit government resources chasing partnership targets.",
    competencies: {
      professional: { economics: 62, diplomacy: 78, security: 15, communications: 62, legal: 40, administration: 75, technology: 52, management: 65, politics: 68 },
      personal: { loyalty: 60, charisma: 80, leadership: 72, ambition: 70, integrity: 72, resilience: 75, intrigue: 42, discretion: 65 },
    },
    qualifiedFor: ["director-youth-employment", "director-industrial-relations"],
  },

  {
    name: "Engr. Sani Danlami-Borgu",
    age: 54,
    state: "Niger",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "SD",
    traits: ["Occupational Safety Expert", "Technical", "Persistent"],
    bio: "Led the Factory Inspectorate division of the Federal Ministry of Labour for twelve years, shutting down 340 death-trap facilities and surviving three political attempts to reinstall their owners. Survived a live-wire electrocution during a factory inspection in 2015 — and filed his incident report from the hospital bed. Inspectors do not argue with him.",
    education: "Ahmadu Bello University (Mechanical Engineering), University of Salford (MSc Occupational Health and Safety)",
    tradeOff: "Will dramatically improve workplace safety compliance but his enforcement-first approach will create investor perception problems during foreign direct investment drives.",
    competencies: {
      professional: { economics: 45, diplomacy: 45, security: 55, communications: 38, legal: 60, administration: 78, technology: 65, management: 73, politics: 61 },
      personal: { loyalty: 62, charisma: 45, leadership: 70, ambition: 52, integrity: 88, resilience: 90, intrigue: 25, discretion: 88 },
    honorific: "Engr.",
    },
    qualifiedFor: ["director-industrial-relations", "director-social-insurance"],
  },

  {
    name: "Dr. Josephine Adeola-Bankole",
    age: 47,
    state: "Oyo",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "JA",
    traits: ["Data Analyst", "Reform-Minded", "Academic Bridges"],
    bio: "Chaired the NBS labour force survey technical committee that for the first time captured informal economy employment comprehensively, changing Nigeria's published unemployment rate. Her fellowship at the International Institute for Labour Studies in Geneva produced a model for informal worker social insurance that four African nations have since adopted. She makes invisible workers visible in policy.",
    education: "University of Ibadan (Economics), Sciences Po Paris (MSc International Development), Geneva Graduate Institute (PhD)",
    tradeOff: "Redefines the evidence base for labour policy with scholarly rigour but her academic instincts slow decision-making when urgent operational interventions are needed.",
    competencies: {
      professional: { economics: 78, diplomacy: 60, security: 15, communications: 55, legal: 45, administration: 68, technology: 75, management: 68, politics: 65 },
      personal: { loyalty: 48, charisma: 60, leadership: 65, ambition: 65, integrity: 85, resilience: 70, intrigue: 30, discretion: 79 },
    honorific: "Dr.",
    },
    qualifiedFor: ["director-social-insurance", "director-youth-employment"],
  },

  // ── Interior Sector ───────────────────────────────────────────────────────

  {
    name: "AIG (Rtd.) Ibrahim Musa Dikko",
    age: 58,
    state: "Katsina",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "ID",
    traits: ["Command Authority", "Disciplinarian", "Institutional Reformer"],
    bio: "Rose to Assistant Inspector-General through the CID, leading the dismantling of four organised crime syndicates operating across the Sahel corridor. His redesign of the Police Service Commission's promotion examination ended a decade of rank-buying at the senior cadre level. Feared by corrupt officers, respected by the rank and file who benefited from his welfare reforms.",
    education: "University of Maiduguri (Criminology), National Institute for Policy and Strategic Studies (Certificate), Royal Military Academy Sandhurst (Senior Command Course)",
    tradeOff: "Will clean up the Police Commission decisively but his command-and-control style will clash with civilian ministry culture and National Assembly oversight committees.",
    competencies: {
      professional: { economics: 35, diplomacy: 50, security: 88, communications: 45, legal: 60, administration: 75, technology: 42, management: 84, politics: 67 },
      personal: { loyalty: 70, charisma: 62, leadership: 85, ambition: 60, integrity: 75, resilience: 88, intrigue: 48, discretion: 86 },
    },
    qualifiedFor: ["director-police-commission", "director-state-security"],
  },

  {
    name: "Mrs. Zainab Abdullahi-Kwara",
    age: 51,
    state: "Kwara",
    gender: "Female",
    religion: "Islam",
    ethnicity: "Yoruba",
    avatar: "ZA",
    traits: ["Governance Reformer", "Process-Driven", "Diplomatic"],
    bio: "Served as Deputy Director at the Independent Corrupt Practices Commission before moving to the Police Service Commission as Secretary. Her performance appraisal framework, the first merit-based one in the Commission's history, was implemented over fierce internal resistance. She navigates male-dominated security institutions by making every reform look inevitable.",
    education: "University of Ilorin (Law), Nigerian Law School (BL), University of Birmingham (LLM Public Law)",
    tradeOff: "Exceptional governance reformer who will modernise the Commission's processes but lacks the command presence to manage serving police officers who resist civilian oversight.",
    competencies: {
      professional: { economics: 40, diplomacy: 70, security: 48, communications: 55, legal: 80, administration: 82, technology: 52, management: 72, politics: 71 },
      personal: { loyalty: 65, charisma: 68, leadership: 72, ambition: 68, integrity: 82, resilience: 78, intrigue: 50, discretion: 75 },
    },
    qualifiedFor: ["director-police-commission", "director-electoral-commission"],
  },

  {
    name: "Mr. Murtala Abba-Gana",
    age: 55,
    state: "Borno",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Kanuri",
    avatar: "MA",
    traits: ["Customs Strategist", "Revenue Hawk", "Politically Wired"],
    bio: "Spent twenty-two years inside the Nigeria Customs Service, ending as Comptroller for the Apapa command — historically the country's highest-revenue zone. His task force crackdown on the Tin Can Island container fraud syndicate recovered ₦187 billion in a single operation. Has accumulated allies and enemies in almost equal measure across the import-export industry.",
    education: "University of Maiduguri (Accounting), Cranfield University (MSc Logistics and Supply Chain Management)",
    tradeOff: "Can dramatically increase Customs revenue and smash smuggling rings but his deep insider networks in the trade make it hard to distinguish enforcement from selective targeting.",
    competencies: {
      professional: { economics: 78, diplomacy: 52, security: 65, communications: 42, legal: 55, administration: 80, technology: 48, management: 88, politics: 76 },
      personal: { loyalty: 72, charisma: 58, leadership: 75, ambition: 70, integrity: 62, resilience: 82, intrigue: 72, discretion: 82 },
    },
    qualifiedFor: ["director-customs-services"],
  },

  {
    name: "Dr. Ngozi Okafor-Aneke",
    age: 50,
    state: "Anambra",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "NO",
    traits: ["Trade Economist", "Compliance Expert", "Fearless"],
    bio: "Led the World Customs Organization's capacity-building programme in West Africa before returning to Nigeria as head of the Customs Service's Research and Statistics Unit. Her risk-profiling model for import declarations reduced under-valuation by 34% in two years and earned Nigeria an international trade facilitation award. She has declined three offers of private-sector exit packages.",
    education: "University of Nigeria Nsukka (Economics), University of Ghana (MSc Trade Policy), WCO Headquarters Brussels (Technical Attaché)",
    tradeOff: "Will bring world-class technical standards to Customs but her internationalist reform agenda may move faster than domestic political tolerance allows.",
    competencies: {
      professional: { economics: 82, diplomacy: 65, security: 42, communications: 50, legal: 60, administration: 78, technology: 70, management: 83, politics: 80 },
      personal: { loyalty: 50, charisma: 62, leadership: 72, ambition: 68, integrity: 88, resilience: 78, intrigue: 35, discretion: 91 },
    honorific: "Dr.",
    },
    qualifiedFor: ["director-customs-services", "director-immigration-services"],
  },

  {
    name: "DIG (Rtd.) Suleiman Bako-Yola",
    age: 61,
    state: "Adamawa",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Fulani",
    avatar: "SB",
    traits: ["Counter-Terror Veteran", "Hard-nosed", "State-Loyal"],
    bio: "Served as Commander of the Counter-Terrorism Unit before his appointment as Deputy Inspector-General in charge of Operations. Coordinated the multinational Lake Chad Basin security operations from the Nigerian side for four years. His knowledge of Boko Haram's financial networks and recruitment pipelines is the deepest in the federal government.",
    education: "Nigerian Defence Academy (Security Studies), US Army War College (Senior Security Management)",
    tradeOff: "Unparalleled operational counter-terrorism knowledge but his security-state worldview will push the police commission towards military-style governance that civilian rights groups will loudly oppose.",
    competencies: {
      professional: { economics: 28, diplomacy: 42, security: 92, communications: 35, legal: 52, administration: 68, technology: 55, management: 68, politics: 45 },
      personal: { loyalty: 75, charisma: 50, leadership: 88, ambition: 55, integrity: 70, resilience: 92, intrigue: 55, discretion: 71 },
    },
    qualifiedFor: ["director-police-commission", "director-state-security"],
  },

  {
    name: "Mrs. Chidinma Eze-Okonkwo",
    age: 47,
    state: "Ebonyi",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "CE",
    traits: ["Immigration Technologist", "Process Innovator", "Persistent"],
    bio: "Led the Nigeria Immigration Service's biometric passport system rollout, reducing issuance time from 12 weeks to 48 hours across 42 service centres. Her integration of the INTERPOL fugitive database into NIS border posts was the first such real-time link on the African continent. She has been offered a senior UNHCR position twice and turned it down both times.",
    education: "University of Nigeria Nsukka (Computer Science), University of Reading (MSc Information Management), NIS Advanced Leadership Programme",
    tradeOff: "Will modernise immigration services dramatically but her focus on technology solutions means she underestimates the human intelligence and on-ground knowledge that veteran border officers carry.",
    competencies: {
      professional: { economics: 42, diplomacy: 55, security: 62, communications: 48, legal: 45, administration: 80, technology: 88, management: 71, politics: 63 },
      personal: { loyalty: 62, charisma: 55, leadership: 72, ambition: 65, integrity: 82, resilience: 78, intrigue: 35, discretion: 75 },
    },
    qualifiedFor: ["director-immigration-services"],
  },

  {
    name: "Mr. Abdulkarim Lafia-Nassarawa",
    age: 53,
    state: "Nasarawa",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Tiv",
    avatar: "AL",
    traits: ["Border Intelligence", "Discreet", "Multi-agency Coordinator"],
    bio: "Spent sixteen years at the State Security Service's Border Intelligence Directorate before transitioning to the NIS as a Deputy Comptroller-General. Designed the joint NIS-SSS-Customs border information-sharing protocol that reduced illicit arms entries at land borders by 28%. He collects no social media presence and gives no interviews — by policy.",
    education: "University of Jos (Political Science), National Defence College (Strategic Intelligence Programme)",
    tradeOff: "Exceptional at multi-agency border security coordination but his extreme opacity will create accountability problems with the National Assembly and civil society.",
    competencies: {
      professional: { economics: 35, diplomacy: 48, security: 85, communications: 22, legal: 50, administration: 72, technology: 58, management: 64, politics: 50 },
      personal: { loyalty: 78, charisma: 38, leadership: 75, ambition: 55, integrity: 72, resilience: 85, intrigue: 80, discretion: 69 },
    },
    qualifiedFor: ["director-immigration-services", "director-state-security"],
  },

  {
    name: "Prof. Obiageli Nwosu-Dike",
    age: 56,
    state: "Imo",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "OB",
    traits: ["Constitutional Scholar", "Electoral Reformer", "Media Savvy"],
    bio: "Nigeria's foremost scholar of electoral law, having argued the governorship election tribunal cases that established the threshold for substantial non-compliance. Her 400-page review of the 2015 and 2019 INEC operations is required reading in the Elections Division. Twice appointed to INEC's electoral reform committee — both times her recommendations were only partially implemented.",
    education: "University of Lagos (LLB), Nigerian Law School (BL), Harvard Law School (LLM Constitutional Law), University of Pretoria (PhD Electoral Law)",
    tradeOff: "Will transform the Electoral Commission's legal architecture but her academic insistence on best-in-class standards will create confrontations with politicians whose elections she is adjudicating.",
    competencies: {
      professional: { economics: 35, diplomacy: 58, security: 20, communications: 70, legal: 92, administration: 68, technology: 50, management: 71, politics: 64 },
      personal: { loyalty: 42, charisma: 72, leadership: 72, ambition: 70, integrity: 90, resilience: 78, intrigue: 40, discretion: 85 },
    honorific: "Prof.",
    },
    qualifiedFor: ["director-electoral-commission"],
  },

  {
    name: "Mr. Danjuma Garba-Zuru",
    age: 60,
    state: "Kebbi",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "DG",
    traits: ["INEC Insider", "Process Steward", "Low-Profile"],
    bio: "Spent 28 years inside INEC, rising to Resident Electoral Commissioner in three states before becoming a National Commissioner. Oversaw the biometric voter registration exercise for the North West zone — the continent's largest such exercise by population — without a single successful legal challenge to its results. He has seen every manipulation technique and built procedural defences against all of them.",
    education: "Usmanu Danfodiyo University (Political Science), University of Ibadan (MPA)",
    tradeOff: "Institutional memory no external appointee can match but his deep INEC roots mean he is seen as an insider pick by opposition parties who will challenge his independence.",
    competencies: {
      professional: { economics: 38, diplomacy: 62, security: 35, communications: 45, legal: 72, administration: 85, technology: 55, management: 80, politics: 76 },
      personal: { loyalty: 68, charisma: 48, leadership: 70, ambition: 45, integrity: 78, resilience: 80, intrigue: 55, discretion: 81 },
    },
    qualifiedFor: ["director-electoral-commission", "director-police-commission"],
  },

  {
    name: "DSS Director (Rtd.) Halima Binta-Waziri",
    age: 54,
    state: "Bauchi",
    gender: "Female",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "HB",
    traits: ["Intelligence Analyst", "Steady Nerve", "Institutional"],
    bio: "One of the very few women to reach director level inside the Department of State Services, heading the Domestic Threat Analysis division for six years. Her threat assessments on farmer-herder conflicts in 2018 and 2019 were adopted verbatim as NSC policy. She reads political situations with the same cold precision she applies to security threats.",
    education: "ABU Zaria (Political Science), Fletcher School of Law and Diplomacy (MA Security Studies)",
    tradeOff: "Brings rare analytical depth to state security operations but will struggle with the administrative and budgetary management dimensions that the role also demands.",
    competencies: {
      professional: { economics: 30, diplomacy: 55, security: 88, communications: 35, legal: 55, administration: 65, technology: 62, management: 74, politics: 62 },
      personal: { loyalty: 75, charisma: 52, leadership: 78, ambition: 60, integrity: 78, resilience: 88, intrigue: 72, discretion: 85 },
    },
    qualifiedFor: ["director-state-security", "director-police-commission"],
  },

  {
    name: "Mr. Rotimi Adeyemi-Ogun",
    age: 48,
    state: "Ogun",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "RA",
    traits: ["Customs Moderniser", "Trade Facilitation", "Tech-Oriented"],
    bio: "Led the Nigeria Customs Service's automation and single-window trade reform as Deputy Comptroller-General, cutting average cargo clearance from 21 days to 5 days at Lagos ports. His integration of the HS code classification AI tool earned Nigeria a WTO trade facilitation compliance award. The import lobby quietly funded three unsuccessful petitions against his tenure.",
    education: "University of Lagos (Economics), Warwick Business School (MSc International Trade and Finance)",
    tradeOff: "Will accelerate legitimate trade flows and increase revenue through technology but his reform agenda creates powerful enemies among clearing agents and informal freight networks.",
    competencies: {
      professional: { economics: 75, diplomacy: 60, security: 38, communications: 55, legal: 52, administration: 80, technology: 82, management: 72, politics: 66 },
      personal: { loyalty: 58, charisma: 62, leadership: 72, ambition: 68, integrity: 80, resilience: 75, intrigue: 42, discretion: 74 },
    },
    qualifiedFor: ["director-customs-services"],
  },

  {
    name: "Dr. Aisha Mohammed-Gusau",
    age: 46,
    state: "Zamfara",
    gender: "Female",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "AG",
    traits: ["Conflict Analyst", "Community Intelligence", "Resilient"],
    bio: "A political scientist who embedded with the National Security Adviser's office during the armed banditry crisis in the Northwest, producing the threat mapping that allowed targeted amnesty negotiations to succeed where military operations had failed. Her 2022 monograph on ungoverned spaces and state security remained classified for 18 months. Fearless in hostile environments.",
    education: "Usmanu Danfodiyo University (Political Science), Princeton University (PhD Security Studies)",
    tradeOff: "Provides the analytical depth and community intelligence perspective that conventional security appointees lack but has no administrative track record managing large security institutions.",
    competencies: {
      professional: { economics: 38, diplomacy: 65, security: 82, communications: 58, legal: 42, administration: 55, technology: 60, management: 56, politics: 56 },
      personal: { loyalty: 58, charisma: 68, leadership: 65, ambition: 72, integrity: 80, resilience: 85, intrigue: 60, discretion: 79 },
    honorific: "Dr.",
    },
    qualifiedFor: ["director-state-security", "director-immigration-services"],
  },

  {
    name: "Mr. Taribo Tonye-Dikibo",
    age: 52,
    state: "Bayelsa",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Ijaw",
    avatar: "TT",
    traits: ["Maritime Security", "Oil Community Liaison", "Resilient"],
    bio: "Served as NIS Comptroller for the Niger Delta's maritime border zone for nine years, reducing oil theft through illegal border crossings by coordinating with the Nigerian Navy and JTF. His community intelligence approach — building informant networks within fishing and creeks communities — produced results that aerial surveillance never could. The Delta's creeks hold no secrets from him.",
    education: "University of Port Harcourt (Political Science), King's College London (MSc Maritime Security)",
    tradeOff: "Irreplaceable maritime intelligence and community trust in the Niger Delta but his background is narrow and he would struggle to manage immigration services outside the coastal domain.",
    competencies: {
      professional: { economics: 35, diplomacy: 62, security: 82, communications: 42, legal: 48, administration: 68, technology: 52, management: 78, politics: 73 },
      personal: { loyalty: 70, charisma: 65, leadership: 72, ambition: 58, integrity: 72, resilience: 85, intrigue: 60, discretion: 87 },
    },
    qualifiedFor: ["director-immigration-services", "director-state-security"],
  },

  {
    name: "Mrs. Blessing Okoro-Effiom",
    age: 49,
    state: "Cross River",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Efik",
    avatar: "BO",
    traits: ["Electoral Law Practitioner", "Advocacy Champion", "Networked"],
    bio: "Has represented civil society groups as lead counsel in seven Supreme Court election petition cases, winning five. Her campaign for electronic transmission of results was cited by INEC's legal team when drafting the 2022 Electoral Act amendments. She turned down a Senate seat nomination to remain as a watchdog — colleagues say this was her shrewdest political move.",
    education: "University of Calabar (LLB), Nigerian Law School (BL), University of Cape Town (LLM Electoral Law)",
    tradeOff: "Unimpeachable on electoral integrity and civil society confidence but her career as an opposition litigant means the ruling party will never fully trust her independence.",
    competencies: {
      professional: { economics: 32, diplomacy: 62, security: 18, communications: 72, legal: 88, administration: 65, technology: 50, management: 67, politics: 64 },
      personal: { loyalty: 40, charisma: 75, leadership: 68, ambition: 72, integrity: 90, resilience: 80, intrigue: 45, discretion: 85 },
    },
    qualifiedFor: ["director-electoral-commission"],
  },

  {
    name: "Comptroller (Rtd.) Joseph Anyebe-Idoko",
    age: 60,
    state: "Benue",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Tiv",
    avatar: "JA",
    traits: ["Customs Enforcer", "Anti-Smuggling", "Battle-Tested"],
    bio: "Led the Customs anti-smuggling task force along the Nigeria-Cameroon border for twelve years, seizing goods worth over ₦300 billion and dismantling three major transnational contraband networks. His testimony before the Senate Finance Committee in 2020 directly led to additional funding for border patrol equipment. He is respected in the customs community for never shielding officers implicated in his operations.",
    education: "University of Jos (Public Administration), NCS Staff College (Senior Command Programme)",
    tradeOff: "Fierce and incorruptible enforcement culture but his confrontational style with trade associations will complicate the revenue-facilitation balance that modern Customs demands.",
    competencies: {
      professional: { economics: 55, diplomacy: 38, security: 78, communications: 42, legal: 60, administration: 75, technology: 42, management: 75, politics: 55 },
      personal: { loyalty: 65, charisma: 50, leadership: 78, ambition: 52, integrity: 85, resilience: 88, intrigue: 45, discretion: 85 },
    },
    qualifiedFor: ["director-customs-services", "director-police-commission"],
  },

  {
    name: "Dr. Abubakar Yunusa-Sokoto",
    age: 57,
    state: "Sokoto",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Fulani",
    avatar: "AY",
    traits: ["Security Policy Architect", "Consensus Builder", "Cautious"],
    bio: "Served as a senior analyst at the Office of the National Security Adviser before heading the Security Sector Reform Secretariat, producing Nigeria's first comprehensive national security strategy document. His framework for civilian oversight of security agencies was adopted by the African Union as a model for the continent. Prefers reform through consensus to confrontation.",
    education: "Usmanu Danfodiyo University (Law), King's College London (MA War Studies), Oxford University (DPhil Security Policy)",
    tradeOff: "Provides genuine strategic depth and international credibility in security governance but his preference for consensus slows responses when decisive action is needed.",
    competencies: {
      professional: { economics: 38, diplomacy: 70, security: 80, communications: 52, legal: 72, administration: 70, technology: 48, management: 81, politics: 80 },
      personal: { loyalty: 62, charisma: 60, leadership: 72, ambition: 58, integrity: 80, resilience: 75, intrigue: 52, discretion: 88 },
    honorific: "Dr.",
    },
    qualifiedFor: ["director-state-security", "director-police-commission"],
  },

  // ── Trade & Investment Sector ─────────────────────────────────────────────

  {
    name: "Dr. Temitope Akinwande-Bello",
    age: 50,
    state: "Lagos",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "TA",
    traits: ["Standards Evangelist", "Consumer Champion", "Fearless Regulator"],
    bio: "Transformed the Standards Organisation of Nigeria's product certification regime from a rubber-stamp operation to one that passed its first ISO 17065 international accreditation. Personally led the recall of 14 million substandard electrical fittings that had penetrated the Lagos market, working through the weekend to issue the public safety order before a mass-casualty fire. Industry feared her; consumers celebrated her.",
    education: "University of Lagos (Chemistry), National Open University (MSc Quality Management), TÜV Rheinland (Conformity Assessment Certification)",
    tradeOff: "Will build SON into a credible regulatory institution but her aggressive recall actions against politically connected manufacturers will require substantial presidential cover.",
    competencies: {
      professional: { economics: 55, diplomacy: 52, security: 15, communications: 65, legal: 62, administration: 82, technology: 70, management: 70, politics: 58 },
      personal: { loyalty: 52, charisma: 65, leadership: 75, ambition: 65, integrity: 90, resilience: 82, intrigue: 32, discretion: 77 },
    honorific: "Dr.",
    },
    qualifiedFor: ["director-standards-organisation"],
  },

  {
    name: "Mr. Chukwudi Anyanwu-Obasi",
    age: 55,
    state: "Abia",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "CA",
    traits: ["Export Promotion Expert", "Diaspora Connector", "Commercial"],
    bio: "Built the Nigerian Export Promotion Council's value-chain development programme into an operation that directly enabled ₦240 billion in non-oil exports over five years. Personally led 14 buyer-seller missions to Europe, Asia, and North America that resulted in verified long-term supply agreements for processed cassava, cocoa butter, and sesame. He sells Nigeria with a confidence that is contagious.",
    education: "University of Nigeria Nsukka (Business Administration), University of Sussex (MSc Trade Policy)",
    tradeOff: "Exceptional at opening international markets for Nigerian products but his deal-making energy can outpace the production capacity of the SMEs he champions, leading to missed delivery commitments.",
    competencies: {
      professional: { economics: 78, diplomacy: 82, security: 15, communications: 65, legal: 42, administration: 70, technology: 52, management: 61, politics: 66 },
      personal: { loyalty: 62, charisma: 85, leadership: 72, ambition: 75, integrity: 72, resilience: 75, intrigue: 42, discretion: 64 },
    },
    qualifiedFor: ["director-export-promotion"],
  },

  {
    name: "Mrs. Aisha Musa-Gamawa",
    age: 48,
    state: "Bauchi",
    gender: "Female",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "AM",
    traits: ["SME Champion", "Rural Commerce", "Patient Builder"],
    bio: "Led the Bank of Industry's SME cluster development programme in the northeast, helping 3,200 micro-enterprises formalise and access government procurement contracts. Her rural product development work with women's cooperatives produced the first certified shea butter exports from Bauchi State. She finds supply chains where others see only subsistence.",
    education: "Abubakar Tafawa Balewa University Bauchi (Business Administration), University of Edinburgh (MBA International Business)",
    tradeOff: "Outstanding at building grassroots export capacity for northern small enterprises but lacks the sophisticated financial structuring skills to negotiate large investment treaties.",
    competencies: {
      professional: { economics: 70, diplomacy: 62, security: 18, communications: 52, legal: 40, administration: 78, technology: 48, management: 75, politics: 71 },
      personal: { loyalty: 68, charisma: 68, leadership: 70, ambition: 60, integrity: 80, resilience: 78, intrigue: 35, discretion: 80 },
    },
    qualifiedFor: ["director-export-promotion", "director-standards-organisation"],
  },

  {
    name: "Prof. Emmanuel Adeyeye-Oke",
    age: 59,
    state: "Osun",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "EA",
    traits: ["Tourism Academic", "Heritage Advocate", "Visionary"],
    bio: "Chaired the Nigerian Tourism Development Corporation's master planning committee that produced the first comprehensive national tourism strategy in 20 years. His UNESCO collaboration to inscribe Osun-Osogbo as a World Heritage site increased annual visitor revenue to the site sixfold. He has more ideas for Nigerian tourism than any single administration can fund — and he knows it.",
    education: "Obafemi Awolowo University (Hospitality and Tourism Management), University of Surrey (PhD Tourism Policy)",
    tradeOff: "Provides the strategic vision and international credibility to transform tourism policy but his expansive ambitions regularly exceed the budgets available, leading to high-profile incomplete projects.",
    competencies: {
      professional: { economics: 62, diplomacy: 70, security: 15, communications: 72, legal: 42, administration: 68, technology: 52, management: 65, politics: 65 },
      personal: { loyalty: 55, charisma: 78, leadership: 70, ambition: 78, integrity: 75, resilience: 68, intrigue: 42, discretion: 68 },
    honorific: "Prof.",
    },
    qualifiedFor: ["director-tourism-board"],
  },

  {
    name: "Mrs. Funmilola Adegoke-Martins",
    age: 46,
    state: "Ekiti",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "FM",
    traits: ["Investment Promoter", "Brand Builder", "Globally Connected"],
    bio: "Spent ten years at the Nigeria Investment Promotion Commission before moving to the African Development Bank as a private sector specialist. She designed the 'Invest Nigeria' global brand campaign that ran in 28 countries and contributed to a 22% increase in Greenfield FDI inflows in its launch year. Knows every sovereign wealth fund and private equity desk that looks at West Africa.",
    education: "University of Ado-Ekiti (Economics), University of Chicago Booth (MBA)",
    tradeOff: "Extraordinary investment attraction skills and global network but her private sector sensibility creates friction with the civil service culture of the agencies she would oversee.",
    competencies: {
      professional: { economics: 78, diplomacy: 82, security: 15, communications: 72, legal: 45, administration: 65, technology: 60, management: 62, politics: 68 },
      personal: { loyalty: 52, charisma: 85, leadership: 70, ambition: 80, integrity: 72, resilience: 72, intrigue: 50, discretion: 66 },
    },
    qualifiedFor: ["director-export-promotion", "director-tourism-board"],
  },

  {
    name: "Engr. Uche Nwofor-Obiora",
    age: 54,
    state: "Anambra",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "UN",
    traits: ["Mining Engineer", "Value Chain Thinker", "Tenacious"],
    bio: "Built a mining consultancy firm that led the geological survey and development programme for three solid mineral concessions in Nasarawa before joining the Nigerian Mining Corporation as Executive Director. His community development compact model for mining host communities has been cited by the African Union as a best practice framework. Knows where the minerals are and how to get them out sustainably.",
    education: "University of Nigeria Nsukka (Geology), University of Leeds (MSc Mineral Economics), Imperial College London (Mining Engineering Certificate)",
    tradeOff: "Genuine technical mining expertise and community relations experience but his private sector roots create perceptions of conflict of interest with former business associates who hold concessions.",
    competencies: {
      professional: { economics: 70, diplomacy: 58, security: 28, communications: 42, legal: 50, administration: 72, technology: 75, management: 78, politics: 71 },
      personal: { loyalty: 60, charisma: 55, leadership: 72, ambition: 68, integrity: 72, resilience: 80, intrigue: 48, discretion: 82 },
    honorific: "Engr.",
    },
    qualifiedFor: ["director-mining-development"],
  },

  {
    name: "Dr. Maryam Bagudu-Kebbi",
    age: 47,
    state: "Kebbi",
    gender: "Female",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "MB",
    traits: ["Standards Technocrat", "Metrology Expert", "Systematic"],
    bio: "Designed the national calibration and metrology framework as Director of Metrology at SON, ensuring that Nigerian measuring instruments meet international standards for the first time. Her work with NAFDAC on food labelling standards directly reduced adulterated imports at land borders by 40%. She believes that a standard is only as good as its enforcement mechanism.",
    education: "Usmanu Danfodiyo University (Physics), University of Berlin (MSc Metrology and Quality Assurance), ISO Geneva (Expert Technical Committee Member)",
    tradeOff: "Technically unimpeachable on standards and metrology but her narrow technical expertise means she struggles with the commercial promotion dimensions of the SON mandate.",
    competencies: {
      professional: { economics: 52, diplomacy: 48, security: 18, communications: 35, legal: 55, administration: 82, technology: 85, management: 78, politics: 68 },
      personal: { loyalty: 62, charisma: 40, leadership: 68, ambition: 55, integrity: 88, resilience: 75, intrigue: 28, discretion: 85 },
    honorific: "Dr.",
    },
    qualifiedFor: ["director-standards-organisation"],
  },

  {
    name: "Mr. Solomon Gyang-Bwakai",
    age: 52,
    state: "Plateau",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Tiv",
    avatar: "SG",
    traits: ["Mineral Development", "Community Advocate", "Conflict-Sensitive"],
    bio: "Worked as a geologist with the Geological Survey of Nigeria for fifteen years before becoming the Director of Mineral Resources in Plateau State, where he navigated the politically explosive tin and columbite mining sector during peak farmer-herder tensions. His conflict-sensitive mining approach brought host communities and operators into revenue-sharing agreements that held through multiple crises.",
    education: "University of Jos (Geology), Australian National University (MSc Mineral Policy)",
    tradeOff: "Uniquely skilled at managing mining operations in conflict-affected communities but his state-level experience hasn't prepared him for the regulatory complexity of federal mining governance.",
    competencies: {
      professional: { economics: 62, diplomacy: 68, security: 45, communications: 48, legal: 52, administration: 72, technology: 65, management: 80, politics: 79 },
      personal: { loyalty: 65, charisma: 60, leadership: 70, ambition: 58, integrity: 78, resilience: 82, intrigue: 45, discretion: 89 },
    },
    qualifiedFor: ["director-mining-development"],
  },

  {
    name: "Mrs. Amaka Udeh-Obiechina",
    age: 51,
    state: "Enugu",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "AU",
    traits: ["Trade Policy Expert", "WTO Negotiator", "Precision-Oriented"],
    bio: "Served as Nigeria's lead negotiator on the African Continental Free Trade Area protocol on goods, fighting hard for transition periods that protected Nigerian manufacturers from premature competition. Her WTO dispute settlement case on Nigerian processed tomato imports was the first sub-Saharan African trade remedy case to succeed at the panel level. Every word of a trade text matters to her.",
    education: "University of Nigeria Nsukka (Law), University of Nottingham (LLM International Trade Law), WTO Geneva (Trade Policy Training)",
    tradeOff: "Best trade negotiator in the federal system for protecting Nigerian producers but her defensive trade instincts can delay the facilitation reforms that foreign investors want to see.",
    competencies: {
      professional: { economics: 72, diplomacy: 78, security: 15, communications: 50, legal: 88, administration: 68, technology: 45, management: 77, politics: 82 },
      personal: { loyalty: 58, charisma: 60, leadership: 68, ambition: 65, integrity: 82, resilience: 78, intrigue: 45, discretion: 89 },
    },
    qualifiedFor: ["director-export-promotion", "director-standards-organisation"],
  },

  {
    name: "Mr. Aliyu Tanko-Gombe",
    age: 56,
    state: "Gombe",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Kanuri",
    avatar: "AT",
    traits: ["Investment Bureaucrat", "Reliable", "Behind-the-scenes"],
    bio: "Spent 24 years at the Nigerian Investment Promotion Commission, the last seven as Deputy Executive Director for Investment Promotion. Oversaw the NIPC's one-stop shop for investor facilitation, cutting business registration from 40 days to 6 days. He is the quietly indispensable civil servant who makes investment happen after the minister's press conference.",
    education: "University of Maiduguri (Business Administration), Georgetown University (Executive Programme in International Trade)",
    tradeOff: "Unmatched institutional knowledge of investment facilitation processes but his career-bureaucrat identity means he lacks the entrepreneurial energy to attract transformative investments.",
    competencies: {
      professional: { economics: 68, diplomacy: 62, security: 18, communications: 38, legal: 55, administration: 85, technology: 52, management: 78, politics: 77 },
      personal: { loyalty: 75, charisma: 45, leadership: 65, ambition: 48, integrity: 78, resilience: 72, intrigue: 40, discretion: 78 },
    },
    qualifiedFor: ["director-standards-organisation", "director-mining-development"],
  },

  {
    name: "Mr. Godwin Akpobome-Eferebo",
    age: 49,
    state: "Delta",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Urhobo",
    avatar: "GA",
    traits: ["Tourism Entrepreneur", "Creative Disruptor", "High-Energy"],
    bio: "Founded Nigeria's first ecotourism certification company, listing 140 Delta waterways and forest lodges with international booking platforms before selling the business to pivot into government. His consultation with state governments on tourism infrastructure produced three award-winning waterfront tourism zones. He sees Nigeria's cultural and natural heritage as an untapped balance sheet asset.",
    education: "Delta State University (Business Administration), Cornell University (School of Hotel Administration Executive Certificate)",
    tradeOff: "Brings entrepreneurial energy and private-sector tourism experience that no career civil servant can match but his lack of experience managing large public institutions will show during financial and staffing crises.",
    competencies: {
      professional: { economics: 65, diplomacy: 70, security: 15, communications: 78, legal: 38, administration: 60, technology: 65, management: 69, politics: 70 },
      personal: { loyalty: 55, charisma: 82, leadership: 68, ambition: 78, integrity: 70, resilience: 70, intrigue: 48, discretion: 75 },
    },
    qualifiedFor: ["director-tourism-board"],
  },

  {
    name: "Dr. Binta Aliyu-Maigari",
    age: 53,
    state: "Sokoto",
    gender: "Female",
    religion: "Islam",
    ethnicity: "Fulani",
    avatar: "BA",
    traits: ["Mineral Economist", "Policy Thinker", "Deliberate"],
    bio: "Led the Nigerian Mining Cadastre Office's digital licence management system, cutting turnaround on mining licence applications from 18 months to 45 days and eliminating the opaque queuing system that had fed corruption for two decades. Her World Bank-funded review of Nigeria's mining fiscal regime produced royalty rate recommendations that added ₦18 billion annually to government revenues.",
    education: "Usmanu Danfodiyo University (Economics), University of British Columbia (MSc Mining Economics)",
    tradeOff: "Will bring transparency and fiscal rigour to mining governance but her reform pace will be deliberately slow as she builds broad stakeholder consensus before acting.",
    competencies: {
      professional: { economics: 80, diplomacy: 58, security: 22, communications: 42, legal: 55, administration: 78, technology: 68, management: 71, politics: 66 },
      personal: { loyalty: 60, charisma: 48, leadership: 68, ambition: 58, integrity: 85, resilience: 72, intrigue: 35, discretion: 77 },
    honorific: "Dr.",
    },
    qualifiedFor: ["director-mining-development", "director-export-promotion"],
  },

];
