// client/src/lib/directorPool.ts
// Hand-crafted director (agency head) candidate pool — all ministries
// Batch 1: Finance, Health, Education, Agriculture, Works & Housing, Petroleum/Power
// Batch 2: Labour & Employment, Interior, Trade & Investment
// Batch 3: Communications, Environment, Justice, Transport, Youth Dev, Foreign Affairs, Defence

import { DIRECTOR_CANDIDATES_BATCH2 } from "./directorPoolBatch2";
import { DIRECTOR_CANDIDATES_BATCH3 } from "./directorPoolBatch3";

export interface DirectorCandidate {
  name: string;
  age: number;
  state: string;
  gender: "Male" | "Female";
  religion: string;
  ethnicity: string;
  avatar: string;
  traits: string[];
  bio: string;
  education: string;
  tradeOff: string;
  competencies: {
    professional: {
      economics: number;
      diplomacy: number;
      security: number;
      media: number;
      legal: number;
      administration: number;
      technology: number;
    };
    personal: {
      loyalty: number;
      charisma: number;
      leadership: number;
      ambition: number;
      integrity: number;
      resilience: number;
      intrigue: number;
    };
  };
  qualifiedFor: string[]; // position IDs from directorPositions.ts
}

const BATCH1_CANDIDATES: DirectorCandidate[] = [
  // ── Finance Sector ──────────────────────────────────────────────────────────

  {
    name: "Prof. Usman Yusuf Dangida",
    age: 61,
    state: "Sokoto",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Fulani",
    avatar: "UD",
    traits: ["Monetary Hawk", "Institutional", "Austere"],
    bio: "Served as Deputy Governor of the Central Bank for nine years, architecting Nigeria's inflation-targeting transition. His doctoral thesis on West African monetary union remains required reading at the African Development Bank. Loathes politicians who treat the CBN as an ATM.",
    education: "Usmanu Danfodiyo University (Economics), London School of Economics (PhD Monetary Policy)",
    tradeOff: "Extraordinary monetary credibility but will publicly clash with the presidency over any fiscal dominance of monetary policy.",
    competencies: {
      professional: { economics: 95, diplomacy: 60, security: 20, media: 40, legal: 50, administration: 70, technology: 55 },
      personal: { loyalty: 35, charisma: 50, leadership: 80, ambition: 55, integrity: 92, resilience: 85, intrigue: 25 },
    },
    qualifiedFor: ["governor-central-bank", "director-budget-office", "director-investment-council"],
  },

  {
    name: "Dr. Ngozi Okonkwo-Briggs",
    age: 54,
    state: "Anambra",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "NO",
    traits: ["Reformist", "Sharp-tongued", "Globally Networked"],
    bio: "Spent twelve years at the IMF's Fiscal Affairs Department before returning to lead the Nigerian Economic Summit Group. Brokered the 2019 debt restructuring that saved states from default. Her blunt assessments of fiscal recklessness have made powerful enemies in the National Assembly.",
    education: "University of Nigeria Nsukka (Economics), Harvard Kennedy School (MPA), Oxford (DPhil Development Economics)",
    tradeOff: "Exceptional reformist credibility with international markets but her candour will create constant political friction.",
    competencies: {
      professional: { economics: 91, diplomacy: 72, security: 15, media: 60, legal: 55, administration: 68, technology: 50 },
      personal: { loyalty: 42, charisma: 68, leadership: 78, ambition: 70, integrity: 85, resilience: 80, intrigue: 35 },
    },
    qualifiedFor: ["governor-central-bank", "director-investment-council", "director-budget-office"],
  },

  {
    name: "Alhaji Musa Makarfi Funtua",
    age: 58,
    state: "Katsina",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "MF",
    traits: ["Loyalist", "Operator", "Networked"],
    bio: "A fixture of NW banking circles who served as MD of two tier-1 commercial banks before entering public service. His appointment as Budget Director under two administrations earned him the nickname 'The Steady Hand.' Loyalty to the presidency is his defining trait — and his critics say his only one.",
    education: "Ahmadu Bello University (Accounting), University of Warwick (MBA Finance)",
    tradeOff: "Reliable political loyalty and smooth implementation but will bend fiscal rules to serve the presidency's interests.",
    competencies: {
      professional: { economics: 72, diplomacy: 58, security: 25, media: 45, legal: 48, administration: 80, technology: 42 },
      personal: { loyalty: 88, charisma: 62, leadership: 70, ambition: 65, integrity: 52, resilience: 75, intrigue: 60 },
    },
    qualifiedFor: ["director-budget-office", "director-revenue-service", "director-investment-council"],
  },

  {
    name: "Mrs. Kemi Adesanya-Ogundele",
    age: 50,
    state: "Ogun",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "KA",
    traits: ["Tax Technocrat", "Incorruptible", "Systematic"],
    bio: "Built the FIRS's automated tax compliance system from scratch, doubling collection efficiency in four years. A former PricewaterhouseCoopers senior partner, she prosecuted the first successful transfer-pricing case against a multinational in West Africa. Feared by tax evaders, beloved by auditors.",
    education: "University of Lagos (Accounting), ICAN (Fellow), CIMA (UK)",
    tradeOff: "Her zero-tolerance for non-compliance will boost revenues dramatically but will alienate influential business elites who fund party operations.",
    competencies: {
      professional: { economics: 80, diplomacy: 50, security: 20, media: 42, legal: 75, administration: 85, technology: 65 },
      personal: { loyalty: 50, charisma: 55, leadership: 75, ambition: 60, integrity: 93, resilience: 82, intrigue: 28 },
    },
    qualifiedFor: ["director-revenue-service", "director-budget-office", "director-bureau-statistics"],
  },

  {
    name: "Dr. Bello Abubakar Gombe",
    age: 48,
    state: "Gombe",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Tangale",
    avatar: "BG",
    traits: ["Data-Driven", "Quiet Ambition", "Policy Wonk"],
    bio: "Nigeria's youngest-ever Director of Statistics when appointed at 39, he transformed the NBS into a credible data institution recognised by the UN. His GDP rebasing exercise in 2021 altered the country's economic self-understanding overnight. Operates quietly but with enormous institutional influence.",
    education: "University of Maiduguri (Statistics), University of Cambridge (MPhil Economics), Paris School of Economics (PhD)",
    tradeOff: "Technically unimpeachable and will produce data that reflects harsh economic reality — which may embarrass the administration mid-term.",
    competencies: {
      professional: { economics: 83, diplomacy: 55, security: 18, media: 38, legal: 40, administration: 72, technology: 78 },
      personal: { loyalty: 55, charisma: 45, leadership: 68, ambition: 72, integrity: 85, resilience: 70, intrigue: 40 },
    },
    qualifiedFor: ["director-bureau-statistics", "director-budget-office", "director-investment-council"],
  },

  {
    name: "Prof. Titilayo Adewale-Fashola",
    age: 56,
    state: "Ekiti",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "TA",
    traits: ["Investment Diplomat", "Polished", "Strategic"],
    bio: "Served as Nigeria's trade attaché in Singapore before becoming Senior VP at the African Export-Import Bank. She personally led negotiations for three sovereign bond issuances that oversubscribed 3x. Her Rolodex of Gulf sovereign wealth funds is unmatched.",
    education: "Obafemi Awolowo University (Finance), Columbia Business School (MBA), Wharton (Executive Finance)",
    tradeOff: "Opens doors no one else can but her ambitions for a future political career mean she may prioritise her profile over institutional discipline.",
    competencies: {
      professional: { economics: 82, diplomacy: 85, security: 15, media: 70, legal: 52, administration: 65, technology: 48 },
      personal: { loyalty: 55, charisma: 82, leadership: 74, ambition: 85, integrity: 68, resilience: 72, intrigue: 58 },
    },
    qualifiedFor: ["director-investment-council", "director-export-promotion", "director-diaspora-commission"],
  },

  {
    name: "Alhaji Suleiman Haliru Zamfara",
    age: 63,
    state: "Zamfara",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "SZ",
    traits: ["Political Heavyweight", "Patronage Master", "Shrewd"],
    bio: "A former state finance commissioner who survived four gubernatorial administrations through masterful political navigation. Chairs the Zamfara Bankers Forum and controls significant rural cooperative credit networks. His enemies accuse him of ghost-worker racketeering; his supporters call him a survivor.",
    education: "Bayero University Kano (Accounting), ABU Zaria (MBA Public Administration)",
    tradeOff: "Brings deep northern political networks and guarantees smooth legislative cooperation but comes with credible corruption exposure.",
    competencies: {
      professional: { economics: 65, diplomacy: 55, security: 35, media: 50, legal: 58, administration: 75, technology: 30 },
      personal: { loyalty: 82, charisma: 70, leadership: 68, ambition: 78, integrity: 38, resilience: 80, intrigue: 85 },
    },
    qualifiedFor: ["director-budget-office", "director-revenue-service"],
  },

  {
    name: "Dr. Ifeoma Obi-Nwosu",
    age: 46,
    state: "Imo",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "IO",
    traits: ["Econometrician", "Meticulous", "Outspoken"],
    bio: "A World Bank consultant who built early-warning fiscal models for twelve African governments before returning home to chair the NISER research committee. Published the definitive study on Nigeria's tax-to-GDP ratio that embarrassed three successive finance ministries. She does not suffer political interference quietly.",
    education: "University of Ibadan (Statistics), University of Toronto (PhD Econometrics)",
    tradeOff: "Best statistical mind in the country but will publish data uncomfortable to the government and cannot be silenced without political cost.",
    competencies: {
      professional: { economics: 85, diplomacy: 48, security: 12, media: 52, legal: 42, administration: 68, technology: 82 },
      personal: { loyalty: 38, charisma: 58, leadership: 65, ambition: 68, integrity: 90, resilience: 75, intrigue: 30 },
    },
    qualifiedFor: ["director-bureau-statistics", "director-budget-office"],
  },

  {
    name: "Mr. Emeka Okafor-Dike",
    age: 52,
    state: "Enugu",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "EO",
    traits: ["Private Equity Veteran", "Deal-Maker", "Cosmopolitan"],
    bio: "Spent twenty years in London and Dubai structuring infrastructure bonds for sub-Saharan Africa. Co-founded the Lagos-listed Nile Capital Partners before answering a patriotic call to return. He speaks the language of international capital fluently and knows exactly what scares foreign investors about Nigeria.",
    education: "University of Nigeria Nsukka (Economics), Imperial College London (MSc Finance), CFA Charterholder",
    tradeOff: "Can unlock foreign direct investment like no other candidate but his private equity mindset may lead him to commodify public assets.",
    competencies: {
      professional: { economics: 86, diplomacy: 78, security: 15, media: 65, legal: 60, administration: 62, technology: 58 },
      personal: { loyalty: 52, charisma: 75, leadership: 72, ambition: 80, integrity: 70, resilience: 68, intrigue: 48 },
    },
    qualifiedFor: ["director-investment-council", "director-export-promotion", "director-ports-authority"],
  },

  {
    name: "Mallam Ibrahim Yakubu Ningi",
    age: 55,
    state: "Bauchi",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "IY",
    traits: ["Revenue Hunter", "Methodical", "Compliant"],
    bio: "Overhauled tax administration in Bauchi State, achieving a 140% non-oil revenue growth in three years as State Internal Revenue Chairman. A veteran of five federal fiscal committees who knows every loophole in the Finance Act. He executes directives faithfully and avoids the limelight.",
    education: "Abubakar Tafawa Balewa University (Business Administration), CITN (Fellow)",
    tradeOff: "Competent and politically compliant but lacks the stature to confront entrenched interests at the federal level.",
    competencies: {
      professional: { economics: 74, diplomacy: 45, security: 22, media: 35, legal: 65, administration: 82, technology: 48 },
      personal: { loyalty: 85, charisma: 42, leadership: 65, ambition: 50, integrity: 72, resilience: 72, intrigue: 42 },
    },
    qualifiedFor: ["director-revenue-service", "director-budget-office"],
  },

  {
    name: "Dr. Hadiza Murtala Kano",
    age: 44,
    state: "Kano",
    gender: "Female",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "HM",
    traits: ["Monetary Technocrat", "Modest", "Precise"],
    bio: "Rose through the CBN research department to become the youngest-ever head of the Monetary Policy Department at 38. Her inflation forecasting models have outperformed every external predictor for six consecutive years. Conservative in lifestyle as in policy — she drives a ten-year-old Camry.",
    education: "BUK Kano (Economics), University of Manchester (MSc Money, Banking and Finance), PhD (University of Abuja)",
    tradeOff: "Technically impeccable and politically uncontroversial but may lack the gravitas to stare down commercial bank lobbyists.",
    competencies: {
      professional: { economics: 88, diplomacy: 55, security: 18, media: 38, legal: 45, administration: 72, technology: 68 },
      personal: { loyalty: 60, charisma: 48, leadership: 70, ambition: 58, integrity: 87, resilience: 78, intrigue: 28 },
    },
    qualifiedFor: ["governor-central-bank", "director-bureau-statistics", "director-budget-office"],
  },

  {
    name: "Chief Babatunde Olaitan Adetokunbo",
    age: 65,
    state: "Lagos",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "BA",
    traits: ["Elder Statesman", "Consensus Builder", "Politically Seasoned"],
    bio: "A founding director of Zenith Bank who went on to chair the Lagos State Economic Advisory Council for eight years. His mediation ended two banking sector crises that nearly became systemic. At 65, he carries the weight of institutional memory and the patience to use it wisely.",
    education: "University of Lagos (Banking & Finance), University of Birmingham (MSc Finance), honorary LLD (Covenant University)",
    tradeOff: "Unmatched in stabilising institutions and managing elite consensus but his age and establishment ties may slow bold reforms.",
    competencies: {
      professional: { economics: 78, diplomacy: 82, security: 28, media: 60, legal: 58, administration: 78, technology: 38 },
      personal: { loyalty: 70, charisma: 78, leadership: 82, ambition: 48, integrity: 75, resilience: 72, intrigue: 55 },
    },
    qualifiedFor: ["governor-central-bank", "director-investment-council", "director-revenue-service"],
  },

  {
    name: "Dr. Fatima Al-Hassan Sokoto",
    age: 49,
    state: "Sokoto",
    gender: "Female",
    religion: "Islam",
    ethnicity: "Fulani",
    avatar: "FS",
    traits: ["Development Economist", "Diplomatic", "Principled"],
    bio: "Served as the African Development Bank's lead economist for the Sahel region, designing social protection frameworks for four Sahelian countries. Her return to Nigeria was motivated by a clear-eyed ambition to reform the Budget Office from within. Speaks fluently in the language of both development donors and Islamic finance.",
    education: "Usmanu Danfodiyo University (Economics), University of Edinburgh (MSc Development Economics), AfDB Institute (Executive Certificate)",
    tradeOff: "Combines international credibility with northern political capital but her development-focused lens may deprioritise revenue generation.",
    competencies: {
      professional: { economics: 83, diplomacy: 75, security: 15, media: 50, legal: 45, administration: 72, technology: 55 },
      personal: { loyalty: 62, charisma: 65, leadership: 70, ambition: 65, integrity: 82, resilience: 75, intrigue: 35 },
    },
    qualifiedFor: ["director-budget-office", "director-investment-council", "director-bureau-statistics"],
  },

  {
    name: "Mr. Rufus Tamaraebi Ebiegberi",
    age: 51,
    state: "Bayelsa",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Ijaw",
    avatar: "RT",
    traits: ["Revenue Strategist", "Assertive", "Pragmatic"],
    bio: "Former Commissioner for Finance in Bayelsa State who turned around a near-insolvent treasury by restructuring contractors' liabilities without default. A sharp negotiator who once stopped an IMF-imposed conditionality clause by threatening to mobilise Niger Delta governors in opposition. His pragmatism occasionally shades into opportunism.",
    education: "Niger Delta University (Accounting), University of Benin (MBA), ICAN (Fellow)",
    tradeOff: "Creative in revenue management and politically assertive but his loyalties shift with the wind of who controls the federation account.",
    competencies: {
      professional: { economics: 75, diplomacy: 62, security: 30, media: 55, legal: 58, administration: 80, technology: 40 },
      personal: { loyalty: 65, charisma: 72, leadership: 74, ambition: 78, integrity: 58, resilience: 78, intrigue: 70 },
    },
    qualifiedFor: ["director-revenue-service", "director-budget-office", "director-investment-council"],
  },

  {
    name: "Dr. Augustine Nwachukwu-Eze",
    age: 47,
    state: "Cross River",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Efik",
    avatar: "AN",
    traits: ["FDI Specialist", "Articulate", "Relentless"],
    bio: "Built the Cross River Investment Promotion Agency into one of the top-rated in the country, attracting $2.1bn in FDI in three years. A skilled negotiator who cut four major joint-venture deals with Chinese and European partners. His critics call him a salesman; his results are undeniable.",
    education: "University of Calabar (Economics), Georgetown University (MA International Trade), CFA Charterholder",
    tradeOff: "Outstanding track record drawing investment but his aggressive deal-making has occasionally bypassed due diligence processes.",
    competencies: {
      professional: { economics: 80, diplomacy: 82, security: 18, media: 68, legal: 55, administration: 65, technology: 52 },
      personal: { loyalty: 58, charisma: 80, leadership: 72, ambition: 82, integrity: 65, resilience: 72, intrigue: 52 },
    },
    qualifiedFor: ["director-investment-council", "director-export-promotion", "director-bureau-statistics"],
  },

  // ── Health Sector ────────────────────────────────────────────────────────────

  {
    name: "Dr. Hauwa Bello-Idris",
    age: 53,
    state: "Niger",
    gender: "Female",
    religion: "Islam",
    ethnicity: "Nupe",
    avatar: "HB",
    traits: ["Public Health Champion", "Community-Rooted", "Persistent"],
    bio: "Built 47 functional primary health centres across Niger State from the ruins of neglected structures over five years as State PHC Director. Trained under WHO's AFRO office and led Nigeria's polio eradication surge in five resistant LGAs. She refuses Abuja postings without rural posting clauses for her staff.",
    education: "University of Ilorin (Medicine and Surgery), Johns Hopkins Bloomberg School (MPH), WHO-AFRO Leadership Programme",
    tradeOff: "Transformative at grassroots delivery but will resist urban-biased health spending priorities championed by political elites.",
    competencies: {
      professional: { economics: 48, diplomacy: 60, security: 22, media: 55, legal: 35, administration: 82, technology: 52 },
      personal: { loyalty: 58, charisma: 65, leadership: 80, ambition: 58, integrity: 85, resilience: 90, intrigue: 25 },
    },
    qualifiedFor: ["director-primary-healthcare", "director-disease-control"],
  },

  {
    name: "Prof. Chukwuemeka Nnadi",
    age: 60,
    state: "Abia",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "CN",
    traits: ["Epidemiologist", "Academic Authority", "Cautious"],
    bio: "Chair of the Department of Epidemiology at UNTH Enugu and lead investigator during the 2018 Lassa fever surge that threatened four states. Coordinated Nigeria's contact-tracing system during COVID-19 with minimal resources and maximum improvisation. His academic caution sometimes frustrates action-oriented ministers.",
    education: "University of Nigeria Enugu Campus (Medicine), Liverpool School of Tropical Medicine (MSc Epidemiology), London School of Hygiene and Tropical Medicine (PhD)",
    tradeOff: "Irreplaceable scientific authority in outbreak response but his academic deliberateness makes him slow to act in fast-moving crises.",
    competencies: {
      professional: { economics: 40, diplomacy: 55, security: 28, media: 50, legal: 38, administration: 68, technology: 65 },
      personal: { loyalty: 52, charisma: 55, leadership: 70, ambition: 48, integrity: 88, resilience: 72, intrigue: 28 },
    },
    qualifiedFor: ["director-disease-control", "director-primary-healthcare", "director-food-drug-safety"],
  },

  {
    name: "Dr. Salamatu Aliyu-Gwarzo",
    age: 47,
    state: "Kaduna",
    gender: "Female",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "SA",
    traits: ["Health Financing Expert", "Ambitious", "Systems Thinker"],
    bio: "Designed Kaduna State's community-based health insurance scheme that enrolled 800,000 informal workers — the largest state-level scheme in the North. Spent three years at the World Bank's Health, Nutrition and Population department before returning. Her redesigned capitation model has become a national template.",
    education: "ABU Zaria (Medicine), Harvard T.H. Chan School of Public Health (MPH Health Policy), World Bank Institute (Health Financing Certification)",
    tradeOff: "Genuinely innovative in health financing but her scheme's success has given her presidential ambitions that could distract from the position.",
    competencies: {
      professional: { economics: 72, diplomacy: 62, security: 15, media: 55, legal: 45, administration: 78, technology: 60 },
      personal: { loyalty: 55, charisma: 70, leadership: 74, ambition: 80, integrity: 72, resilience: 75, intrigue: 48 },
    },
    qualifiedFor: ["director-health-insurance", "director-primary-healthcare", "director-disease-control"],
  },

  {
    name: "Dr. Emeka Ogbuoji-Eze",
    age: 50,
    state: "Rivers",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Ogoni",
    avatar: "EG",
    traits: ["Pharma Regulator", "Uncompromising", "Detail-Oriented"],
    bio: "Spent a decade at NAFDAC battling counterfeit drug networks before rising to become the agency's zonal coordinator for the South-South. His sting operations removed 63 substandard drug brands from the market in one year. Pharmaceutical companies fear him; patients trust him implicitly.",
    education: "University of Port Harcourt (Pharmacy), University of Strathclyde (MSc Pharmaceutical Analysis), NAFDAC Regulatory Science Programme",
    tradeOff: "A world-class drug regulator who will make life difficult for politically-connected pharmaceutical importers the presidency may rely on.",
    competencies: {
      professional: { economics: 45, diplomacy: 48, security: 35, media: 52, legal: 70, administration: 80, technology: 62 },
      personal: { loyalty: 45, charisma: 55, leadership: 72, ambition: 60, integrity: 90, resilience: 82, intrigue: 32 },
    },
    qualifiedFor: ["director-food-drug-safety", "director-disease-control"],
  },

  {
    name: "Mrs. Nneka Osei-Opoku",
    age: 48,
    state: "Delta",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Urhobo",
    avatar: "NK",
    traits: ["Insurance Operator", "Pragmatic", "Relationship-Driven"],
    bio: "Spent fifteen years at the National Health Insurance Authority before founding a health management organisation that covered 200,000 private sector workers. Her negotiation with private hospital networks brought down capitation rates by 30%. She knows both sides of the insurance equation.",
    education: "Delta State University (Nursing), University of Ibadan (MBA Health Management), NHIA Regulatory Certification",
    tradeOff: "Has the operational knowledge to fix the NHIA's dysfunction but her private sector ties create potential conflicts of interest with insurers.",
    competencies: {
      professional: { economics: 65, diplomacy: 60, security: 15, media: 48, legal: 52, administration: 82, technology: 55 },
      personal: { loyalty: 65, charisma: 68, leadership: 72, ambition: 65, integrity: 70, resilience: 75, intrigue: 45 },
    },
    qualifiedFor: ["director-health-insurance", "director-primary-healthcare"],
  },

  {
    name: "Dr. Sani Dangaladima",
    age: 55,
    state: "Kebbi",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "SD",
    traits: ["Rural Health Advocate", "Quiet Reformer", "Loyal"],
    bio: "Built a sustainable immunisation cold-chain network across Kebbi and Sokoto States that became a WHO best-practice case study. Served as Federal Director of Immunisation under two presidents without ever attracting controversy. His strength is implementation — not ideation — and he knows it.",
    education: "BUK Kano (Medicine and Surgery), NIMR Nigeria (Field Epidemiology), UNICEF Health Systems Training",
    tradeOff: "Exceptionally reliable in execution and politically safe but will not drive innovative reforms without clear directives from above.",
    competencies: {
      professional: { economics: 40, diplomacy: 52, security: 25, media: 35, legal: 38, administration: 85, technology: 48 },
      personal: { loyalty: 85, charisma: 45, leadership: 68, ambition: 42, integrity: 80, resilience: 80, intrigue: 30 },
    },
    qualifiedFor: ["director-primary-healthcare", "director-disease-control"],
  },

  {
    name: "Dr. Aisha Waziri-Gusau",
    age: 43,
    state: "Zamfara",
    gender: "Female",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "AW",
    traits: ["Tropical Medicine Specialist", "Courageous", "Field-Tested"],
    bio: "Led medical teams into active conflict zones in Zamfara during bandit attacks, establishing mobile clinics that served 30,000 IDPs. Published ground-breaking research on meningitis prophylaxis in the Sahel belt with Médecins Sans Frontières. She has stared down both bandits and bureaucrats.",
    education: "University of Maiduguri (Medicine), London School of Hygiene and Tropical Medicine (MSc Infectious Diseases), Doctors Without Borders Field Training",
    tradeOff: "Heroic field credentials and rare courage but her outsider's distrust of Abuja bureaucracy may make institutional management a struggle.",
    competencies: {
      professional: { economics: 38, diplomacy: 58, security: 45, media: 60, legal: 32, administration: 65, technology: 55 },
      personal: { loyalty: 55, charisma: 72, leadership: 78, ambition: 65, integrity: 90, resilience: 95, intrigue: 22 },
    },
    qualifiedFor: ["director-disease-control", "director-primary-healthcare"],
  },

  {
    name: "Prof. Tunde Okafor-Williams",
    age: 57,
    state: "Oyo",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "TW",
    traits: ["Pharmaceutical Policy Expert", "Networked", "Judicious"],
    bio: "Chaired the National Committee on Essential Medicines for six years, redesigning the essential medicines list that 11,000 primary health centres rely on. A former senior consultant at GlaxoSmithKline Nigeria who crossed into public service out of frustration at regulatory capture. He understands pharma industry tactics from the inside.",
    education: "University of Ibadan (Pharmacy), University College London (PhD Pharmacoeconomics)",
    tradeOff: "Knows the industry's tricks and can outmanoeuvre them — but his past corporate ties will attract scrutiny from anti-corruption watchdogs.",
    competencies: {
      professional: { economics: 60, diplomacy: 62, security: 18, media: 55, legal: 65, administration: 75, technology: 60 },
      personal: { loyalty: 60, charisma: 65, leadership: 72, ambition: 60, integrity: 75, resilience: 72, intrigue: 50 },
    },
    qualifiedFor: ["director-food-drug-safety", "director-health-insurance"],
  },

  {
    name: "Dr. Ngozi Udeozo-Aham",
    age: 45,
    state: "Enugu",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "NU",
    traits: ["Health Systems Researcher", "Progressive", "Vocal"],
    bio: "Spent five years at the Africa Centre for Disease Control developing pan-African surveillance protocols before returning to teach at UNTH. Her peer-reviewed papers on Nigeria's disease burden have been cited in three WHO global health reports. She is openly critical of the underfunding of NCDC.",
    education: "University of Nigeria Enugu Campus (Medicine), Tulane University (PhD Global Health Systems)",
    tradeOff: "Intellectually formidable and internationally respected but her willingness to publicly criticise government health spending is a liability.",
    competencies: {
      professional: { economics: 52, diplomacy: 60, security: 20, media: 65, legal: 40, administration: 70, technology: 68 },
      personal: { loyalty: 42, charisma: 68, leadership: 68, ambition: 70, integrity: 85, resilience: 72, intrigue: 35 },
    },
    qualifiedFor: ["director-disease-control", "director-primary-healthcare", "director-health-insurance"],
  },

  {
    name: "Mr. Abdullahi Tukur Misau",
    age: 52,
    state: "Borno",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Kanuri",
    avatar: "AT",
    traits: ["Crisis Manager", "Stoic", "Institution Builder"],
    bio: "Oversaw health infrastructure reconstruction in Borno State after Boko Haram's destruction of 36 hospitals — rebuilding 28 functional facilities in two years on a shoestring budget. Coordinated the state's COVID-19 response while managing active insurgency. Unflappable under conditions that break lesser administrators.",
    education: "University of Maiduguri (Public Health Administration), World Health Organization (Health Emergency Management Certification)",
    tradeOff: "A proven crisis administrator of extraordinary resilience but his operational strengths do not extend to policy innovation or financial management.",
    competencies: {
      professional: { economics: 42, diplomacy: 55, security: 50, media: 45, legal: 35, administration: 88, technology: 45 },
      personal: { loyalty: 75, charisma: 52, leadership: 82, ambition: 52, integrity: 82, resilience: 95, intrigue: 35 },
    },
    qualifiedFor: ["director-primary-healthcare", "director-disease-control"],
  },

  {
    name: "Dr. Blessing Akpan-Obot",
    age: 46,
    state: "Akwa Ibom",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Ibibio",
    avatar: "BK",
    traits: ["Drug Safety Enforcer", "Tenacious", "Principled"],
    bio: "Made international headlines when she shut down a Chinese-owned pharmaceutical warehouse in Apapa storing 42 tonnes of expired drugs destined for Nigerian hospitals. A former NAFDAC deputy director who turned down three lucrative private sector offers. Her prosecution record is the best in the agency's history.",
    education: "University of Calabar (Pharmacy), Northeastern University Boston (MS Pharmaceutical Regulatory Affairs), NAFDAC Advanced Regulatory Programme",
    tradeOff: "Exceptional integrity and enforcement track record but will create diplomatic headaches by targeting politically-connected pharmaceutical operators.",
    competencies: {
      professional: { economics: 42, diplomacy: 45, security: 38, media: 60, legal: 72, administration: 78, technology: 62 },
      personal: { loyalty: 48, charisma: 60, leadership: 74, ambition: 62, integrity: 93, resilience: 85, intrigue: 28 },
    },
    qualifiedFor: ["director-food-drug-safety", "director-disease-control"],
  },

  {
    name: "Prof. Ibrahim Adamu-Lafia",
    age: 59,
    state: "Nasarawa",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Tiv",
    avatar: "IL",
    traits: ["Health Insurance Architect", "Academic", "Persistent"],
    bio: "Designed the first successful micro-health insurance scheme in a middle-belt state, covering 120,000 farmers in Nasarawa. His textbook on Nigerian health financing is the standard reference at six medical schools. A consummate committee man who builds coalitions slowly but solidly.",
    education: "University of Jos (Medicine and Surgery), University of Ibadan (MPH Health Economics), London Business School (Healthcare Finance Executive Programme)",
    tradeOff: "Thorough and credible in health financing design but his academic pace makes him unsuited to fast-turnaround political environments.",
    competencies: {
      professional: { economics: 68, diplomacy: 55, security: 18, media: 42, legal: 48, administration: 75, technology: 52 },
      personal: { loyalty: 62, charisma: 50, leadership: 68, ambition: 55, integrity: 82, resilience: 72, intrigue: 35 },
    },
    qualifiedFor: ["director-health-insurance", "director-primary-healthcare"],
  },

  // ── Education Sector ─────────────────────────────────────────────────────────

  {
    name: "Prof. Abubakar Rimi-Shehu",
    age: 62,
    state: "Kano",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "AR",
    traits: ["Almajiri Reformer", "Principled Iconoclast", "Northern Champion"],
    bio: "Nigeria's most outspoken advocate for integrating Quranic education into the formal curriculum, he piloted a model Tsangaya-Basic school hybrid in Kano that enrolled 12,000 previously out-of-school boys. Fought bitter battles with both traditionalist ulama and secular education bureaucrats — and won both. His ambition is to end the cycle of almajiri children on Kano streets within a generation.",
    education: "Bayero University Kano (Islamic Studies and Education), University of Birmingham (MEd Comparative Education), ABU Zaria (PhD Education Policy)",
    tradeOff: "Could transform Northern basic education but his polarising reform agenda will provoke fierce resistance from ulama networks and traditionalist political patrons.",
    competencies: {
      professional: { economics: 45, diplomacy: 58, security: 28, media: 62, legal: 42, administration: 75, technology: 40 },
      personal: { loyalty: 55, charisma: 72, leadership: 80, ambition: 75, integrity: 80, resilience: 85, intrigue: 42 },
    },
    qualifiedFor: ["director-basic-education", "director-higher-education"],
  },

  {
    name: "Dr. Bisi Adeyemi-Lawson",
    age: 49,
    state: "Osun",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "BL",
    traits: ["Education Technocrat", "Data-Led", "Reform-Minded"],
    bio: "Led the redesign of the Universal Basic Education Commission's disbursement system, ending the era of states receiving grants without accountability. Her state-by-state learning outcomes study exposed the deception behind official school enrolment figures and forced a national policy reckoning. She has no time for sentimentality in education statistics.",
    education: "Obafemi Awolowo University (Education Administration), University of Sussex (MA Education & International Development), UNICEF Nigeria Education Programme",
    tradeOff: "Will radically improve transparency and outcomes measurement but her readiness to shame underperforming states will create political enemies.",
    competencies: {
      professional: { economics: 60, diplomacy: 55, security: 15, media: 62, legal: 42, administration: 82, technology: 65 },
      personal: { loyalty: 52, charisma: 65, leadership: 74, ambition: 70, integrity: 85, resilience: 78, intrigue: 35 },
    },
    qualifiedFor: ["director-basic-education", "director-education-fund", "director-higher-education"],
  },

  {
    name: "Prof. Danladi Wakili",
    age: 58,
    state: "Plateau",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Berom",
    avatar: "DW",
    traits: ["University Administrator", "Consensus Seeker", "Establishment"],
    bio: "Vice-Chancellor of the University of Jos for two terms — surviving two student crises, an ASUU strike, and a failed assassination attempt without missing a senate meeting. His patience with academic bureaucracy is near-infinite. Critics say he has made stability his god at the expense of excellence.",
    education: "University of Jos (Physics), University of Reading (MSc Physics Education), University of Leeds (PhD Higher Education Policy)",
    tradeOff: "Brings stability and management experience to a chronically unstable universities system but will avoid the confrontational reforms the sector actually needs.",
    competencies: {
      professional: { economics: 52, diplomacy: 70, security: 30, media: 52, legal: 48, administration: 82, technology: 55 },
      personal: { loyalty: 72, charisma: 58, leadership: 75, ambition: 52, integrity: 75, resilience: 85, intrigue: 48 },
    },
    qualifiedFor: ["director-higher-education", "director-basic-education", "director-education-fund"],
  },

  {
    name: "Mrs. Hauwa Dikko-Atiku",
    age: 46,
    state: "Jigawa",
    gender: "Female",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "HD",
    traits: ["Girls' Education Crusader", "Community Mobiliser", "Diplomatic"],
    bio: "Enrolled 80,000 out-of-school girls across Jigawa's most conservative communities through a combination of door-to-door persuasion and cash transfer incentives. Her programme became the blueprint for UNICEF's Nigeria Safe Schools Initiative. She speaks Hausa, Fulfulde, and Kanuri — and uses all three in the field.",
    education: "Bayero University Kano (Social Work), George Washington University (MPA International Development), Ashoka Fellow",
    tradeOff: "Transformative in girls' basic education but lacks the institutional management experience to run a federal agency with 4,000 staff.",
    competencies: {
      professional: { economics: 50, diplomacy: 72, security: 18, media: 65, legal: 35, administration: 70, technology: 48 },
      personal: { loyalty: 65, charisma: 80, leadership: 78, ambition: 65, integrity: 85, resilience: 82, intrigue: 30 },
    },
    qualifiedFor: ["director-basic-education"],
  },

  {
    name: "Prof. Chinwe Ezenwachi",
    age: 55,
    state: "Imo",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "CE",
    traits: ["Academic Rigour", "TETFUND Expert", "Principled"],
    bio: "Spent fifteen years managing TETFund research grants as the University of Nigeria's grants director, recovering ₦2.4 billion in misappropriated interventions. A professor of Educational Psychology who understands university funding from both the academic and administrative sides. Her audit reports are models of forensic clarity.",
    education: "University of Nigeria Nsukka (Education Psychology), University of Michigan (PhD Higher Education Administration)",
    tradeOff: "Unimpeachable on financial accountability in education funding but her academic seniority makes her dismissive of technical and vocational education as a parallel track.",
    competencies: {
      professional: { economics: 68, diplomacy: 52, security: 12, media: 48, legal: 60, administration: 80, technology: 50 },
      personal: { loyalty: 58, charisma: 52, leadership: 72, ambition: 62, integrity: 88, resilience: 75, intrigue: 32 },
    },
    qualifiedFor: ["director-education-fund", "director-higher-education"],
  },

  {
    name: "Engr. Mfon Udofia-Bassey",
    age: 47,
    state: "Cross River",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Efik",
    avatar: "MU",
    traits: ["TVET Pioneer", "Industry-Connected", "Practical"],
    bio: "Built the first ISO-certified technical college in Cross River State by partnering with Dangote Group and Siemens Nigeria. Her apprenticeship-to-employment pipeline placed 3,000 graduates in industrial jobs within two years. A former mechanical engineer who retrained in education management after seeing graduates unable to operate basic machinery.",
    education: "University of Nigeria (Mechanical Engineering), Coventry University (MSc Technical and Vocational Education), German-Nigerian TVET Institute",
    tradeOff: "Could modernise TVET through strong industry partnerships but her private sector bias may erode the public access mission of technical schools.",
    competencies: {
      professional: { economics: 58, diplomacy: 60, security: 15, media: 52, legal: 38, administration: 72, technology: 82 },
      personal: { loyalty: 58, charisma: 65, leadership: 74, ambition: 68, integrity: 75, resilience: 78, intrigue: 38 },
    },
    qualifiedFor: ["director-technical-education", "director-basic-education"],
  },

  {
    name: "Alhaji Abdulkadir Nafiu-Dutse",
    age: 60,
    state: "Kano",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "AF",
    traits: ["Political Loyalist", "Education Administrator", "Well-Connected"],
    bio: "Served as Commissioner for Education in Kano State under two governors and rebuilt 600 dilapidated school buildings through UBEC matching grants. His political connections extend across the NW establishment. He is not an education theorist — he is an education contractor in the best sense of the word.",
    education: "ABU Zaria (Public Administration), Kano State Polytechnic (Higher National Diploma, Management)",
    tradeOff: "Superb at mobilising political will and funding for school infrastructure but weak on curriculum reform and learning outcomes.",
    competencies: {
      professional: { economics: 52, diplomacy: 60, security: 28, media: 52, legal: 40, administration: 80, technology: 38 },
      personal: { loyalty: 85, charisma: 65, leadership: 70, ambition: 62, integrity: 62, resilience: 75, intrigue: 58 },
    },
    qualifiedFor: ["director-basic-education", "director-education-fund"],
  },

  {
    name: "Dr. Seun Akinyemi",
    age: 44,
    state: "Ondo",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "SK",
    traits: ["EdTech Evangelist", "Disruptive", "Media-Savvy"],
    bio: "Founded EduBridge Nigeria, deploying tablet-based learning to 400 rural schools before selling the company to a South African ed-tech firm. Spent three years at UNESCO's Education Sector division in Paris before returning with a mandate to disrupt Nigeria's educational establishment. He makes traditional education administrators uncomfortable — deliberately.",
    education: "University of Ife (Computer Science), Teachers College Columbia University (EdD Education Technology)",
    tradeOff: "Can leapfrog Nigeria's education system with technology but his disruptive style will alienate the ASUU and teacher union establishments whose cooperation is essential.",
    competencies: {
      professional: { economics: 55, diplomacy: 55, security: 12, media: 80, legal: 38, administration: 62, technology: 90 },
      personal: { loyalty: 48, charisma: 82, leadership: 70, ambition: 82, integrity: 72, resilience: 68, intrigue: 45 },
    },
    qualifiedFor: ["director-technical-education", "director-higher-education"],
  },

  {
    name: "Mrs. Zainab Lawal-Yusuf",
    age: 51,
    state: "Niger",
    gender: "Female",
    religion: "Islam",
    ethnicity: "Nupe",
    avatar: "ZL",
    traits: ["Fund Steward", "Audit-Minded", "Steady"],
    bio: "Spent fourteen years inside the Universal Basic Education Commission's finance department, surviving three politically-motivated purges by making herself indispensable through sheer institutional knowledge. Her internal audit framework is the only reason the Commission still passes external reviews. She knows where every naira has gone — and where it went missing.",
    education: "Federal University of Technology Minna (Accounting), ICAN (Fellow), ACA (England and Wales)",
    tradeOff: "Exceptional stewardship of education funds but her defensive insider mentality makes her resistant to the structural reforms the fund desperately needs.",
    competencies: {
      professional: { economics: 68, diplomacy: 48, security: 18, media: 35, legal: 58, administration: 82, technology: 50 },
      personal: { loyalty: 72, charisma: 42, leadership: 65, ambition: 50, integrity: 85, resilience: 80, intrigue: 45 },
    },
    qualifiedFor: ["director-education-fund", "director-basic-education"],
  },

  {
    name: "Prof. Ejike Onyeka-Mbah",
    age: 58,
    state: "Anambra",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "EM",
    traits: ["University Reformer", "Contrarian", "Scholarly"],
    bio: "Led the accreditation reform at the National Universities Commission that stripped recognition from 19 degree mills in one exercise, prompting death threats from five university proprietors. A professor of Educational Administration at UNIZIK who writes sharp op-eds on what ails Nigerian higher education. Has earned enemies in proportion to his impact.",
    education: "University of Nigeria Nsukka (Education), University of Edinburgh (MSc Higher Education), Boston University (PhD Education Administration)",
    tradeOff: "His reform record is outstanding but his enjoyment of controversy means he will generate political noise that distracts from governance.",
    competencies: {
      professional: { economics: 55, diplomacy: 48, security: 15, media: 70, legal: 55, administration: 78, technology: 52 },
      personal: { loyalty: 45, charisma: 68, leadership: 74, ambition: 68, integrity: 85, resilience: 78, intrigue: 42 },
    },
    qualifiedFor: ["director-higher-education", "director-education-fund"],
  },

  {
    name: "Mallam Sule Tanko-Katagum",
    age: 53,
    state: "Borno",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Kanuri",
    avatar: "ST",
    traits: ["Reconstruction Educator", "Survivor", "Tenacious"],
    bio: "Rebuilt Borno State's education system from the ruins of Boko Haram's targeted school burnings — reopening 140 primary schools between 2017 and 2022. His trauma-informed teaching curriculum, developed with UNICEF, has been adapted for conflict-affected zones in three other African countries. He has negotiated with chieftains who sheltered insurgents to get schools reopened.",
    education: "University of Maiduguri (Education), University of Amsterdam (MEd Conflict and Education), Harvard (Humanitarian Leadership Certificate)",
    tradeOff: "Brings extraordinary moral authority and conflict-education expertise but lacks the technical skills to run a large federal education bureaucracy.",
    competencies: {
      professional: { economics: 40, diplomacy: 65, security: 52, media: 60, legal: 35, administration: 72, technology: 42 },
      personal: { loyalty: 68, charisma: 72, leadership: 82, ambition: 55, integrity: 88, resilience: 95, intrigue: 30 },
    },
    qualifiedFor: ["director-basic-education"],
  },

  {
    name: "Dr. Yemisi Adeyeye-Ogunlana",
    age: 50,
    state: "Kwara",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "YA",
    traits: ["Skills-Economy Strategist", "Persistent", "Results-Oriented"],
    bio: "Chaired the Nigerian Vocational Education Council's curriculum committee that introduced mechatronics and solar installation as TVET pathways — the first new vocational tracks in 20 years. Her industry-linkage model placed 78% of graduating TVET students directly into employment. She has little patience for theoretical debates about education.",
    education: "University of Ilorin (Vocational Education), University of Nottingham (MSc Technical Education Management), CITY & GUILDS International",
    tradeOff: "Transformative on outcomes and industry linkage but her impatience with procedure has led to process shortcuts that civil service auditors flag.",
    competencies: {
      professional: { economics: 58, diplomacy: 55, security: 15, media: 52, legal: 40, administration: 75, technology: 78 },
      personal: { loyalty: 60, charisma: 65, leadership: 76, ambition: 70, integrity: 75, resilience: 80, intrigue: 38 },
    },
    qualifiedFor: ["director-technical-education", "director-education-fund"],
  },

  // ── Agriculture Sector ───────────────────────────────────────────────────────

  {
    name: "Dr. Aliyu Wamakko-Rimi",
    age: 55,
    state: "Sokoto",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Fulani",
    avatar: "AK",
    traits: ["Agronomist", "Sahel Expert", "Patient Reformer"],
    bio: "Spent a decade with ICRISAT developing drought-tolerant cowpea and millet varieties suited to Sahel conditions that are now planted by 800,000 smallholders across six states. His seed variety catalogue is the practical foundation of NASC's certified seed programme. Approaches agricultural reform the way a farmer approaches soil — slowly and with respect for the land.",
    education: "Usmanu Danfodiyo University (Agronomy), ICRISAT India (MSc Plant Breeding), Wageningen University Netherlands (PhD Crop Science)",
    tradeOff: "Scientifically formidable but resistant to commercialising research breakthroughs — prefers smallholders over agribusinesses and this limits yield at scale.",
    competencies: {
      professional: { economics: 50, diplomacy: 55, security: 22, media: 42, legal: 35, administration: 68, technology: 80 },
      personal: { loyalty: 58, charisma: 50, leadership: 70, ambition: 52, integrity: 85, resilience: 80, intrigue: 28 },
    },
    qualifiedFor: ["director-crop-research", "director-land-development"],
  },

  {
    name: "Mrs. Grace Nwachukwu-Okonkwo",
    age: 50,
    state: "Anambra",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "GN",
    traits: ["Food Systems Specialist", "Organised", "Sharp"],
    bio: "Ran the South-East Regional Silos complex for eight years, cutting post-harvest losses from 42% to 11% through upgraded fumigation protocols and digitised inventory management. Her regional food reserve model attracted a $120m World Bank investment for nationwide scaling. She runs a tight operation and despises waste.",
    education: "Nnamdi Azikiwe University (Food Science and Technology), Michigan State University (MSc Food Systems), FAO Post-Harvest Management Diploma",
    tradeOff: "Outstanding on operational efficiency in food storage but has limited political dexterity for managing farmer unions and state governments' competing demands.",
    competencies: {
      professional: { economics: 60, diplomacy: 50, security: 22, media: 45, legal: 38, administration: 85, technology: 68 },
      personal: { loyalty: 60, charisma: 55, leadership: 75, ambition: 65, integrity: 82, resilience: 80, intrigue: 32 },
    },
    qualifiedFor: ["director-food-storage", "director-crop-research"],
  },

  {
    name: "Mr. Dogo Yakowa",
    age: 53,
    state: "Kaduna",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Kagoro",
    avatar: "DY",
    traits: ["Land Administrator", "Political", "Conflict-Sensitive"],
    bio: "Mediated the first successful land-use boundary agreement between Fulani herders and Hausa farmers in three Kaduna LGAs — a feat regarded as near-impossible. His grasp of the Land Use Act's political geography is unmatched. Has survived two governorship changes in Kaduna without losing institutional footing.",
    education: "ABU Zaria (Geography), Kaduna State University (LLB Land Law), NIM (Postgraduate Diploma, Land Administration)",
    tradeOff: "Exceptional at navigating the politics of land conflict but his pragmatic deal-making occasionally sacrifices formal legal processes for speed.",
    competencies: {
      professional: { economics: 48, diplomacy: 75, security: 42, media: 52, legal: 70, administration: 78, technology: 38 },
      personal: { loyalty: 68, charisma: 68, leadership: 78, ambition: 60, integrity: 72, resilience: 85, intrigue: 55 },
    },
    qualifiedFor: ["director-land-development", "director-food-storage"],
  },

  {
    name: "Dr. Hauwa Saleh-Gwadabawa",
    age: 44,
    state: "Kebbi",
    gender: "Female",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "HS",
    traits: ["Rice Economy Champion", "Determined", "Technically Acute"],
    bio: "Her variety-testing programme for Sahel rice varieties increased average yields per hectare from 1.8 to 4.2 tonnes in pilot communities across Kebbi, Kano, and Sokoto. A protégé of the AfDB's Feed Africa team, she returned to the National Cereals Research Institute as Deputy Director at 38. Quiet in meetings but devastating in technical reviews.",
    education: "Usmanu Danfodiyo University (Agriculture), Kyushu University Japan (MSc Crop Science), Africa Rice Centre (PhD Rice Agronomy)",
    tradeOff: "Her crop research expertise is world-class but her narrow specialisation in cereals makes her unsuited to the breadth of crop research mandate.",
    competencies: {
      professional: { economics: 48, diplomacy: 52, security: 18, media: 38, legal: 30, administration: 65, technology: 85 },
      personal: { loyalty: 60, charisma: 48, leadership: 68, ambition: 62, integrity: 85, resilience: 78, intrigue: 28 },
    },
    qualifiedFor: ["director-crop-research"],
  },

  {
    name: "Engr. Okey Nwosu-Agu",
    age: 56,
    state: "Ebonyi",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "ON",
    traits: ["Agricultural Engineer", "Systemic Thinker", "Steady"],
    bio: "Designed the irrigation and storage infrastructure for the Lower Anambra Development Authority, enabling year-round farming for 40,000 families. His drainage networks in Ebonyi reduced flood losses by 60% over six years. A quiet man who produces extraordinary infrastructure on minimal budgets.",
    education: "University of Nigeria (Agricultural Engineering), University of Wageningen (MSc Water Resources and Environmental Management)",
    tradeOff: "Technically brilliant on agricultural infrastructure but his engineering background leaves him ill-equipped for the social and political dimensions of land tenure reform.",
    competencies: {
      professional: { economics: 45, diplomacy: 48, security: 20, media: 35, legal: 38, administration: 72, technology: 85 },
      personal: { loyalty: 65, charisma: 45, leadership: 68, ambition: 50, integrity: 82, resilience: 78, intrigue: 28 },
    },
    qualifiedFor: ["director-land-development", "director-food-storage"],
  },

  {
    name: "Mrs. Folake Adejumo-Oni",
    age: 49,
    state: "Ekiti",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "FA",
    traits: ["Food Security Strategist", "Communicator", "Pragmatic"],
    bio: "Led FAO Nigeria's emergency food response to the 2021 floods that displaced 1.3 million people, coordinating distribution of 120,000 metric tonnes of relief grains. Her household food security mapping tool has been adopted by twelve African governments. She can manage chaos with a spreadsheet and a satellite phone.",
    education: "University of Agriculture Abeokuta (Agricultural Economics), University of Reading (MSc Food Policy), FAO Emergency Management Programme",
    tradeOff: "Outstanding in crisis food logistics but more effective in emergency mode than in the slow institutional grind of daily storage management.",
    competencies: {
      professional: { economics: 65, diplomacy: 65, security: 30, media: 62, legal: 38, administration: 80, technology: 60 },
      personal: { loyalty: 62, charisma: 72, leadership: 78, ambition: 65, integrity: 80, resilience: 88, intrigue: 35 },
    },
    qualifiedFor: ["director-food-storage", "director-land-development"],
  },

  {
    name: "Dr. James Luka-Mancha",
    age: 52,
    state: "Plateau",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Berom",
    avatar: "JL",
    traits: ["Cassava Breeder", "Research-Focused", "Independent"],
    bio: "Developed three commercially-released cassava varieties at IITA that are now grown on 2.2 million hectares across Sub-Saharan Africa, including Nigeria's dominant agric belt. His royalty reinvestment model for research funding has made the institute financially sustainable. A scientist first, administrator second — and he knows it.",
    education: "University of Jos (Botany), IITA Nigeria (MSc Plant Breeding), Cornell University (PhD Plant Genetics)",
    tradeOff: "Scientific achievements that will outlast his career but his preference for the lab over the boardroom makes institutional leadership a secondary concern.",
    competencies: {
      professional: { economics: 42, diplomacy: 50, security: 15, media: 42, legal: 32, administration: 60, technology: 88 },
      personal: { loyalty: 52, charisma: 48, leadership: 62, ambition: 52, integrity: 88, resilience: 72, intrigue: 22 },
    },
    qualifiedFor: ["director-crop-research"],
  },

  {
    name: "Mr. Babagana Kyari-Musa",
    age: 57,
    state: "Borno",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Kanuri",
    avatar: "BM",
    traits: ["Land Tenure Expert", "Pragmatic", "NE Representative"],
    bio: "Served as Director of Land Administration in Borno State for twelve years, managing land titling in territories liberated from Boko Haram — an exercise requiring extraordinary diplomatic sensitivity with traditional rulers. His database of 280,000 digitised land certificates in the Lake Chad basin is a model for conflict-sensitive land administration.",
    education: "University of Maiduguri (Geography), RECTAS Nigeria (MSc Land Administration), UN-Habitat Urban Land Training",
    tradeOff: "Unmatched experience in conflict-affected land administration but lacks the agronomic background to integrate farming and land development effectively.",
    competencies: {
      professional: { economics: 45, diplomacy: 70, security: 45, media: 48, legal: 65, administration: 80, technology: 55 },
      personal: { loyalty: 72, charisma: 55, leadership: 72, ambition: 55, integrity: 78, resilience: 85, intrigue: 42 },
    },
    qualifiedFor: ["director-land-development"],
  },

  {
    name: "Mrs. Amaka Okonkwo-Anikwe",
    age: 47,
    state: "Enugu",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "AO",
    traits: ["Agro-Policy Analyst", "Networked", "Articulate"],
    bio: "Former Nigerian representative to the Comprehensive Africa Agriculture Development Programme Steering Committee who shaped Nigeria's CAADP National Agriculture Investment Plan. Her policy papers are read in the AU and ECOWAS. She translates complex agricultural science into language that moves ministers.",
    education: "Michael Okpara University of Agriculture (Agricultural Economics), University of Ghana (MSc Agricultural Policy), IFPRI Washington (Research Fellowship)",
    tradeOff: "Exceptional at policy architecture and international agricultural diplomacy but thin on field experience to validate what looks good on paper.",
    competencies: {
      professional: { economics: 72, diplomacy: 75, security: 18, media: 65, legal: 42, administration: 68, technology: 55 },
      personal: { loyalty: 58, charisma: 72, leadership: 68, ambition: 72, integrity: 75, resilience: 70, intrigue: 45 },
    },
    qualifiedFor: ["director-food-storage", "director-crop-research", "director-land-development"],
  },

  // ── Works & Housing Sector ───────────────────────────────────────────────────

  {
    name: "Engr. Chidi Mbah-Okafor",
    age: 57,
    state: "Rivers",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Ikwerre",
    avatar: "CM",
    traits: ["Infrastructure Veteran", "Contract-Savvy", "Decisive"],
    bio: "Supervised the construction of three major federal road arteries worth over ₦200 billion as a FERMA director, completing two ahead of schedule and within budget — a near-mythological achievement in federal road management. His knowledge of contractor networks and material supply chains is encyclopaedic. Critics note his project record and question whether the procurement methods hold up to scrutiny.",
    education: "University of Port Harcourt (Civil Engineering), University of Southampton (MSc Transportation Engineering), COREN Fellow",
    tradeOff: "Gets infrastructure built when others stall but his procurement methods invite contractor kickback accusations that could trigger anti-corruption scrutiny.",
    competencies: {
      professional: { economics: 55, diplomacy: 52, security: 28, media: 48, legal: 45, administration: 82, technology: 75 },
      personal: { loyalty: 70, charisma: 60, leadership: 80, ambition: 65, integrity: 58, resilience: 82, intrigue: 58 },
    },
    qualifiedFor: ["director-public-works", "director-housing-authority"],
  },

  {
    name: "Engr. Fatima Bashir-Yusuf",
    age: 46,
    state: "Sokoto",
    gender: "Female",
    religion: "Islam",
    ethnicity: "Fulani",
    avatar: "FB",
    traits: ["Structural Engineer", "Principled", "Determined"],
    bio: "First female Chief Engineer in Sokoto State's Works Ministry, where she redesigned the state's building code to reflect local climate conditions — reducing public building collapses by 40%. Completed a World Bank-funded rural roads project under budget by renegotiating contractor terms she inherited from her predecessor.",
    education: "ABU Zaria (Civil and Structural Engineering), University of Bath (MSc Structural Engineering), COREN (Fellow)",
    tradeOff: "Strong technical integrity and rare ability to hold contractors accountable but will struggle with the political patronage expectations around federal road contracts.",
    competencies: {
      professional: { economics: 48, diplomacy: 52, security: 20, media: 42, legal: 45, administration: 78, technology: 82 },
      personal: { loyalty: 58, charisma: 55, leadership: 74, ambition: 65, integrity: 88, resilience: 80, intrigue: 30 },
    },
    qualifiedFor: ["director-public-works", "director-housing-authority"],
  },

  {
    name: "Arc. Deji Adesanya-Folarin",
    age: 54,
    state: "Ogun",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "DF",
    traits: ["Urban Planner", "Visionary", "Cosmopolitan"],
    bio: "Designed the Abeokuta Urban Renewal Master Plan that restructured informal settlements without mass evictions — still used as a model by UN-Habitat. Led the Federal Housing Authority's Abuja satellite town programme before leaving in frustration over contractor interference. His designs win awards; his battles with procurement officers are legendary.",
    education: "University of Lagos (Architecture), UCL Bartlett School (MSc Urban Planning and Development), RIBA (Chartered)",
    tradeOff: "Visionary urban design credentials but his uncompromising standards for quality have left previous infrastructure programmes gridlocked in disputes.",
    competencies: {
      professional: { economics: 52, diplomacy: 58, security: 15, media: 60, legal: 48, administration: 72, technology: 78 },
      personal: { loyalty: 52, charisma: 65, leadership: 72, ambition: 70, integrity: 80, resilience: 72, intrigue: 42 },
    },
    qualifiedFor: ["director-housing-authority", "director-public-works"],
  },

  {
    name: "Mrs. Ngozi Eke-Anyanwu",
    age: 51,
    state: "Abia",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "NE",
    traits: ["Housing Finance Expert", "Businesslike", "Persistent"],
    bio: "Structured the first mortgage-backed securities issuance in West Africa at the Federal Mortgage Bank, unlocking ₦80 billion for affordable housing. Her community land trust model in Aba successfully housed 4,000 low-income families without government subsidy. She speaks developers' and tenants' languages equally well.",
    education: "University of Benin (Estate Management), University of Cambridge (MBA Finance), RICS (Chartered)",
    tradeOff: "Excellent in housing finance innovation but her market-driven instincts may deprioritise housing for the very poor in favour of commercially viable middle-class schemes.",
    competencies: {
      professional: { economics: 72, diplomacy: 58, security: 15, media: 52, legal: 60, administration: 78, technology: 58 },
      personal: { loyalty: 60, charisma: 62, leadership: 72, ambition: 72, integrity: 75, resilience: 78, intrigue: 45 },
    },
    qualifiedFor: ["director-housing-authority"],
  },

  {
    name: "Engr. Musa Garba-Toro",
    age: 59,
    state: "Taraba",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Jukun",
    avatar: "MG",
    traits: ["Bridge Builder", "Practical", "Patient"],
    bio: "Completed the Taraba River Bridge project that reconnected 200,000 residents to markets and health facilities after a three-year construction stall — without additional federal funding, through contractor renegotiation. A former federal roads engineer who has seen every variety of contractor fraud. Methodical to the point of frustration for those in a hurry.",
    education: "Federal University of Technology Yola (Civil Engineering), University of Leeds (MSc Highway Engineering), COREN (Fellow)",
    tradeOff: "Deeply experienced on highway and bridge infrastructure but struggles with the political management of governors who want roads in their backyards.",
    competencies: {
      professional: { economics: 45, diplomacy: 55, security: 25, media: 38, legal: 42, administration: 80, technology: 78 },
      personal: { loyalty: 68, charisma: 48, leadership: 72, ambition: 48, integrity: 80, resilience: 82, intrigue: 35 },
    },
    qualifiedFor: ["director-public-works"],
  },

  {
    name: "Arc. Ihuoma Nweke-Alozie",
    age: 47,
    state: "Imo",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "IN",
    traits: ["Housing Policy Innovator", "Outspoken", "Strategic"],
    bio: "Published a scathing assessment of the National Housing Fund's disbursement failures that led to the 2023 reform of its contribution structure. Her Lagos Island waterfront housing regeneration project housed 8,000 residents while generating commercial returns that made the project self-financing. She argues loudly for rental housing over homeownership as Nigeria's primary housing solution.",
    education: "University of Nigeria Enugu Campus (Architecture), London School of Economics (MSc Real Estate Economics), ARCON (Fellow)",
    tradeOff: "Her housing policy analysis is the sharpest in the field but her tendency to publicise failures will complicate relationships with political patrons.",
    competencies: {
      professional: { economics: 68, diplomacy: 55, security: 15, media: 70, legal: 55, administration: 72, technology: 72 },
      personal: { loyalty: 45, charisma: 72, leadership: 70, ambition: 75, integrity: 82, resilience: 75, intrigue: 42 },
    },
    qualifiedFor: ["director-housing-authority", "director-public-works"],
  },

  // ── Petroleum & Power Sector ─────────────────────────────────────────────────

  {
    name: "Engr. Bayo Oduola-Fashola",
    age: 58,
    state: "Lagos",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "BF",
    traits: ["Petroleum Engineer", "Commercially Sharp", "Politically Wired"],
    bio: "Spent twenty years at Shell Nigeria before serving as Executive Vice President at the NNPC's upstream division, overseeing the country's largest deepwater lease portfolio. Negotiated three production-sharing contracts that added 400,000 barrels per day to Nigeria's capacity. His industry connections run deep — and so does his understanding of where the money goes.",
    education: "University of Ife (Chemical Engineering), Heriot-Watt University Edinburgh (MSc Petroleum Engineering), Harvard Business School (AMP)",
    tradeOff: "Unmatched upstream expertise and industry relationships but his Shell background means oil majors will be comfortable with him — perhaps too comfortable.",
    competencies: {
      professional: { economics: 78, diplomacy: 68, security: 28, media: 55, legal: 60, administration: 75, technology: 82 },
      personal: { loyalty: 62, charisma: 70, leadership: 80, ambition: 75, integrity: 65, resilience: 78, intrigue: 60 },
    },
    qualifiedFor: ["director-petroleum-corporation", "director-electricity-regulation"],
  },

  {
    name: "Dr. Zainab Sani-Dankama",
    age: 47,
    state: "Katsina",
    gender: "Female",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "ZS",
    traits: ["Energy Economist", "Reform-Minded", "Internationally Networked"],
    bio: "Led the International Energy Agency's Nigeria desk for four years, producing the authoritative analysis of Nigerian subsidy reform options that three presidents have commissioned but ignored. Her return to Nigeria was driven by the Petroleum Industry Act's passage — she sees it as a once-in-a-generation opportunity to rebuild. Known for being the only analyst who has correctly predicted Nigerian crude production figures three years running.",
    education: "ABU Zaria (Economics), Sciences Po Paris (MPA Energy and Climate), IEA Paris (Research Fellow), PhD (University of Oxford, Energy Economics)",
    tradeOff: "The most credible reformer for the petroleum sector but her IEA background gives her global credibility at the expense of domestic political networks.",
    competencies: {
      professional: { economics: 88, diplomacy: 75, security: 22, media: 65, legal: 52, administration: 68, technology: 70 },
      personal: { loyalty: 48, charisma: 68, leadership: 74, ambition: 75, integrity: 85, resilience: 78, intrigue: 38 },
    },
    qualifiedFor: ["director-petroleum-corporation", "director-electricity-regulation", "director-investment-council"],
  },

  {
    name: "Engr. Chukwudi Okonkwo-Agbu",
    age: 55,
    state: "Delta",
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Urhobo",
    avatar: "CO",
    traits: ["Power Sector Veteran", "Bureaucratic Survivor", "Institutional"],
    bio: "Survived the PHCN unbundling, the DisCo privatisation, and three regulatory overhauls at NERC — always emerging in a senior role. His encyclopaedic knowledge of Nigeria's electricity sector contractual architecture means no minister can outmanoeuvre him on technical grounds. Critics call him a creature of the power sector establishment.",
    education: "University of Benin (Electrical Engineering), University of Calgary (MSc Power Systems), NERC Regulatory Programme",
    tradeOff: "Irreplaceable institutional memory on electricity regulation but his investment in the status quo makes him a poor candidate for transformative reform.",
    competencies: {
      professional: { economics: 65, diplomacy: 60, security: 22, media: 45, legal: 65, administration: 82, technology: 82 },
      personal: { loyalty: 72, charisma: 50, leadership: 72, ambition: 58, integrity: 68, resilience: 82, intrigue: 58 },
    },
    qualifiedFor: ["director-electricity-regulation", "director-rural-electrification"],
  },

  {
    name: "Engr. Amaka Ofor-Nwadike",
    age: 45,
    state: "Enugu",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "AF",
    traits: ["Rural Energy Specialist", "Grassroots-Connected", "Tenacious"],
    bio: "Electrified 212 rural communities across the South-East and South-South through mini-grid deployments, working with the Rural Electrification Agency at a time when colleagues warned it was impossible at that scale. Her procurement innovations cut mini-grid installation costs by 35%. A champion of renewable energy who has never worked for a fossil fuel company.",
    education: "University of Nigeria (Electrical Engineering), Utrecht University (MSc Sustainable Energy Technology), REA Nigeria (Advanced Renewable Energy Finance)",
    tradeOff: "Exceptional at rural electrification delivery and renewable energy deployment but lacks the scale of experience to manage the full regulatory apparatus of the electricity sector.",
    competencies: {
      professional: { economics: 60, diplomacy: 55, security: 18, media: 55, legal: 42, administration: 78, technology: 85 },
      personal: { loyalty: 60, charisma: 65, leadership: 76, ambition: 68, integrity: 85, resilience: 82, intrigue: 32 },
    },
    qualifiedFor: ["director-rural-electrification", "director-electricity-regulation"],
  },

  {
    name: "Engr. Tanimu Bala-Kofar",
    age: 54,
    state: "Kano",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "TB",
    traits: ["Gas Monetisation Expert", "Deal-Maker", "Commercially Acute"],
    bio: "Structured the Ajaokuta-Kano-Katsina-Kaduna gas pipeline's commercial framework as a NNPC commercial director, a deal that had stalled for a decade before he reorganised its financing structure. His understanding of how international gas trading works is rare at the federal level. He plays the long game — always.",
    education: "Bayero University Kano (Chemical Engineering), University of Aberdeen (MSc Petroleum Management), NNPC Executive Programme",
    tradeOff: "Capable of unlocking transformative petroleum deals but his comfort with complex financial arrangements has attracted scrutiny from anti-corruption bodies.",
    competencies: {
      professional: { economics: 78, diplomacy: 68, security: 25, media: 50, legal: 60, administration: 72, technology: 78 },
      personal: { loyalty: 65, charisma: 65, leadership: 75, ambition: 80, integrity: 62, resilience: 78, intrigue: 65 },
    },
    qualifiedFor: ["director-petroleum-corporation", "director-electricity-regulation"],
  },

  {
    name: "Mrs. Ngozi Ike-Nwobi",
    age: 48,
    state: "Rivers",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Ogoni",
    avatar: "NI",
    traits: ["Energy Regulator", "Principled", "Community Voice"],
    bio: "Spent a decade as a petroleum rights advocate for Ogoni communities before joining NERC as a consumer rights commissioner. Her landmark ruling against Eko Electricity Distribution Company for discriminatory disconnections was upheld by the Federal High Court. She brings moral authority from communities who have suffered Nigeria's energy failures personally.",
    education: "University of Port Harcourt (Law), Queen Mary University of London (LLM Energy and Natural Resources Law), NERC Regulatory Certification",
    tradeOff: "Brings irreplaceable community legitimacy to electricity regulation but her advocacy background makes industry actors view her as adversarial rather than regulatory.",
    competencies: {
      professional: { economics: 55, diplomacy: 62, security: 28, media: 68, legal: 85, administration: 68, technology: 52 },
      personal: { loyalty: 52, charisma: 72, leadership: 72, ambition: 68, integrity: 90, resilience: 82, intrigue: 38 },
    },
    qualifiedFor: ["director-electricity-regulation", "director-rural-electrification"],
  },

  {
    name: "Engr. Mohammed Abdulqadir-Gashua",
    age: 59,
    state: "Yobe",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Kanuri",
    avatar: "MA",
    traits: ["Petroleum Operations Chief", "Steady", "Loyal"],
    bio: "The NNPC's most dependable operations director — three consecutive managing directors kept him in post because he simply made things run. Managed the emergency restart of four oil terminals after the 2020 COVID shutdown with zero supply disruptions. He is not a visionary; he is the man you call when you need the lights to stay on.",
    education: "University of Maiduguri (Chemical Engineering), Petroleum Training Institute Warri, Harvard (Energy Executive Programme)",
    tradeOff: "Guarantees operational continuity and institutional reliability but will not reform NNPC structures that protect embedded interests — including those of political patrons.",
    competencies: {
      professional: { economics: 62, diplomacy: 52, security: 30, media: 38, legal: 48, administration: 85, technology: 78 },
      personal: { loyalty: 82, charisma: 50, leadership: 75, ambition: 50, integrity: 72, resilience: 85, intrigue: 42 },
    },
    qualifiedFor: ["director-petroleum-corporation", "director-rural-electrification"],
  },

  {
    name: "Dr. Adaeze Okonkwo-Ihejirika",
    age: 43,
    state: "Imo",
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "AI",
    traits: ["Clean Energy Economist", "Visionary", "International"],
    bio: "Nigeria's representative on the International Renewable Energy Agency's Africa working group, she co-authored the 'Nigeria Energy Transition Plan' that was presented at COP27. Structured the first green bond issuance for an African state energy utility. Her ambition is to replace Nigeria's diesel dependency with renewables within a decade.",
    education: "University of Nigeria Nsukka (Economics), Imperial College London (MSc Environmental Economics), IRENA Masdar Institute (Renewable Energy Finance)",
    tradeOff: "Provides Nigeria with credible international clean energy credentials but her green agenda will clash directly with powerful petroleum lobby interests.",
    competencies: {
      professional: { economics: 80, diplomacy: 72, security: 15, media: 65, legal: 50, administration: 65, technology: 78 },
      personal: { loyalty: 48, charisma: 72, leadership: 70, ambition: 82, integrity: 82, resilience: 75, intrigue: 40 },
    },
    qualifiedFor: ["director-rural-electrification", "director-electricity-regulation", "director-investment-council"],
  },

  {
    name: "Engr. Haruna Shehu-Kebbi",
    age: 51,
    state: "Kebbi",
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "HK",
    traits: ["Rural Electrification Manager", "Community Pragmatist", "Humble"],
    bio: "Supervised the electrification of 1,400 rural communities in the NW zone during his time as zonal coordinator for the Rural Electrification Agency — more communities than any other zonal office in the agency's history. His relationships with traditional rulers in Kebbi, Sokoto, and Zamfara are the reason his communities pay their bills. A man who gets things done without getting credit.",
    education: "Usmanu Danfodiyo University (Electrical Engineering), Renewable Energy Training Centre Zaria, USAID Energy Governance Programme",
    tradeOff: "Extraordinary at community-level electrification and northern political networks but too modest and insufficiently strategic for the visibility the director role demands.",
    competencies: {
      professional: { economics: 50, diplomacy: 65, security: 30, media: 35, legal: 35, administration: 80, technology: 72 },
      personal: { loyalty: 80, charisma: 52, leadership: 72, ambition: 42, integrity: 82, resilience: 80, intrigue: 30 },
    },
    qualifiedFor: ["director-rural-electrification"],
  },
];

export const DIRECTOR_CANDIDATES: DirectorCandidate[] = [
  ...BATCH1_CANDIDATES,
  ...DIRECTOR_CANDIDATES_BATCH2,
  ...DIRECTOR_CANDIDATES_BATCH3,
];
