// client/src/lib/godfatherProfiles.ts
import type { Godfather } from "./godfatherTypes";

/**
 * 24 handcrafted godfather profiles covering all 6 geopolitical zones
 * and all 7 archetypes. Each profile represents a power broker who can
 * help or hinder the player's presidency.
 *
 * Zone distribution: NC:4, NW:4, NE:5, SW:4, SE:4, SS:3
 * Archetype distribution:
 *   business-oligarch: 5, military-elder: 3, party-boss: 4,
 *   labour-civil: 2, religious-leader: 3, regional-strongman: 4, media-mogul: 3
 *   Total: 24
 */
export const GODFATHER_PROFILES: Godfather[] = [
  // ============================================================
  // NORTH-CENTRAL (NC) — 4 godfathers
  // ============================================================
  {
    id: "gf-nc-gambo",
    name: "Alhaji Aminu Gambo",
    archetype: "business-oligarch",
    zone: "NC",
    description:
      "A Nupe industrialist who built a cement and logistics empire stretching from Bida to Abuja. Controls several federal contracts through shell companies and maintains a web of financial obligations across party lines. Known for his quiet ruthlessness — he never raises his voice, but his rivals tend to disappear from the bidding lists.",
    traits: { aggression: 55, loyalty: 40, greed: 85, visibility: 30 },
    disposition: "neutral",
    dealStyle: "contract",
    interests: [
      "Federal infrastructure contracts",
      "Import waivers on industrial inputs",
      "Cement industry protectionism",
      "Abuja land allocation",
    ],
    stable: {
      governors: ["Nasarawa", "Niger"],
      legislativeBloc: { house: 12, senate: 4 },
      cabinetCandidates: ["Works Minister nominee", "FCT Minister nominee"],
      directorInterests: ["director-public-works", "director-housing-authority"],
      traditionalRulerAllies: ["etsu-nupe"],
      connections: [
        {
          entityType: "business",
          description: "Controls 30% of federal road construction contracts through front companies",
          effect: [{ target: "macroEconomy", delta: 3 }],
          revealed: true,
        },
        {
          entityType: "legislator-bloc",
          description: "Bankrolls 12 House members from NC who vote as directed",
          effect: [{ target: "politicalCapital", delta: 5 }],
          revealed: true,
        },
        {
          entityType: "cabinet",
          description: "Has a preferred candidate for Works Ministry who would steer contracts his way",
          effect: [{ target: "approval", delta: -2 }],
          revealed: true,
        },
        {
          entityType: "governor",
          description: "Nasarawa and Niger governors owe their election war chests to him",
          effect: [{ target: "partyLoyalty", delta: 4 }],
          revealed: false,
        },
        {
          entityType: "media",
          description: "Owns a mid-tier Abuja newspaper used to plant favourable coverage",
          effect: [{ target: "trust", delta: 2 }],
          revealed: false,
        },
      ],
    },
    escalationStage: 0,
    favourDebt: 0,
    activeContracts: [],
    neutralized: false,
    influenceScore: 78,
  },
  {
    id: "gf-nc-tarka",
    name: "Comrade Mwuese Tarka",
    archetype: "labour-civil",
    zone: "NC",
    description:
      "A firebrand Tiv labour organizer who rose through the NLC ranks to command the loyalty of unions across the Middle Belt. His word can shut down power stations, close ports, or flood the streets of Abuja with angry workers. Ideologically committed to workers' rights, but not above leveraging that commitment for political favours.",
    traits: { aggression: 75, loyalty: 65, greed: 30, visibility: 85 },
    disposition: "neutral",
    dealStyle: "favour-bank",
    interests: [
      "Minimum wage increases",
      "Anti-privatization of public utilities",
      "Labour representation on government boards",
      "Middle Belt political recognition",
    ],
    stable: {
      governors: [],
      legislativeBloc: { house: 5, senate: 1 },
      cabinetCandidates: ["Labour Minister nominee"],
      directorInterests: ["director-industrial-relations", "director-pensions"],
      traditionalRulerAllies: ["tor-tiv"],
      connections: [
        {
          entityType: "street",
          description: "Can mobilize 200,000 workers for nationwide strikes within 48 hours",
          effect: [{ target: "stability", delta: -8 }],
          revealed: true,
        },
        {
          entityType: "legislator-bloc",
          description: "Labour-aligned legislators who champion workers' bills",
          effect: [{ target: "politicalCapital", delta: 2 }],
          revealed: true,
        },
        {
          entityType: "media",
          description: "Sympathetic journalists in national dailies amplify labour grievances",
          effect: [{ target: "outrage", delta: 5 }],
          revealed: true,
        },
        {
          entityType: "cabinet",
          description: "Insists on vetting any Labour Ministry appointment",
          effect: [{ target: "factionGrievance", delta: 3 }],
          revealed: false,
        },
        {
          entityType: "business",
          description: "Has quiet backchannel to telecom union leaders who can disrupt networks",
          effect: [{ target: "stability", delta: -4 }],
          revealed: false,
        },
      ],
    },
    escalationStage: 0,
    favourDebt: 0,
    activeContracts: [],
    neutralized: false,
    influenceScore: 72,
  },
  {
    id: "gf-nc-danladi",
    name: "Gen. Yakubu Danladi (rtd)",
    archetype: "military-elder",
    zone: "NC",
    description:
      "A retired two-star general from Plateau State who served as military governor of two states during the 1990s. Still commands respect in Abuja's defence establishment and maintains an informal council of retired officers who advise — and sometimes pressure — the sitting president. Believes civilian politicians are inherently incompetent.",
    traits: { aggression: 60, loyalty: 70, greed: 45, visibility: 40 },
    disposition: "cold",
    dealStyle: "favour-bank",
    interests: [
      "Defence procurement oversight",
      "Military pension reform",
      "Security appointments",
      "Plateau State peace architecture",
    ],
    stable: {
      governors: ["Plateau"],
      legislativeBloc: { house: 4, senate: 2 },
      cabinetCandidates: ["Defence Minister nominee"],
      militaryInterests: ["chief-defence-force", "chief-army-force"],
      directorInterests: ["director-defence-industries", "director-state-security"],
      traditionalRulerAllies: ["gbong-gwom-jos"],
      connections: [
        {
          entityType: "cabinet",
          description: "His protégés occupy key positions in the defence establishment",
          effect: [{ target: "stability", delta: 4 }],
          revealed: true,
        },
        {
          entityType: "governor",
          description: "Plateau governor consults him on all major security decisions",
          effect: [{ target: "approval", delta: 2 }],
          revealed: true,
        },
        {
          entityType: "business",
          description: "Connected to defence contractors who depend on his endorsement",
          effect: [{ target: "macroEconomy", delta: 2 }],
          revealed: true,
        },
        {
          entityType: "legislator-bloc",
          description: "Former military officers now in the Senate defer to his counsel",
          effect: [{ target: "politicalCapital", delta: 3 }],
          revealed: false,
        },
        {
          entityType: "media",
          description: "Retired officers' WhatsApp network shapes security narratives",
          effect: [{ target: "trust", delta: -2 }],
          revealed: false,
        },
      ],
    },
    escalationStage: 0,
    favourDebt: 0,
    activeContracts: [],
    neutralized: false,
    influenceScore: 70,
  },
  {
    id: "gf-nc-onimisi",
    name: "Pastor Emmanuel Onimisi",
    archetype: "religious-leader",
    zone: "NC",
    description:
      "Founder of the Glorious Harvest Ministry with a congregation of 500,000 across the Middle Belt. His Sunday sermons are political events — a veiled endorsement or condemnation from his pulpit can swing voter sentiment across Kogi, Kwara and Benue. Presents himself as a man of God but privately trades access to his flock for political concessions.",
    traits: { aggression: 40, loyalty: 50, greed: 55, visibility: 90 },
    disposition: "neutral",
    dealStyle: "favour-bank",
    interests: [
      "Christian Association of Nigeria representation",
      "Faith-based education funding",
      "Middle Belt security against herdsmen",
      "Tax exemptions for religious organizations",
    ],
    stable: {
      governors: ["Kogi"],
      legislativeBloc: { house: 6, senate: 2 },
      cabinetCandidates: [],
      traditionalRulerAllies: ["atta-igala"],
      religiousLeaderAllies: ["pres-christian-society"],
      connections: [
        {
          entityType: "street",
          description: "Half a million congregants who follow his political direction",
          effect: [{ target: "approval", delta: 6 }],
          revealed: true,
        },
        {
          entityType: "media",
          description: "Owns a satellite TV channel broadcasting across West Africa",
          effect: [{ target: "trust", delta: 3 }],
          revealed: true,
        },
        {
          entityType: "governor",
          description: "Kogi governor is a church elder who tithes politically",
          effect: [{ target: "partyLoyalty", delta: 2 }],
          revealed: true,
        },
        {
          entityType: "legislator-bloc",
          description: "Christian caucus in the House consults him on sensitive bills",
          effect: [{ target: "politicalCapital", delta: 3 }],
          revealed: false,
        },
        {
          entityType: "business",
          description: "Church investment arm holds stakes in real estate and banking",
          effect: [{ target: "macroEconomy", delta: 1 }],
          revealed: false,
        },
      ],
    },
    escalationStage: 0,
    favourDebt: 0,
    activeContracts: [],
    neutralized: false,
    influenceScore: 68,
  },

  // ============================================================
  // NORTH-WEST (NW) — 4 godfathers
  // ============================================================
  {
    id: "gf-nw-dantata",
    name: "Alhaji Abdulrazak Dantata",
    archetype: "business-oligarch",
    zone: "NW",
    description:
      "Third-generation Kano merchant prince whose family wealth predates independence. Controls a conglomerate spanning textiles, flour milling, and real estate across Northern Nigeria. His business network doubles as a political machine — every contract he awards comes with an implied obligation to support his chosen candidates.",
    traits: { aggression: 35, loyalty: 55, greed: 80, visibility: 50 },
    disposition: "neutral",
    dealStyle: "contract",
    interests: [
      "Northern industrialization policy",
      "Textile import restrictions",
      "Kano Free Trade Zone expansion",
      "CBN monetary policy favouring manufacturers",
    ],
    stable: {
      governors: ["Kano", "Jigawa"],
      legislativeBloc: { house: 15, senate: 5 },
      cabinetCandidates: ["Trade Minister nominee", "Industry Minister nominee"],
      diplomaticInterests: ["amb-saudi", "amb-uae"],
      directorInterests: ["director-customs-services", "director-standards-organisation"],
      traditionalRulerAllies: ["emir-kano"],
      religiousLeaderAllies: ["pres-muslim-society"],
      connections: [
        {
          entityType: "business",
          description: "Dantata Group employs 40,000 workers across the NW — a political constituency",
          effect: [{ target: "macroEconomy", delta: 4 }],
          revealed: true,
        },
        {
          entityType: "governor",
          description: "Kano and Jigawa governors are former Dantata Group executives",
          effect: [{ target: "partyLoyalty", delta: 5 }],
          revealed: true,
        },
        {
          entityType: "legislator-bloc",
          description: "Largest single bloc of legislators loyal to one patron in the NW",
          effect: [{ target: "politicalCapital", delta: 7 }],
          revealed: true,
        },
        {
          entityType: "cabinet",
          description: "Wants to place loyalists in Trade and Industry ministries",
          effect: [{ target: "approval", delta: -2 }],
          revealed: false,
        },
        {
          entityType: "media",
          description: "Major advertiser in northern media — can pull ads to punish critical outlets",
          effect: [{ target: "trust", delta: -3 }],
          revealed: false,
        },
      ],
    },
    escalationStage: 0,
    favourDebt: 0,
    activeContracts: [],
    neutralized: false,
    influenceScore: 90,
  },
  {
    id: "gf-nw-maigari",
    name: "Sheikh Abubakar Maigari",
    archetype: "religious-leader",
    zone: "NW",
    description:
      "Chief Imam of the Kaduna Central Mosque and chairman of the Supreme Council for Sharia Affairs. His fatwas carry the weight of law in many northern communities. Presidents court his blessing; those who cross him face mass protests and boycotts. Quietly progressive on economic matters but fiercely conservative on social policy.",
    traits: { aggression: 50, loyalty: 60, greed: 25, visibility: 95 },
    disposition: "neutral",
    dealStyle: "favour-bank",
    interests: [
      "Sharia compliance in federal policy",
      "Islamic banking expansion",
      "Northern education reform (Almajiri system)",
      "Religious harmony and anti-blasphemy legislation",
    ],
    stable: {
      governors: ["Kaduna"],
      legislativeBloc: { house: 8, senate: 3 },
      cabinetCandidates: [],
      diplomaticInterests: ["amb-saudi"],
      traditionalRulerAllies: ["sultan-sokoto", "emir-zazzau"],
      religiousLeaderAllies: ["pres-muslim-society"],
      connections: [
        {
          entityType: "street",
          description: "Can mobilize millions of faithful across the NW for protests or support rallies",
          effect: [{ target: "stability", delta: -10 }],
          revealed: true,
        },
        {
          entityType: "legislator-bloc",
          description: "Northern Muslim caucus seeks his blessing before voting on sensitive bills",
          effect: [{ target: "politicalCapital", delta: 4 }],
          revealed: true,
        },
        {
          entityType: "governor",
          description: "Kaduna governor maintains close spiritual counsel with him",
          effect: [{ target: "partyLoyalty", delta: 3 }],
          revealed: true,
        },
        {
          entityType: "media",
          description: "Network of Islamic radio stations amplify his messages",
          effect: [{ target: "outrage", delta: 6 }],
          revealed: false,
        },
        {
          entityType: "business",
          description: "Almajiri education reform foundation receives international donor funding",
          effect: [{ target: "trust", delta: 2 }],
          revealed: false,
        },
      ],
    },
    escalationStage: 0,
    favourDebt: 0,
    activeContracts: [],
    neutralized: false,
    influenceScore: 82,
  },
  {
    id: "gf-nw-kwande",
    name: "Gen. Umaru Kwande (rtd)",
    archetype: "military-elder",
    zone: "NW",
    description:
      "Former Head of State who ruled Nigeria for three years in the 1990s. Despite handing over to civilian rule, he never truly left power — his phone calls to Aso Rock carry more weight than most cabinet memos. Controls a network of retired generals, serving officers, and intelligence operatives. Every president since the transition has had to negotiate with him.",
    traits: { aggression: 70, loyalty: 45, greed: 60, visibility: 55 },
    disposition: "cold",
    dealStyle: "favour-bank",
    interests: [
      "North-West political dominance",
      "Military-industrial complex contracts",
      "Control of security architecture",
      "Kingmaker status preservation",
    ],
    stable: {
      governors: ["Katsina", "Zamfara"],
      legislativeBloc: { house: 10, senate: 4 },
      cabinetCandidates: ["NSA nominee", "Defence Minister nominee"],
      militaryInterests: ["chief-defence-force", "chief-army-force", "chief-air-force"],
      directorInterests: ["director-defence-industries", "director-state-security", "director-police-commission"],
      traditionalRulerAllies: ["sultan-sokoto", "emir-katsina"],
      connections: [
        {
          entityType: "cabinet",
          description: "Former military officers in key security positions report to him informally",
          effect: [{ target: "stability", delta: 5 }],
          revealed: true,
        },
        {
          entityType: "governor",
          description: "Katsina and Zamfara governors were installed through his political machine",
          effect: [{ target: "partyLoyalty", delta: 5 }],
          revealed: true,
        },
        {
          entityType: "business",
          description: "Defence procurement network worth billions flows through his associates",
          effect: [{ target: "macroEconomy", delta: 3 }],
          revealed: true,
        },
        {
          entityType: "legislator-bloc",
          description: "Senate committee chairmen consult him before approving defence budgets",
          effect: [{ target: "politicalCapital", delta: 5 }],
          revealed: false,
        },
        {
          entityType: "media",
          description: "Can plant stories through intelligence contacts in major newspapers",
          effect: [{ target: "trust", delta: -4 }],
          revealed: false,
        },
      ],
    },
    escalationStage: 0,
    favourDebt: 0,
    activeContracts: [],
    neutralized: false,
    influenceScore: 92,
  },
  {
    id: "gf-nw-suleiman",
    name: "Alhaji Bello Suleiman",
    archetype: "party-boss",
    zone: "NW",
    description:
      "The perpetual party chairman who has survived five leadership changes by making himself indispensable. Controls the party machinery in the NW with an iron grip — candidate selection, delegate management, and ward-level organization all pass through his office. No one wins a primary in the NW without his nod.",
    traits: { aggression: 65, loyalty: 35, greed: 70, visibility: 45 },
    disposition: "neutral",
    dealStyle: "contract",
    interests: [
      "Party chairmanship retention",
      "Control of NW primaries",
      "Government patronage for party loyalists",
      "Zonal representation in federal appointments",
    ],
    stable: {
      governors: ["Sokoto"],
      legislativeBloc: { house: 8, senate: 3 },
      cabinetCandidates: ["Party Affairs Minister nominee"],
      directorInterests: ["director-revenue-service", "director-electoral-commission"],
      traditionalRulerAllies: ["sultan-sokoto"],
      connections: [
        {
          entityType: "legislator-bloc",
          description: "Controls delegate lists for NW party congresses",
          effect: [{ target: "partyLoyalty", delta: 6 }],
          revealed: true,
        },
        {
          entityType: "governor",
          description: "Sokoto governor depends on his machinery for re-election",
          effect: [{ target: "approval", delta: 2 }],
          revealed: true,
        },
        {
          entityType: "street",
          description: "Commands an army of ward chairmen and local party agents",
          effect: [{ target: "politicalCapital", delta: 4 }],
          revealed: true,
        },
        {
          entityType: "cabinet",
          description: "Demands patronage slots for loyal party workers",
          effect: [{ target: "factionGrievance", delta: 3 }],
          revealed: false,
        },
        {
          entityType: "business",
          description: "Party financing network channels funds from NW business interests",
          effect: [{ target: "macroEconomy", delta: -1 }],
          revealed: false,
        },
      ],
    },
    escalationStage: 0,
    favourDebt: 0,
    activeContracts: [],
    neutralized: false,
    influenceScore: 75,
  },

  // ============================================================
  // NORTH-EAST (NE) — 4 godfathers
  // ============================================================
  {
    id: "gf-ne-shettima",
    name: "Alhaji Musa Shettima",
    archetype: "business-oligarch",
    zone: "NE",
    description:
      "Borno-born logistics magnate who made his fortune supplying the military during the insurgency. What began as legitimate contracts evolved into a vast network of influence connecting him to generals, governors, and humanitarian NGOs. His warehouses in Maiduguri are the beating heart of NE commerce and aid distribution.",
    traits: { aggression: 50, loyalty: 45, greed: 75, visibility: 35 },
    disposition: "neutral",
    dealStyle: "contract",
    interests: [
      "Military supply contracts",
      "Humanitarian aid logistics",
      "NE reconstruction contracts",
      "Border trade facilitation",
    ],
    stable: {
      governors: ["Borno"],
      legislativeBloc: { house: 7, senate: 2 },
      cabinetCandidates: ["Humanitarian Affairs Minister nominee"],
      militaryInterests: ["chief-army-force"],
      diplomaticInterests: ["amb-saudi", "amb-uae"],
      directorInterests: ["director-customs-services"],
      traditionalRulerAllies: ["shehu-borno"],
      religiousLeaderAllies: ["pres-muslim-society"],
      connections: [
        {
          entityType: "business",
          description: "Monopoly on military supply logistics in the NE theatre",
          effect: [{ target: "macroEconomy", delta: 3 }],
          revealed: true,
        },
        {
          entityType: "governor",
          description: "Borno governor relies on his logistics network for reconstruction",
          effect: [{ target: "approval", delta: 3 }],
          revealed: true,
        },
        {
          entityType: "cabinet",
          description: "Has informants in the Ministry of Humanitarian Affairs",
          effect: [{ target: "trust", delta: -2 }],
          revealed: true,
        },
        {
          entityType: "media",
          description: "Controls the narrative around NE reconstruction progress",
          effect: [{ target: "outrage", delta: -3 }],
          revealed: false,
        },
        {
          entityType: "legislator-bloc",
          description: "Funds NE legislators who push for increased security spending",
          effect: [{ target: "politicalCapital", delta: 3 }],
          revealed: false,
        },
      ],
    },
    escalationStage: 0,
    favourDebt: 0,
    activeContracts: [],
    neutralized: false,
    influenceScore: 73,
  },
  {
    id: "gf-ne-abubakar",
    name: "Mallam Ibrahim Abubakar",
    archetype: "regional-strongman",
    zone: "NE",
    description:
      "Former governor of Adamawa who turned two terms in office into a permanent political dynasty. His family controls politics in Adamawa and extends influence into Taraba and Gombe. Operates through a network of traditional rulers and local government chairmen who ensure his candidates win at every level.",
    traits: { aggression: 65, loyalty: 50, greed: 60, visibility: 60 },
    disposition: "neutral",
    dealStyle: "contract",
    interests: [
      "NE federal appointments",
      "Adamawa State development funds",
      "Control of traditional institutions",
      "Cross-border trade with Cameroon",
    ],
    stable: {
      governors: ["Adamawa", "Gombe"],
      legislativeBloc: { house: 9, senate: 3 },
      cabinetCandidates: ["Water Resources Minister nominee"],
      militaryInterests: ["chief-police-force"],
      traditionalRulerAllies: ["emir-adamawa", "shehu-borno"],
      diplomaticInterests: ["amb-cameroon"],
      connections: [
        {
          entityType: "governor",
          description: "Adamawa and Gombe governors are his political protégés",
          effect: [{ target: "partyLoyalty", delta: 4 }],
          revealed: true,
        },
        {
          entityType: "legislator-bloc",
          description: "Controls a disciplined bloc of NE legislators",
          effect: [{ target: "politicalCapital", delta: 4 }],
          revealed: true,
        },
        {
          entityType: "street",
          description: "Network of traditional rulers and local chairmen ensures grassroots control",
          effect: [{ target: "approval", delta: 3 }],
          revealed: true,
        },
        {
          entityType: "business",
          description: "Family controls cross-border trade routes with Cameroon",
          effect: [{ target: "macroEconomy", delta: 2 }],
          revealed: false,
        },
        {
          entityType: "cabinet",
          description: "Expects representation in any cabinet that wants NE cooperation",
          effect: [{ target: "factionGrievance", delta: 4 }],
          revealed: false,
        },
      ],
    },
    escalationStage: 0,
    favourDebt: 0,
    activeContracts: [],
    neutralized: false,
    influenceScore: 76,
  },
  {
    id: "gf-ne-bukar",
    name: "Sheikh Muhammadu Bukar",
    archetype: "religious-leader",
    zone: "NE",
    description:
      "The spiritual leader of the Tijaniyya brotherhood in the North-East, with millions of adherents across Borno, Yobe, and Bauchi. His influence transcends politics — he mediates conflicts, blesses campaigns, and his displeasure can delegitimize any politician in the region. Deeply concerned about the insurgency's impact on Islamic scholarship.",
    traits: { aggression: 30, loyalty: 70, greed: 20, visibility: 80 },
    disposition: "friendly",
    dealStyle: "favour-bank",
    interests: [
      "Counter-radicalization programs",
      "Islamic education reform",
      "NE peace and reconciliation",
      "Protection of Sufi traditions",
    ],
    stable: {
      governors: ["Yobe"],
      legislativeBloc: { house: 4, senate: 1 },
      cabinetCandidates: [],
      diplomaticInterests: ["amb-saudi"],
      traditionalRulerAllies: ["shehu-borno"],
      religiousLeaderAllies: ["pres-muslim-society"],
      connections: [
        {
          entityType: "street",
          description: "Millions of Tijaniyya faithful who follow his spiritual and political guidance",
          effect: [{ target: "approval", delta: 5 }],
          revealed: true,
        },
        {
          entityType: "governor",
          description: "Yobe governor seeks his blessing for all major policy announcements",
          effect: [{ target: "partyLoyalty", delta: 2 }],
          revealed: true,
        },
        {
          entityType: "media",
          description: "Islamic education network provides counter-narrative to extremism",
          effect: [{ target: "stability", delta: 3 }],
          revealed: true,
        },
        {
          entityType: "legislator-bloc",
          description: "NE legislators consult him on bills affecting Islamic institutions",
          effect: [{ target: "politicalCapital", delta: 2 }],
          revealed: false,
        },
        {
          entityType: "cabinet",
          description: "Advocates for NE representation in education and religious affairs",
          effect: [{ target: "factionGrievance", delta: 2 }],
          revealed: false,
        },
      ],
    },
    escalationStage: 0,
    favourDebt: 0,
    activeContracts: [],
    neutralized: false,
    influenceScore: 65,
  },
  {
    id: "gf-ne-haruna",
    name: "Hajiya Fatima Haruna",
    archetype: "party-boss",
    zone: "NE",
    description:
      "A formidable Kanuri woman who rose through party ranks to become the most powerful political organizer in the NE. Controls the women's wing and youth mobilization apparatus across three states. Broke every glass ceiling in northern politics with a combination of strategic marriages, business acumen, and sheer force of will.",
    traits: { aggression: 70, loyalty: 55, greed: 50, visibility: 65 },
    disposition: "neutral",
    dealStyle: "contract",
    interests: [
      "Women's political representation",
      "NE youth empowerment programs",
      "Party women's wing leadership",
      "Social welfare ministries",
    ],
    stable: {
      governors: ["Bauchi"],
      legislativeBloc: { house: 6, senate: 2 },
      cabinetCandidates: ["Women Affairs Minister nominee"],
      directorInterests: ["director-youth-employment", "director-social-investment"],
      traditionalRulerAllies: ["emir-bauchi"],
      connections: [
        {
          entityType: "street",
          description: "Commands women's and youth mobilization networks across three NE states",
          effect: [{ target: "approval", delta: 4 }],
          revealed: true,
        },
        {
          entityType: "legislator-bloc",
          description: "Female legislators and youth caucus members follow her lead",
          effect: [{ target: "politicalCapital", delta: 3 }],
          revealed: true,
        },
        {
          entityType: "governor",
          description: "Bauchi governor owes his primary victory to her delegate management",
          effect: [{ target: "partyLoyalty", delta: 3 }],
          revealed: true,
        },
        {
          entityType: "cabinet",
          description: "Demands Women Affairs portfolio as minimum representation",
          effect: [{ target: "factionGrievance", delta: 2 }],
          revealed: false,
        },
        {
          entityType: "media",
          description: "Active social media presence amplifies NE political narratives",
          effect: [{ target: "outrage", delta: 3 }],
          revealed: false,
        },
      ],
    },
    escalationStage: 0,
    favourDebt: 0,
    activeContracts: [],
    neutralized: false,
    influenceScore: 67,
  },

  // ============================================================
  // SOUTH-WEST (SW) — 4 godfathers
  // ============================================================
  {
    id: "gf-sw-adeniyi",
    name: "Chief Bode Adeniyi",
    archetype: "media-mogul",
    zone: "SW",
    description:
      "Owner of Nigeria's largest media conglomerate — three newspapers, two TV stations, and a digital media empire. A Yoruba chieftain from Ibadan who weaponized media ownership into political kingmaking. His front pages have made and destroyed careers. Politicians fear his editorial meetings more than EFCC investigations.",
    traits: { aggression: 60, loyalty: 30, greed: 65, visibility: 85 },
    disposition: "neutral",
    dealStyle: "contract",
    interests: [
      "Media industry deregulation",
      "Digital economy investments",
      "SW political representation",
      "Anti-media censorship legislation",
    ],
    stable: {
      governors: ["Oyo"],
      legislativeBloc: { house: 7, senate: 2 },
      cabinetCandidates: ["Information Minister nominee"],
      directorInterests: ["director-broadcasting-commission", "director-communications-commission"],
      diplomaticInterests: ["amb-usa", "amb-uk"],
      traditionalRulerAllies: ["alaafin-oyo"],
      connections: [
        {
          entityType: "media",
          description: "Controls the largest print and broadcast media group in Nigeria",
          effect: [{ target: "trust", delta: -6 }],
          revealed: true,
        },
        {
          entityType: "governor",
          description: "Oyo governor received crucial endorsement from his media empire",
          effect: [{ target: "approval", delta: 3 }],
          revealed: true,
        },
        {
          entityType: "legislator-bloc",
          description: "SW legislators court his favour to get positive coverage",
          effect: [{ target: "politicalCapital", delta: 3 }],
          revealed: true,
        },
        {
          entityType: "business",
          description: "Digital media ventures give him influence over online narratives",
          effect: [{ target: "outrage", delta: 5 }],
          revealed: false,
        },
        {
          entityType: "cabinet",
          description: "Wants Information Ministry under someone sympathetic to media interests",
          effect: [{ target: "factionGrievance", delta: 2 }],
          revealed: false,
        },
      ],
    },
    escalationStage: 0,
    favourDebt: 0,
    activeContracts: [],
    neutralized: false,
    influenceScore: 80,
  },
  {
    id: "gf-sw-afolabi",
    name: "Chief Oluwaseun Afolabi",
    archetype: "business-oligarch",
    zone: "SW",
    description:
      "Lagos-based oil and gas tycoon whose Afolabi Energy Group controls a significant share of downstream petroleum distribution. Built his empire during the deregulation era by being the first to secure private refinery licenses. His wealth translates directly into political power — he personally bankrolled the campaigns of a dozen legislators.",
    traits: { aggression: 45, loyalty: 35, greed: 90, visibility: 55 },
    disposition: "neutral",
    dealStyle: "contract",
    interests: [
      "Petroleum industry deregulation",
      "Refinery licensing",
      "Port concessions in Lagos",
      "SW infrastructure development",
    ],
    stable: {
      governors: ["Lagos"],
      legislativeBloc: { house: 10, senate: 3 },
      cabinetCandidates: ["Petroleum Minister nominee"],
      diplomaticInterests: ["amb-usa", "amb-uk"],
      directorInterests: ["director-petroleum-corporation", "director-ports-authority"],
      traditionalRulerAllies: ["oba-lagos"],
      connections: [
        {
          entityType: "business",
          description: "Afolabi Energy controls 15% of downstream petroleum distribution",
          effect: [{ target: "macroEconomy", delta: 5 }],
          revealed: true,
        },
        {
          entityType: "governor",
          description: "Lagos governor's campaign was partly funded by Afolabi interests",
          effect: [{ target: "partyLoyalty", delta: 3 }],
          revealed: true,
        },
        {
          entityType: "legislator-bloc",
          description: "Bankrolled 10 House members who protect oil industry interests",
          effect: [{ target: "politicalCapital", delta: 5 }],
          revealed: true,
        },
        {
          entityType: "cabinet",
          description: "Wants a loyalist in the Petroleum Ministry to protect his licenses",
          effect: [{ target: "approval", delta: -3 }],
          revealed: false,
        },
        {
          entityType: "media",
          description: "Major sponsor of Lagos business press — shapes energy policy narrative",
          effect: [{ target: "trust", delta: -2 }],
          revealed: false,
        },
      ],
    },
    escalationStage: 0,
    favourDebt: 0,
    activeContracts: [],
    neutralized: false,
    influenceScore: 85,
  },
  {
    id: "gf-sw-ogundele",
    name: "Chief Ademola Ogundele",
    archetype: "regional-strongman",
    zone: "SW",
    description:
      "The 'Lion of Yorubaland' — a former governor who built an unshakeable political machine across the SW. Every aspirant in Yoruba politics must pass through his living room in Abeokuta. Controls the traditional political structures from ward level up, and his endorsement is worth more than any party ticket.",
    traits: { aggression: 75, loyalty: 40, greed: 55, visibility: 70 },
    disposition: "cold",
    dealStyle: "favour-bank",
    interests: [
      "Yoruba political unity",
      "SW federal appointments (proportional)",
      "Lagos-Ibadan economic corridor",
      "Restructuring and true federalism",
    ],
    stable: {
      governors: ["Ogun", "Osun"],
      legislativeBloc: { house: 12, senate: 4 },
      cabinetCandidates: ["Finance Minister nominee", "SGF nominee"],
      militaryInterests: ["chief-police-force"],
      traditionalRulerAllies: ["ooni-ife", "alake-abeokuta", "oba-lagos"],
      directorInterests: ["governor-central-bank"],
      connections: [
        {
          entityType: "governor",
          description: "Ogun and Osun governors are his handpicked successors",
          effect: [{ target: "partyLoyalty", delta: 5 }],
          revealed: true,
        },
        {
          entityType: "legislator-bloc",
          description: "SW legislative caucus answers to his political direction",
          effect: [{ target: "politicalCapital", delta: 6 }],
          revealed: true,
        },
        {
          entityType: "street",
          description: "Ward-level political machinery guarantees grassroots mobilization",
          effect: [{ target: "approval", delta: 4 }],
          revealed: true,
        },
        {
          entityType: "cabinet",
          description: "Expects SGF or Finance for the SW as non-negotiable",
          effect: [{ target: "factionGrievance", delta: 5 }],
          revealed: false,
        },
        {
          entityType: "media",
          description: "Yoruba-language media outlets amplify his political messaging",
          effect: [{ target: "outrage", delta: 4 }],
          revealed: false,
        },
      ],
    },
    escalationStage: 0,
    favourDebt: 0,
    activeContracts: [],
    neutralized: false,
    influenceScore: 88,
  },
  {
    id: "gf-sw-oni",
    name: "Pastor Adeboye Oni",
    archetype: "party-boss",
    zone: "SW",
    description:
      "A former pastor turned political operative who combines Pentecostal fervour with ruthless party organization. Runs the party machinery in the SW with a mix of spiritual authority and transactional politics. His 'prayer breakfasts' are actually strategy sessions where candidates are vetted and deals are struck.",
    traits: { aggression: 55, loyalty: 50, greed: 60, visibility: 50 },
    disposition: "friendly",
    dealStyle: "contract",
    interests: [
      "SW party structure control",
      "Faith-based social programs",
      "Youth empowerment schemes",
      "Patronage distribution in SW",
    ],
    stable: {
      governors: ["Ekiti"],
      legislativeBloc: { house: 5, senate: 2 },
      cabinetCandidates: ["Youth Minister nominee"],
      directorInterests: ["director-youth-service-corps", "director-social-investment"],
      traditionalRulerAllies: ["ewi-ado-ekiti"],
      religiousLeaderAllies: ["pres-christian-society"],
      connections: [
        {
          entityType: "street",
          description: "Church network doubles as party mobilization infrastructure",
          effect: [{ target: "approval", delta: 3 }],
          revealed: true,
        },
        {
          entityType: "legislator-bloc",
          description: "Mentored several young legislators who remain loyal",
          effect: [{ target: "politicalCapital", delta: 3 }],
          revealed: true,
        },
        {
          entityType: "governor",
          description: "Ekiti governor emerged from his political mentorship program",
          effect: [{ target: "partyLoyalty", delta: 3 }],
          revealed: true,
        },
        {
          entityType: "media",
          description: "Active social media operation shapes SW youth political narratives",
          effect: [{ target: "trust", delta: 2 }],
          revealed: false,
        },
        {
          entityType: "cabinet",
          description: "Pushes youth-focused ministerial appointments from his network",
          effect: [{ target: "factionGrievance", delta: 2 }],
          revealed: false,
        },
      ],
    },
    escalationStage: 0,
    favourDebt: 0,
    activeContracts: [],
    neutralized: false,
    influenceScore: 64,
  },

  // ============================================================
  // SOUTH-EAST (SE) — 4 godfathers
  // ============================================================
  {
    id: "gf-se-mbah",
    name: "Chief Ugochukwu Mbah",
    archetype: "party-boss",
    zone: "SE",
    description:
      "The 'Chairman General' — an Igbo political baron from Enugu who has controlled the party apparatus in the SE for two decades. No governorship candidate in the SE wins a primary without his approval. Combines old-school political patronage with a genuine grievance about Igbo marginalization in federal politics.",
    traits: { aggression: 70, loyalty: 45, greed: 65, visibility: 55 },
    disposition: "neutral",
    dealStyle: "contract",
    interests: [
      "SE presidential slot rotation",
      "Igbo federal appointments",
      "SE infrastructure (roads, rail)",
      "Party chairmanship for SE zone",
    ],
    stable: {
      governors: ["Enugu", "Ebonyi"],
      legislativeBloc: { house: 11, senate: 4 },
      cabinetCandidates: ["Works Minister nominee", "Science Minister nominee"],
      directorInterests: ["director-revenue-service", "director-electoral-commission"],
      traditionalRulerAllies: ["obi-onitsha", "igwe-enugu"],
      connections: [
        {
          entityType: "governor",
          description: "Enugu and Ebonyi governors are his political protégés",
          effect: [{ target: "partyLoyalty", delta: 5 }],
          revealed: true,
        },
        {
          entityType: "legislator-bloc",
          description: "Commands the largest SE legislative bloc through party machinery",
          effect: [{ target: "politicalCapital", delta: 5 }],
          revealed: true,
        },
        {
          entityType: "street",
          description: "Party ward structures across SE respond to his directives",
          effect: [{ target: "approval", delta: 3 }],
          revealed: true,
        },
        {
          entityType: "cabinet",
          description: "Maintains a list of 'acceptable' SE ministerial nominees",
          effect: [{ target: "factionGrievance", delta: 4 }],
          revealed: false,
        },
        {
          entityType: "business",
          description: "Connected to SE construction firms that depend on federal contracts",
          effect: [{ target: "macroEconomy", delta: 2 }],
          revealed: false,
        },
      ],
    },
    escalationStage: 0,
    favourDebt: 0,
    activeContracts: [],
    neutralized: false,
    influenceScore: 77,
  },
  {
    id: "gf-se-okonkwo",
    name: "Chief Emeka Okonkwo",
    archetype: "business-oligarch",
    zone: "SE",
    description:
      "An Nnewi-born auto parts magnate who parlayed his manufacturing empire into political power. His factories employ thousands across Anambra and Imo, giving him enormous leverage over state economies. Known as 'Odinaka' (the one who decides) — a man who views politics as simply another market to dominate.",
    traits: { aggression: 55, loyalty: 40, greed: 85, visibility: 40 },
    disposition: "neutral",
    dealStyle: "contract",
    interests: [
      "Manufacturing sector protection",
      "SE special economic zones",
      "Import duty on competing auto parts",
      "Onitsha port development",
    ],
    stable: {
      governors: ["Anambra"],
      legislativeBloc: { house: 6, senate: 2 },
      cabinetCandidates: ["Trade Minister nominee"],
      diplomaticInterests: ["amb-china", "amb-india"],
      directorInterests: ["director-standards-organisation", "director-export-promotion"],
      traditionalRulerAllies: ["obi-onitsha", "igwe-nnewi"],
      connections: [
        {
          entityType: "business",
          description: "Okonkwo Industries employs 8,000 workers — major SE economic force",
          effect: [{ target: "macroEconomy", delta: 4 }],
          revealed: true,
        },
        {
          entityType: "governor",
          description: "Anambra governor's industrial policy shaped by Okonkwo interests",
          effect: [{ target: "approval", delta: 2 }],
          revealed: true,
        },
        {
          entityType: "legislator-bloc",
          description: "Funds SE legislators who champion manufacturing-friendly policies",
          effect: [{ target: "politicalCapital", delta: 3 }],
          revealed: true,
        },
        {
          entityType: "cabinet",
          description: "Wants Trade Ministry under someone who will protect local manufacturing",
          effect: [{ target: "factionGrievance", delta: 2 }],
          revealed: false,
        },
        {
          entityType: "media",
          description: "Sponsors business journalism that frames SE industry positively",
          effect: [{ target: "trust", delta: 2 }],
          revealed: false,
        },
      ],
    },
    escalationStage: 0,
    favourDebt: 0,
    activeContracts: [],
    neutralized: false,
    influenceScore: 74,
  },
  {
    id: "gf-se-eze",
    name: "Chief Nnamdi Eze",
    archetype: "regional-strongman",
    zone: "SE",
    description:
      "A former senator and Igbo nationalist who channels the SE's longstanding grievances about marginalization into political leverage. Commands the loyalty of town unions, age-grade associations, and diaspora organizations across Igboland. His rallies draw tens of thousands and his rhetoric about 'Igbo fair share' resonates deeply.",
    traits: { aggression: 80, loyalty: 60, greed: 40, visibility: 75 },
    disposition: "cold",
    dealStyle: "favour-bank",
    interests: [
      "SE presidency rotation",
      "Igbo marginalization redress",
      "SE infrastructure rehabilitation",
      "Biafra war reparations dialogue",
    ],
    stable: {
      governors: ["Imo"],
      legislativeBloc: { house: 8, senate: 3 },
      cabinetCandidates: [],
      militaryInterests: ["chief-police-force"],
      traditionalRulerAllies: ["obi-onitsha", "igwe-orlu"],
      connections: [
        {
          entityType: "street",
          description: "Commands loyalty of town unions and age-grade associations across SE",
          effect: [{ target: "stability", delta: -5 }],
          revealed: true,
        },
        {
          entityType: "legislator-bloc",
          description: "SE legislators aligned with Igbo nationalist agenda follow his lead",
          effect: [{ target: "politicalCapital", delta: 4 }],
          revealed: true,
        },
        {
          entityType: "governor",
          description: "Imo governor maintains alliance to keep grassroots support",
          effect: [{ target: "partyLoyalty", delta: 3 }],
          revealed: true,
        },
        {
          entityType: "media",
          description: "Igbo diaspora media and social networks amplify his messaging globally",
          effect: [{ target: "outrage", delta: 6 }],
          revealed: false,
        },
        {
          entityType: "business",
          description: "Diaspora remittance networks fund his political activities",
          effect: [{ target: "macroEconomy", delta: 1 }],
          revealed: false,
        },
      ],
    },
    escalationStage: 0,
    favourDebt: 0,
    activeContracts: [],
    neutralized: false,
    influenceScore: 71,
  },
  {
    id: "gf-se-nwosu",
    name: "Barr. Chidinma Nwosu",
    archetype: "media-mogul",
    zone: "SE",
    description:
      "A lawyer-turned-media entrepreneur from Abia who built a digital media empire targeting the Igbo diaspora. Her platforms reach millions in the UK, US, and across West Africa. She shapes narratives about SE politics for both domestic and international audiences, making her a crucial ally — or a devastating enemy — for any administration.",
    traits: { aggression: 50, loyalty: 45, greed: 55, visibility: 70 },
    disposition: "neutral",
    dealStyle: "contract",
    interests: [
      "Digital media regulation",
      "Diaspora voting rights",
      "Press freedom legislation",
      "SE narrative in national discourse",
    ],
    stable: {
      governors: [],
      legislativeBloc: { house: 3, senate: 1 },
      cabinetCandidates: ["Communication Minister nominee"],
      directorInterests: ["director-communications-commission", "director-it-development"],
      diplomaticInterests: ["amb-usa", "amb-uk"],
      connections: [
        {
          entityType: "media",
          description: "Digital platforms reach 5 million Igbo diaspora readers weekly",
          effect: [{ target: "trust", delta: -4 }],
          revealed: true,
        },
        {
          entityType: "street",
          description: "Diaspora advocacy network can organize international pressure campaigns",
          effect: [{ target: "outrage", delta: 5 }],
          revealed: true,
        },
        {
          entityType: "legislator-bloc",
          description: "Younger SE legislators rely on her platforms for constituency outreach",
          effect: [{ target: "politicalCapital", delta: 2 }],
          revealed: true,
        },
        {
          entityType: "business",
          description: "Ad-tech business gives her data on political sentiment across SE",
          effect: [{ target: "approval", delta: -2 }],
          revealed: false,
        },
        {
          entityType: "cabinet",
          description: "Advocates for SE tech-savvy appointees in communications",
          effect: [{ target: "factionGrievance", delta: 2 }],
          revealed: false,
        },
      ],
    },
    escalationStage: 0,
    favourDebt: 0,
    activeContracts: [],
    neutralized: false,
    influenceScore: 62,
  },

  // ============================================================
  // SOUTH-SOUTH (SS) — 4 godfathers
  // ============================================================
  {
    id: "gf-ss-amaechi",
    name: "Chief Tonye Amaechi",
    archetype: "regional-strongman",
    zone: "SS",
    description:
      "An Ikwerre strongman from Rivers State who controls Niger Delta politics through a combination of oil money, militant connections, and grassroots organization. Former militant leader turned politician, he straddles the line between legitimate politics and the shadowy world of creek warlords. His phone calls can start or stop pipeline vandalism.",
    traits: { aggression: 85, loyalty: 55, greed: 70, visibility: 60 },
    disposition: "neutral",
    dealStyle: "favour-bank",
    interests: [
      "Niger Delta amnesty program continuation",
      "Oil-producing community compensation",
      "SS political representation",
      "Pipeline surveillance contracts",
    ],
    stable: {
      governors: ["Rivers"],
      legislativeBloc: { house: 8, senate: 3 },
      cabinetCandidates: ["Niger Delta Minister nominee"],
      militaryInterests: ["chief-police-force", "chief-naval-force"],
      directorInterests: ["director-petroleum-corporation"],
      traditionalRulerAllies: ["amanyanabo-bonny", "pere-gbaramatu"],
      connections: [
        {
          entityType: "street",
          description: "Former militant networks who can disrupt or protect oil infrastructure",
          effect: [{ target: "stability", delta: -8 }],
          revealed: true,
        },
        {
          entityType: "governor",
          description: "Rivers governor relies on his grassroots muscle for political survival",
          effect: [{ target: "partyLoyalty", delta: 4 }],
          revealed: true,
        },
        {
          entityType: "business",
          description: "Pipeline surveillance contracts generate massive revenue streams",
          effect: [{ target: "macroEconomy", delta: -3 }],
          revealed: true,
        },
        {
          entityType: "legislator-bloc",
          description: "SS legislators fear his capacity to destabilize their constituencies",
          effect: [{ target: "politicalCapital", delta: 4 }],
          revealed: false,
        },
        {
          entityType: "cabinet",
          description: "Demands Niger Delta Ministry and NDDC board positions",
          effect: [{ target: "factionGrievance", delta: 5 }],
          revealed: false,
        },
      ],
    },
    escalationStage: 0,
    favourDebt: 0,
    activeContracts: [],
    neutralized: false,
    influenceScore: 83,
  },
  {
    id: "gf-ss-obaseki",
    name: "Comrade Osaro Obaseki",
    archetype: "labour-civil",
    zone: "SS",
    description:
      "An Edo-born civil society leader who cut his teeth organizing oil workers' unions before expanding into environmental activism. Leads a coalition of Niger Delta civil society organizations that monitors oil spills, government accountability, and human rights. His reports are cited by international organizations and his campaigns have forced policy reversals.",
    traits: { aggression: 65, loyalty: 70, greed: 20, visibility: 80 },
    disposition: "friendly",
    dealStyle: "favour-bank",
    interests: [
      "Environmental remediation in Niger Delta",
      "Oil spill compensation enforcement",
      "Workers' safety regulations",
      "Civil society space protection",
    ],
    stable: {
      governors: ["Edo"],
      legislativeBloc: { house: 4, senate: 1 },
      cabinetCandidates: ["Environment Minister nominee"],
      directorInterests: ["director-environmental-standards", "director-petroleum-corporation"],
      traditionalRulerAllies: ["oba-benin"],
      connections: [
        {
          entityType: "street",
          description: "Coalition of 50+ Niger Delta CSOs that can mobilize communities",
          effect: [{ target: "outrage", delta: 6 }],
          revealed: true,
        },
        {
          entityType: "media",
          description: "International media contacts amplify Niger Delta environmental stories",
          effect: [{ target: "trust", delta: -3 }],
          revealed: true,
        },
        {
          entityType: "governor",
          description: "Edo governor maintains a working relationship to avoid CSO scrutiny",
          effect: [{ target: "approval", delta: 2 }],
          revealed: true,
        },
        {
          entityType: "legislator-bloc",
          description: "Environmentally-conscious legislators use his data for bills",
          effect: [{ target: "politicalCapital", delta: 2 }],
          revealed: false,
        },
        {
          entityType: "business",
          description: "International donor funding gives him independence from government",
          effect: [{ target: "stability", delta: -2 }],
          revealed: false,
        },
      ],
    },
    escalationStage: 0,
    favourDebt: 0,
    activeContracts: [],
    neutralized: false,
    influenceScore: 60,
  },
  {
    id: "gf-ss-akintoye",
    name: "Chief Mercy Akintoye",
    archetype: "media-mogul",
    zone: "SS",
    description:
      "An Itsekiri media entrepreneur who built the Niger Delta's most influential broadcast network. Her TV and radio stations are the primary news source for millions across the SS. Started as a journalist covering the Niger Delta crisis and transformed that expertise into a media empire that shapes how Nigeria sees the region.",
    traits: { aggression: 45, loyalty: 50, greed: 50, visibility: 75 },
    disposition: "neutral",
    dealStyle: "contract",
    interests: [
      "Broadcast licensing reform",
      "Niger Delta positive narrative",
      "Media industry investment",
      "SS cultural representation",
    ],
    stable: {
      governors: ["Delta"],
      legislativeBloc: { house: 4, senate: 1 },
      cabinetCandidates: ["Information Minister nominee"],
      directorInterests: ["director-broadcasting-commission"],
      diplomaticInterests: ["amb-south-africa", "amb-ghana"],
      traditionalRulerAllies: ["olu-warri"],
      connections: [
        {
          entityType: "media",
          description: "Delta Broadcasting Network is the dominant media voice in the SS",
          effect: [{ target: "trust", delta: -5 }],
          revealed: true,
        },
        {
          entityType: "governor",
          description: "Delta governor depends on her network for public communication",
          effect: [{ target: "approval", delta: 3 }],
          revealed: true,
        },
        {
          entityType: "street",
          description: "Radio stations shape public opinion in remote Niger Delta communities",
          effect: [{ target: "outrage", delta: 4 }],
          revealed: true,
        },
        {
          entityType: "legislator-bloc",
          description: "SS legislators seek airtime on her platforms for constituency visibility",
          effect: [{ target: "politicalCapital", delta: 2 }],
          revealed: false,
        },
        {
          entityType: "business",
          description: "Advertising revenue from oil companies gives her corporate leverage",
          effect: [{ target: "macroEconomy", delta: 1 }],
          revealed: false,
        },
      ],
    },
    escalationStage: 0,
    favourDebt: 0,
    activeContracts: [],
    neutralized: false,
    influenceScore: 66,
  },

  // ============================================================
  // Additional profiles for archetype coverage
  // ============================================================
  {
    id: "gf-ne-yusuf",
    name: "Gen. Mohammed Yusuf (rtd)",
    archetype: "military-elder",
    zone: "NE",
    description:
      "A retired brigadier general from Bauchi who served as theatre commander during counter-insurgency operations. His knowledge of the NE security architecture is unmatched, and serving commanders still seek his counsel. Frustrated by what he sees as civilian mismanagement of the insurgency, he believes only military discipline can save the region.",
    traits: { aggression: 70, loyalty: 60, greed: 35, visibility: 35 },
    disposition: "neutral",
    dealStyle: "favour-bank",
    interests: [
      "Counter-insurgency strategy",
      "Military welfare improvements",
      "NE security architecture reform",
      "Veterans affairs",
    ],
    stable: {
      governors: [],
      legislativeBloc: { house: 3, senate: 1 },
      cabinetCandidates: ["Defence Minister nominee"],
      militaryInterests: ["chief-army-force", "chief-defence-force"],
      directorInterests: ["director-defence-industries"],
      traditionalRulerAllies: ["emir-bauchi"],
      connections: [
        {
          entityType: "cabinet",
          description: "Serving officers in theatre command consult him on operations",
          effect: [{ target: "stability", delta: 4 }],
          revealed: true,
        },
        {
          entityType: "street",
          description: "Network of veterans who can be mobilized for political purposes",
          effect: [{ target: "approval", delta: 2 }],
          revealed: true,
        },
        {
          entityType: "business",
          description: "Connected to security contractors operating in the NE",
          effect: [{ target: "macroEconomy", delta: 1 }],
          revealed: false,
        },
        {
          entityType: "legislator-bloc",
          description: "Defence committee members value his security briefings",
          effect: [{ target: "politicalCapital", delta: 2 }],
          revealed: true,
        },
        {
          entityType: "media",
          description: "Security analysts in his network shape media coverage of the insurgency",
          effect: [{ target: "trust", delta: 2 }],
          revealed: false,
        },
      ],
    },
    escalationStage: 0,
    favourDebt: 0,
    activeContracts: [],
    neutralized: false,
    influenceScore: 58,
  },
];
