// client/src/lib/houseRepPool.ts
// Nigerian House of Representatives — 360 reps (100 hand-crafted + 260 generated)
// Seat distribution: ADU 145, PFC 80, NDM 45, NSF 35, TLA 20, HDP 15, PAP 12, UPA 8

import { generateCharacterPool } from "./characterPoolGenerator";
import { GEOPOLITICAL_ZONES, getZoneForState } from "./zones";
import { seededRandom, pick } from "./seededRandom";

export interface HouseRep {
  name: string;
  state: string;
  zone: string;
  party: string;
  constituency: string; // e.g., "Ikeja Federal Constituency"
  age: number;
  gender: "Male" | "Female";
  religion: string;
  ethnicity: string;
  avatar: string;
  traits: string[];
  bio: string;
  education: string;
  competence: number;
  influence: number;
  loyalty: number;
  isHandCrafted: boolean;
}

export const HOUSE_REP_TRAITS = [
  "Committee Member", "Floor Speaker", "Constituency Champion", "First-Term Rep",
  "Former Councillor", "Business Owner", "Legal Practitioner", "Party Loyalist",
  "Independent Voice", "Cross-Party Builder", "Media Savvy", "Grassroots Politician",
  "Budget Watchdog", "Security Advocate", "Education Champion", "Health Crusader",
  "Infrastructure Focused", "Anti-Corruption Fighter", "Youth Representative", "Women's Voice",
  "Diaspora Representative", "Agricultural Champion", "Trade Unionist", "Community Leader",
];

// ── Party seat distribution for House ─────────────────────────────────────
// Total: 360 seats
const HOUSE_PARTY_SEATS: Record<string, number> = {
  ADU: 145, PFC: 80, NDM: 45, NSF: 35, TLA: 20, HDP: 15, PAP: 12, UPA: 8,
};

// Zone-weighted party pools
const PARTY_ZONE_WEIGHTS: Record<string, string[]> = {
  NW: ["ADU","ADU","ADU","PFC","ADU","NDM","NSF","ADU","PFC","TLA","HDP","ADU"],
  NE: ["ADU","ADU","PFC","ADU","NDM","NSF","PFC","ADU","TLA","HDP","ADU","NDM"],
  NC: ["ADU","PFC","ADU","NDM","NSF","PFC","ADU","HDP","TLA","PAP","ADU","PFC"],
  SW: ["PFC","ADU","NDM","PFC","NSF","TLA","ADU","HDP","PAP","NDM","PFC","TLA"],
  SE: ["NDM","PFC","NSF","ADU","TLA","NDM","HDP","PAP","PFC","NSF","NDM","ADU"],
  SS: ["PFC","NDM","ADU","NSF","PFC","TLA","NDM","HDP","PAP","UPA","PFC","ADU"],
};

// ── 100 Hand-crafted House Reps ────────────────────────────────────────────
// NW: 20, NE: 15, NC: 18, SW: 18, SE: 14, SS: 15

export const HANDCRAFTED_HOUSE_REPS: HouseRep[] = [

  // ── NORTH-WEST (20) ───────────────────────────────────────────────────────

  {
    name: "Hon. Usman Garba Katsina",
    state: "Katsina",
    zone: "NW",
    party: "ADU",
    constituency: "Katsina North Federal Constituency",
    age: 48,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "UG",
    traits: ["Grassroots Politician", "Infrastructure Focused", "Party Loyalist"],
    bio: "A former local government chairman who won his House seat on the promise of completing the Katsina-Dutsinma road. Three years on he has secured ₦4.2 billion in constituency projects and holds the record for the most ministerial summons by a House committee in one session.",
    education: "Katsina Polytechnic (HND Business Admin), BUK (PGD Public Admin)",
    competence: 66,
    influence: 58,
    loyalty: 74,
    isHandCrafted: true,
  },
  {
    name: "Hon. Amina Dantsoho",
    state: "Katsina",
    zone: "NW",
    party: "ADU",
    constituency: "Katsina South Federal Constituency",
    age: 42,
    gender: "Female",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "AD",
    traits: ["Women's Voice", "Education Champion", "Media Savvy"],
    bio: "A schoolteacher who organised Katsina's first Girls' Science Fair and ran for the House on an education reform platform. Her quiet persistence in the House Committee on Basic Education has produced three amendments strengthening compulsory enrolment law.",
    education: "BUK Kano (Education), University of Lagos (MEd)",
    competence: 65,
    influence: 55,
    loyalty: 69,
    isHandCrafted: true,
  },
  {
    name: "Hon. Murtala Yusuf Kano",
    state: "Kano",
    zone: "NW",
    party: "ADU",
    constituency: "Dala Federal Constituency",
    age: 55,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "MY",
    traits: ["Committee Member", "Trade Unionist", "Cross-Party Builder"],
    bio: "A former president of the National Market Traders Association whose network covers every major market in northern Nigeria. His Commodity Markets Regulation Bill passed the House on first reading with unprecedented support from both sides of the aisle.",
    education: "Kano State Polytechnic (Business Studies), Bayero University (BBA)",
    competence: 64,
    influence: 63,
    loyalty: 65,
    isHandCrafted: true,
  },
  {
    name: "Hon. Ibrahim Shehu-Kano",
    state: "Kano",
    zone: "NW",
    party: "PFC",
    constituency: "Kano Municipal Federal Constituency",
    age: 50,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "IS",
    traits: ["Anti-Corruption Fighter", "Budget Watchdog", "Independent Voice"],
    bio: "An accountant who defeated a three-term incumbent by publishing spreadsheets showing how constituency funds had been misapplied. His forensic committee work on the House Appropriations Committee has won him admirers across party lines and enemies among the old guard.",
    education: "Bayero University (Accounting), ICAN Fellow",
    competence: 72,
    influence: 60,
    loyalty: 42,
    isHandCrafted: true,
  },
  {
    name: "Hon. Lawal Bello Kaduna",
    state: "Kaduna",
    zone: "NW",
    party: "ADU",
    constituency: "Kaduna Central Federal Constituency",
    age: 47,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "LB",
    traits: ["Security Advocate", "Constituency Champion", "First-Term Rep"],
    bio: "A former police divisional officer who ran for the House to address Kaduna's chronic insecurity from the inside. He has used procedural tools to force four emergency debates on security funding into the House calendar in his first term.",
    education: "ABU Zaria (Criminology), Nigeria Police Academy (Advanced Command)",
    competence: 68,
    influence: 57,
    loyalty: 64,
    isHandCrafted: true,
  },
  {
    name: "Hon. Mrs. Hannatu Garba-Kaduna",
    state: "Kaduna",
    zone: "NW",
    party: "ADU",
    constituency: "Kaduna North Federal Constituency",
    age: 44,
    gender: "Female",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "HG",
    traits: ["Women's Voice", "Health Crusader", "Community Leader"],
    bio: "A community midwife who trained 800 traditional birth attendants across Kaduna's rural wards before entering politics. Her Private Member Bill on Maternal Health Emergency Response has received glowing endorsements from the WHO and the UN Population Fund.",
    education: "Kaduna State University (Nursing), ABU Zaria (BSc Public Health)",
    competence: 64,
    influence: 54,
    loyalty: 70,
    isHandCrafted: true,
  },
  {
    name: "Hon. Sani Abubakar-Sokoto",
    state: "Sokoto",
    zone: "NW",
    party: "ADU",
    constituency: "Sokoto East Federal Constituency",
    age: 52,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Fulani",
    avatar: "SA",
    traits: ["Agricultural Champion", "Infrastructure Focused", "Party Loyalist"],
    bio: "A livestock and dairy cooperative leader who won by mobilising Fulani pastoralist communities who had never voted in a federal election. His constituency has seen 14 boreholes, 2 solar mini-grids, and a veterinary clinic built through his office's intervention.",
    education: "Usmanu Danfodiyo University (Animal Science), NIPSS Kuru (Public Policy)",
    competence: 62,
    influence: 56,
    loyalty: 75,
    isHandCrafted: true,
  },
  {
    name: "Hon. Binta Tambari",
    state: "Sokoto",
    zone: "NW",
    party: "NSF",
    constituency: "Sokoto North Federal Constituency",
    age: 40,
    gender: "Female",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "BT",
    traits: ["Youth Representative", "Anti-Corruption Fighter", "Media Savvy"],
    bio: "The youngest representative from Sokoto who ran against a sitting two-term member of the same party on an anti-godfatherism platform. Her weekly constituency account reports — broadcast on Sokoto Radio — have set a new standard for House member transparency.",
    education: "Usmanu Danfodiyo University (Mass Communication), London (MA Journalism)",
    competence: 63,
    influence: 53,
    loyalty: 46,
    isHandCrafted: true,
  },
  {
    name: "Hon. Kabir Wada-Zamfara",
    state: "Zamfara",
    zone: "NW",
    party: "ADU",
    constituency: "Gusau Federal Constituency",
    age: 56,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "KW",
    traits: ["Security Advocate", "Grassroots Politician", "Cross-Party Builder"],
    bio: "A Zamfara trader-politician who has organised three cross-partisan peace delegations to meet banditry kingpins in the bush. His informal shuttle diplomacy has produced two local ceasefires that preceded the government's formal Zamfara Security Dialogue.",
    education: "Sokoto State Polytechnic (Business Studies)",
    competence: 58,
    influence: 62,
    loyalty: 60,
    isHandCrafted: true,
  },
  {
    name: "Hon. Mustapha Aliyu-Zamfara",
    state: "Zamfara",
    zone: "NW",
    party: "NDM",
    constituency: "Kaura Namoda Federal Constituency",
    age: 49,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "MA",
    traits: ["Agricultural Champion", "Anti-Corruption Fighter", "Budget Watchdog"],
    bio: "An opposition rep who has built his career on exposing fake agricultural input distributions in Zamfara. His committee work documented ₦3.8 billion in phantom fertiliser purchases, leading to a presidential panel of inquiry.",
    education: "Bayero University Kano (Agriculture), University of Ibadan (MSc)",
    competence: 69,
    influence: 58,
    loyalty: 44,
    isHandCrafted: true,
  },
  {
    name: "Hon. Bashir Yusuf-Jigawa",
    state: "Jigawa",
    zone: "NW",
    party: "ADU",
    constituency: "Dutse Federal Constituency",
    age: 46,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "BY",
    traits: ["Infrastructure Focused", "Education Champion", "Party Loyalist"],
    bio: "A civil engineer who built his reputation rehabilitating rural roads in Jigawa before his first election. Now sits on the House Committee on Works and has guided ₦7 billion in road contracts to Jigawa constituencies using project management skills rare in the legislature.",
    education: "ABU Zaria (Civil Engineering), University of Leeds (MSc Infrastructure Management)",
    competence: 70,
    influence: 59,
    loyalty: 72,
    isHandCrafted: true,
  },
  {
    name: "Hon. Hauwa Babangida-Jigawa",
    state: "Jigawa",
    zone: "NW",
    party: "ADU",
    constituency: "Birnin Kudu Federal Constituency",
    age: 43,
    gender: "Female",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "HB",
    traits: ["Health Crusader", "Community Leader", "First-Term Rep"],
    bio: "A pharmacist who ran a mobile drug dispensary in rural Jigawa for a decade before entering politics. Her Private Member Bill on Rural Pharmacy Access passed second reading with 247 votes — the biggest single-day majority in the House in three years.",
    education: "BUK Kano (Pharmacy), University of Nottingham (MPharm)",
    competence: 66,
    influence: 55,
    loyalty: 68,
    isHandCrafted: true,
  },
  {
    name: "Hon. Suleiman Dantata-Kano",
    state: "Kano",
    zone: "NW",
    party: "ADU",
    constituency: "Gwale Federal Constituency",
    age: 58,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "SD",
    traits: ["Business Owner", "Floor Speaker", "Diaspora Representative"],
    bio: "A textile and commodities merchant who divides his time between Kano and Dubai, where his trading house employs 1,200 Nigerian expatriates. His contributions to the ECOWAS Trade Facilitation debates in the House draw on real-time commercial intelligence from across West Africa.",
    education: "Bayero University (Economics), University of Dubai (MBA)",
    competence: 67,
    influence: 65,
    loyalty: 62,
    isHandCrafted: true,
  },
  {
    name: "Hon. Yakubu Musa-Kebbi",
    state: "Kebbi",
    zone: "NW",
    party: "ADU",
    constituency: "Birnin Kebbi Federal Constituency",
    age: 53,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "YM",
    traits: ["Agricultural Champion", "Constituency Champion", "Party Loyalist"],
    bio: "A fish farmer who lobbied the Federal Ministry of Agriculture for seven years to get the Lake Kainji Aquaculture Development Programme funded. His patience paid off when the ₦12 billion programme passed in the last supplementary budget.",
    education: "Usmanu Danfodiyo University (Fisheries), FUTO Owerri (PGD Aquaculture)",
    competence: 61,
    influence: 55,
    loyalty: 74,
    isHandCrafted: true,
  },
  {
    name: "Hon. Abubakar Liman-Kano",
    state: "Kano",
    zone: "NW",
    party: "PFC",
    constituency: "Tarauni Federal Constituency",
    age: 45,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "AL",
    traits: ["Legal Practitioner", "Anti-Corruption Fighter", "Independent Voice"],
    bio: "A former EFCC prosecutor who crossed to private practice before contesting under PFC. His committee interrogations of ministry officials are aired live on television by popular demand — he is the most-watched House member on YouTube in Nigeria.",
    education: "ABU Zaria (LLB), Nigerian Law School (BL), University of London (LLM)",
    competence: 75,
    influence: 63,
    loyalty: 45,
    isHandCrafted: true,
  },
  {
    name: "Hon. Zainab Waziri-Sokoto",
    state: "Sokoto",
    zone: "NW",
    party: "ADU",
    constituency: "Wamakko Federal Constituency",
    age: 39,
    gender: "Female",
    religion: "Islam",
    ethnicity: "Fulani",
    avatar: "ZW",
    traits: ["Youth Representative", "Education Champion", "Women's Voice"],
    bio: "A 39-year-old sociology lecturer who contested on a platform of tackling child marriage and won by a stunning margin in a constituency that had never elected a woman. Her coalition of women's groups and youth organisations has become a template for other female aspirants.",
    education: "Usmanu Danfodiyo University (Sociology), Edinburgh (MSc Gender Studies)",
    competence: 64,
    influence: 57,
    loyalty: 67,
    isHandCrafted: true,
  },
  {
    name: "Hon. Haruna Idris-Kaduna",
    state: "Kaduna",
    zone: "NW",
    party: "NDM",
    constituency: "Zaria Federal Constituency",
    age: 51,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "HI",
    traits: ["Cross-Party Builder", "Community Leader", "Security Advocate"],
    bio: "A former community mediator who has facilitated 23 inter-ethnic peace agreements in Zaria. Running on NDM's reform ticket, he beat the ADU incumbent by positioning himself as above sectarian politics — a label he has jealously guarded since his arrival in Abuja.",
    education: "ABU Zaria (Political Science), Bradford University (MSc Peace Studies)",
    competence: 68,
    influence: 61,
    loyalty: 48,
    isHandCrafted: true,
  },
  {
    name: "Hon. Farouk Dandago",
    state: "Kano",
    zone: "NW",
    party: "ADU",
    constituency: "Nassarawa Federal Constituency",
    age: 54,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "FD",
    traits: ["Floor Speaker", "Trade Unionist", "Party Loyalist"],
    bio: "A former Kano State civil servants' union president who commands deep loyalty among the public sector workforce. On the floor of the House he is known for stirring oratory that can shift the mood of a debate within three minutes.",
    education: "Bayero University (Public Administration), NIPSS Kuru",
    competence: 65,
    influence: 64,
    loyalty: 76,
    isHandCrafted: true,
  },
  {
    name: "Hon. Rukayya Bello-Zamfara",
    state: "Zamfara",
    zone: "NW",
    party: "ADU",
    constituency: "Talata-Mafara Federal Constituency",
    age: 41,
    gender: "Female",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "RB",
    traits: ["Women's Voice", "Health Crusader", "Constituency Champion"],
    bio: "A community health extension worker who turned to politics after watching three of her patients die from preventable diseases without referral transport. Her Maternal and Child Health Referral Bill — providing government ambulances to rural communities — passed second reading.",
    education: "UDUS Sokoto (Community Health), NIPSS (Health Policy)",
    competence: 62,
    influence: 53,
    loyalty: 71,
    isHandCrafted: true,
  },
  {
    name: "Hon. Mohammed Dangyadi",
    state: "Kebbi",
    zone: "NW",
    party: "TLA",
    constituency: "Argungu Federal Constituency",
    age: 47,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "MD",
    traits: ["Independent Voice", "Agricultural Champion", "Media Savvy"],
    bio: "A rice mill owner whose Liberty Alliance membership surprised Argungu voters, but his independent-minded approach to constituency service has converted critics. He has published a monthly 'constituency report card' that other reps are now being pressured to replicate.",
    education: "UDUS Sokoto (Agribusiness), Lagos Business School (Executive MBA)",
    competence: 64,
    influence: 57,
    loyalty: 40,
    isHandCrafted: true,
  },

  // ── NORTH-EAST (15) ───────────────────────────────────────────────────────

  {
    name: "Hon. Modu Bukar-Borno",
    state: "Borno",
    zone: "NE",
    party: "ADU",
    constituency: "Maiduguri Metropolitan Federal Constituency",
    age: 59,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Kanuri",
    avatar: "MB",
    traits: ["Security Advocate", "Veteran Lawmaker", "Community Leader"],
    bio: "A three-term representative who has sat on every House security committee since his first election. Survived an assassination attempt by Boko Haram in 2015 and returned to Maiduguri ten days later to chair a ward security meeting. His fearlessness is legend in the North-East.",
    education: "University of Maiduguri (Political Science), National Defence College",
    competence: 72,
    influence: 68,
    loyalty: 70,
    isHandCrafted: true,
  },
  {
    name: "Hon. Fatima Al-Amin-Borno",
    state: "Borno",
    zone: "NE",
    party: "ADU",
    constituency: "Bama Federal Constituency",
    age: 45,
    gender: "Female",
    religion: "Islam",
    ethnicity: "Kanuri",
    avatar: "FA",
    traits: ["Health Crusader", "Women's Voice", "Constituency Champion"],
    bio: "An INGO programme coordinator who managed IDP nutrition programmes across Borno for seven years before contesting the House seat. Her Humanitarian Access to Education Bill has transformed how the federal government funds schooling in conflict-affected communities.",
    education: "University of Maiduguri (Nutrition), University of Sussex (MA Development Studies)",
    competence: 68,
    influence: 58,
    loyalty: 66,
    isHandCrafted: true,
  },
  {
    name: "Hon. Tanko Yerima",
    state: "Adamawa",
    zone: "NE",
    party: "PFC",
    constituency: "Yola North Federal Constituency",
    age: 51,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Fulani",
    avatar: "TY",
    traits: ["Anti-Corruption Fighter", "Legal Practitioner", "Independent Voice"],
    bio: "A law lecturer who moonlighted as a pro-bono defence counsel for persecuted minority farmers before entering politics. Has filed six private member bills since entering the House, more than any other first-term rep from Adamawa.",
    education: "University of Jos (LLB), Ahmadu Bello University (LLM)",
    competence: 71,
    influence: 58,
    loyalty: 43,
    isHandCrafted: true,
  },
  {
    name: "Hon. Hajiya Maryam Tukur-Bauchi",
    state: "Bauchi",
    zone: "NE",
    party: "ADU",
    constituency: "Bauchi Central Federal Constituency",
    age: 48,
    gender: "Female",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "MT",
    traits: ["Education Champion", "Women's Voice", "Party Loyalist"],
    bio: "A headmistress who became local government councillor, then state commissioner, then federal rep — a steady ascent built on genuine constituency service. Her advocacy has produced a dedicated education line in the federal budget for conflict-affected North-East states.",
    education: "Abubakar Tafawa Balewa University (Education), ABU Zaria (MEd)",
    competence: 65,
    influence: 57,
    loyalty: 73,
    isHandCrafted: true,
  },
  {
    name: "Hon. Gambo Ali-Gombe",
    state: "Gombe",
    zone: "NE",
    party: "ADU",
    constituency: "Gombe North Federal Constituency",
    age: 53,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "GA",
    traits: ["Infrastructure Focused", "Agricultural Champion", "Party Loyalist"],
    bio: "A contract civil engineer whose campaign promise of building a modern abattoir in Gombe has become the most-tracked federal constituency project in the state. Now chairs the sub-committee on rural infrastructure and has delivered four of seven promised projects.",
    education: "ATBU Bauchi (Civil Engineering), ABU Zaria (PGD Project Management)",
    competence: 65,
    influence: 57,
    loyalty: 72,
    isHandCrafted: true,
  },
  {
    name: "Hon. Rev. Titus Mangai-Taraba",
    state: "Taraba",
    zone: "NE",
    party: "PFC",
    constituency: "Jalingo Federal Constituency",
    age: 56,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Tiv",
    avatar: "TM",
    traits: ["Cross-Party Builder", "Security Advocate", "Community Leader"],
    bio: "A retired Anglican reverend who mediated the Taraba farmer-herder conflicts from a church hall for 12 years before contesting. His moral authority crosses ethnic lines and he chairs an informal interfaith peace council that includes Muslim imams and traditional rulers.",
    education: "University of Jos (Theology), Trinity College Bristol (MA Reconciliation Studies)",
    competence: 66,
    influence: 65,
    loyalty: 48,
    isHandCrafted: true,
  },
  {
    name: "Hon. Adama Buba-Taraba",
    state: "Taraba",
    zone: "NE",
    party: "NDM",
    constituency: "Wukari Federal Constituency",
    age: 44,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Tiv",
    avatar: "AB",
    traits: ["Agricultural Champion", "Budget Watchdog", "Anti-Corruption Fighter"],
    bio: "A cocoa and sesame farmer who organised Taraba's first agricultural cooperative export venture, generating $3 million in foreign exchange. His questioning at a Ministry of Agriculture budget hearing exposed that 60% of the state's extension services allocation had been unspent for three years.",
    education: "University of Agriculture Makurdi (Agriculture), Wageningen (MSc Agribusiness)",
    competence: 67,
    influence: 56,
    loyalty: 46,
    isHandCrafted: true,
  },
  {
    name: "Hon. Bukar Ibrahim-Yobe",
    state: "Yobe",
    zone: "NE",
    party: "ADU",
    constituency: "Damaturu Federal Constituency",
    age: 60,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Kanuri",
    avatar: "BI",
    traits: ["Veteran Lawmaker", "Security Advocate", "Party Loyalist"],
    bio: "A two-term rep who has survived constituency elections even as Boko Haram temporarily displaced him from his home in 2014. His resilience is matched by his legislative record — he has passed 11 constituency-specific motions in the current assembly, the most in the North-East.",
    education: "University of Maiduguri (Economics), NIPSS Kuru",
    competence: 66,
    influence: 61,
    loyalty: 75,
    isHandCrafted: true,
  },
  {
    name: "Hon. Aishatu Lawan-Yobe",
    state: "Yobe",
    zone: "NE",
    party: "ADU",
    constituency: "Potiskum Federal Constituency",
    age: 46,
    gender: "Female",
    religion: "Islam",
    ethnicity: "Kanuri",
    avatar: "AL",
    traits: ["Health Crusader", "Women's Voice", "First-Term Rep"],
    bio: "A nurse who ran six mobile clinics across Yobe rural wards from her own NGO before entering politics. Pushed successfully for the inclusion of Yobe communities in the national meningitis vaccination rollout — a campaign credited with preventing 6,000 deaths.",
    education: "University of Maiduguri (Nursing), Liverpool School of Tropical Medicine (MSc)",
    competence: 63,
    influence: 55,
    loyalty: 68,
    isHandCrafted: true,
  },
  {
    name: "Hon. Sulaiman Abubakar-Gombe",
    state: "Gombe",
    zone: "NE",
    party: "NSF",
    constituency: "Billiri Federal Constituency",
    age: 49,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Tiv",
    avatar: "SA",
    traits: ["Anti-Corruption Fighter", "Education Champion", "Independent Voice"],
    bio: "An opposition rep who made headlines by tabling evidence that Billiri's federal school grant had been diverted to a shell company owned by a state party official. The resulting prosecution has made him a hero in his constituency and a marked man at party headquarters.",
    education: "University of Jos (Education), Leeds University (MA Education Policy)",
    competence: 68,
    influence: 58,
    loyalty: 40,
    isHandCrafted: true,
  },
  {
    name: "Hon. Bashir Kyari-Borno",
    state: "Borno",
    zone: "NE",
    party: "ADU",
    constituency: "Gwoza Federal Constituency",
    age: 52,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Kanuri",
    avatar: "BK",
    traits: ["Security Advocate", "Constituency Champion", "Grassroots Politician"],
    bio: "Gwoza was Boko Haram's proclaimed 'caliphate capital' in 2014. Kyari stayed in Nigeria, coordinated relief operations from Maiduguri and returned the moment the military reclaimed the area. His legitimacy in the constituency is unmatched by any elected official in recent North-East history.",
    education: "University of Maiduguri (Geography), NIPSS (Security Studies)",
    competence: 64,
    influence: 62,
    loyalty: 70,
    isHandCrafted: true,
  },
  {
    name: "Hon. Yakubu Pella-Adamawa",
    state: "Adamawa",
    zone: "NE",
    party: "ADU",
    constituency: "Demsa Federal Constituency",
    age: 55,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Fulani",
    avatar: "YP",
    traits: ["Agricultural Champion", "Community Leader", "Party Loyalist"],
    bio: "A cattle ranching magnate who unified disparate pastoralist groups behind a single development agenda. His Grazing Reserve Act Amendment has given settled Fulani communities legal title to land for the first time in Nigerian legislative history.",
    education: "University of Agriculture Makurdi (Animal Science), University of Ibadan (MSc)",
    competence: 65,
    influence: 60,
    loyalty: 72,
    isHandCrafted: true,
  },
  {
    name: "Hon. Dr. Grace Danladi-Bauchi",
    state: "Bauchi",
    zone: "NE",
    party: "PFC",
    constituency: "Dass Federal Constituency",
    age: 47,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Tiv",
    avatar: "GD",
    traits: ["Health Crusader", "Anti-Corruption Fighter", "Media Savvy"],
    bio: "A medical doctor who published a widely-read exposé on mortality statistics inside Bauchi General Hospital before running under the PFC platform. Chairs the House Sub-committee on Rural Health and has driven three emergency motions on meningitis outbreaks into the House record.",
    education: "Abubakar Tafawa Balewa University (Medicine), Johns Hopkins Bloomberg (MPH)",
    competence: 72,
    influence: 60,
    loyalty: 48,
    isHandCrafted: true,
  },
  {
    name: "Hon. Sani Abdullahi-Adamawa",
    state: "Adamawa",
    zone: "NE",
    party: "ADU",
    constituency: "Song Federal Constituency",
    age: 50,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Fulani",
    avatar: "SA",
    traits: ["Infrastructure Focused", "Party Loyalist", "Constituency Champion"],
    bio: "A roads contractor who entered politics after watching poor procurement practices destroy projects he had personally built. Sits on the House Works Committee and now tracks 12 ongoing road projects in Adamawa using a GPS-based monitoring app.",
    education: "Modibbo Adama University (Civil Engineering), ABU Zaria (PGD Project Evaluation)",
    competence: 65,
    influence: 55,
    loyalty: 74,
    isHandCrafted: true,
  },
  {
    name: "Hon. Hauwa Ibrahim-Borno",
    state: "Borno",
    zone: "NE",
    party: "NDM",
    constituency: "Monguno Federal Constituency",
    age: 43,
    gender: "Female",
    religion: "Islam",
    ethnicity: "Kanuri",
    avatar: "HI",
    traits: ["Women's Voice", "Youth Representative", "Anti-Corruption Fighter"],
    bio: "A first-term rep who won by 700 votes in a constituency where the opposition had never held a seat. Her digital-first campaign — run entirely on WhatsApp broadcast groups — is studied by political communications academics as a breakthrough in low-resource electioneering.",
    education: "University of Maiduguri (Computer Science), Open University (MBA Digital Management)",
    competence: 64,
    influence: 54,
    loyalty: 46,
    isHandCrafted: true,
  },

  // ── NORTH-CENTRAL (18) ────────────────────────────────────────────────────

  {
    name: "Hon. Terkura Iorhemen",
    state: "Benue",
    zone: "NC",
    party: "PFC",
    constituency: "Makurdi North Federal Constituency",
    age: 48,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Tiv",
    avatar: "TI",
    traits: ["Security Advocate", "Community Leader", "Anti-Corruption Fighter"],
    bio: "A former Tiv Youth Council president who channelled his grassroots network into a winning House campaign. His emergency motion on Benue farmer-herder killings, tabled with video evidence, forced the first ever joint session of the House and Senate security committees.",
    education: "University of Jos (Political Science), Bradford University (MA Peace Studies)",
    competence: 70,
    influence: 63,
    loyalty: 46,
    isHandCrafted: true,
  },
  {
    name: "Hon. Ngina Orduen",
    state: "Benue",
    zone: "NC",
    party: "ADU",
    constituency: "Makurdi South Federal Constituency",
    age: 44,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Tiv",
    avatar: "NO",
    traits: ["Agricultural Champion", "Women's Voice", "Education Champion"],
    bio: "A cassava processing entrepreneur who turned a Benue pilot programme into Nigeria's largest cassava value-addition project employing 4,000 women. She used the same coalition of market women to win her House seat by 14,000 votes.",
    education: "University of Agriculture Makurdi (Food Science), University of Ibadan (MBA)",
    competence: 67,
    influence: 60,
    loyalty: 64,
    isHandCrafted: true,
  },
  {
    name: "Hon. Idris Ohere-Kogi",
    state: "Kogi",
    zone: "NC",
    party: "ADU",
    constituency: "Okene Federal Constituency",
    age: 55,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Ebira",
    avatar: "IO",
    traits: ["Business Owner", "Floor Speaker", "Party Loyalist"],
    bio: "A mining investor whose companies operate three quarries in Kogi. His detailed knowledge of the solid minerals sector has made him the de facto spokesperson for the House Committee on Solid Minerals whenever technical questions arise in plenary.",
    education: "ABU Zaria (Geology), University of Leeds (MSc Mining Engineering)",
    competence: 68,
    influence: 63,
    loyalty: 71,
    isHandCrafted: true,
  },
  {
    name: "Hon. Blessing Okoye-Kogi",
    state: "Kogi",
    zone: "NC",
    party: "PFC",
    constituency: "Lokoja Federal Constituency",
    age: 46,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "BO",
    traits: ["Anti-Corruption Fighter", "Legal Practitioner", "Independent Voice"],
    bio: "A human rights lawyer who ran a successful SERAP lawsuit against Kogi's notorious salary crisis before pivoting to electoral politics. Her razor-sharp legal mind has produced five landmark House committee reports on financial propriety.",
    education: "University of Benin (LLB), Nigerian Law School, UCL (LLM Human Rights)",
    competence: 73,
    influence: 61,
    loyalty: 44,
    isHandCrafted: true,
  },
  {
    name: "Hon. Saliu Mustapha-Kwara",
    state: "Kwara",
    zone: "NC",
    party: "ADU",
    constituency: "Ilorin East Federal Constituency",
    age: 52,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Yoruba",
    avatar: "SM",
    traits: ["Grassroots Politician", "Trade Unionist", "Party Loyalist"],
    bio: "A motor park transport union leader who mobilised Ilorin's informal sector vote that no formal campaign had reached. His constituency office runs a daily jobs board and skills training programme that has placed 3,200 young people in employment.",
    education: "University of Ilorin (Business Admin), Lagos Business School (Certificate)",
    competence: 60,
    influence: 60,
    loyalty: 74,
    isHandCrafted: true,
  },
  {
    name: "Hon. Nneka Afolabi-Kwara",
    state: "Kwara",
    zone: "NC",
    party: "ADU",
    constituency: "Ilorin West Federal Constituency",
    age: 41,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "NA",
    traits: ["Youth Representative", "Education Champion", "Media Savvy"],
    bio: "A digital marketing consultant who ran the most successful data-driven federal constituency campaign in Kwara's history. Her House interventions on digital economy legislation are broadcast live on her YouTube channel, which has 380,000 subscribers.",
    education: "University of Ilorin (Computer Science), Henley Business School (MBA Digital)",
    competence: 65,
    influence: 58,
    loyalty: 65,
    isHandCrafted: true,
  },
  {
    name: "Hon. Chidi Ezema-Nasarawa",
    state: "Nasarawa",
    zone: "NC",
    party: "ADU",
    constituency: "Lafia Federal Constituency",
    age: 50,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Tiv",
    avatar: "CE",
    traits: ["Infrastructure Focused", "Agricultural Champion", "Constituency Champion"],
    bio: "A civil servant turned rep who has turned Lafia constituency into the most infrastructure-rich in Nasarawa through methodical project tracking. His decision to live full-time in the constituency — not Abuja — has set a new standard for constituency presence.",
    education: "University of Jos (Public Administration), Nasarawa State University (MSc)",
    competence: 64,
    influence: 57,
    loyalty: 70,
    isHandCrafted: true,
  },
  {
    name: "Hon. Judith Danladi-Nasarawa",
    state: "Nasarawa",
    zone: "NC",
    party: "NSF",
    constituency: "Keffi Federal Constituency",
    age: 43,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Tiv",
    avatar: "JD",
    traits: ["Anti-Corruption Fighter", "Women's Voice", "First-Term Rep"],
    bio: "A first-term rep from NSF who upset the ADU incumbent by documenting in excruciating detail how her predecessor's constituency funds were spent — none on her constituency. Her public accounts tracking system has since been adopted by 12 other House members.",
    education: "University of Abuja (Accounting), ICAN Associate",
    competence: 66,
    influence: 56,
    loyalty: 44,
    isHandCrafted: true,
  },
  {
    name: "Hon. Abdul Rahman-Niger",
    state: "Niger",
    zone: "NC",
    party: "ADU",
    constituency: "Bida Federal Constituency",
    age: 57,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Nupe",
    avatar: "AR",
    traits: ["Veteran Lawmaker", "Community Leader", "Party Loyalist"],
    bio: "A three-term rep who has sat on the Appropriations Committee since his second term and can cite budget line-items from memory. He is the acknowledged dean of the Niger State House delegation and mediates disputes within it with quiet authority.",
    education: "FUT Minna (Business Admin), Ahmadu Bello University (MBA)",
    competence: 67,
    influence: 65,
    loyalty: 76,
    isHandCrafted: true,
  },
  {
    name: "Hon. Mary Pam-Plateau",
    state: "Plateau",
    zone: "NC",
    party: "PFC",
    constituency: "Jos North Federal Constituency",
    age: 45,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Berom",
    avatar: "MP",
    traits: ["Security Advocate", "Women's Voice", "Cross-Party Builder"],
    bio: "A peace-building NGO director who stood on the rubble of her destroyed church in Jos and decided to run for the House. Her Plateau Peace and Reconciliation Bill — drafted with victims' groups from all religious communities — is the most publicly-consulted House bill in five years.",
    education: "University of Jos (Sociology), University of Bradford (MA Peace and Conflict)",
    competence: 70,
    influence: 63,
    loyalty: 48,
    isHandCrafted: true,
  },
  {
    name: "Hon. Daniel Ayom-Plateau",
    state: "Plateau",
    zone: "NC",
    party: "ADU",
    constituency: "Barkin Ladi Federal Constituency",
    age: 52,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Berom",
    avatar: "DA",
    traits: ["Security Advocate", "Agricultural Champion", "Constituency Champion"],
    bio: "A former military officer who returned to his ancestral farming community after retirement only to watch it suffer repeated attacks. His decision to contest came after documenting 14 village raids in a single year. He now chairs the House Sub-committee on Farmer-Herder Conflict.",
    education: "Nigerian Military School (Zaria), NDA (Political Science), Army Command College",
    competence: 68,
    influence: 61,
    loyalty: 66,
    isHandCrafted: true,
  },
  {
    name: "Hon. Benjamin Dang",
    state: "Plateau",
    zone: "NC",
    party: "NDM",
    constituency: "Mangu Federal Constituency",
    age: 48,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Berom",
    avatar: "BD",
    traits: ["Education Champion", "Anti-Corruption Fighter", "Budget Watchdog"],
    bio: "A former university registrar who ran for the House after catching widespread examination malpractice in a federal ministry tender. His Education Committee work has blocked three suspect accreditation processes and referred seven cases to the EFCC.",
    education: "University of Jos (Education Administration), Leeds University (MEd)",
    competence: 69,
    influence: 57,
    loyalty: 46,
    isHandCrafted: true,
  },
  {
    name: "Hon. Danjuma Musa-Niger",
    state: "Niger",
    zone: "NC",
    party: "ADU",
    constituency: "Minna Federal Constituency",
    age: 54,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Nupe",
    avatar: "DM",
    traits: ["Infrastructure Focused", "Party Loyalist", "Floor Speaker"],
    bio: "A former director of the Niger State Roads Agency who has used his technical expertise to veto three sub-standard federal road contracts in his constituency. His detailed technical reports are quoted approvingly by the Bureau of Public Procurement.",
    education: "FUT Minna (Civil Engineering), University of Birmingham (MSc Highway Engineering)",
    competence: 70,
    influence: 60,
    loyalty: 73,
    isHandCrafted: true,
  },
  {
    name: "Hon. Abubakar Yusuf-FCT",
    state: "FCT",
    zone: "NC",
    party: "ADU",
    constituency: "Abuja Municipal Federal Constituency",
    age: 49,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    avatar: "AY",
    traits: ["Grassroots Politician", "Community Leader", "Media Savvy"],
    bio: "An Abuja-born politician who ran on protecting the rights of indigenous Gbagyi communities against mass evictions by city developers. His weekly constituency town halls — sometimes attended by over 1,000 residents — are the most-attended in the FCT federal constituencies.",
    education: "University of Abuja (Political Science), NIPSS Kuru (Governance)",
    competence: 63,
    influence: 60,
    loyalty: 66,
    isHandCrafted: true,
  },
  {
    name: "Hon. Patience Attah-Kogi",
    state: "Kogi",
    zone: "NC",
    party: "ADU",
    constituency: "Ofu Federal Constituency",
    age: 51,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "PA",
    traits: ["Health Crusader", "Constituency Champion", "Party Loyalist"],
    bio: "A former state coordinator for the National Primary Health Care Development Agency who documented every non-functional health facility in Kogi before her election. Has since secured rehabilitation funds for 34 primary health centres in the first two years of her term.",
    education: "University of Benin (Nursing), University of Lagos (MPH)",
    competence: 66,
    influence: 57,
    loyalty: 72,
    isHandCrafted: true,
  },
  {
    name: "Hon. Tunde Adeyemi-Kwara",
    state: "Kwara",
    zone: "NC",
    party: "TLA",
    constituency: "Offa Federal Constituency",
    age: 46,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Yoruba",
    avatar: "TA",
    traits: ["Independent Voice", "Budget Watchdog", "Legal Practitioner"],
    bio: "A TLA member who has consistently refused party directions on budget votes, earning the nickname 'Offa's Conscience'. His cross-party alliance on fiscal discipline has blocked ₦9 billion in questionable supplementary estimates in two years.",
    education: "University of Ilorin (LLB), Nigerian Law School, LSE (LLM Public Finance)",
    competence: 73,
    influence: 59,
    loyalty: 35,
    isHandCrafted: true,
  },
  {
    name: "Hon. Nnamdi Ezenwachi-Benue",
    state: "Benue",
    zone: "NC",
    party: "PFC",
    constituency: "Gboko Federal Constituency",
    age: 53,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Tiv",
    avatar: "NE",
    traits: ["Agricultural Champion", "Cross-Party Builder", "Floor Speaker"],
    bio: "A yam farmer-politician who has championed the TIV Agricultural Collective's expansion into national export markets. Persuaded the House Agric Committee to approve a ₦15 billion food-processing cluster for the Benue River basin with cross-partisan support.",
    education: "University of Agriculture Makurdi (Agriculture), University of Ibadan (MBA Agribusiness)",
    competence: 66,
    influence: 62,
    loyalty: 50,
    isHandCrafted: true,
  },
  {
    name: "Hon. Mrs. Comfort Ibrahim-Niger",
    state: "Niger",
    zone: "NC",
    party: "ADU",
    constituency: "Suleja Federal Constituency",
    age: 48,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Nupe",
    avatar: "CI",
    traits: ["Education Champion", "Women's Voice", "Community Leader"],
    bio: "A schoolteacher who mobilised Niger State's Parent-Teacher Associations into a voters bloc that swung the Suleja constituency for the first time in a decade. Now chairs the House Committee on Basic Education and chairs Nigeria's first all-female inter-party education caucus.",
    education: "FUT Minna (Education), ABU Zaria (MEd)",
    competence: 63,
    influence: 56,
    loyalty: 68,
    isHandCrafted: true,
  },

  // ── SOUTH-WEST (18) ───────────────────────────────────────────────────────

  {
    name: "Hon. Rotimi Adesanya-Lagos",
    state: "Lagos",
    zone: "SW",
    party: "PFC",
    constituency: "Ikeja Federal Constituency",
    age: 50,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "RA",
    traits: ["Business Owner", "Floor Speaker", "Anti-Corruption Fighter"],
    bio: "A tech entrepreneur who sold his payments startup for $22 million and ran for Ikeja on a digital governance platform. His Private Member Bill on Open Government Data passed the House with 289 votes — the widest majority in the current assembly.",
    education: "University of Lagos (Computer Science), MIT (MBA Technology Management)",
    competence: 74,
    influence: 67,
    loyalty: 50,
    isHandCrafted: true,
  },
  {
    name: "Hon. Funmilayo Okunola",
    state: "Lagos",
    zone: "SW",
    party: "PFC",
    constituency: "Ajeromi-Ifelodun Federal Constituency",
    age: 46,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "FO",
    traits: ["Women's Voice", "Health Crusader", "Grassroots Politician"],
    bio: "A community health activist from Ajegunle who built Lagos's largest grassroots women's health network before entering politics. Her constituency office in Ajegunle offers free maternal health consultations twice a week and is a model being replicated in three other Lagos constituencies.",
    education: "Lagos State University (Nursing), University of Lagos (MPH)",
    competence: 65,
    influence: 60,
    loyalty: 60,
    isHandCrafted: true,
  },
  {
    name: "Hon. Adegoke Fashola",
    state: "Lagos",
    zone: "SW",
    party: "ADU",
    constituency: "Eti-Osa Federal Constituency",
    age: 55,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "AF",
    traits: ["Business Owner", "Committee Member", "Party Loyalist"],
    bio: "A former Lagos Island local government chairman and investment banker who chairs the House Committee on Capital Markets. His regulatory amendments to the Investments and Securities Act have been praised by the SEC and the Nigerian Exchange Group for their technical precision.",
    education: "University of Lagos (Economics), London Business School (MBA), CFA Charter",
    competence: 76,
    influence: 66,
    loyalty: 70,
    isHandCrafted: true,
  },
  {
    name: "Hon. Adeola Agboola-Ogun",
    state: "Ogun",
    zone: "SW",
    party: "PFC",
    constituency: "Abeokuta South Federal Constituency",
    age: 48,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "AA",
    traits: ["Education Champion", "Youth Representative", "Media Savvy"],
    bio: "A former Ogun state tertiary education commissioner who authored the state's free-tuition polytechnic policy. Her House committee work has produced a blueprint for reducing the ASUU-FG conflict through multi-year university funding agreements.",
    education: "Obafemi Awolowo University (Education), Cambridge University (MEd)",
    competence: 70,
    influence: 61,
    loyalty: 55,
    isHandCrafted: true,
  },
  {
    name: "Hon. Niyi Adeyemi-Ogun",
    state: "Ogun",
    zone: "SW",
    party: "ADU",
    constituency: "Sagamu Federal Constituency",
    age: 52,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "NA",
    traits: ["Infrastructure Focused", "Business Owner", "Party Loyalist"],
    bio: "A construction magnate whose expressway contracts span four south-west states. He is equally comfortable at a Lagos business dinner and at a community development meeting in rural Ogun, and has built a bipartisan coalition that has delivered three federal roads to his constituency.",
    education: "University of Lagos (Civil Engineering), INSEAD (MBA)",
    competence: 69,
    influence: 63,
    loyalty: 70,
    isHandCrafted: true,
  },
  {
    name: "Hon. Seun Olaiya-Oyo",
    state: "Oyo",
    zone: "SW",
    party: "NDM",
    constituency: "Ibadan North-West Federal Constituency",
    age: 44,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "SO",
    traits: ["Youth Representative", "Anti-Corruption Fighter", "Media Savvy"],
    bio: "A 44-year-old investigative journalist who pivoted to politics after his documentary on Oyo water sector corruption won a CNN African Journalist Award. His House questions to the FMWR about water sector privatisation have been viewed 4 million times online.",
    education: "University of Ibadan (Mass Communication), Columbia University (MS Journalism)",
    competence: 70,
    influence: 63,
    loyalty: 45,
    isHandCrafted: true,
  },
  {
    name: "Hon. Mrs. Abimbola Akinwande",
    state: "Oyo",
    zone: "SW",
    party: "PFC",
    constituency: "Ogbomoso North Federal Constituency",
    age: 50,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "AA",
    traits: ["Health Crusader", "Women's Voice", "Cross-Party Builder"],
    bio: "A pharmacist-politician who chairs the House Sub-committee on Primary Health Care. Her cross-party Maternal Mortality Emergency Motion brought five PFC senators and three ADU members to a single press conference — a rare show of united purpose.",
    education: "Obafemi Awolowo University (Pharmacy), University of London (MSc Health Policy)",
    competence: 68,
    influence: 60,
    loyalty: 55,
    isHandCrafted: true,
  },
  {
    name: "Hon. Kayode Alabi",
    state: "Osun",
    zone: "SW",
    party: "TLA",
    constituency: "Osogbo Federal Constituency",
    age: 47,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "KA",
    traits: ["Independent Voice", "Agricultural Champion", "Constituency Champion"],
    bio: "TLA's most prominent southern rep who has built his brand on cocoa farmers' rights. He organised the Osun Cocoa Cooperative that secured a $28 million EU development grant and personally negotiated a farmgate price guarantee with the NCCE.",
    education: "Obafemi Awolowo University (Agriculture), Wageningen (MSc Commodity Markets)",
    competence: 67,
    influence: 60,
    loyalty: 40,
    isHandCrafted: true,
  },
  {
    name: "Hon. Remi Babalola-Osun",
    state: "Osun",
    zone: "SW",
    party: "ADU",
    constituency: "Ife North Federal Constituency",
    age: 56,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "RB",
    traits: ["Legal Practitioner", "Veterans Lawmaker", "Budget Watchdog"],
    bio: "A senior advocate and three-term House veteran who has argued before the Supreme Court on constitutional cases emerging from House impeachment proceedings. His private archive of legislative precedents from the 1st to 10th Assembly is regularly consulted by the Clerk of the House.",
    education: "Obafemi Awolowo University (LLB, LLM), Cambridge (LLM)",
    competence: 81,
    influence: 68,
    loyalty: 66,
    isHandCrafted: true,
  },
  {
    name: "Hon. Dr. Biodun Adefemi",
    state: "Ekiti",
    zone: "SW",
    party: "PFC",
    constituency: "Ado-Ekiti Federal Constituency",
    age: 49,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "BA",
    traits: ["Education Champion", "Anti-Corruption Fighter", "Independent Voice"],
    bio: "A university academic who ran on a platform of reforming TETFUND and won. His amendment to the Tertiary Education Trust Fund Act redirected ₦45 billion from construction vanity projects to research grants and postgraduate scholarships.",
    education: "Ekiti State University (Education), University of Manchester (PhD Education Policy)",
    competence: 75,
    influence: 61,
    loyalty: 46,
    isHandCrafted: true,
  },
  {
    name: "Hon. Femi Olawale-Lagos",
    state: "Lagos",
    zone: "SW",
    party: "PFC",
    constituency: "Apapa Federal Constituency",
    age: 53,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "FO",
    traits: ["Business Owner", "Trade Unionist", "Floor Speaker"],
    bio: "A shipping and port logistics magnate whose Apapa-based business empire directly employs 2,400 Nigerians. In the House he chairs the Maritime sub-committee and has driven amendments to the Nigerian Ports Authority Act that have reduced average port clearance time by 30%.",
    education: "University of Lagos (Business Admin), London Business School (MBA Maritime Management)",
    competence: 72,
    influence: 68,
    loyalty: 55,
    isHandCrafted: true,
  },
  {
    name: "Hon. Sola Adeyemi-Ondo",
    state: "Ondo",
    zone: "SW",
    party: "NDM",
    constituency: "Akure North Federal Constituency",
    age: 45,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "SA",
    traits: ["Agricultural Champion", "Anti-Corruption Fighter", "Grassroots Politician"],
    bio: "A cocoa and oil palm farmer who has documented illegal land grabbing from smallholder farmers in Ondo and published the findings in a national newspaper. His House tenure has produced two bills on land rights for indigenous farming communities.",
    education: "Federal University of Technology Akure (Agriculture), University of Ibadan (MSc)",
    competence: 66,
    influence: 57,
    loyalty: 46,
    isHandCrafted: true,
  },
  {
    name: "Hon. Titi Oluwafemi",
    state: "Ondo",
    zone: "SW",
    party: "ADU",
    constituency: "Ondo South Federal Constituency",
    age: 43,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "TO",
    traits: ["Youth Representative", "Women's Voice", "Media Savvy"],
    bio: "A former TV presenter who used her media profile to build a constituency campaign that reached 85% of registered voters through social media. Chairs the House Sub-committee on Information Technology and is the most-cited House member by Nigerian technology journalists.",
    education: "Lagos State University (Mass Communication), Cardiff University (MA Broadcast Journalism)",
    competence: 63,
    influence: 58,
    loyalty: 64,
    isHandCrafted: true,
  },
  {
    name: "Hon. Gbenga Ogunyemi-Osun",
    state: "Osun",
    zone: "SW",
    party: "ADU",
    constituency: "Ile-Ife Federal Constituency",
    age: 57,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "GO",
    traits: ["Veteran Lawmaker", "Community Leader", "Party Loyalist"],
    bio: "Three-term rep and traditional title holder in Ile-Ife who combines royal legitimacy with legislative experience. His standing ovation speech at the Osun water crisis debate in 2022 was broadcast nationwide and is credited with unblocking the emergency relief allocation.",
    education: "Obafemi Awolowo University (History), University of Ibadan (MA Political History)",
    competence: 65,
    influence: 65,
    loyalty: 73,
    isHandCrafted: true,
  },
  {
    name: "Hon. Dr. Yemi Ajibade-Ogun",
    state: "Ogun",
    zone: "SW",
    party: "ADU",
    constituency: "Ijebu North Federal Constituency",
    age: 51,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "YA",
    traits: ["Health Crusader", "Business Owner", "Committee Member"],
    bio: "A medical director who founded Nigeria's largest private diagnostic chain before pivoting to politics. His experience navigating healthcare markets gives the House Committee on Health a rare combination of clinical and commercial expertise.",
    education: "University of Ibadan (MBBS, MBA Health Management), Johns Hopkins (MPH)",
    competence: 74,
    influence: 63,
    loyalty: 65,
    isHandCrafted: true,
  },
  {
    name: "Hon. Fola Ayodele-Ekiti",
    state: "Ekiti",
    zone: "SW",
    party: "ADU",
    constituency: "Ekiti South Federal Constituency",
    age: 48,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "FA",
    traits: ["Women's Voice", "Infrastructure Focused", "Party Loyalist"],
    bio: "A structural engineer who built her reputation on the Ekiti Rural Electrification Project before contesting. Her technical input into the House Electricity Bill amendment phase produced the most detailed grid reliability clause in Nigerian legislative history.",
    education: "University of Ibadan (Civil Engineering), University of Birmingham (MSc Structural Engineering)",
    competence: 72,
    influence: 59,
    loyalty: 71,
    isHandCrafted: true,
  },
  {
    name: "Hon. Adeleke Makinde-Oyo",
    state: "Oyo",
    zone: "SW",
    party: "ADU",
    constituency: "Ibadan South-West Federal Constituency",
    age: 54,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Yoruba",
    avatar: "AM",
    traits: ["Floor Speaker", "Budget Watchdog", "Party Loyalist"],
    bio: "A former budget analyst at the World Bank's Lagos office who brought international public finance methodologies to the House Appropriations Committee. His annual 'Budget Red Book' — a 200-page critique of the federal spending plan — is downloaded 50,000 times on publication day.",
    education: "University of Ibadan (Economics), Oxford (MSc Development Economics), World Bank Institute",
    competence: 78,
    influence: 65,
    loyalty: 69,
    isHandCrafted: true,
  },
  {
    name: "Hon. Eniola Daramola-Lagos",
    state: "Lagos",
    zone: "SW",
    party: "HDP",
    constituency: "Kosofe Federal Constituency",
    age: 46,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Yoruba",
    avatar: "ED",
    traits: ["Independent Voice", "Anti-Corruption Fighter", "Media Savvy"],
    bio: "An HDP first-term rep who won Kosofe in one of the biggest upsets of the last federal election, defeating a two-term ADU incumbent. Her 'Citizens Budget' tool — which lets residents suggest constituency priorities via WhatsApp — has received global recognition from the Open Government Partnership.",
    education: "Lagos State University (Accounting), ACCA, University of Edinburgh (MSc Public Policy)",
    competence: 68,
    influence: 58,
    loyalty: 42,
    isHandCrafted: true,
  },

  // ── SOUTH-EAST (14) ───────────────────────────────────────────────────────

  {
    name: "Hon. Chukwuemeka Obi-Anambra",
    state: "Anambra",
    zone: "SE",
    party: "NDM",
    constituency: "Onitsha North Federal Constituency",
    age: 55,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "CO",
    traits: ["Business Owner", "Floor Speaker", "Trade Unionist"],
    bio: "The president of the Onitsha Main Market Traders Association whose constituency straddles the largest inland market in West Africa. His Private Member Bill on Electronic Market Tolls replaced a 40-year manual levy system with a transparent digital equivalent.",
    education: "University of Nigeria Nsukka (Business Admin), Harvard Business School (AMP)",
    competence: 69,
    influence: 67,
    loyalty: 53,
    isHandCrafted: true,
  },
  {
    name: "Hon. Adaeze Nwosu",
    state: "Anambra",
    zone: "SE",
    party: "PFC",
    constituency: "Awka South Federal Constituency",
    age: 44,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "AN",
    traits: ["Youth Representative", "Education Champion", "Anti-Corruption Fighter"],
    bio: "A former NYSC coordinator who ran on a platform of tertiary graduate employment reform. Her Graduate Employability Skills Bill — mandating industry-certified vocational modules in polytechnic curricula — passed second reading with the highest number of co-sponsors in the 10th Assembly.",
    education: "Nnamdi Azikiwe University (Education), University of Edinburgh (MEd Curriculum Design)",
    competence: 68,
    influence: 58,
    loyalty: 48,
    isHandCrafted: true,
  },
  {
    name: "Hon. Dr. Kingsley Eze-Enugu",
    state: "Enugu",
    zone: "SE",
    party: "NDM",
    constituency: "Enugu North Federal Constituency",
    age: 53,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "KE",
    traits: ["Health Crusader", "Anti-Corruption Fighter", "Committee Member"],
    bio: "A professor of epidemiology who stood down from his university chair to fight what he called 'the scandal of preventable deaths' in Enugu hospitals. His forensic analysis of Enugu's infant mortality data — presented to the House Health Committee — triggered a presidential inquiry.",
    education: "University of Nigeria ENUGU CAMPUS (MBBS, PhD Epidemiology), Johns Hopkins Bloomberg (MPH)",
    competence: 79,
    influence: 63,
    loyalty: 50,
    isHandCrafted: true,
  },
  {
    name: "Hon. Mrs. Chioma Okereke",
    state: "Imo",
    zone: "SE",
    party: "NDM",
    constituency: "Owerri Municipal Federal Constituency",
    age: 48,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "CO",
    traits: ["Women's Voice", "Grassroots Politician", "Community Leader"],
    bio: "A market women's association president who turned her network of 45,000 traders in Imo into a political force. Her constituency office runs a micro-credit programme that has disbursed ₦800 million to female entrepreneurs since she took office.",
    education: "Imo State University (Business Admin), Lagos Business School (Certificate)",
    competence: 63,
    influence: 61,
    loyalty: 56,
    isHandCrafted: true,
  },
  {
    name: "Hon. Nonso Achike",
    state: "Abia",
    zone: "SE",
    party: "PFC",
    constituency: "Aba North Federal Constituency",
    age: 50,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "NA",
    traits: ["Trade Unionist", "Business Owner", "Anti-Corruption Fighter"],
    bio: "The chairman of the Aba Made Shoes Manufacturers Cooperative who successfully lobbied for anti-dumping tariffs on Chinese footwear imports. His committee work on customs and excise has saved an estimated 120,000 Aba manufacturing jobs from unfair competition.",
    education: "Abia State University (Business), LCCI Fellow",
    competence: 67,
    influence: 64,
    loyalty: 50,
    isHandCrafted: true,
  },
  {
    name: "Hon. Obiageli Okafor-Ebonyi",
    state: "Ebonyi",
    zone: "SE",
    party: "ADU",
    constituency: "Abakaliki Federal Constituency",
    age: 46,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "OO",
    traits: ["Agricultural Champion", "Women's Voice", "Party Loyalist"],
    bio: "An Ebonyi salt lake farmer's daughter who rode a rice farming expansion programme to a surprising first-term win. Her committee work on agriculture has produced Nigeria's first Certified Organic Farming Standards Bill, which passed the House on third reading.",
    education: "Michael Okpara University of Agriculture (Agriculture), University of Ghana (MSc Agribusiness)",
    competence: 64,
    influence: 56,
    loyalty: 70,
    isHandCrafted: true,
  },
  {
    name: "Hon. Emeka Chukwu-Imo",
    state: "Imo",
    zone: "SE",
    party: "NDM",
    constituency: "Orlu Federal Constituency",
    age: 57,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "EC",
    traits: ["Legal Practitioner", "Anti-Corruption Fighter", "Veterans Lawmaker"],
    bio: "A three-term rep and SANs-ranked advocate who drafted the template for the Imo Oil Palm Estates Revenue Transparency Act — later adopted nationally. His parliamentary questioning style is modelled on the Westminster tradition and cited in the House standing orders manual.",
    education: "University of Nigeria Nsukka (LLB), Nigerian Law School, Inner Temple London (Called)",
    competence: 78,
    influence: 67,
    loyalty: 52,
    isHandCrafted: true,
  },
  {
    name: "Hon. Chidimma Onuoha",
    state: "Abia",
    zone: "SE",
    party: "NDM",
    constituency: "Isuikwuato Federal Constituency",
    age: 42,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "CO",
    traits: ["Youth Representative", "Anti-Corruption Fighter", "Media Savvy"],
    bio: "A diaspora returnee from Canada who launched a blockchain-based constituency funds tracking system that has been adopted by seven other House members. Her monthly financial transparency reports are automatically uploaded to IPFS for immutable public record.",
    education: "University of Nigeria (Computer Science), University of Waterloo (MCS), Harvard Kennedy (MPP)",
    competence: 71,
    influence: 58,
    loyalty: 48,
    isHandCrafted: true,
  },
  {
    name: "Hon. Ifeanyi Anozie",
    state: "Anambra",
    zone: "SE",
    party: "NSF",
    constituency: "Nnewi North Federal Constituency",
    age: 52,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "IA",
    traits: ["Business Owner", "Cross-Party Builder", "Diaspora Representative"],
    bio: "An auto-parts industrialist whose Nnewi cluster is one of Nigeria's few genuine manufacturing success stories. His Manufacturing Competitiveness Bill passed with ADU, PFC, and NDM support — a rare feat in the fractious 10th Assembly.",
    education: "University of Nigeria Nsukka (Mechanical Engineering), Wharton (MBA Manufacturing)",
    competence: 71,
    influence: 65,
    loyalty: 46,
    isHandCrafted: true,
  },
  {
    name: "Hon. Chioma Ezike-Ebonyi",
    state: "Ebonyi",
    zone: "SE",
    party: "ADU",
    constituency: "Ohaukwu Federal Constituency",
    age: 45,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "CE",
    traits: ["Health Crusader", "Women's Voice", "Constituency Champion"],
    bio: "A midwife who founded the only well-equipped maternal ward in rural Ebonyi and used it as the centrepiece of her election campaign. She has since won four federal health grants for Ebonyi through strategic committee positioning.",
    education: "Ebonyi State University (Nursing), University of Ibadan (MPH)",
    competence: 63,
    influence: 55,
    loyalty: 68,
    isHandCrafted: true,
  },
  {
    name: "Hon. Ike Mbam-Enugu",
    state: "Enugu",
    zone: "SE",
    party: "PFC",
    constituency: "Udi Federal Constituency",
    age: 54,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "IM",
    traits: ["Agricultural Champion", "Constituency Champion", "Cross-Party Builder"],
    bio: "A yam and palm oil farmer who ran on a platform of rural electrification and agricultural modernisation. His cross-party agricultural energy bill has secured 14 co-sponsors from five parties — testament to his reputation for elevating shared interests above partisan ones.",
    education: "University of Nigeria (Agriculture), Wageningen University (MSc)",
    competence: 64,
    influence: 59,
    loyalty: 50,
    isHandCrafted: true,
  },
  {
    name: "Hon. Ikenna Ogbu",
    state: "Imo",
    zone: "SE",
    party: "ADU",
    constituency: "Mbaitoli Federal Constituency",
    age: 49,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "IO",
    traits: ["Infrastructure Focused", "Party Loyalist", "Community Leader"],
    bio: "A former Imo Roads Agency director who has used his technical contacts to fast-track three constituency road projects that had stalled in the ministry for five years. His reputation for delivery — not oratory — is why he consistently wins by 20-point margins.",
    education: "Federal University of Technology Owerri (Civil Engineering), ABU Zaria (MSc)",
    competence: 67,
    influence: 59,
    loyalty: 73,
    isHandCrafted: true,
  },
  {
    name: "Hon. Nnamdi Obi-Ebonyi",
    state: "Ebonyi",
    zone: "SE",
    party: "PFC",
    constituency: "Ishielu Federal Constituency",
    age: 47,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "NO",
    traits: ["Legal Practitioner", "Budget Watchdog", "Anti-Corruption Fighter"],
    bio: "A lawyer who ran against and defeated the sitting ADU incumbent on a platform of restoring trust in Ebonyi federal representation. His first bill — the Federal Constituency Audit Transparency Act — requires all constituency project expenditure to be audited by an independent CPA.",
    education: "Ebonyi State University (LLB), Nigerian Law School, University of Edinburgh (LLM Public Law)",
    competence: 70,
    influence: 57,
    loyalty: 46,
    isHandCrafted: true,
  },
  {
    name: "Hon. Dr. Stella Mba-Enugu",
    state: "Enugu",
    zone: "SE",
    party: "NDM",
    constituency: "Igbo-Eze South Federal Constituency",
    age: 51,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    avatar: "SM",
    traits: ["Education Champion", "Women's Voice", "Diaspora Representative"],
    bio: "Returned from a decade in the UK where she headed an NHS trust's diversity department to run for the House. Her UK network of Nigerian diaspora professionals funds a scholarship programme that has placed 140 Enugu students in UK universities on partial bursaries.",
    education: "University of Nigeria (Medicine), University of Manchester (MPH, MBA Health Management)",
    competence: 72,
    influence: 61,
    loyalty: 53,
    isHandCrafted: true,
  },

  // ── SOUTH-SOUTH (15) ─────────────────────────────────────────────────────

  {
    name: "Hon. Barr. Preye Amayanabo",
    state: "Bayelsa",
    zone: "SS",
    party: "PFC",
    constituency: "Yenagoa Federal Constituency",
    age: 49,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Ijaw",
    avatar: "PA",
    traits: ["Legal Practitioner", "Anti-Corruption Fighter", "Security Advocate"],
    bio: "An environmental law advocate who has successfully litigated six oil-spill compensation cases on behalf of Bayelsa fishing communities. His Private Member Bill on Mandatory Oil Spill Remediation Bonds is the most significant environmental legislation before the House in a decade.",
    education: "University of Benin (LLB), Nigerian Law School, University of Amsterdam (LLM Environmental Law)",
    competence: 75,
    influence: 63,
    loyalty: 46,
    isHandCrafted: true,
  },
  {
    name: "Hon. Mrs. Grace Ekine-Bayelsa",
    state: "Bayelsa",
    zone: "SS",
    party: "ADU",
    constituency: "Ogbia Federal Constituency",
    age: 50,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Ijaw",
    avatar: "GE",
    traits: ["Constituency Champion", "Health Crusader", "Party Loyalist"],
    bio: "A former NDDC social development director who used her institutional knowledge to track every undelivered hospital project in her constituency. Since winning she has compelled the NDDC to restart 8 stalled health facilities through a combination of litigation threat and committee pressure.",
    education: "University of Port Harcourt (Social Work), University of Leeds (MA Development Studies)",
    competence: 66,
    influence: 59,
    loyalty: 70,
    isHandCrafted: true,
  },
  {
    name: "Hon. Prof. Ebitimi Banigo-Rivers",
    state: "Rivers",
    zone: "SS",
    party: "PFC",
    constituency: "Port Harcourt Federal Constituency",
    age: 57,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Ogoni",
    avatar: "EB",
    traits: ["Education Champion", "Anti-Corruption Fighter", "Committee Member"],
    bio: "A professor of petroleum geosciences who resigned from the University of Port Harcourt to run for the House. His technical expertise has transformed the House Committee on Petroleum Resources' bill-drafting capacity — three major petroleum-sector bills bear his intellectual imprint.",
    education: "University of Port Harcourt (BSc, MSc, PhD Petroleum Geosciences), Stanford (Postdoc)",
    competence: 80,
    influence: 66,
    loyalty: 48,
    isHandCrafted: true,
  },
  {
    name: "Hon. Rosemary Okowa-Delta",
    state: "Delta",
    zone: "SS",
    party: "ADU",
    constituency: "Oshimili North Federal Constituency",
    age: 47,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Urhobo",
    avatar: "RO",
    traits: ["Women's Voice", "Agricultural Champion", "Cross-Party Builder"],
    bio: "An Urhobo palm oil producer whose cooperative exports to East Asia have generated $12 million in foreign exchange in three years. Her cross-party agricultural processing bill has secured 22 co-sponsors and is described by the World Bank as 'a model African agricultural law.'",
    education: "Delta State University (Agriculture), Wageningen (MSc Agri-Food Value Chains)",
    competence: 68,
    influence: 62,
    loyalty: 63,
    isHandCrafted: true,
  },
  {
    name: "Hon. Victor Ihide-Delta",
    state: "Delta",
    zone: "SS",
    party: "NDM",
    constituency: "Ughelli South Federal Constituency",
    age: 53,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Itsekiri",
    avatar: "VI",
    traits: ["Security Advocate", "Community Leader", "Anti-Corruption Fighter"],
    bio: "A former Delta State JTF intelligence officer who knows the names of every major oil bunkering kingpin in the Niger Delta. His private briefings to the House Intelligence Sub-committee have led to three interdiction operations and the arrest of two of Nigeria's most-wanted illegal refinery operators.",
    education: "University of Benin (Criminology), National Defence College (Strategic Studies)",
    competence: 72,
    influence: 65,
    loyalty: 50,
    isHandCrafted: true,
  },
  {
    name: "Hon. Mrs. Eferebo Amadi-Rivers",
    state: "Rivers",
    zone: "SS",
    party: "ADU",
    constituency: "Obio/Akpor Federal Constituency",
    age: 45,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Ikwerre",
    avatar: "EA",
    traits: ["Business Owner", "Youth Representative", "Media Savvy"],
    bio: "A micro-finance bank CEO who ran the fastest-growing women's enterprise fund in Rivers State before entering politics. Her constituency now hosts the House's first entrepreneurship hub — a physical space providing free business registration, tax advice, and grant information.",
    education: "University of Port Harcourt (Accounting), Henley Business School (MBA Finance)",
    competence: 69,
    influence: 62,
    loyalty: 65,
    isHandCrafted: true,
  },
  {
    name: "Hon. Effiong Bassey-Akwa Ibom",
    state: "Akwa Ibom",
    zone: "SS",
    party: "ADU",
    constituency: "Uyo Federal Constituency",
    age: 56,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Ibibio",
    avatar: "EB",
    traits: ["Veterans Lawmaker", "Business Owner", "Party Loyalist"],
    bio: "A three-term rep and former state commissioner for finance who has shaped two federal budgets through his position on the House Appropriations Committee. His private infrastructure fund has co-financed four inter-community roads in Uyo using a public-private-constituency model.",
    education: "University of Calabar (Economics), LSE (MSc Finance)",
    competence: 72,
    influence: 67,
    loyalty: 74,
    isHandCrafted: true,
  },
  {
    name: "Hon. Dr. Okon Ita",
    state: "Akwa Ibom",
    zone: "SS",
    party: "PFC",
    constituency: "Oron Federal Constituency",
    age: 51,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Efik",
    avatar: "OI",
    traits: ["Health Crusader", "Anti-Corruption Fighter", "Legal Practitioner"],
    bio: "A public health physician who built a private hospital network across coastal Akwa Ibom before entering politics. Revealed in House testimony that 62% of federal health allocations to Oron had been diverted, a disclosure that led to the suspension of three local government officials.",
    education: "University of Calabar (MBBS), Liverpool School of Tropical Medicine (MPH)",
    competence: 73,
    influence: 61,
    loyalty: 46,
    isHandCrafted: true,
  },
  {
    name: "Hon. Dumo Lulu-Briggs-Rivers",
    state: "Rivers",
    zone: "SS",
    party: "NDM",
    constituency: "Degema Federal Constituency",
    age: 46,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Ikwerre",
    avatar: "DL",
    traits: ["Business Owner", "Anti-Corruption Fighter", "Diaspora Representative"],
    bio: "An oil services entrepreneur who returned from Aberdeen to run for the House on a local content bill platform. His Petroleum Local Content (Amendment) Act has increased Nigerian company participation in oil services contracts from 32% to 47% since it passed.",
    education: "University of Port Harcourt (Petroleum Engineering), University of Aberdeen (MSc Energy Management)",
    competence: 73,
    influence: 66,
    loyalty: 50,
    isHandCrafted: true,
  },
  {
    name: "Hon. Nene Obi-Cross River",
    state: "Cross River",
    zone: "SS",
    party: "ADU",
    constituency: "Calabar Municipal Federal Constituency",
    age: 48,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Efik",
    avatar: "NO",
    traits: ["Grassroots Politician", "Constituency Champion", "Women's Voice"],
    bio: "A former Calabar Cultural Festival director who built a tourism-linked women's artisans network employing 7,000 women before running for the House. Her constituency office runs the only federal-constituency-funded tourism promotion desk in Nigeria.",
    education: "University of Calabar (Tourism Management), University of Edinburgh (MSc Creative Economy)",
    competence: 63,
    influence: 60,
    loyalty: 66,
    isHandCrafted: true,
  },
  {
    name: "Hon. Okoi Obono-Obla-Cross River",
    state: "Cross River",
    zone: "SS",
    party: "NDM",
    constituency: "Ogoja Federal Constituency",
    age: 54,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Efik",
    avatar: "OO",
    traits: ["Legal Practitioner", "Anti-Corruption Fighter", "Independent Voice"],
    bio: "A former Special Presidential Investigation Panel chairman who ran for the House after his anti-corruption panel was shut down by political pressure. His committee work at the House Judiciary Committee has produced the most comprehensive whistleblower protection amendments in the 10th Assembly.",
    education: "University of Calabar (LLB), Nigerian Law School, University of Toronto (LLM)",
    competence: 77,
    influence: 64,
    loyalty: 42,
    isHandCrafted: true,
  },
  {
    name: "Hon. Eze Nwachukwu-Edo",
    state: "Edo",
    zone: "SS",
    party: "ADU",
    constituency: "Oredo Federal Constituency",
    age: 52,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Bini",
    avatar: "EN",
    traits: ["Veterans Lawmaker", "Community Leader", "Party Loyalist"],
    bio: "A three-term rep and Benin Kingdom title holder who bridges traditional governance and modern legislature. His mediation role in the Edo post-election violence of 2020 is credited by civil society as preventing a broader crisis.",
    education: "University of Benin (Political Science), University of Reading (MA Government)",
    competence: 65,
    influence: 67,
    loyalty: 73,
    isHandCrafted: true,
  },
  {
    name: "Hon. Dr. Efosa Ize-Iyamu",
    state: "Edo",
    zone: "SS",
    party: "PFC",
    constituency: "Egor Federal Constituency",
    age: 50,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Bini",
    avatar: "EI",
    traits: ["Health Crusader", "Business Owner", "Anti-Corruption Fighter"],
    bio: "A hospital proprietor and former Edo state health commissioner who exposed the diversion of federal health grants through a forensic audit published in four national newspapers. He ran under PFC on a health accountability platform and won Egor for the first time in 12 years.",
    education: "University of Benin (MBBS, MBA Health Management), Kings College London (PhD Health Policy)",
    competence: 76,
    influence: 62,
    loyalty: 48,
    isHandCrafted: true,
  },
  {
    name: "Hon. Tonye Thompson",
    state: "Rivers",
    zone: "SS",
    party: "TLA",
    constituency: "Khana Federal Constituency",
    age: 45,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Ogoni",
    avatar: "TT",
    traits: ["Anti-Corruption Fighter", "Security Advocate", "Independent Voice"],
    bio: "A TLA environmental activist whose legal case on behalf of Ogoni communities against Shell went to the ECOWAS Community Court of Justice. His election on a minority platform in a PFC-leaning constituency is the most remarkable upset in the current House.",
    education: "University of Port Harcourt (Law), University of London (LLM Environmental Law)",
    competence: 70,
    influence: 59,
    loyalty: 38,
    isHandCrafted: true,
  },
  {
    name: "Hon. Rukevwe Ologbosere-Delta",
    state: "Delta",
    zone: "SS",
    party: "ADU",
    constituency: "Sapele Federal Constituency",
    age: 54,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Urhobo",
    avatar: "RO",
    traits: ["Agricultural Champion", "Constituency Champion", "Party Loyalist"],
    bio: "A palm oil industry executive whose Sapele Agro-Processing Hub attracted ₦3 billion in private investment and 1,400 permanent jobs before she entered politics. Her constituency capital projects tracking sheet is published quarterly and compared publicly against original budget commitments.",
    education: "Delta State University (Agriculture), University of Wageningen (MSc Food Science)",
    competence: 67,
    influence: 60,
    loyalty: 72,
    isHandCrafted: true,
  },
];

// ── Helpers ────────────────────────────────────────────────────────────────

function deriveCompetence(professional: Record<string, number>): number {
  const vals = Object.values(professional);
  const avg = vals.reduce((a, b) => a + b, 0) / vals.length;
  return Math.round(Math.max(40, Math.min(90, avg)));
}

function deriveInfluence(personal: Record<string, number>): number {
  const c = personal.charisma ?? 60;
  const l = personal.leadership ?? 60;
  return Math.round(Math.max(30, Math.min(85, (c + l) / 2)));
}

function deriveLoyalty(personal: Record<string, number>): number {
  return Math.round(Math.max(30, Math.min(80, personal.loyalty ?? 55)));
}

// All states for cycling state assignment in generated pool
const ALL_STATES: string[] = GEOPOLITICAL_ZONES.flatMap(z => z.states);

// ── Main generator ─────────────────────────────────────────────────────────

export function generateHouseRepPool(seed = 6001): HouseRep[] {
  const handCrafted = HANDCRAFTED_HOUSE_REPS;
  const generatedCount = 360 - handCrafted.length; // 260

  const generated = generateCharacterPool({
    count: generatedCount,
    seed,
    role: "house representative",
    traitPool: HOUSE_REP_TRAITS,
    ageRange: { min: 35, max: 65 },
    genderBalance: { minFemalePercent: 25, minMalePercent: 50 },
  });

  const rng = seededRandom(seed + 2000);

  // Calculate remaining party seats after hand-crafted allocation
  const handCraftedPartyCount: Record<string, number> = {};
  for (const r of handCrafted) {
    handCraftedPartyCount[r.party] = (handCraftedPartyCount[r.party] ?? 0) + 1;
  }

  const partyQueue: string[] = [];
  for (const [party, seats] of Object.entries(HOUSE_PARTY_SEATS)) {
    const used = handCraftedPartyCount[party] ?? 0;
    const remaining = Math.max(0, seats - used);
    for (let i = 0; i < remaining; i++) partyQueue.push(party);
  }

  // Shuffle party queue
  for (let i = partyQueue.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [partyQueue[i], partyQueue[j]] = [partyQueue[j], partyQueue[i]];
  }

  // Pad if short (shouldn't happen, but safety net)
  while (partyQueue.length < generatedCount) partyQueue.push("ADU");

  const reps: HouseRep[] = [...handCrafted];

  const CONSTITUENCY_SUFFIXES = [
    "North", "South", "East", "West", "Central",
    "North-East", "South-West", "North-West", "South-East",
  ];

  for (let i = 0; i < generated.length; i++) {
    const char = generated[i];
    const state = char.state ?? ALL_STATES[i % ALL_STATES.length];
    const zone = getZoneForState(state)?.abbrev ?? "NC";
    const party = partyQueue[i];
    const suffix = CONSTITUENCY_SUFFIXES[i % CONSTITUENCY_SUFFIXES.length];
    const constituency = `${state} ${suffix} Federal Constituency`;

    const professional = char.competencies.professional as unknown as Record<string, number>;
    const personal = char.competencies.personal as unknown as Record<string, number>;

    reps.push({
      name: char.name,
      state,
      zone,
      party,
      constituency,
      age: char.age,
      gender: char.gender,
      religion: char.religion,
      ethnicity: char.ethnicity,
      avatar: char.avatar,
      traits: char.traits,
      bio: char.biography,
      education: char.education,
      competence: deriveCompetence(professional),
      influence: deriveInfluence(personal),
      loyalty: deriveLoyalty(personal),
      isHandCrafted: false,
    });
  }

  return reps;
}

// ── Cached access ──────────────────────────────────────────────────────────

let _cached: HouseRep[] | null = null;

export function getHouseRepPool(): HouseRep[] {
  if (!_cached) _cached = generateHouseRepPool();
  return _cached;
}

export function getHouseRepsForState(state: string): HouseRep[] {
  return getHouseRepPool().filter(r => r.state === state);
}
