// client/src/lib/partyProfiles.ts
// Static party definitions and 64 NWC character profiles (8 per party)

import type { NWCPosition, NWCMember } from "./partyTypes";

export interface PartyProfile {
  id: string;
  name: string;
  abbreviation: string;
  initialSeats: { house: number; senate: number };
}

export interface NWCCharacter extends NWCMember {
  partyId: string;
  age: number;
  gender: "Male" | "Female";
  religion: string;
  ethnicity: string;
  traits: [string, string, string];
  bio: string;
  education: { university: string; degree: string };
}

// ── 8 Party Profiles ──────────────────────────────────────────────────

export const PARTY_PROFILES: PartyProfile[] = [
  { id: "adu", name: "African Democratic Union", abbreviation: "ADU", initialSeats: { house: 145, senate: 56 } },
  { id: "pfc", name: "People's Freedom Congress", abbreviation: "PFC", initialSeats: { house: 80, senate: 22 } },
  { id: "ndm", name: "New Direction Movement", abbreviation: "NDM", initialSeats: { house: 45, senate: 12 } },
  { id: "nsf", name: "National Solidarity Front", abbreviation: "NSF", initialSeats: { house: 35, senate: 8 } },
  { id: "tla", name: "The Liberty Alliance", abbreviation: "TLA", initialSeats: { house: 20, senate: 5 } },
  { id: "hdp", name: "Heritage Democratic Party", abbreviation: "HDP", initialSeats: { house: 15, senate: 3 } },
  { id: "pap", name: "Progressive Action Party", abbreviation: "PAP", initialSeats: { house: 12, senate: 2 } },
  { id: "upa", name: "United People's Alliance", abbreviation: "UPA", initialSeats: { house: 8, senate: 1 } },
];

// ── Helpers ───────────────────────────────────────────────────────────

const POSITIONS: NWCPosition[] = [
  "national-chairman",
  "vice-chairman",
  "national-secretary",
  "national-treasurer",
  "publicity-secretary",
  "organising-secretary",
  "legal-adviser",
  "youth-women-leader",
];

// ── 64 NWC Characters ────────────────────────────────────────────────
// Each party has 8 members covering all 6 zones (2 zones get 2 members, 4 zones get 1).
// Names match ethnic/zone conventions:
//   NW/NE → Hausa/Fulani   NC → Tiv/Nupe/Idoma   SW → Yoruba   SE → Igbo   SS → Ijaw/Efik/Urhobo

export const NWC_CHARACTERS: NWCCharacter[] = [
  // ── ADU (African Democratic Union) — centre-right, NW/SW base ──────
  {
    characterId: "nwc-adu-001",
    partyId: "adu",
    name: "Alhaji Garba Danlami",
    position: "national-chairman",
    zone: "NW",
    state: "Kano",
    competence: 82,
    loyalty: 75,
    disposition: "supportive",
    age: 62,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    traits: ["Consensus builder", "Party patriarch", "Shrewd negotiator"],
    bio: "A veteran Hausa-Fulani political operator who built ADU's Northwest machinery over three decades. His quiet authority commands respect from party elders and rank-and-file alike.",
    education: { university: "Ahmadu Bello University, Zaria", degree: "B.Sc. Political Science" },
  },
  {
    characterId: "nwc-adu-002",
    partyId: "adu",
    name: "Chief Babatunde Adesanya",
    position: "vice-chairman",
    zone: "SW",
    state: "Lagos",
    competence: 78,
    loyalty: 68,
    disposition: "supportive",
    age: 58,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    traits: ["Urbane strategist", "Business-linked", "Media savvy"],
    bio: "A Lagos business baron who bridged ADU into Southwest commercial circles. He leverages his corporate network to fund party operations and sway media coverage.",
    education: { university: "University of Lagos", degree: "MBA Finance" },
  },
  {
    characterId: "nwc-adu-003",
    partyId: "adu",
    name: "Hajiya Fatima Bello",
    position: "national-secretary",
    zone: "NE",
    state: "Borno",
    competence: 70,
    loyalty: 60,
    disposition: "neutral",
    age: 50,
    gender: "Female",
    religion: "Islam",
    ethnicity: "Kanuri",
    traits: ["Meticulous administrator", "Diplomatic reserve", "Quiet reformer"],
    bio: "One of ADU's most capable administrators, Hajiya Fatima brings disciplined record-keeping to a party infamous for chaotic internal processes. She navigates intra-party tensions with careful neutrality.",
    education: { university: "University of Maiduguri", degree: "B.A. Public Administration" },
  },
  {
    characterId: "nwc-adu-004",
    partyId: "adu",
    name: "Chief Emeka Okonkwo",
    position: "national-treasurer",
    zone: "SE",
    state: "Anambra",
    competence: 85,
    loyalty: 55,
    disposition: "neutral",
    age: 56,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    traits: ["Financial hawk", "Independent-minded", "Deal maker"],
    bio: "A trained accountant and Onitsha merchant prince, Chief Emeka keeps ADU's books with forensic precision while quietly building his own political capital. His loyalty is calibrated to opportunity.",
    education: { university: "University of Nigeria, Nsukka", degree: "B.Sc. Accounting" },
  },
  {
    characterId: "nwc-adu-005",
    partyId: "adu",
    name: "Alhaji Sani Abubakar",
    position: "publicity-secretary",
    zone: "NW",
    state: "Kaduna",
    competence: 65,
    loyalty: 80,
    disposition: "supportive",
    age: 45,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    traits: ["Party loyalist", "Populist orator", "Aggressive campaigner"],
    bio: "A firebrand communicator who rose through Kaduna's youth politics to become ADU's mouthpiece. His unwavering party loyalty makes him the chairman's most reliable attack dog.",
    education: { university: "Kaduna State University", degree: "B.A. Mass Communication" },
  },
  {
    characterId: "nwc-adu-006",
    partyId: "adu",
    name: "Hon. Terhemba Agbese",
    position: "organising-secretary",
    zone: "NC",
    state: "Benue",
    competence: 72,
    loyalty: 58,
    disposition: "neutral",
    age: 47,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Tiv",
    traits: ["Grassroots mobiliser", "Pragmatic operator", "Community networker"],
    bio: "A Tiv community leader who built ADU's North Central ward structures from scratch. He is valued for his ground-level reach but keeps his own counsel on factional disputes.",
    education: { university: "Benue State University, Makurdi", degree: "B.Sc. Sociology" },
  },
  {
    characterId: "nwc-adu-007",
    partyId: "adu",
    name: "Barrister Adebayo Ogundimu",
    position: "legal-adviser",
    zone: "SW",
    state: "Ogun",
    competence: 88,
    loyalty: 62,
    disposition: "supportive",
    age: 54,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    traits: ["Constitutional expert", "Principled litigator", "Elite networker"],
    bio: "A Senior Advocate of Nigeria renowned for election-petition victories, Barrister Ogundimu safeguards ADU's legal interests with meticulous tenacity. His SAN chambers double as a party strategy room.",
    education: { university: "University of Ife (Obafemi Awolowo University)", degree: "LL.B, B.L." },
  },
  {
    characterId: "nwc-adu-008",
    partyId: "adu",
    name: "Engr. Ebitimi Amadi",
    position: "youth-women-leader",
    zone: "SS",
    state: "Rivers",
    competence: 60,
    loyalty: 45,
    disposition: "hostile",
    age: 38,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Ijaw",
    traits: ["Restless agitator", "Delta militant background", "Anti-establishment"],
    bio: "A former Niger Delta activist turned party operative, Engr. Ebitimi arrived in ADU's NWC via a controversial merger. His frustration with the old guard simmers openly.",
    education: { university: "Rivers State University of Science and Technology", degree: "B.Eng. Civil Engineering" },
  },

  // ── PFC (People's Freedom Congress) — centre-left, NC/SS base ──────
  {
    characterId: "nwc-pfc-001",
    partyId: "pfc",
    name: "Chief Solomon Lar",
    position: "national-chairman",
    zone: "NC",
    state: "Plateau",
    competence: 80,
    loyalty: 72,
    disposition: "supportive",
    age: 67,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Berom",
    traits: ["Elder statesman", "Pan-Nigerian idealist", "Measured authority"],
    bio: "A founding figure of the PFC and veteran of four political republics, Chief Solomon Lar commands almost reverential respect across the Middle Belt. He sees the PFC as democracy's last honest bulwark.",
    education: { university: "University of Jos", degree: "B.A. History" },
  },
  {
    characterId: "nwc-pfc-002",
    partyId: "pfc",
    name: "Chief Broderick Ebidougha",
    position: "vice-chairman",
    zone: "SS",
    state: "Bayelsa",
    competence: 74,
    loyalty: 65,
    disposition: "supportive",
    age: 60,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Ijaw",
    traits: ["Delta power broker", "Patronage network", "Oil-bloc voice"],
    bio: "An Ijaw chieftain and oil-sector veteran who controls Bayelsa's PFC chapters with quiet authority. His patronage extends from local government chairmen to university vice-chancellors.",
    education: { university: "University of Port Harcourt", degree: "B.Sc. Economics" },
  },
  {
    characterId: "nwc-pfc-003",
    partyId: "pfc",
    name: "Alhaji Shehu Musa",
    position: "national-secretary",
    zone: "NW",
    state: "Sokoto",
    competence: 68,
    loyalty: 58,
    disposition: "neutral",
    age: 52,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Fulani",
    traits: ["Cautious administrator", "Caliphate-connected", "Protocol-minded"],
    bio: "A former Sokoto State civil servant who carries the quiet endorsement of the Sultan's palace. Alhaji Shehu manages PFC's secretariat with old-fashioned bureaucratic formality.",
    education: { university: "Usmanu Danfodiyo University, Sokoto", degree: "B.A. Islamic Studies" },
  },
  {
    characterId: "nwc-pfc-004",
    partyId: "pfc",
    name: "Dr. Chinyere Obi",
    position: "national-treasurer",
    zone: "SE",
    state: "Imo",
    competence: 83,
    loyalty: 50,
    disposition: "hostile",
    age: 49,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    traits: ["Forensic auditor", "Outspoken critic", "Anti-corruption crusader"],
    bio: "A World Bank-trained economist who joined PFC on an anti-corruption ticket. Dr. Chinyere's refusal to cover party financial irregularities has made her powerful enemies within the NWC.",
    education: { university: "University of Nigeria, Nsukka; London School of Economics", degree: "Ph.D. Development Economics" },
  },
  {
    characterId: "nwc-pfc-005",
    partyId: "pfc",
    name: "Hon. Ishaya Danjuma",
    position: "publicity-secretary",
    zone: "NC",
    state: "Nasarawa",
    competence: 66,
    loyalty: 78,
    disposition: "supportive",
    age: 43,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Eggon",
    traits: ["Spin doctor", "Social-media native", "Loyal party man"],
    bio: "A former broadcast journalist who handles PFC's messaging with youthful energy and unshakeable party devotion. His WhatsApp broadcast lists reach over two million subscribers.",
    education: { university: "Nasarawa State University, Keffi", degree: "B.Sc. Mass Communication" },
  },
  {
    characterId: "nwc-pfc-006",
    partyId: "pfc",
    name: "Chief Yetunde Adeyemo",
    position: "organising-secretary",
    zone: "SW",
    state: "Oyo",
    competence: 71,
    loyalty: 63,
    disposition: "neutral",
    age: 53,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Yoruba",
    traits: ["Market-woman mobiliser", "Gender champion", "Pragmatic realist"],
    bio: "A veteran Ibadan political organiser who has delivered Oyo's women-bloc vote across three parties. Chief Yetunde joined PFC for ideological reasons but keeps pragmatic options open.",
    education: { university: "University of Ibadan", degree: "B.A. Sociology" },
  },
  {
    characterId: "nwc-pfc-007",
    partyId: "pfc",
    name: "Barrister Aisha Mohammed",
    position: "legal-adviser",
    zone: "NE",
    state: "Adamawa",
    competence: 77,
    loyalty: 55,
    disposition: "neutral",
    age: 46,
    gender: "Female",
    religion: "Islam",
    ethnicity: "Fulani",
    traits: ["Rights-oriented lawyer", "Bilingual communicator", "Proceduralist"],
    bio: "A human rights barrister and Adamawa State Bar Association chair who brings international law sensibility to PFC's internal governance. She represents the party's progressive intellectual wing.",
    education: { university: "University of Abuja; University of London", degree: "LL.M. International Law" },
  },
  {
    characterId: "nwc-pfc-008",
    partyId: "pfc",
    name: "Engr. Tombra Ogboju",
    position: "youth-women-leader",
    zone: "SS",
    state: "Delta",
    competence: 62,
    loyalty: 70,
    disposition: "supportive",
    age: 36,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Urhobo",
    traits: ["Youth galvaniser", "Pipeline-community advocate", "Party loyalist"],
    bio: "A young Urhobo engineer who parlayed community development work into PFC youth politics. He delivers Delta's urban youth vote with infectious enthusiasm for the party's social-democratic agenda.",
    education: { university: "Delta State University, Abraka", degree: "B.Eng. Petroleum Engineering" },
  },

  // ── NDM (New Direction Movement) — progressive, SW/SE base ─────────
  {
    characterId: "nwc-ndm-001",
    partyId: "ndm",
    name: "Prof. Olufemi Adebanjo",
    position: "national-chairman",
    zone: "SW",
    state: "Ekiti",
    competence: 86,
    loyalty: 70,
    disposition: "supportive",
    age: 64,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    traits: ["Intellectual heavyweight", "Policy reformer", "Principled democrat"],
    bio: "A former economics professor who left academia to lead NDM's charge for structural reform. Prof. Adebanjo's manifestos are treated as policy blueprints by development economists.",
    education: { university: "University of Ibadan; Oxford University", degree: "D.Phil. Development Economics" },
  },
  {
    characterId: "nwc-ndm-002",
    partyId: "ndm",
    name: "Dr. Nkechi Azikiwe",
    position: "vice-chairman",
    zone: "SE",
    state: "Enugu",
    competence: 79,
    loyalty: 66,
    disposition: "supportive",
    age: 55,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    traits: ["Feminist organiser", "Thought leader", "Coalition builder"],
    bio: "A Georgetown-trained political scientist bearing one of Nigeria's most iconic surnames, Dr. Nkechi carries the NDM's gender-equity platform with scholarly rigour and grassroots charm.",
    education: { university: "University of Nigeria, Nsukka; Georgetown University", degree: "Ph.D. Political Science" },
  },
  {
    characterId: "nwc-ndm-003",
    partyId: "ndm",
    name: "Alhaji Bala Usman",
    position: "national-secretary",
    zone: "NW",
    state: "Zamfara",
    competence: 64,
    loyalty: 48,
    disposition: "neutral",
    age: 51,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    traits: ["Reluctant reformer", "Tribal-interest guard", "Fence-sitter"],
    bio: "Alhaji Bala arrived in NDM after a falling-out with the NSF old guard. His allegiance to progressive ideals is thin; he is primarily motivated by protecting Zamfara interests.",
    education: { university: "Bayero University, Kano", degree: "B.A. Political Science" },
  },
  {
    characterId: "nwc-ndm-004",
    partyId: "ndm",
    name: "Hon. Terngu Ikyaator",
    position: "national-treasurer",
    zone: "NC",
    state: "Benue",
    competence: 73,
    loyalty: 55,
    disposition: "neutral",
    age: 48,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Tiv",
    traits: ["Steady steward", "Cautious spender", "Factional balancer"],
    bio: "A chartered accountant and Benue agribusiness investor, Hon. Terngu manages NDM's finances with conservative prudence. He stays out of ideological battles and focuses on the party's fiscal health.",
    education: { university: "Ahmadu Bello University, Zaria", degree: "B.Sc. Accounting" },
  },
  {
    characterId: "nwc-ndm-005",
    partyId: "ndm",
    name: "Chief Kayode Fayemi",
    position: "publicity-secretary",
    zone: "SW",
    state: "Ondo",
    competence: 81,
    loyalty: 72,
    disposition: "supportive",
    age: 57,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    traits: ["Public intellectual", "Policy-driven communicator", "Media insider"],
    bio: "A former governor turned NDM's chief image-maker, Chief Kayode crafts narratives that position the party as Nigeria's credible alternative. His op-eds trend nationally.",
    education: { university: "University of Lagos; King's College London", degree: "M.Sc. International Relations" },
  },
  {
    characterId: "nwc-ndm-006",
    partyId: "ndm",
    name: "Alhaji Adamu Garba",
    position: "organising-secretary",
    zone: "NE",
    state: "Yobe",
    competence: 58,
    loyalty: 42,
    disposition: "hostile",
    age: 44,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Kanuri",
    traits: ["Opportunist defector", "Grudge-bearer", "Disruptive presence"],
    bio: "Alhaji Adamu was placed in NDM through a shotgun merger and has never reconciled himself to the party's progressive platform. He actively undermines organising drives he sees as culturally alien.",
    education: { university: "University of Maiduguri", degree: "B.Sc. Public Administration" },
  },
  {
    characterId: "nwc-ndm-007",
    partyId: "ndm",
    name: "Barrister Obiageli Eze",
    position: "legal-adviser",
    zone: "SE",
    state: "Abia",
    competence: 84,
    loyalty: 60,
    disposition: "neutral",
    age: 50,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Igbo",
    traits: ["Constitutional scholar", "Precise draftsperson", "Professional distance"],
    bio: "One of Nigeria's foremost election-law specialists, Barrister Obiageli has won landmark tribunal cases across five states. She serves NDM with professional competence while maintaining career independence.",
    education: { university: "University of Nigeria, Nsukka; Nigerian Law School", degree: "LL.B, B.L., LL.M." },
  },
  {
    characterId: "nwc-ndm-008",
    partyId: "ndm",
    name: "Comrade Ibinabo Hart",
    position: "youth-women-leader",
    zone: "SS",
    state: "Rivers",
    competence: 67,
    loyalty: 52,
    disposition: "neutral",
    age: 37,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Kalabari",
    traits: ["Labour activist", "Women's-rights champion", "Impatient idealist"],
    bio: "A former NLC youth wing leader, Comrade Ibinabo champions Rivers' working-class women with fiery advocacy. She pushes NDM toward bolder gender-equality commitments than the leadership is comfortable with.",
    education: { university: "University of Port Harcourt", degree: "B.A. Sociology" },
  },

  // ── NSF (National Solidarity Front) — populist, NW/NE base ─────────
  {
    characterId: "nwc-nsf-001",
    partyId: "nsf",
    name: "Alhaji Abdullahi Ganduje",
    position: "national-chairman",
    zone: "NW",
    state: "Katsina",
    competence: 75,
    loyalty: 82,
    disposition: "supportive",
    age: 65,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    traits: ["Old-guard tactician", "Bloc-vote controller", "Patronage master"],
    bio: "A NSF patriarch who has survived every political storm since the Second Republic. Alhaji Abdullahi's control of Katsina's bloc votes makes him indispensable to the party's northern dominance.",
    education: { university: "Ahmadu Bello University, Zaria", degree: "B.Sc. Public Administration" },
  },
  {
    characterId: "nwc-nsf-002",
    partyId: "nsf",
    name: "Alhaji Kashim Ibrahim",
    position: "vice-chairman",
    zone: "NE",
    state: "Borno",
    competence: 70,
    loyalty: 76,
    disposition: "supportive",
    age: 61,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Kanuri",
    traits: ["Security-focused pragmatist", "Lake Chad influence", "Quiet enforcer"],
    bio: "Alhaji Kashim's family connections span Borno's traditional emirate and military networks. He is NSF's go-to broker for northeastern electoral arithmetic and security-sector relationships.",
    education: { university: "University of Maiduguri", degree: "B.A. History" },
  },
  {
    characterId: "nwc-nsf-003",
    partyId: "nsf",
    name: "Chief Folarin Ogundipe",
    position: "national-secretary",
    zone: "SW",
    state: "Lagos",
    competence: 63,
    loyalty: 50,
    disposition: "neutral",
    age: 50,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    traits: ["Urban opportunist", "Party-hopper history", "Transactional loyalist"],
    bio: "Chief Folarin arrived in NSF after stints in three other parties. He manages the party's Lagos secretariat competently enough while keeping channels open to potential future patrons.",
    education: { university: "University of Lagos", degree: "B.Sc. Business Administration" },
  },
  {
    characterId: "nwc-nsf-004",
    partyId: "nsf",
    name: "Dr. Okechukwu Nwankpa",
    position: "national-treasurer",
    zone: "SE",
    state: "Ebonyi",
    competence: 72,
    loyalty: 45,
    disposition: "hostile",
    age: 53,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    traits: ["Frustrated technocrat", "Ethnic-interest voice", "Contrarian"],
    bio: "A World Bank consultant who entered politics to advance Ebonyi's development agenda. Dr. Okechukwu found NSF's northern-dominated culture unwelcoming and now occupies his seat as a reluctant dissenter.",
    education: { university: "Ebonyi State University; Johns Hopkins University", degree: "M.P.H. Health Economics" },
  },
  {
    characterId: "nwc-nsf-005",
    partyId: "nsf",
    name: "Alhaji Musa Rabiu",
    position: "publicity-secretary",
    zone: "NW",
    state: "Jigawa",
    competence: 68,
    loyalty: 85,
    disposition: "supportive",
    age: 44,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    traits: ["Ardent loyalist", "Hausa-media veteran", "Party propagandist"],
    bio: "A Radio Jigawa broadcaster-turned-party-spokesman, Alhaji Musa delivers NSF's message with passionate conviction across Hausa-language media. His loyalty to the party chairman is absolute.",
    education: { university: "Federal Polytechnic, Kaura-Namoda", degree: "HND Mass Communication" },
  },
  {
    characterId: "nwc-nsf-006",
    partyId: "nsf",
    name: "Mallam Ibrahim Shettima",
    position: "organising-secretary",
    zone: "NE",
    state: "Gombe",
    competence: 60,
    loyalty: 70,
    disposition: "supportive",
    age: 46,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Kanuri",
    traits: ["Party mobiliser", "Rural-outreach specialist", "Mosque-network organiser"],
    bio: "Mallam Ibrahim built NSF's Gombe chapter from a handful of supporters into the state's second-largest party network by engaging religious community leaders and traditional rulers.",
    education: { university: "Gombe State University", degree: "B.Sc. Political Science" },
  },
  {
    characterId: "nwc-nsf-007",
    partyId: "nsf",
    name: "Barrister Nuhu Idris",
    position: "legal-adviser",
    zone: "NC",
    state: "Niger",
    competence: 78,
    loyalty: 58,
    disposition: "neutral",
    age: 52,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Nupe",
    traits: ["Careful constitutionalist", "Cross-bloc intermediary", "Detached professional"],
    bio: "A Minna-based corporate lawyer who advises NSF on electoral law while maintaining a private practice that keeps him financially independent from party politics.",
    education: { university: "Ahmadu Bello University, Zaria; Nigerian Law School", degree: "LL.B, B.L." },
  },
  {
    characterId: "nwc-nsf-008",
    partyId: "nsf",
    name: "Comrade Preye Aganaba",
    position: "youth-women-leader",
    zone: "SS",
    state: "Bayelsa",
    competence: 55,
    loyalty: 40,
    disposition: "hostile",
    age: 34,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Ijaw",
    traits: ["Militant activist", "Oil-spill advocate", "Anti-establishment"],
    bio: "A former Ijaw Youth Council leader, Comrade Preye entered NSF through a coerced alignment and has never disguised her contempt for the party's northern establishment. She is a volatile but authentic voice.",
    education: { university: "Niger Delta University, Wilberforce Island", degree: "B.Sc. Environmental Science" },
  },

  // ── TLA (The Liberty Alliance) — regionalist, SE/SS base ───────────
  {
    characterId: "nwc-tla-001",
    partyId: "tla",
    name: "Chief Ikenna Nnamdi",
    position: "national-chairman",
    zone: "SE",
    state: "Anambra",
    competence: 80,
    loyalty: 78,
    disposition: "supportive",
    age: 63,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    traits: ["Igbo nationalist", "Business empire", "Commanding presence"],
    bio: "A Onitsha merchant chief who bankrolled TLA's founding and shaped its federalist platform. Chief Ikenna commands the Igbo business community's respect and uses it to fund party operations.",
    education: { university: "University of Nigeria, Nsukka", degree: "B.Sc. Commerce" },
  },
  {
    characterId: "nwc-tla-002",
    partyId: "tla",
    name: "Chief Effiong Bassey",
    position: "vice-chairman",
    zone: "SS",
    state: "Cross River",
    competence: 73,
    loyalty: 72,
    disposition: "supportive",
    age: 59,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Efik",
    traits: ["Efik cultural ambassador", "Tourism-sector patron", "Consensus seeker"],
    bio: "An Efik traditional title-holder and Calabar tourism promoter, Chief Effiong anchors TLA in the South South with aristocratic authority and personal charm that transcends ethnic boundaries.",
    education: { university: "University of Calabar", degree: "B.A. Tourism Management" },
  },
  {
    characterId: "nwc-tla-003",
    partyId: "tla",
    name: "Alhaji Lawal Dankadai",
    position: "national-secretary",
    zone: "NW",
    state: "Kebbi",
    competence: 58,
    loyalty: 40,
    disposition: "hostile",
    age: 48,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    traits: ["Political prisoner", "Marginalised northerner", "Resentful operative"],
    bio: "Alhaji Lawal was installed in TLA's NWC as part of a federal-character arrangement he openly resents. His secretariat work is perfunctory; his real energies go toward building an exit strategy.",
    education: { university: "Kebbi State University of Science and Technology", degree: "B.Sc. Business Management" },
  },
  {
    characterId: "nwc-tla-004",
    partyId: "tla",
    name: "Chief Adewale Tinubu",
    position: "national-treasurer",
    zone: "SW",
    state: "Osun",
    competence: 76,
    loyalty: 55,
    disposition: "neutral",
    age: 55,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    traits: ["Financial pragmatist", "Osun power broker", "Regionalist"],
    bio: "A former Osun State accountant-general who manages TLA's finances with technical competence. Chief Adewale's political loyalty lies primarily with Southwest regionalist interests rather than the party itself.",
    education: { university: "Obafemi Awolowo University, Ile-Ife", degree: "B.Sc. Accounting" },
  },
  {
    characterId: "nwc-tla-005",
    partyId: "tla",
    name: "Dr. Chukwuma Soludo",
    position: "publicity-secretary",
    zone: "SE",
    state: "Enugu",
    competence: 85,
    loyalty: 68,
    disposition: "supportive",
    age: 58,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    traits: ["Technocratic communicator", "Pan-African intellectual", "Data-driven strategist"],
    bio: "An economist of international standing, Dr. Chukwuma frames TLA's federalism agenda in hard-nosed economic terms that attract educated Nigerians tired of ethnic platitudes.",
    education: { university: "University of Nigeria, Nsukka; MIT", degree: "Ph.D. Economics" },
  },
  {
    characterId: "nwc-tla-006",
    partyId: "tla",
    name: "Hon. Monday Okpebholo",
    position: "organising-secretary",
    zone: "SS",
    state: "Edo",
    competence: 65,
    loyalty: 62,
    disposition: "neutral",
    age: 46,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Bini",
    traits: ["Ward-level operator", "Trade-union background", "Steady mobiliser"],
    bio: "A former Edo market-traders union chairman who built TLA's Benin City base through patient ward-by-ward organisation. His politics are pragmatic and community-centred.",
    education: { university: "Ambrose Alli University, Ekpoma", degree: "B.Sc. Political Science" },
  },
  {
    characterId: "nwc-tla-007",
    partyId: "tla",
    name: "Barrister Yakubu Dogara",
    position: "legal-adviser",
    zone: "NE",
    state: "Bauchi",
    competence: 70,
    loyalty: 45,
    disposition: "neutral",
    age: 50,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Jarawa",
    traits: ["Parliamentary proceduralist", "Christian-minority voice", "Detached counsel"],
    bio: "A Bauchi-based lawyer representing TLA's thin northeastern presence, Barrister Yakubu handles legal matters with competence while maintaining cautious distance from the party's more strident regionalism.",
    education: { university: "University of Jos; Nigerian Law School", degree: "LL.B, B.L." },
  },
  {
    characterId: "nwc-tla-008",
    partyId: "tla",
    name: "Comrade Joseph Ityav",
    position: "youth-women-leader",
    zone: "NC",
    state: "Benue",
    competence: 56,
    loyalty: 50,
    disposition: "hostile",
    age: 35,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Tiv",
    traits: ["Herdsmen-crisis survivor", "Aggrieved youth", "Reluctant party man"],
    bio: "A Benue displacement-camp community organiser who entered TLA for resource access. Comrade Joseph's primary loyalty is to his Tiv community, not to a party he regards as too Igbo-centric.",
    education: { university: "University of Agriculture, Makurdi", degree: "B.Sc. Agricultural Economics" },
  },

  // ── HDP (Heritage Democratic Party) — traditionalist, NE/NC base ───
  {
    characterId: "nwc-hdp-001",
    partyId: "hdp",
    name: "Alhaji Muhammadu Jibril",
    position: "national-chairman",
    zone: "NE",
    state: "Bauchi",
    competence: 74,
    loyalty: 80,
    disposition: "supportive",
    age: 66,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Fulani",
    traits: ["Traditionalist patriarch", "Emirate-connected", "Measured conservative"],
    bio: "A scion of a Bauchi emirate family and lifelong advocate of traditional governance structures, Alhaji Muhammadu steers HDP toward conservative Islamic federalism while maintaining inter-faith alliances.",
    education: { university: "Ahmadu Bello University, Zaria", degree: "B.A. Arabic and Islamic Studies" },
  },
  {
    characterId: "nwc-hdp-002",
    partyId: "hdp",
    name: "Alhaji Tanko Yakassai",
    position: "vice-chairman",
    zone: "NC",
    state: "Kogi",
    competence: 69,
    loyalty: 73,
    disposition: "supportive",
    age: 61,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Igala",
    traits: ["Cross-zone bridge", "Confluence-area operator", "Party loyalist"],
    bio: "An Igala Muslim who bridges HDP's northeastern base with North Central communities, Alhaji Tanko has built an unusual coalition that crosses the religion and ethnicity lines of Kogi politics.",
    education: { university: "Kogi State University, Anyigba", degree: "B.Sc. Political Science" },
  },
  {
    characterId: "nwc-hdp-003",
    partyId: "hdp",
    name: "Chief Adeniyi Akintola",
    position: "national-secretary",
    zone: "SW",
    state: "Oyo",
    competence: 66,
    loyalty: 52,
    disposition: "neutral",
    age: 53,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    traits: ["Ibadan kingmaker aspirant", "Bureaucratic survivor", "Cautious participant"],
    bio: "Chief Adeniyi joined HDP after losing out in Oyo's ADU primary. He manages the national secretariat competently while watching for opportunities to return to Southwest mainstream politics.",
    education: { university: "University of Ibadan", degree: "B.A. Public Administration" },
  },
  {
    characterId: "nwc-hdp-004",
    partyId: "hdp",
    name: "Chief Okezie Ikpeazu",
    position: "national-treasurer",
    zone: "SE",
    state: "Abia",
    competence: 71,
    loyalty: 48,
    disposition: "neutral",
    age: 55,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    traits: ["Finance-literate pragmatist", "Cross-regional bridge", "Uncommitted centrist"],
    bio: "A former Abia State commissioner for finance who keeps HDP's accounts balanced while maintaining discreet relationships with competing parties. His allegiance follows the best deal available.",
    education: { university: "University of Nigeria, Nsukka", degree: "B.Sc. Finance" },
  },
  {
    characterId: "nwc-hdp-005",
    partyId: "hdp",
    name: "Mallam Abubakar Atiku",
    position: "publicity-secretary",
    zone: "NE",
    state: "Adamawa",
    competence: 77,
    loyalty: 85,
    disposition: "supportive",
    age: 56,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Fulani",
    traits: ["Fulani-bloc spokesman", "Traditional media expert", "Devout loyalist"],
    bio: "Mallam Abubakar commands HDP's northern media presence through a network of Hausa-language newspapers and radio stations he helped found. His fanatical party loyalty is matched only by his communication skill.",
    education: { university: "Bayero University, Kano", degree: "B.A. Communication Arts" },
  },
  {
    characterId: "nwc-hdp-006",
    partyId: "hdp",
    name: "Hon. Zakari Abubakar",
    position: "organising-secretary",
    zone: "NC",
    state: "Nasarawa",
    competence: 62,
    loyalty: 65,
    disposition: "neutral",
    age: 47,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Gwari",
    traits: ["Rural-outreach organiser", "Modest ambition", "Reliable foot soldier"],
    bio: "A quiet worker who has registered more rural HDP chapters than anyone in the party's history. Hon. Zakari's organisational output is impressive even if his political profile remains low.",
    education: { university: "Nasarawa State University, Keffi", degree: "B.Sc. Sociology" },
  },
  {
    characterId: "nwc-hdp-007",
    partyId: "hdp",
    name: "Barrister Aminu Waziri",
    position: "legal-adviser",
    zone: "NW",
    state: "Sokoto",
    competence: 80,
    loyalty: 58,
    disposition: "neutral",
    age: 52,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Fulani",
    traits: ["Sharia-law specialist", "Constitutional scholar", "Professional detachment"],
    bio: "One of Nigeria's foremost Islamic jurisprudence and constitutional lawyers, Barrister Aminu keeps HDP's legal affairs pristine while earning considerably more from private practice than from party service.",
    education: { university: "Usmanu Danfodiyo University, Sokoto; University of London", degree: "LL.M. Islamic Law" },
  },
  {
    characterId: "nwc-hdp-008",
    partyId: "hdp",
    name: "Comrade Douye Diri",
    position: "youth-women-leader",
    zone: "SS",
    state: "Bayelsa",
    competence: 55,
    loyalty: 38,
    disposition: "hostile",
    age: 37,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Ijaw",
    traits: ["Militant youth leader", "Resource-control advocate", "Outsider in HDP"],
    bio: "Comrade Douye was brought into HDP's NWC as a southern-inclusion gesture he never asked for. His Ijaw-youth-movement roots make him culturally incompatible with the party's conservative Islamic identity.",
    education: { university: "Niger Delta University, Wilberforce Island", degree: "B.Sc. Political Science" },
  },

  // ── PAP (Progressive Action Party) — social democratic, SS base ────
  {
    characterId: "nwc-pap-001",
    partyId: "pap",
    name: "Chief Timi Alaibe",
    position: "national-chairman",
    zone: "SS",
    state: "Bayelsa",
    competence: 78,
    loyalty: 75,
    disposition: "supportive",
    age: 60,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Ijaw",
    traits: ["Delta development champion", "Presidential ambition", "Community patriarch"],
    bio: "A former NDDC managing director who channelled development projects into political capital, Chief Timi leads PAP with the confidence of a man who knows where the oil money flows and how to direct it.",
    education: { university: "University of Port Harcourt", degree: "B.Eng. Civil Engineering" },
  },
  {
    characterId: "nwc-pap-002",
    partyId: "pap",
    name: "Engr. Godwin Emefiele",
    position: "vice-chairman",
    zone: "SS",
    state: "Delta",
    competence: 72,
    loyalty: 70,
    disposition: "supportive",
    age: 58,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Urhobo",
    traits: ["Technocratic administrator", "Banking-sector pedigree", "Measured loyalist"],
    bio: "An Urhobo technocrat with a banking and central-bank background, Engr. Godwin brings PAP a credibility in financial governance that distinguishes it from more populist rivals.",
    education: { university: "University of Nigeria, Nsukka; Wharton School", degree: "M.B.A. Finance" },
  },
  {
    characterId: "nwc-pap-003",
    partyId: "pap",
    name: "Chief Oladipo Abiodun",
    position: "national-secretary",
    zone: "SW",
    state: "Ogun",
    competence: 65,
    loyalty: 55,
    disposition: "neutral",
    age: 51,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    traits: ["Gateway-state networker", "Federal-character placeholder", "Quiet technocrat"],
    bio: "An Ogun State former permanent secretary who fills PAP's Southwest slot with bureaucratic reliability. Chief Oladipo's primary concern is maintaining his Abeokuta patronage network.",
    education: { university: "Obafemi Awolowo University, Ile-Ife", degree: "B.Sc. Public Administration" },
  },
  {
    characterId: "nwc-pap-004",
    partyId: "pap",
    name: "Dr. Ugochukwu Nnaji",
    position: "national-treasurer",
    zone: "SE",
    state: "Enugu",
    competence: 80,
    loyalty: 50,
    disposition: "neutral",
    age: 52,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    traits: ["Energy-sector expert", "Fiscal disciplinarian", "Independent-minded"],
    bio: "A former Enugu State energy commissioner with a Harvard Business School executive education, Dr. Ugochukwu manages PAP's finances with corporate rigour and tells the chairman uncomfortable truths.",
    education: { university: "University of Nigeria, Nsukka; Harvard Business School", degree: "Ph.D. Energy Economics" },
  },
  {
    characterId: "nwc-pap-005",
    partyId: "pap",
    name: "Alhaji Saminu Turaki",
    position: "publicity-secretary",
    zone: "NW",
    state: "Jigawa",
    competence: 60,
    loyalty: 42,
    disposition: "hostile",
    age: 49,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Hausa",
    traits: ["Disillusioned northerner", "Reluctant spokesman", "Passive-aggressive communicator"],
    bio: "Alhaji Saminu was parachuted into PAP's NWC as a northern-inclusion token. He finds the party's social-democratic platform alien to his conservative instincts and communicates it without conviction.",
    education: { university: "Bayero University, Kano", degree: "B.A. Mass Communication" },
  },
  {
    characterId: "nwc-pap-006",
    partyId: "pap",
    name: "Mallam Buba Galadima",
    position: "organising-secretary",
    zone: "NE",
    state: "Yobe",
    competence: 58,
    loyalty: 45,
    disposition: "hostile",
    age: 50,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Kanuri",
    traits: ["Serial political wanderer", "Mercenary organiser", "Grudge-filled operator"],
    bio: "A veteran of five parties in twenty years, Mallam Buba organises PAP's northeastern chapters with mechanical efficiency but zero ideological commitment. He is visibly scouting his next political home.",
    education: { university: "University of Maiduguri", degree: "B.Sc. Political Science" },
  },
  {
    characterId: "nwc-pap-007",
    partyId: "pap",
    name: "Barrister Sylvanus Nenshi",
    position: "legal-adviser",
    zone: "NC",
    state: "Plateau",
    competence: 75,
    loyalty: 60,
    disposition: "neutral",
    age: 49,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Ngas",
    traits: ["Human-rights advocate", "Jos-crisis survivor", "Careful constitutionalist"],
    bio: "A Plateau State bar leader who made his name representing displaced communities during the Jos crisis. Barrister Sylvanus brings PAP a moral authority on minority-rights issues that no other party NWC member can match.",
    education: { university: "University of Jos; Nigerian Law School", degree: "LL.B, B.L., LL.M." },
  },
  {
    characterId: "nwc-pap-008",
    partyId: "pap",
    name: "Comrade Fehintola Balogun",
    position: "youth-women-leader",
    zone: "SW",
    state: "Lagos",
    competence: 68,
    loyalty: 65,
    disposition: "supportive",
    age: 39,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Yoruba",
    traits: ["Lagos feminist activist", "Digital organiser", "Generational voice"],
    bio: "A former #EndSARS digital coordinator who pivoted into formal party politics through PAP's youth wing. Comrade Fehintola represents Lagos' activist generation and brings social-media reach that money cannot buy.",
    education: { university: "University of Lagos", degree: "B.Sc. Computer Science" },
  },

  // ── UPA (United People's Alliance) — ethnic federalist, SW/NC base ─
  {
    characterId: "nwc-upa-001",
    partyId: "upa",
    name: "Chief Olusegun Awolowo",
    position: "national-chairman",
    zone: "SW",
    state: "Ondo",
    competence: 82,
    loyalty: 77,
    disposition: "supportive",
    age: 65,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Yoruba",
    traits: ["Awoist ideologue", "Federalism champion", "Authoritative patriarch"],
    bio: "A grand-nephew of the Sage of Ikenne who has made the Awolowo federalist philosophy the bedrock of UPA's platform. Chief Olusegun commands reverence in Yoruba intellectual circles and uses it to discipline party ranks.",
    education: { university: "University of Ibadan; London School of Economics", degree: "M.Sc. Political Economy" },
  },
  {
    characterId: "nwc-upa-002",
    partyId: "upa",
    name: "Hon. Danladi Abubakar",
    position: "vice-chairman",
    zone: "NC",
    state: "Niger",
    competence: 70,
    loyalty: 72,
    disposition: "supportive",
    age: 57,
    gender: "Male",
    religion: "Islam",
    ethnicity: "Nupe",
    traits: ["Confluence-zone bridge", "Quiet consensus-builder", "Middle-Belt voice"],
    bio: "A Nupe former legislator who anchors UPA's North Central presence, Hon. Danladi translates the party's federalist agenda into terms that resonate with the Middle Belt's multi-ethnic communities.",
    education: { university: "University of Ilorin", degree: "B.Sc. Political Science" },
  },
  {
    characterId: "nwc-upa-003",
    partyId: "upa",
    name: "Chief Rotimi Amaechi",
    position: "national-secretary",
    zone: "SS",
    state: "Rivers",
    competence: 75,
    loyalty: 55,
    disposition: "neutral",
    age: 56,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Ikwerre",
    traits: ["Rivers power broker", "Confrontational dealmaker", "Independently ambitious"],
    bio: "A former Rivers State governor who landed in UPA after exhausting his welcome in two other parties. Chief Rotimi runs the secretariat with the impatience of a man who believes he should be running the whole party.",
    education: { university: "University of Port Harcourt", degree: "B.A. English" },
  },
  {
    characterId: "nwc-upa-004",
    partyId: "upa",
    name: "Dr. Obinna Uzoh",
    position: "national-treasurer",
    zone: "SE",
    state: "Imo",
    competence: 78,
    loyalty: 50,
    disposition: "neutral",
    age: 52,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igbo",
    traits: ["Medical-sector investor", "Diaspora-linked financier", "Cautious independent"],
    bio: "An Imo-born medical doctor turned healthcare investor, Dr. Obinna manages UPA's finances with clinical precision. His diaspora funding connections make him valuable but also hard to control.",
    education: { university: "University of Nigeria, Enugu Campus; Johns Hopkins", degree: "M.D., M.P.H." },
  },
  {
    characterId: "nwc-upa-005",
    partyId: "upa",
    name: "Chief Modupe Adeleke",
    position: "publicity-secretary",
    zone: "SW",
    state: "Osun",
    competence: 73,
    loyalty: 80,
    disposition: "supportive",
    age: 47,
    gender: "Female",
    religion: "Christianity",
    ethnicity: "Yoruba",
    traits: ["Yoruba cultural communicator", "Artistic-community connector", "Impassioned loyalist"],
    bio: "A former Osun cultural affairs commissioner, Chief Modupe weaves Yoruba cultural identity into UPA's political messaging with striking effect. Her loyalty to the party's Awoist roots is personal and deep.",
    education: { university: "Obafemi Awolowo University, Ile-Ife", degree: "B.A. Theatre Arts" },
  },
  {
    characterId: "nwc-upa-006",
    partyId: "upa",
    name: "Hon. Simon Achuba",
    position: "organising-secretary",
    zone: "NC",
    state: "Kogi",
    competence: 64,
    loyalty: 68,
    disposition: "neutral",
    age: 50,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Igala",
    traits: ["Kogi ward-captain network", "Patronage distributor", "Steady operator"],
    bio: "A former Kogi deputy governor who built UPA's North Central chapter network through tireless ward-by-ward work. Hon. Simon is valued for delivery rather than ideas.",
    education: { university: "Kogi State University, Anyigba", degree: "B.Sc. Business Administration" },
  },
  {
    characterId: "nwc-upa-007",
    partyId: "upa",
    name: "Barrister Maryam Aliyu",
    position: "legal-adviser",
    zone: "NW",
    state: "Kaduna",
    competence: 76,
    loyalty: 44,
    disposition: "hostile",
    age: 44,
    gender: "Female",
    religion: "Islam",
    ethnicity: "Hausa",
    traits: ["Gender-rights crusader", "Structural critic", "Northern women's voice"],
    bio: "A Kaduna-based human-rights lawyer who accepted UPA's legal-adviser role specifically to push the party on northern women's representation. Her open criticism of the old guard's tokenism makes her deeply uncomfortable company for the party establishment.",
    education: { university: "Ahmadu Bello University, Zaria; University of London", degree: "LL.M. Human Rights Law" },
  },
  {
    characterId: "nwc-upa-008",
    partyId: "upa",
    name: "Comrade Adamu Ciroma",
    position: "youth-women-leader",
    zone: "NE",
    state: "Taraba",
    competence: 57,
    loyalty: 48,
    disposition: "hostile",
    age: 36,
    gender: "Male",
    religion: "Christianity",
    ethnicity: "Jukun",
    traits: ["Minority-rights agitator", "Inter-ethnic conflict survivor", "Alienated youth leader"],
    bio: "A Jukun activist who witnessed the Taraba inter-ethnic conflicts first-hand and channelled his anger into UPA youth politics. Comrade Adamu's resentment of both major ethnic groups in his party makes him an unpredictable voice.",
    education: { university: "Taraba State University, Jalingo", degree: "B.Sc. Political Science" },
  },
];
