// client/src/lib/religiousLeaderPool.ts
// 10 hand-crafted religious leader candidates — 5 per position
import type { ReligiousLeaderCandidate } from "./religiousLeaderTypes";

export const RELIGIOUS_LEADER_CANDIDATES: ReligiousLeaderCandidate[] = [
  // ═══ President, Christian Association of Nigeria (5) ═══
  {
    name: "Rev. Dr. Emmanuel Okonkwo",
    state: "Anambra", zone: "SE", age: 62, gender: "Male",
    religion: "Christianity", ethnicity: "Igbo", avatar: "EO",
    traits: ["Ecumenical Leader", "Interfaith Diplomat", "Pan-Nigerian"],
    bio: "A prominent Anglican bishop who has spent three decades building bridges between denominations. Known for his measured diplomacy and deep institutional knowledge. Led CAN's southeast chapter for eight years before rising to national prominence.",
    education: "University of Nigeria Nsukka (Theology), Wycliffe Hall Oxford (MDiv), Cambridge (PhD Divinity)",
    disposition: "supportive", influence: 88,
    qualifiedFor: ["pres-christian-society"],
    honorific: "Rev. Dr.",
    competencies: {
      professional: { economics: 45, diplomacy: 82, security: 30, communications: 65, legal: 50, administration: 70, technology: 35, management: 74, politics: 72 },
      personal: { loyalty: 70, charisma: 78, leadership: 85, ambition: 55, integrity: 90, resilience: 72, intrigue: 25, discretion: 77 },
    },
  },
  {
    name: "Archbishop Felix Adeyemi",
    state: "Ogun", zone: "SW", age: 58, gender: "Male",
    religion: "Christianity", ethnicity: "Yoruba", avatar: "FA",
    traits: ["Televangelist", "Prosperity Gospel", "Youth Pastor"],
    bio: "Head of one of Nigeria's largest Pentecostal ministries with a global congregation. His televised crusades draw millions. His popularity and media reach make him a formidable candidate, though traditionalists question his prosperity theology.",
    education: "University of Lagos (Mathematics), Redeemed Seminary (MDiv), Oral Roberts University (DD)",
    disposition: "neutral", influence: 92,
    qualifiedFor: ["pres-christian-society"],
    honorific: "Archbishop",
    competencies: {
      professional: { economics: 60, diplomacy: 55, security: 25, communications: 90, legal: 35, administration: 65, technology: 50, management: 80, politics: 67 },
      personal: { loyalty: 55, charisma: 95, leadership: 80, ambition: 75, integrity: 60, resilience: 70, intrigue: 40, discretion: 72 },
    },
  },
  {
    name: "Bishop Matthew Kukah",
    state: "Kaduna", zone: "NW", age: 70, gender: "Male",
    religion: "Christianity", ethnicity: "Kataf", avatar: "MK",
    traits: ["Social Justice Advocate", "Political Operator", "Pan-Nigerian"],
    bio: "A Catholic bishop known for fearless criticism of both military and civilian governments. His Christmas messages are anticipated as much as policy statements. He sees the church's role as speaking truth to power regardless of political consequences.",
    education: "St. Augustine's Seminary Kaduna, University of London (MA Political Science), SOAS London (PhD)",
    disposition: "critical", influence: 90,
    qualifiedFor: ["pres-christian-society"],
    honorific: "Bishop",
    competencies: {
      professional: { economics: 55, diplomacy: 78, security: 40, communications: 85, legal: 65, administration: 60, technology: 30, management: 63, politics: 61 },
      personal: { loyalty: 45, charisma: 80, leadership: 82, ambition: 50, integrity: 92, resilience: 85, intrigue: 35, discretion: 81 },
    },
  },
  {
    name: "Reverend Samson Ayokunle",
    state: "Oyo", zone: "SW", age: 64, gender: "Male",
    religion: "Christianity", ethnicity: "Yoruba", avatar: "SA",
    traits: ["Builder of Institutions", "Conservative Theologian", "Community Builder"],
    bio: "President of the Nigerian Baptist Convention and a methodical administrator who has strengthened denominational structures across the country. He favours quiet diplomacy with government over public confrontation.",
    education: "Baptist College Ogbomoso, University of Ibadan (PhD Theology), Southern Baptist Seminary Kentucky",
    disposition: "supportive", influence: 78,
    qualifiedFor: ["pres-christian-society"],
    honorific: "Rev.",
    competencies: {
      professional: { economics: 50, diplomacy: 70, security: 25, communications: 55, legal: 45, administration: 80, technology: 30, management: 79, politics: 76 },
      personal: { loyalty: 75, charisma: 65, leadership: 75, ambition: 45, integrity: 82, resilience: 70, intrigue: 20, discretion: 77 },
    },
  },
  {
    name: "Rev. Dr. Cornelius Omonokhua",
    state: "Edo", zone: "SS", age: 60, gender: "Male",
    religion: "Christianity", ethnicity: "Edo", avatar: "CO",
    traits: ["Interfaith Diplomat", "Builder of Institutions", "Peacemaker"],
    bio: "A Catholic priest who has served as CAN's director of interfaith dialogue. His experience working with Muslim counterparts across northern Nigeria gives him unique insight into managing religious tensions at a national level.",
    education: "Pontifical University Rome (Theology), University of Benin (MA Peace Studies), Boston College (PhD)",
    disposition: "neutral", influence: 75,
    qualifiedFor: ["pres-christian-society"],
    honorific: "Rev. Dr.",
    competencies: {
      professional: { economics: 40, diplomacy: 85, security: 30, communications: 50, legal: 55, administration: 65, technology: 25, management: 75, politics: 81 },
      personal: { loyalty: 65, charisma: 70, leadership: 72, ambition: 40, integrity: 88, resilience: 75, intrigue: 20, discretion: 88 },
    },
  },

  // ═══ President, Supreme Council for Islamic Affairs (5) ═══
  {
    name: "Sheikh Abdulrahman Ahmad",
    state: "Kano", zone: "NW", age: 68, gender: "Male",
    religion: "Islam", ethnicity: "Hausa", avatar: "AA",
    traits: ["Islamic Scholar", "Interfaith Diplomat", "Peacemaker"],
    bio: "A renowned Islamic jurist who studied in Medina and Al-Azhar. He has been instrumental in interfaith dialogue initiatives and commands respect from both Sunni mainstream and Sufi orders. His moderate stance has drawn criticism from conservative clerics.",
    education: "Islamic University of Medina (Sharia), Al-Azhar University Cairo (PhD Islamic Jurisprudence), BUK Kano (Law)",
    disposition: "supportive", influence: 88,
    qualifiedFor: ["pres-muslim-society"],
    honorific: "Sheikh",
    competencies: {
      professional: { economics: 40, diplomacy: 80, security: 30, communications: 55, legal: 75, administration: 65, technology: 25, management: 72, politics: 72 },
      personal: { loyalty: 72, charisma: 75, leadership: 80, ambition: 45, integrity: 88, resilience: 75, intrigue: 20, discretion: 81 },
    },
  },
  {
    name: "Alhaji Ibrahim Datti",
    state: "Kaduna", zone: "NW", age: 72, gender: "Male",
    religion: "Islam", ethnicity: "Hausa", avatar: "ID",
    traits: ["Conservative Cleric", "Political Operator", "Community Builder"],
    bio: "A powerful figure in northern Islamic circles who leads the Jama'atu Nasril Islam. He has been openly critical of government policies he considers anti-Islamic and has significant influence over northern political mobilisation.",
    education: "School for Arabic Studies Kano, Bayero University Kano (Islamic Studies), International Islamic University Malaysia",
    disposition: "critical", influence: 85,
    qualifiedFor: ["pres-muslim-society"],
    honorific: "Alhaji",
    competencies: {
      professional: { economics: 50, diplomacy: 60, security: 35, communications: 70, legal: 65, administration: 55, technology: 20, management: 76, politics: 67 },
      personal: { loyalty: 40, charisma: 72, leadership: 78, ambition: 60, integrity: 70, resilience: 80, intrigue: 50, discretion: 84 },
    },
  },
  {
    name: "Sheikh Muhammad Abubakar",
    state: "Sokoto", zone: "NW", age: 65, gender: "Male",
    religion: "Islam", ethnicity: "Fulani", avatar: "MA",
    traits: ["Sufi Mystic", "Modernist Muslim", "Pan-Nigerian"],
    bio: "Grand Mufti of a major Tijjaniyya order with followers across West Africa. He promotes a synthesis of Islamic scholarship with modern governance and has advocated for girl-child education in the North.",
    education: "Usmanu Danfodiyo University Sokoto (Arabic), University of Khartoum (Islamic Studies), SOAS London (MA)",
    disposition: "neutral", influence: 82,
    qualifiedFor: ["pres-muslim-society"],
    honorific: "Sheikh",
    competencies: {
      professional: { economics: 35, diplomacy: 75, security: 25, communications: 50, legal: 70, administration: 60, technology: 30, management: 74, politics: 74 },
      personal: { loyalty: 65, charisma: 80, leadership: 75, ambition: 40, integrity: 85, resilience: 78, intrigue: 25, discretion: 88 },
    },
  },
  {
    name: "Dr. Khalid Aliyu Abubakar",
    state: "Niger", zone: "NC", age: 60, gender: "Male",
    religion: "Islam", ethnicity: "Nupe", avatar: "KA",
    traits: ["Modernist Muslim", "Youth Engagement", "Builder of Institutions"],
    bio: "A medical doctor turned Islamic scholar who founded a network of modern Islamic schools across the Middle Belt. He represents a younger generation of Muslim leadership that emphasises education, technology, and interfaith cooperation.",
    education: "ABU Zaria (Medicine), Islamic University Medina (Islamic Studies), Harvard Divinity School (MA)",
    disposition: "supportive", influence: 75,
    qualifiedFor: ["pres-muslim-society"],
    honorific: "Dr.",
    competencies: {
      professional: { economics: 55, diplomacy: 70, security: 25, communications: 60, legal: 50, administration: 72, technology: 55, management: 81, politics: 81 },
      personal: { loyalty: 70, charisma: 72, leadership: 70, ambition: 55, integrity: 80, resilience: 68, intrigue: 25, discretion: 84 },
    },
  },
  {
    name: "Sheikh Dahiru Usman Bauchi",
    state: "Bauchi", zone: "NE", age: 67, gender: "Male",
    religion: "Islam", ethnicity: "Hausa", avatar: "DU",
    traits: ["Sufi Mystic", "Conservative Cleric", "Peacemaker"],
    bio: "Leader of the Qadiriyya order in Nigeria with millions of followers. His annual Maulud celebration draws crowds rivalling political rallies. He has played a behind-the-scenes role mediating between the government and disaffected northern youth.",
    education: "Traditional Quranic School, ATBU Bauchi (Islamic Studies), University of Khartoum (PhD)",
    disposition: "critical", influence: 80,
    qualifiedFor: ["pres-muslim-society"],
    honorific: "Sheikh",
    competencies: {
      professional: { economics: 30, diplomacy: 72, security: 30, communications: 45, legal: 60, administration: 50, technology: 20, management: 54, politics: 52 },
      personal: { loyalty: 55, charisma: 82, leadership: 76, ambition: 35, integrity: 78, resilience: 80, intrigue: 30, discretion: 70 },
    },
  },
];
