import type { SponsorCandidate } from "./legislativeTypes";

/** 3 sponsor candidates per sector (15 total). Fixed characters, not rotating. */
export const SPONSOR_CANDIDATES: Record<string, SponsorCandidate[]> = {
  economy: [
    {
      name: "Hon. Chidi Okonkwo",
      avatar: "CO",
      gender: "male",
      chamber: "house",
      faction: "Core Ruling",
      tier: "chair",
      competence: 78,
      influenceBonus: 15,
      pcCost: 5,
    },
    {
      name: "Sen. Hauwa Ibrahim",
      avatar: "HI",
      gender: "female",
      chamber: "senate",
      faction: "Ruling Allies",
      tier: "senior",
      competence: 65,
      influenceBonus: 10,
      pcCost: 2,
    },
    {
      name: "Hon. Tunde Bakare",
      avatar: "TB",
      gender: "male",
      chamber: "house",
      faction: "Core Ruling",
      tier: "junior",
      competence: 52,
      influenceBonus: 5,
      pcCost: 0,
    },
  ],
  security: [
    {
      name: "Sen. Bala Kaita",
      avatar: "BK",
      gender: "male",
      chamber: "senate",
      faction: "Core Ruling",
      tier: "chair",
      competence: 82,
      influenceBonus: 15,
      pcCost: 5,
    },
    {
      name: "Hon. Ngozi Eze",
      avatar: "NE",
      gender: "female",
      chamber: "house",
      faction: "Core Ruling",
      tier: "senior",
      competence: 68,
      influenceBonus: 10,
      pcCost: 2,
    },
    {
      name: "Hon. Yusuf Danladi",
      avatar: "YD",
      gender: "male",
      chamber: "house",
      faction: "Ruling Allies",
      tier: "junior",
      competence: 48,
      influenceBonus: 5,
      pcCost: 0,
    },
  ],
  social: [
    {
      name: "Hon. Amaka Nwosu",
      avatar: "AN",
      gender: "female",
      chamber: "house",
      faction: "Core Ruling",
      tier: "chair",
      competence: 75,
      influenceBonus: 15,
      pcCost: 5,
    },
    {
      name: "Sen. Mohammed Sule",
      avatar: "MS",
      gender: "male",
      chamber: "senate",
      faction: "Core Ruling",
      tier: "senior",
      competence: 62,
      influenceBonus: 10,
      pcCost: 2,
    },
    {
      name: "Hon. Blessing Obi",
      avatar: "BO",
      gender: "female",
      chamber: "house",
      faction: "Ruling Allies",
      tier: "junior",
      competence: 45,
      influenceBonus: 5,
      pcCost: 0,
    },
  ],
  governance: [
    {
      name: "Sen. Aisha Danjuma",
      avatar: "AD",
      gender: "female",
      chamber: "senate",
      faction: "Core Ruling",
      tier: "chair",
      competence: 80,
      influenceBonus: 15,
      pcCost: 5,
    },
    {
      name: "Hon. Emeka Udoh",
      avatar: "EU",
      gender: "male",
      chamber: "house",
      faction: "Core Ruling",
      tier: "senior",
      competence: 66,
      influenceBonus: 10,
      pcCost: 2,
    },
    {
      name: "Hon. Fatimah Garba",
      avatar: "FG",
      gender: "female",
      chamber: "house",
      faction: "Ruling Allies",
      tier: "junior",
      competence: 50,
      influenceBonus: 5,
      pcCost: 0,
    },
  ],
  constitutional: [
    {
      name: "Sen. Olumide Adesina",
      avatar: "OA",
      gender: "male",
      chamber: "senate",
      faction: "Core Ruling",
      tier: "chair",
      competence: 85,
      influenceBonus: 15,
      pcCost: 5,
    },
    {
      name: "Hon. Chidinma Okeke",
      avatar: "CK",
      gender: "female",
      chamber: "house",
      faction: "Core Ruling",
      tier: "senior",
      competence: 70,
      influenceBonus: 10,
      pcCost: 2,
    },
    {
      name: "Sen. Ibrahim Musa",
      avatar: "IM",
      gender: "male",
      chamber: "senate",
      faction: "Ruling Allies",
      tier: "junior",
      competence: 55,
      influenceBonus: 5,
      pcCost: 0,
    },
  ],
};

/** Get sponsors for a given sector */
export function getSponsorCandidates(sector: string): SponsorCandidate[] {
  return SPONSOR_CANDIDATES[sector] ?? [];
}

/** Get a specific sponsor by sector and tier */
export function getSponsorByTier(
  sector: string,
  tier: "chair" | "senior" | "junior",
): SponsorCandidate | undefined {
  return SPONSOR_CANDIDATES[sector]?.find((s) => s.tier === tier);
}
